---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/complete-preparation-for-upgrade.html 
keywords: storage, encryption, authentication, key, manager, external 
summary: 使用 ARL 升級同一機箱中的控制器機型時、請設定並管理儲存加密、管理驗證金鑰、以及靜態 SnapMirror 關係。 
---
= 完成升級準備工作
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
了解 ONTAP 授權以及如何使用 Onboard Key Manager (OKM) 管理儲存加密。您也可以選擇停止 SnapMirror 關係。



[[learn-about-ontap-licensing]]
== 了解 ONTAP 授權

叢集中的每個節點都必須有自己的 NetApp 授權檔案（ NLF ）。

如果您沒有 NLF 、則叢集中目前授權的功能可用於新的控制器。不過、在控制器上使用未經授權的功能可能會使您不遵守授權合約、因此您應該在升級完成後、為新控制器安裝 NLF 。

請參閱link:other-references.html["參考資料"]以連結至 _NetApp Support Site_，您可以在此取得 NLF。NLF 可在 _My Support_ 區段的 _Software licenses_ 下取得。如果網站沒有您需要的 NLF，請聯絡您的NetApp銷售代表。

有關 ONTAP 授權的詳細資訊，請參閱link:other-references.html["參考資料"]以連結至《系統管理參考》。



[[manage-storage-encryption-using-the-onboard-key-manager]]
[[manage-storage-encryption-using-okm]]
== 使用 Onboard Key Manager 管理儲存加密

使用 Onboard Key Manager（OKM）來管理加密金鑰。如果您已設定 OKM，則必須在開始升級之前記錄通關密語和備份資料。

.步驟
. 記錄叢集範圍的複雜密碼。
+
這是使用 CLI 或 REST API 設定或更新 OKM 時所輸入的複雜密碼。

. 驗證通關密語和金鑰管理程式操作：
+
「安全金鑰管理程式內建同步」

+
出現提示時，輸入您在上一個步驟中記錄的叢集範圍 OKM 複雜密碼。

. 透過查看以下命令的輸出來驗證 cc-mode 是否已啟用：
+
`security key-manager config show`

. 備份金鑰管理器資訊：
+
「安全金鑰管理程式內建show Backup」





[[optionally-quiesce-the-snapmirror-relationships]]
== 或者，也可以讓這些 SnapMirror 關係平靜下來

在繼續執行此程序之前、您必須確認所有SnapMirror關係均已靜止。當SnapMirror關係靜止時、它會在重新開機和容錯移轉之間保持靜止。

.步驟
. 驗證目的地叢集上的SnapMirror關係狀態：
+
「napmirror show」

+
[NOTE]
====
如果狀態為「Transferring（正在傳輸）」、您必須中止傳輸：「napmirror abort-destination-vserver _vserver_name_」

====
+
如果SnapMirror關係未處於「傳輸」狀態、則中止將會失敗。

. 停止叢集之間的所有關係：
+
`snapmirror quiesce -destination-vserver *`



.接下來呢？
準備升級後，link:relocate-non-root-aggr-and-nas-data-lifs-node1-node2.html["將節點 1 擁有的非根 Aggregate 和 NAS 資料 LIF 重新配置到節點 2"]。
