---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/guidelines-for-upgrading-controllers-with-arl.html 
keywords: guidelines, upgrade, ontap, controllers, old, system, chassis, disk, disks 
summary: 瞭解您是否可以使用 ARL 、保留舊的系統機箱和磁碟來進行升級組態。 
---
= 升級控制器的準則
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
若要瞭解是否可以使用 Aggregate 重定位（ ARL ）、請保留舊的系統機箱和磁碟、這取決於系統升級組態和 ONTAP 版本。



== 支援ARL升級

某些系統組態支援控制器升級。請參閱 link:decide-to-use-the-aggregate-relocation-guide.html#supported-systems["支援的系統升級組合"] 以取得支援系統清單和最低 ONTAP 版本。

如果您已收到全新的 AFF A30、AFF A50、AFF A70、AFF A90、AFF A150、AFF A900、AFF C30、AFF C60、AFF C80、FAS2820 或 FAS9500 完整系統（包括新機箱），請參閱link:other-references.html["參考資料"]以連結至_使用「system controller replace」命令升級執行 ONTAP 9.8 或更新版本的控制器硬體_。

使用ARL的控制器升級支援使用SnapLock 「支援」的系統、這些系統均設定了「支援使用者支援使用者支援的功能」和SnapLock 「支援使用者支援



== 雙節點無交換式叢集

如果您要升級雙節點無交換式叢集中的節點、則可在執行升級時、將節點留在無交換器叢集中。您不需要將它們轉換成交換式叢集。



== 切換附加叢集

如果您要在連接至叢集交換器的叢集中升級節點、則必須確認交換器上執行的 make 、 model 、韌體版本、 RCF 和 ONTAP 版本、與升級後在替換控制器上執行的版本相同。如有必要，您必須先執行交換器升級，才能使用 ARL 升級控制器。

如需更多資訊、請參閱 link:cable-node1-for-shared-cluster-HA-storage.html#connect-switch-attached-cluster["連線至交換器連接的叢集"]。



== 疑難排解

升級節點配對時可能會發生故障。節點可能會當機、集合體可能不會重新部署、或是生命體可能無法移轉。故障原因及其解決方案取決於升級程序期間何時發生故障。

如果出現任何問題、請參閱程序結尾的link:aggregate-relocation-failures.html["疑難排解"]一節、以取得更多資訊和可能的解決方案。可能發生的故障相關資訊會依程序階段列於link:overview-of-the-arl-upgrade.html["ARL 升級序列"]中。

如果您沒有找到所遇到問題的解決方案，請聯絡技術支援。
