---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/install-asa900-affa900-fas9500-on-node2.html 
keywords: aff, fas, asa, install, NVRAM, node2, controller, module, modules, replacement 
summary: 在同一機箱中升級控制器機型的 ARL 期間、在 node2 上安裝替換系統模組。 
---
= 在 node2 上安裝 ASA A900 、 AFF A900 或 FAS9500 NVRAM 和控制器模組
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在 node2 上安裝您收到的 ASA A900 、 AFF A900 或 FAS9500 NVRAM 和控制器模組。節點2是位於機箱右側的控制器B、可從系統背面查看控制器。

執行安裝時、您必須注意下列事項：

* 將插槽6-1和6-2中的所有空白填充模組、從舊的NVRAM模組移至新的NVRAM模組。
* 請勿將 coredump 裝置從 AFF A700 NVRAM 模組移至 ASA A900 或 AFF A900 NVRAM 模組。
* 將FAS9000 NVRAM模組中安裝的所有快閃快取模組移至FAS9500 NVRAM模組。


.開始之前
如果您尚未接地、請正確接地。



== 安裝 ASA A900 、 AFF A900 或 FAS9500 NVRAM 模組

在 node2 的插槽 6 中安裝 ASA A900 、 AFF A900 或 FAS9500 NVRAM 模組。

.步驟
. 將NVRAM模組對齊插槽6中機箱開孔的邊緣。
. 將NVRAM模組輕推入插槽、直到帶有字母和編號的I/O CAM栓開始與I/O CAM銷接合、然後將I/O CAM栓完全推入、將NVRAM模組鎖定到位。




== 在 node2 中安裝 ASA A900 、 AFF A900 或 FAS9500 控制器模組

在 node2 中安裝、連接及連接 ASA A900 、 AFF A900 或 FAS9500 控制器模組。

.步驟
. 將控制器模組的一端對準機箱中的托架B、然後將控制器模組輕推至系統的一半。
+

TIP: 機箱標籤位於控制器模組正上方的機箱上。

+

NOTE: 在稍後程序中指示您將控制器模組完全插入機箱之前，請勿將其完全插入機箱。

. 將管理和主控台連接埠連接至節點2控制器模組。
+

NOTE: 由於機箱已開啟電源、因此節點2一旦完全就位、就會立即開始開機。為避免節點2開機、建議您先將主控台和管理纜線連接至節點2控制器模組、再將控制器模組完全插入插槽。

. 將控制器模組穩固地推入機箱、直到它與中間板完全接入。
+
控制器模組完全就位時、鎖定鎖定鎖定會上升。

+

WARNING: 為避免損壞連接器，將控制器模組滑入機箱時請勿過度施力。

. 模組就位後立即連接序列控制台並準備中斷節點 2 的 AUTOBOOT。
. 中斷自動開機後、 node2 會在載入程式提示下停止。如果您沒有在時間中斷自動開機、而 node2 開始開機、請等待提示、然後按 Ctrl-C 進入開機功能表。節點停止在開機功能表後、請使用選項 `8` 重新啟動節點、並在重新開機期間中斷自動開機。
. 在node2的loader>提示下、設定預設環境變數：
+
「預設值」

. 儲存預設環境變數設定：
+
「aveenv」


