---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/move-non-root-aggr-and-nas-data-lifs-back-to-node2.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2 
summary: 使用 ARL 將同一機箱中的控制器機型升級時、請確認節點 1 上的 node2 NAS 資料生命體已從 node1 重新定位至 node2 。 
---
= 將非根Aggregate和NAS資料lifs移回節點2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在您驗證 node2 上的網路組態、並在將集合體從 node1 重新定位至 node2 之前、請確認屬於 node2 的 NAS 資料生命體目前位於 node1 上、已從 node1 重新定位至 node2 。您還必須驗證節點2上是否存在SAN lifs。

.關於這項工作
在升級過程中、遠端LIF會處理SAN LUN的流量。在升級期間、移轉SAN LIF對於叢集或服務健全狀況並不必要。除非需要將SAN LIF對應至新連接埠、否則不會移動SAN LIF。將node2聯機後，必須驗證該生命段是否正常且位於適當的端口上。

.步驟
. 恢復重新定位作業：
+
「系統控制器更換恢復」

+
系統會執行下列工作：

+
--
** 叢集仲裁檢查
** 系統ID檢查
** 映像版本檢查
** 目標平台檢查
** 網路連線能力檢查


--
+
此作業會在網路連線能力檢查的這個階段暫停。

. 恢復重新定位作業：
+
「系統控制器更換恢復」

+
系統會執行下列檢查：

+
--
** 叢集健全狀況檢查
** 叢集LIF狀態檢查


--
+
執行這些檢查之後、系統會將非根集合體和 NAS 資料的生命體重新定位回節點 2 、而節點 2 目前正在替換控制器上執行。

+
資源重新配置完成後、控制器更換作業會暫停。

. 檢查集合體重新配置和NAS資料LIF移動作業的狀態：
+
「System Controller replace show-details」（系統控制器取代顯示詳細資料

+
如果控制器更換程序暫停、請檢查並修正錯誤（如果有）、然後發出「推入」以繼續操作。

. 如有必要、請還原並還原任何已移轉的生命。列出任何已移出的生命生命：
+
「叢集控制器更換網路置換介面show」

+
如果有任何生命段被移除、請將主節點還原回節點2：

+
「叢集控制器更換網路置換介面還原主節點」

. 繼續作業、以提示系統執行必要的POST檢查：
+
「系統控制器更換恢復」

+
系統會執行下列POST檢查：

+
** 叢集仲裁檢查
** 叢集健全狀況檢查
** 集合體重建檢查
** Aggregate狀態檢查
** 磁碟狀態檢查
** 叢集LIF狀態檢查
** Volume檢查



