---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/move-non-root-aggr-nas-lifs-node1-from-node2-to-upgraded-node1.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2 
summary: 使用 ARL 將同一機箱中的控制器機型升級時、請確認 node2 上的 node1 NAS 資料生命體已從 node2 重新定位至 node1 。 
---
= 將 node1 非 root 集合體和 NAS 資料生命體從 node2 移至升級的 node1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在驗證節點 1 上的網路配置後，需要將節點 1 擁有的 NAS 資料 LIF 從節點 2 遷移到節點 1，並確認 SAN LIF 存在於節點 1 上。

.關於這項工作
遠端 LIF 在升級過程中處理到 SAN LUN 的流量。升級過程中，遷移 SAN LIF 對叢集或服務運作狀況並非必要。除非需要將 SAN LIF 對應到新端口，否則不會移動它們。

在節點 1 上線後，您需要驗證 LIF 是否健康以及是否位於正確的連接埠上。

.步驟
. 恢復重新定位作業：
+
[source, cli]
----
system controller replace resume
----
+
系統會執行下列工作：

+
--
** 叢集仲裁檢查
** 系統ID檢查
** 映像版本檢查
** 目標平台檢查
** 網路連線能力檢查


--
+
系統在網路可達性檢查的此階段暫停操作。

. 執行網路連線檢查：
+
[source, cli]
----
network port reachability show -node node1
----
+
確認所有連接的連接埠（包括介面群組和VLAN連接埠）都顯示為「OK（正常）」狀態。

. 對於下列升級，您必須重新指派 FCP SAN 生命體。
+
[cols="35,65"]
|===
| 現有系統 | 更換系統 


| AFF A250 | AFF A30 、 AFF A50 


| AFF C250 | AFF C30 、 AFF C60 


| 解答800 AFF | AFF A70 、 AFF A90 


| AFF C800 | AFF C80 
|===
+
對於所有其他系統升級，請繼續執行<<resume_relocation_step4,步驟4.>>。

+
.. 將用於 FCP 或 FC-NVMe 資料存取的 FCP SAN 生命體重新指派給正確的主連接埠：
+
[source, cli]
----
network interface show -vserver <vserver_hosting_fcp_lifs>
----
.. 對於目前節點為升級節點 1 的生命週期、而目前的連接埠會將「狀態 oper 」報告為「 - 」（因為連接埠存在於 AFF A800 節點上、但不存在於 AFF A90 節點上）、請先修改目前的連接埠、然後再將其上線。
+
驗證是否已建立實體連線至需要移動 FC LIF 的 FC 目標連接埠：

+
--
... 將LIF狀態設為「向下」：
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name>  -status-admin down
----
... 修改 LIF 的主連接埠：
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> - home-node <node1> -home-port <FC_target_port>
----
... 將 LIF 狀態設定為「 UP 」：
+
[source, cli]
----
network interface modify -vserver <vserver> -lif <lif_name>  -status-admin up
----


--
+
對節點 1 上的每個主目錄 FC SAN LIF 重複執行子步驟 a 和 b 。



. [[resume_gress_step4]] 恢復重新定位作業：
+
[source, cli]
----
system controller replace resume
----
+
系統會執行下列檢查：

+
--
** 叢集健全狀況檢查
** 叢集LIF狀態檢查


--
+
執行這些檢查之後、系統會將節點1擁有的非根Aggregate和NAS資料lifs重新定位至新節點1。

+
資源重新配置完成後、控制器更換作業會暫停。

. 檢查集合體重新配置和NAS資料LIF移動作業的狀態：
+
[source, cli]
----
system controller replace show-details
----
+
如果控制器更換程序暫停、請檢查並修正錯誤（如果有）、然後發出「推入」以繼續操作。

. 如有必要，恢復和還原已移位的 LIF，或手動遷移和修改未能自動遷移到 node1 的 node1 LIF。
+
[role="tabbed-block"]
====
.恢復和還原移位的 LIF
--
.. 列出所有已移位的 LIF：
+
[source, cli]
----
cluster controller-replacement network displaced-interface show
----
.. 如果有任何生命期被移除、請將主節點還原回節點1：
+
[source, cli]
----
cluster controller-replacement network displaced-interface restore-home-node -node <node1_nodename> -vserver <vserver name> -lif-name <lif_name>
----


--
.手動遷移和修改 LIF 文件
--
.. 將未能自動遷移到節點 1 的 LIF 遷移：
+
[source, cli]
----
network interface migrate -vserver <vserver name> -lif <lif_name> -destination-node <node1_nodename> -destination-port <port_on_node1>
----
.. 修改已遷移 LIF 的來源節點和來源連接埠：
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <data_lif_name> -home-node <node1_nodename> -home-port <home_port>
----


--
====
. 繼續作業、以提示系統執行必要的POST檢查：
+
[source, cli]
----
system controller replace resume
----
+
系統會執行下列POST檢查：

+
** 叢集仲裁檢查
** 叢集健全狀況檢查
** 集合體重建檢查
** Aggregate狀態檢查
** 磁碟狀態檢查
** 叢集LIF狀態檢查
** Volume檢查



