---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/move-non-root-aggr-and-nas-data-lifs-back-to-node2.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2 
summary: 使用 ARL 將同一機箱中的控制器機型升級時、請確認節點 1 上的 node2 NAS 資料生命體已從 node1 重新定位至 node2 。 
---
= 將非根Aggregate和NAS資料lifs移回節點2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在驗證節點 2 上的網路配置後，需要將節點 2 擁有的 NAS 資料 LIF 從節點 1 遷移到節點 2，並確認 SAN LIF 存在於節點 2 上。

.關於這項工作
遠端 LIF 在升級過程中處理到 SAN LUN 的流量。升級過程中，遷移 SAN LIF 對叢集或服務運作狀況並非必要。除非需要將 SAN LIF 對應到新端口，否則不會移動它們。

在節點 2 上線後，您需要驗證 LIF 是否健康以及是否位於正確的連接埠上。

.步驟
. 恢復重新定位作業：
+
[source, cli]
----
system controller replace resume
----
+
系統會執行下列工作：

+
--
** 叢集仲裁檢查
** 系統ID檢查
** 映像版本檢查
** 目標平台檢查
** 網路連線能力檢查


--
+
系統在網路可達性檢查的此階段暫停操作。

. 恢復重新定位作業：
+
[source, cli]
----
system controller replace resume
----
+
系統會執行下列檢查：

+
--
** 叢集健全狀況檢查
** 叢集LIF狀態檢查


--
+
執行這些檢查之後、系統會將非根集合體和 NAS 資料的生命體重新定位回節點 2 、而節點 2 目前正在替換控制器上執行。

+
資源重新配置完成後、控制器更換作業會暫停。

. 檢查集合體重新配置和NAS資料LIF移動作業的狀態：
+
[source, cli]
----
system controller replace show-details
----
+
如果控制器更換程序暫停、請檢查並修正錯誤（如果有）、然後發出「推入」以繼續操作。

. 如有必要，恢復和還原已移位的 LIF，或手動遷移和修改未能自動遷移到 node2 的 node2 LIF。
+
[role="tabbed-block"]
====
.恢復和還原移位的 LIF
--
.. 列出所有已移位的 LIF：
+
[source, cli]
----
cluster controller-replacement network displaced-interface show
----
.. 如果有任何生命段被移除、請將主節點還原回節點2：
+
[source, cli]
----
cluster controller-replacement network displaced-interface restore-home-node -node <node2_nodename> -vserver <vserver name> -lif-name <lif_name>
----


--
.手動遷移和修改 LIF 文件
--
.. 將未能自動遷移到節點2的LIF遷移出去：
+
[source, cli]
----
network interface migrate -vserver <vserver name> -lif <lif_name> -destination-node <node2_nodename> -destination-port <port_on_node2>
----
.. 修改已遷移 LIF 的來源節點和來源連接埠：
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <data_lif_name> -home-node <node2_nodename> -home-port <home_port>
----


--
====
. 繼續作業、以提示系統執行必要的POST檢查：
+
[source, cli]
----
system controller replace resume
----
+
系統會執行下列POST檢查：

+
** 叢集仲裁檢查
** 叢集健全狀況檢查
** 集合體重建檢查
** Aggregate狀態檢查
** 磁碟狀態檢查
** 叢集LIF狀態檢查
** Volume檢查



