---
permalink: upgrade/migrate-fas2820-node4-lIfs-aggregates.html 
sidebar: sidebar 
keywords: fas2820, ndu, nondisruptive, upgrade, node3, node4, migrate, aggregates, lif 
summary: '要完成升級，您需要將 FAS2820node3 連接到 node4，然後將 node4 上的資料邏輯介面 (LIF) 和資料聚合遷移到 node3。' 
---
= 將FAS2820節點 4 上的 LIF 和資料聚合遷移到節點 3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要完成升級，您需要將FAS2820節點 3 連接到節點 4，然後將節點 4 上的資料邏輯介面 (LIF) 和資料聚合遷移到節點 3。

.關於這項工作
在node3上執行下列步驟。

.步驟
. 在 node3 的載入程式提示下、將節點開機至開機功能表：
+
[source, cli]
----
boot_ontap menu
----
. 選取選項 `6 Update flash from backup config` 將 /var 檔案系統還原至 node3 。
+
這會以最後一次備份到磁碟的方式取代所有 Flash 型組態。

. 輸入「y」繼續。
. 讓節點正常開機。
+
[NOTE]
====
節點會自動重新開機、以載入 /var 檔案系統的新複本。

節點報告系統 ID 不相符的警告。輸入 `y` 以覆寫系統 ID 。

====
. 驗證叢集和 HA 連接埠是否在節點 3 和節點 4 之間連接。
. 顯示節點3和節點4上的叢集和HA連接埠：
+
[source, cli]
----
set -privilege advanced
----
+
[source, cli]
----
network port show
----
. 修改叢集廣播網域以包含所需的叢集連接埠：
+
[source, cli]
----
network port broadcast-domain remove-ports -broadcast-domain <broadcast_domain_name> -ports <port_names>
----
+
[source, cli]
----
network port broadcast-domain add-ports -broadcast-domain Cluster -ports <port_names>
----
+

NOTE: 從 ONTAP 9.8 開始、新的 IPspace 和一個或多個廣播網域可能會指定給現有的實體連接埠、以供叢集連線使用。

. 修改叢集 IPspace 以包含所需的叢集連接埠、並將傳輸單元上限設為 9000 （如果尚未設定）：
+
[source, cli]
----
network port modify -node <node_name> -port <port_name> -mtu 9000 -ipspace Cluster
----
. 顯示所有叢集網路生命：
+
[source, cli]
----
network interface show -role cluster
----
. 將兩個節點上的所有叢集網路 LIF 遷移到其計劃的主連接埠：
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <lif_name> -destination-node <node_name> -destination-port <port_name>
----
. 顯示所有叢集網路生命：
+
[source, cli]
----
network interface show -role cluster
----
. 配置叢集網路 LIF 的主連接埠：
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> -home-port <port_name>
----
. 將用於 node3 的所有資料 LIF 移回 node3：
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <lif_name> -destination-node <node3> -destination-port <port_name>
----
. 顯示所有資料網路生命：
+
[source, cli]
----
network interface show -role data
----
. 為所有資料 LIF 設定主節點和主連接埠。如果任何 LIF 處於關閉狀態，則將其管理狀態設為 `up`為每個 LIF 輸入一次以下命令：
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> -home-node <node_name> -home-port <port_name> -status-admin up
----
. 移轉叢集管理 LIF ：
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <cluster_mgmt_lif> -destination-node <node3> -destination-port <port_name>
----
. 顯示叢集管理 LIF 的狀態：
+
[source, cli]
----
network interface show -role cluster-mgmt
----
. 顯示叢集中所有資料集合體的狀態：
+
[source, cli]
----
storage aggregate show
----
. 在雙節點叢集中啟用叢集高可用性：
+
[source, cli]
----
cluster ha modify -configured true
----
. 啟用並驗證 node3 和 node4 的儲存故障轉移：
+
[source, cli]
----
storage failover modify -node <node3> -enabled true
----
+
[source, cli]
----
storage failover modify -node <node4> -enabled true
----
+
[source, cli]
----
storage failover show
----
. 遷移由 node4 擁有但本應由 node3 擁有的資料聚合：
+
[source, cli]
----
storage aggregate relocation start -aggregate <aggregate_name> -node <node4> -destination <node3>
----
. 顯示叢集中所有資料集合體的狀態：
+
[source, cli]
----
storage aggregate show
----
. 啟用跨節點的網路生命體自動還原：
+
[source, cli]
----
network interface modify -lif * -auto-revert true
----
. 啟用儲存容錯移轉自動恢復：
+
[source, cli]
----
storage failover modify -node * -auto-giveback true
----
. 顯示叢集狀態：
+
[source, cli]
----
cluster show
----
. 顯示容錯移轉資格：
+
[source, cli]
----
storage failover show
----
+

NOTE: 在叢集報告輸出中，一個節點可能錯誤地擁有屬於另一個節點的聚合。如果發生這種情況，請從集群的兩側執行接管和交還。

. 顯示叢集中所有資料集合體的狀態：
+
[source, cli]
----
storage aggregate show
----

