---
permalink: upgrade/upgrade-final-upgrade-steps-in-ontap-9-8.html 
sidebar: sidebar 
keywords: complete, procedure, upgrading, upgrade, moving, move, storage, delete, unused, port, lif, re-enable, failover, availability, service, processor, sp, autosupport, volume, encryption, fc, cna, perform final upgrade steps in ontap 9.8 
summary: 若要透過移動儲存設備來完成升級程序、您必須從新節點刪除任何未使用的連接埠和LIF、重新啟用儲存容錯移轉或高可用度、設定服務處理器（SP\）、安裝新授權、以及設定AutoSupport Re。您可能還需要設定儲存設備或Volume Encryption、並設定FC或CNA連接埠。 
---
= 請執行ONTAP 更新版本的最終升級步驟
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要透過移動儲存設備來完成升級程序、您必須從新節點刪除任何未使用的連接埠和LIF、重新啟用儲存容錯移轉或高可用度、設定服務處理器（SP）、安裝新的授權、以及設定AutoSupport Re。您可能還需要設定儲存設備或Volume Encryption、並設定FC或CNA連接埠。

.開始之前
這些步驟適用於執行ONTAP 不含更新版本的系統。如果您執行ONTAP 的是更新版本的版本、則必須使用中的程序 link:upgrade-final-steps-ontap-9-7-or-earlier-move-storage.html["在更新版本的更新版本中執行ONTAP 最終升級步驟"]。

.步驟
. 如果您的系統執行ONTAP 的是效能不高的版本、*停止*。您必須使用中的程序 link:upgrade-final-steps-ontap-9-7-or-earlier-move-storage.html["在更新版本的更新版本中執行ONTAP 最終升級步驟"]。
. 在儲存系統提示字元中、顯示關於LIF的資訊：
+
「網路介面展示」

. 如果您在SAN環境中、請從連接埠集刪除未使用的lifs、以便移除它們：
+
.. 顯示連接埠集清單：
+
「LUN portset show」

.. 從連接埠集移除任何未使用的LIF：
+
「移除LUN連接埠集」



. 從新節點移除每個未使用的LIF：
+
網路介面刪除

. 視需要在新節點配對上重新啟用儲存容錯移轉或高可用度：
+
[cols="1,2"]
|===
| 如果您有... | 然後... 


 a| 
雙節點叢集
 a| 
重新啟用高可用度：「叢集ha modify -configured true」



 a| 
具有兩個以上節點的叢集
 a| 
重新啟用儲存容錯移轉：「torage容錯移轉修改-node_name -enabled_true」

|===
. 視需要在新節點上設定SP：
+
「系統服務處理器網路修改」

. 視需要在新節點上安裝新授權：
+
《系統授權新增》

. 在AutoSupport 新節點上設定功能：
+
系統節點AutoSupport 的功能不受限制

. 從每個新節點、傳送升級後AutoSupport 的資訊給技術支援：
+
「系統節點AutoSupport 無法叫用節點node_name -type all -m則 訊息「MAn=end node_name custmalled from plate_old to platform _new」（已成功從platfort_old升級至platform _new）。

. 根據您使用的是板載金鑰管理還是外部金鑰管理，使用下列任一程序還原儲存或磁碟區加密功能：
+
** link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html["還原內建金鑰管理加密金鑰"^]
** link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-external-encryption-keys-93-later-task.html["還原外部金鑰管理加密金鑰"^]


. 如果新節點具有FC連接埠（內建或FC介面卡）、內建CNA連接埠或CNA卡、請在儲存系統提示字元中輸入下列命令來設定FC或CNA連接埠：
+
「系統節點硬體統一連線修改節點節點名稱介面卡名稱模式｛fc/cna｝-type｛target | initiator｝」

+
link:https://docs.netapp.com/us-en/ontap/san-admin/index.html["使用CLI進行SAN管理"^]

+
您只能在CNA介面卡離線時修改CNA組態。

. 如有必要、請在新節點上設定無交換器叢集。
+
https://library.netapp.com/ecm/ecm_download_file/ECMP1140536["使用Cisco叢集交換器移轉至雙節點交換叢集"^]

+
https://library.netapp.com/ecm/ecm_download_file/ECMP1140535["使用NetApp CN1610叢集交換器移轉至雙節點交換叢集"^]

. 如果需要、請重新建立舊系統上的主機板管理控制器（ BMC ）的非預設使用者帳戶：
+
.. 變更或重設 BMC 管理使用者帳戶密碼。
+
BMC 管理員使用者帳戶密碼為空白（無密碼）、或與系統管理員使用者帳戶密碼相同。

.. 使用重新建立非預設的 BMC 使用者帳戶 `security login create` 命令 `application` 設定為「服務處理器」、如下列範例所示：
+
`security login create -user-or-group-name bmcuser -application service-processor -authentication-method password -role admin`

+

NOTE: 在 BMC 中建立使用者帳戶時、需要管理員權限。



. 如有需要、請透過NetApp支援網站取消委任原始系統、告知NetApp系統已不再運作、且可從支援資料庫中移除：
+
.. 登入 https://mysupport.netapp.com/site/global/dashboard["NetApp支援"^] 網站。
.. 單擊鏈接* My Installed System*。
.. 在「Installed Systems（安裝的系統）」頁面上、以表格輸入舊系統的序號、然後按一下「* Go！*」
.. 在「取消委任表單」頁面上填寫表單、然後按一下「*提交*」。




.完成後
您已完成升級程序。
