---
permalink: upgrade/upgrade_migrate_aggregates_epsilon_lifs_node1_to_node4.html 
sidebar: sidebar 
keywords: ndu, nondisruptive, upgrade, node1, node4, migrate, aggregates, lifs 
summary: 將 node1 上的資料集合體、 epsilon 和 lifs 移轉至 node4 。 
---
= 將 node1 上的資料集合體、 epsilon 和 lifs 移轉至 node4
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在將 AFF A250 node1 轉換為磁碟機櫃之前、請先將 node1 上的資料集合體、 epsilon 和邏輯介面（ lifs ）移轉至 AFF A400 node4 。

.步驟
. 在 node4 的載入程式提示下、將節點開機至開機功能表：
+
Boot_ONTAP功能表

. 選取選項 `6 Update flash from backup config` 將 /var 檔案系統還原至 node4 。
+
這會以最後一次備份到磁碟的方式取代所有 Flash 型組態。

. 輸入「y」繼續。
+
[NOTE]
====
節點會自動重新開機、以載入 /var 檔案系統的新複本。

節點報告系統 ID 不相符的警告。輸入 `y` 以覆寫系統 ID 。

====
. 移轉叢集生命：
+
"進階權限"

+
「網路連接埠展示」

+
[NOTE]
====
如果將 AFF A250 升級至 AFF A400 時系統叢集連接埠不相同、您可能必須暫時將 node4 上的介面變更為叢集連接埠：

`network port modify -node _node4_ -port _port_name_ -mtu 9000 -ipspace Cluster`

====
+
`network interface migrate -vserver Cluster -lif _cluster_LIF_  -destination-node _node4_ -destination-port _port_name_`

. 等待叢集進入仲裁狀態、然後確認叢集節點狀況良好：
+
`– cluster show`

+

NOTE: HA 配對與儲存容錯移轉會在目前狀態中保持停用狀態。

. 將叢集生命週期移至 node4 上的暫存 25G 叢集連接埠：
+
`network interface modify`

. 如果正在升級的 AFF A250 叢集上正在使用介面群組和資料 VLAN 、請執行此步驟。如果沒有、請前往 <<migrate_node1_nod4,步驟8.>>。
+
AFF A250 和 AFF A400 系統之間的實體網路連接埠名稱不同。因此、在 node4 上可能會有設定錯誤的介面群組和取代的 VLAN 。檢查並視需要修正任何設定不正確的介面群組和移出的 VLAN 。



[[migrate_node1_nod4]]
. 將 node1 上的資料集合體移轉至 node4 ：
+
`storage aggregate relocation start -aggregate-list _aggregate_list_name_ -node _node1_ -destination _node4_ -ndo-controller-upgrade true -override-destination-checks true`

. 顯示叢集中所有資料集合體的狀態：
+
`storage aggregate show`

. 移除 node1 的 IF 、改為將其移至 node4 、以移轉 epsilon 。
+
.. 從 node1 移除 epsilon ：
+
`cluster modify -epsilon false -node _node1_`

.. 將 epsilon 移至 node4 ：
+
`cluster modify -epsilon true -node _node4_`



. 顯示叢集狀態：
+
「叢集展示」

. 顯示所有資料網路生命：
+
`network interface show -role data`

. 將所有資料生命週期移轉至 node4 ：
+
`network interface migrate -vserver _vserver_name_ -lif _lif_name_ -destination-node _node4_ -destination-port _port_name_`

. 顯示叢集中所有資料生命的狀態：
+
`network interface show -role data`

. 如果有任何生命中斷、請輸入下列命令、並針對每個LIF輸入一次、將該生命的管理狀態設定為「UP」：
+
「網路介面修改-vserver _vserver_name_-lif_lif_name_-stue-admin up」

. 移轉叢集管理 LIF ：
+
`network interface migrate -vserver _vserver_name_ -lif cluster_mgmt -destination-node _node4_ -destination-port _port_name_`

. 顯示叢集管理 LIF 的狀態：
+
`network interface show cluster_mgmt`

. 停止節點1：
+
`halt -node _node1_ -inhibit-takeover true -ignore-quorum-warnings true`



.接下來呢？
link:upgrade_convert_node1_drive_shelf_connect_node3.html["將 node1 轉換為磁碟機櫃、並連線至 node3"]
