---
permalink: upgrade/upgrade-map-network-ports-ontap-9-8.html 
sidebar: sidebar 
keywords: enable, node3, node4, node, communicate, cluster, network, upgrade, physical, port, correct, configure, setting, data, map network ports using ontap 9.8 
summary: 若要讓節點3和節點4在升級後與叢集中的其他節點和網路進行通訊、您必須確保實體連接埠已正確設定為適合特定用途的設定、例如叢集、資料等。 
---
= 使用ONTAP 更新版本的版本資訊來對應網路連接埠
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要讓節點3和節點4在升級後與叢集中的其他端口和網路進行通訊、您必須確認實體連接埠已正確設定為適合特定用途的設定、例如叢集、資料等。

這些步驟適用於執行ONTAP 不含更新版本的系統。如果您執行ONTAP 的是更新版本的版本、則必須使用中的程序 xref:upgrade-map-network-ports-ontap-9-7-or-earlier.adoc[使用ONTAP 更新版本的更新版本來對應網路連接埠]。

您必須在節點3和節點4上執行這些步驟。


NOTE: 下列命令範例是指「node1」、因為在程序的這個階段、替換節點「node3」和「node4」實際上是命名為「node1」和「node2」。

.步驟
. 如果您的系統執行ONTAP 的是效能不高的版本、*停止*。您必須使用中的程序 xref:upgrade-map-network-ports-ontap-9-7-or-earlier.adoc[使用ONTAP 更新版本的更新版本來對應網路連接埠]。
. 找到節點1和節點2的連接埠和LIF組態資訊、這些資訊記錄在_移動儲存設備時準備升級_、 link:upgrade-prepare-when-moving-storage.html#prepare_move_store_3["步驟3."]。
. 找到您在_準備在移動儲存設備時升級_中記錄的連接埠、廣播網域和IPspaces資訊、 link:upgrade-prepare-when-moving-storage.html#prepare_move_store_3["步驟3."]。
+
https://hwu.netapp.com["NetApp Hardware Universe"^]

. 進行下列變更：
+
.. 如果您尚未引導並登錄到node3和node4，請執行此操作。
.. 修改將成為叢集廣播網域一部分的連接埠：
+
「網路連接埠修改-node_node_name_-port _port_name_-MTU 9000 -IPSpace叢集」

+
此範例在「node1」上新增「叢集」連接埠e1b：

+
「網路連接埠修改節點節點1 -連接埠e1b -IPSpace叢集-MTU 9000」

.. 針對每個LIF、將叢集生命區移轉至新的連接埠一次：
+
「網路介面移轉-vserver _vserver_name_-lif_lif_name_-source-Node node1 -dest-Node node1 -destation-port _port_name_'

+
移轉所有叢集生命量並建立叢集通訊時、叢集應達到仲裁。

.. 修改叢集lifs的主連接埠：
+
「網路介面修改-vserver叢集-lif_lif_name_–home-port _port_name_`

.. 從"Cluster"廣播網域中移除舊連接埠：
+
「網路連接埠廣播網域移除連接埠-IPSpace叢集-broadcast網域叢集-ports _node1:port_」

.. 顯示節點3和節點4的健全狀況：
+
「cluster show -node1_-Fields heal衛生」

.. 每個叢集LIF都必須偵聽連接埠7700。驗證叢集LIF是否正在偵聽連接埠7700：
+
：「：>網路連線偵聽show -vserver叢集」

+
連接埠7700偵聽叢集連接埠是預期結果、如下列雙節點叢集範例所示：

+
[listing]
----
Cluster::> network connections listening show -vserver Cluster
Vserver Name     Interface Name:Local Port     Protocol/Service
---------------- ----------------------------  -------------------
Node: NodeA
Cluster          NodeA_clus1:7700               TCP/ctlopcp
Cluster          NodeA_clus2:7700               TCP/ctlopcp
Node: NodeB
Cluster          NodeB_clus1:7700               TCP/ctlopcp
Cluster          NodeB_clus2:7700               TCP/ctlopcp
4 entries were displayed.
----
.. 如有必要、請針對未接聽連接埠7700的每個叢集LIF、將LIF的管理狀態設為「自己」、然後設定為「UP」：
+
：`:>net int modify -vserver cluster -lif_cluster－lif_-stue-admin down；net int modify -vserver cluster -lif_cluster－lif_-stue-admin up（net int修改-vserver叢集-lif_cluster－lif_-stue-admin up）

+
重複子步驟（g）、確認叢集LIF現在正在偵聽連接埠7700。



. [[map_9.8_5]<修改裝載資料生命週年之實體連接埠的廣播網域成員資格。您可以手動執行此動作、如所示 link:upgrade-map-network-ports-ontap-9-7-or-earlier.html#map_9.7_7["使用ONTAP VMware版9.7或更早版本對應網路連接埠、步驟7"]。建議使用ONTAP 更新的網路連線能力掃描與修復程序、如下列步驟5（a）至（g）所示。
+
.. 列出所有連接埠的連線狀態：
+
「網路連接埠連線能力顯示」

.. 修復實體連接埠的可連線性、接著在每個連接埠上執行下列命令（一次一個連接埠）：
+
"n連通 性修復-node_node_name_-port _port_name_"

+
預期會出現類似以下的警告。請視需要檢閱並輸入「y」或「n」：

+
[listing]
----
Warning: Repairing port "node_name:port" may cause it to move into a
different broadcast domain, which can cause LIFs to be re-homed away
from the port. Are you sure you want to continue? {y|n}:
----
.. 若要讓ONTAP 支援功能更新完成修復、請在最後一個連接埠上執行「可連線性修復」命令後等待約一分鐘。
.. 列出叢集上的所有廣播網域：
+
《廣播網域節目》

.. 執行可連線性修復時ONTAP 、嘗試將連接埠放在正確的廣播網域中。但是、如果無法判斷連接埠的連線能力、而且與任何現有的廣播網域不相符、ONTAP 則無法針對這些連接埠建立新的廣播網域。如果新建立的廣播網域的所有成員連接埠都會成為介面群組的成員連接埠、您可以視需要刪除這些網域。刪除廣播網域：
+
「廣播網域刪除-廣播網域_broadcast網域_網域_」

.. 檢閱介面群組組態、並視需要新增或刪除成員連接埠。新增成員連接埠至介面群組連接埠：
+
"ifgrp add-port -node_node_name_-ifgrp _ifgrp_port_-port _port_name_"

+
從介面群組連接埠移除成員連接埠：

+
「ifgrp dise-port -node_node_name_-ifgrp _ifgrp_port_-port _port_name_」

.. 視需要刪除並重新建立VLAN連接埠。刪除VLAN連接埠：
+
「vlan DELETE -node_node_name_-vlan-name _vla_port_」

+
建立VLAN連接埠：

+
「vlan create -node_node_name_-vlan-name _vla_port_」

+

NOTE: 視所升級系統的網路組態複雜度而定、您可能需要重複步驟5、子步驟（A）到（g）、直到所有連接埠都正確放置在所需位置。



. 如果系統上未設定任何VLAN、請前往 ,步驟7.。如果已設定VLAN、請還原先前在不再存在的連接埠上設定或是在移至另一個廣播網域的連接埠上設定的已移除VLAN。
+
.. 顯示已移出的VLAN：
+
顯示「叢集控制器更換網路置換VLAN」

.. 將移除的VLAN還原至所需的目的地連接埠：
+
「Dis放置VLAN還原-node_node_name_-port _port_name_-destination-port _destination_port_」

.. 確認所有已移除的VLAN均已還原：
+
顯示「叢集控制器更換網路置換VLAN」

.. VLAN會在建立後約一分鐘內自動置入適當的廣播網域。確認還原的VLAN已置於適當的廣播網域中：
+
「網路連接埠連線能力顯示」



. [[map_98_7]*從ONTAP VMware 9.8開始、ONTAP 如果在網路連接埠可到達性修復程序期間、連接埠在廣播網域之間移動、則會自動修改lifs的主連接埠。如果LIF的主連接埠已移至其他節點、或未指派、則LIF會顯示為已移除的LIF。還原主連接埠不再存在或重新放置到其他節點的已移轉LIF主連接埠。
+
.. 顯示其主連接埠可能移至其他節點或不再存在的LIF：
+
「顯示介面」

.. 還原每個LIF的主連接埠：
+
「Dis放置 介面還原-vserver _vserver_name_-lif-name _lif_name_」

.. 確認所有LIF主連接埠均已還原：
+
「顯示介面」

+
當所有連接埠均已正確設定並新增至正確的廣播網域時、網路連接埠可連線性show命令應針對所有連接的連接埠、將連線狀態報告為「正常」、對於沒有實體連線的連接埠、狀態應顯示為「不可連線」。如果有任何連接埠報告的狀態不是這兩個連接埠、請依照中所述修復連線能力 ,步驟5.。



. 驗證所有生命體都在屬於正確廣播網域的連接埠上以管理方式啟動。
+
.. 檢查是否有任何管理性停機的生命生命：
+
「網路介面show -vserver _vserver_name_-stue-admin down」

.. 檢查是否有任何運作中斷的LIF：「network interface show -vserver _vserver_name_-stue-oper down」
.. 修改任何需要修改的生命期、使其具有不同的主連接埠：
+
「網路介面修改-vserver _vserver_name_-lif_lif_-home-port _home_port_」

+

NOTE: 對於iSCSI LIF、若要修改主連接埠、則需要以管理方式關閉LIF。

.. 將非主目錄連接埠的LIF還原為各自主目錄連接埠：
+
「網路介面回復*」





您已完成實體連接埠的對應。若要完成升級、請前往 xref:upgrade-final-upgrade-steps-in-ontap-9-8.adoc[請執行ONTAP 更新版本的最終升級步驟]。
