---
permalink: upgrade/upgrade_migrate_lifs_aggregates_node2_to_node1.html 
sidebar: sidebar 
keywords: ndu, nondisruptive, upgrade, node1, node2, migrate, aggregates, lifs 
summary: 將 node2 上的邏輯介面（生命體）和資料集合體移轉至 node1 。 
---
= 將 node2 上的生命體和資料集合體移轉至 node1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在將 AFF A250 node2 轉換為磁碟機櫃之前、請先將 node2 上的邏輯介面（生命體）和資料集合體移轉至 node1 。

.開始之前
確認您符合下列要求：

* AFF A250 和 AFF A400 控制器安裝了相同的 ONTAP 版本和修補程式版本。
* 兩個 AFF A400 控制器均處於待命狀態 `Maintenance Mode` 提示。
* 您手邊有所有適當的纜線。


.關於這項工作
以下步驟是在 AFF A250 node1 上執行的。

.步驟
. 停用叢集容錯移轉自動恢復：
+
`storage failover modify -node _node_name_ -auto-giveback false`

. 停用 HA 配對兩個節點之間的自動還原：
+
`network interface modify -lif * -auto-revert false`

. 顯示所有資料網路生命的狀態：
+
`network interface show -role data`

. 顯示叢集管理階層的狀態：
+
`network interface show cluster_mgmt`

. 從節點 2 上託管的儲存虛擬機器移轉所有資料生命。
+
`network interface migrate -vserver _vserver_name_ -lif _lif_name_ -destination-node _node_name_ -destination-port _port_name_`

+

NOTE: 此命令只會移轉非 SAN 的生命體。您無法使用它來移轉 iSCSI 和 FCP 生命。

. 顯示叢集中所有資料生命的狀態：
+
`network interface show -role data`

. 如果有任何生命中斷、請輸入下列命令、並針對每個LIF輸入一次、將該生命的管理狀態設定為「UP」：
+
`network interface modify -vserver _vserver_name_ -lif _lif_name_ -home-node _node_name_ -status-admin up`

. 顯示叢集中所有資料集合體的狀態：
+
`storage aggregate show`

. 顯示容錯移轉資格：
+
「容錯移轉顯示」

. 將 node2 上的資料集合體移轉至 node1 ：
+
`storage aggregate relocation start -aggregate _aggregate_name_ -node _node2_ -destination _node1_`

. 顯示叢集中所有資料集合體的狀態：
+
`storage aggregate show`

. 顯示叢集中所有資料磁碟區的狀態：
+
「Volume show」

. 顯示 `ha` epsilon 的狀態和擁有權：
+
「叢集展示」

. 停用 `cluster ha`：
+
「叢集ha modify -configured假」

. 顯示 `ha` epsilon 的狀態和擁有權：
+
「叢集展示」

. 停止節點2：
+
`halt -node _node2_ -inhibit-takeover true -ignore-quorum-warnings true`


