---
permalink: upgrade/upgrade-attach-shelves-reassign-disks.html 
sidebar: sidebar 
keywords: reassign, disk, belong, node1, node2, node3, node4, node, attach, storage, shelves, shelf, reassign, ownership, attach storage shelves reassign disk ownership 
summary: 您必須分別將屬於節點1和節點2的磁碟重新指派給節點3和節點4。 
---
= 連接儲存櫃並重新指派磁碟擁有權
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須分別將屬於節點1和節點2的磁碟重新指派給節點3和節點4。

.關於這項工作
本節的步驟需要在 node3 和 node4 上執行。在進行下一個步驟之前，請先在 node3 上完成每個步驟，然後再在 node4 上完成每個步驟。

[[reassign-spare-disks-step1]]
.步驟
. 連接先前已連接之機櫃的儲存設備機櫃纜線：
+
** 將節點1的電纜連接到節點3
** 將節點2的電纜連接到節點4。
+

CAUTION: 在此升級過程中，請勿將新機櫃連接到 node3 或 node4。控制器升級完成後，即可將新機櫃無中斷地連接到系統。



. 驗證電源供應器和磁碟櫃的實體連線能力。
. 從node3載入器提示字元中、開機至維護模式：
+
Boot_ONTAP maint

. 顯示節點3的系統ID：
+
「展示-v」

+
[listing]
----
*> disk show -v
Local System ID: 101268854
...
----
+
記錄 node3 的系統 ID，以便在 <<reassign-disks-and-aggregates,步驟5.>> 中使用。

. [[reassign-disks-and-aggregates]]重新指派磁碟和資料聚合：
+
[role="tabbed-block"]
====
.重新分配給節點3
--
將 node1 的備援裝置磁碟、屬於根 Aggregate 的磁碟以及任何資料彙總重新分配給 node3：

`disk reassign -s <node1_sysid> -d <node3_sysid> -p <node4_sysid>`

** 此參數 `node1_sysid`是您在「關閉原始節點」中記錄的值，link:upgrade-shutdown-remove-original-nodes.html#shutdown_node_step5["步驟5."]。
** 僅當存在共享的磁碟時，才指定參數 `-p <node2_sysid>`。


--
.重新分配給節點4
--
將節點 2 的備援裝置磁碟、屬於根 Aggregate 的磁碟以及任何資料彙總重新分配給節點 4：

`disk reassign -s <node2_sysid> -d <node4_sysid> -p <node3_sysid>`

** 此參數 `node2_sysid`是您在「關閉原始節點」中記錄的值，link:upgrade-shutdown-remove-original-nodes.html#shutdown_node_step5["步驟5."]。
** 僅當存在共享的磁碟時，才指定參數 `-p <node3_sysid>`。


--
====
+
系統會顯示類似以下內容的訊息：

+
[listing]
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)?n

After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)?y
----
. 輸入「y」繼續。
+
系統會顯示類似以下內容的訊息：

+
[listing]
----
The system displays the following message:
Disk ownership will be updated on all disks previously belonging to Filer with sysid
<sysid>.
Do you want to continue (y/n)? y
----
. 輸入「y」繼續。
. 確認選項欄位中的node1根Aggregate設為「root」、其他Aggregate則設為線上：
+
「aggr狀態」

+
您應該會看到類似下列的輸出：

+
[listing]
----
*> aggr status
           Aggr State           Status                Options
          aggr0 online          raid_dp, aggr         root
                                64-bit
----
. [[reassign-spare-disks-step9]]退出維護模式：
+
《停止》

. 在 node4 上重複 <<reassign-spare-disks-step1,步驟1.>> 到 <<reassign-spare-disks-step9,步驟9.>> 的步驟。


.接下來呢？
安裝儲存設備機櫃並重新分配磁碟所有權後，link:upgrade-restore-root-volume-config.html["還原根 Volume 組態"]。
