---
permalink: upgrade/upgrade-decide-to-use-this-guide.html 
sidebar: sidebar 
keywords:  
summary: 本內容說明如何AFF 透過移動儲存設備或磁碟區來升級叢FAS 集中的處理器系統或作業系統的控制器硬體。 
---
= 決定是否要透過移動磁碟區或儲存設備來升級
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
本內容說明如何透過移動儲存設備或磁碟區、來升級叢集中 AFF 、 FAS 或 ASA 系統的控制器硬體。

如果您想在下列情況下升級控制器硬體、請使用此程序：

[NOTE]
====
* 不支援 ASA 升級至 ASA R2 更換系統。如需將資料從 ASA 移轉至 ASA R2 系統的相關資訊，請參閱link:https://docs.netapp.com/us-en/asa-r2/install-setup/set-up-data-access.html["啟用從 SAN 主機到 ASA R2 儲存系統的資料存取"^]。
* 當您升級至 ONTAP 9.15.1 或更新版本所推出的系統時， ONTAP 會轉換現有磁碟區的儲存效率，並套用利用硬體卸載功能的新儲存效率功能。這是一個自動背景程序、對系統沒有明顯的效能影響。
+
** 對於 AFF A20 ， AFF A30 ， AFF A50 ， AFF A70 ， AFF A90 ， AFF A1K ， ONTAP C30 ， AFF C60 和 AFF C80 ， AFF 會轉換所有現有精簡配置磁碟區的儲存效率，包括不使用儲存效率的磁碟區。
** 對於 FAS70 和 FAS90 系統、 ONTAP 只會轉換現有精簡配置的磁碟區的儲存效率、這些磁碟區在升級之前已啟用儲存效率。
+
link:https://docs.netapp.com/us-en/ontap/concepts/builtin-storage-efficiency-concept.html["深入瞭解儲存效率"^]。



* 由於推出自動連接埠配置功能、因此在更新過程中、硬體升級程序已在ONTAP 更新過程中簡化。


====
* 您的原始和新節點均相容且受支援。
* 原始節點和新節點執行的是 ONTAP 9.0 或更新版本。NetApp 建議您盡可能在原始節點和新節點上執行相同的 ONTAP 版本。
+
如果您的控制器升級包含混合式 ONTAP 版本、請參閱 https://docs.netapp.com/us-en/ontap/upgrade/concept_mixed_version_requirements.html["混合版本 ONTAP 叢集"^] 以取得更多資訊。

* 您正在重新使用新節點上原始節點的IP位址、網路遮罩和閘道。
* 您計畫透過移動儲存設備或移動磁碟區來升級控制器硬體。
* 如果您要透過移動儲存設備來升級、您就準備好執行中斷程序。
+
透過移動磁碟區進行升級不會中斷營運。

* 您打算將受支援模型的節點轉換成磁碟櫃、然後將其附加至新節點。


如果您要升級 MetroCluster 組態、請參閱 https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_an_upgrade_method_mcc.html["升級、重新整理或擴充MetroCluster 此功能"^]。

.相關資訊
* link:upgrade-considerations.html["升級控制器硬體的考量事項"]
* link:../choose_controller_upgrade_procedure.html["選擇升級控制器硬體的方法"]
* https://docs.netapp.com/us-en/ontap-metrocluster/maintain/concept_where_to_find_procedures_for_mcc_maintenance_tasks.html["哪裡可以找MetroCluster 到執行維護工作的程序"^]
* https://hwu.netapp.com["NetApp Hardware Universe"^]

