---
permalink: upgrade/upgrade_move_delete_recreate_san_lifs.html 
sidebar: sidebar 
keywords: cluster, san, environment, delete, lif, re-create, move san lifs, create 
summary: 視叢集內容和叢集環境而定、您需要移動、刪除或建立SAN生命期、或重新建立刪除的SAN生命期。 
---
= 移動、刪除或建立 SAN LIF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
視叢集內容和叢集環境而定、您必須移動、刪除或建立SAN生命體、或重新建立刪除的SAN生命體。



== 移轉SAN LIF的考量

只有在變更叢集內容（例如、將節點新增至叢集或從叢集刪除節點）時、才需要移動SAN LIF。移動LIF時、您不需要在叢集的附加主機與新的目標介面之間重新分區FC架構或建立新的iSCSI工作階段。

您可以使用「network interface modify」命令來移動SAN LIF。若要移動SAN LIF、您必須將LIF離線、將LIF移至不同的主節點或連接埠、然後將其重新連線至新位置。非對稱邏輯單元存取（ALUA）提供備援路徑和自動路徑選擇、是ONTAP 任何一套SAN解決方案的一部分。因此、當LIF因為移動而離線時、不會中斷I/O。主機只需重試、然後將I/O移至另一個LIF。

在LIF移動期間、您可以不中斷營運地執行下列工作：

* 以對存取LUN資料的主機而言透明的方式、將叢集的一對HA替換成升級的HA配對
* 升級目標介面卡
* 將儲存虛擬機器（SVM）的資源從叢集中的一組節點移至同一叢集中的另一組節點
* 當主機伺服器上線時、您可以將SAN LUN移至新的HA配對、而不會中斷主機伺服器對LUN資料的存取


如需詳細資訊、請參閱 https://docs.netapp.com/us-en/ontap/san-admin/move-san-lifs-task.html["SAN LIF移動"^] _SAN儲存管理_文件中的程序。



== 刪除不再需要的 SAN LIF

如果叢集位於 SAN 環境中，則必須先從原始節點中刪除不再需要的任何 SAN LIF，然後才能將原始節點從叢集中移除。

.步驟
. 如果您有iSCSI啟動器、請完成下列步驟：
+
.. 顯示目前連線至原始節點上SVM的作用中啟動器清單、每個舊生命期各顯示一次：+「iSCSI連線show -vserver _vserver_name_-lif_old_lif_」
+
下列範例顯示命令的輸出、其中使用中的啟動器連接至SVM VS1：

+
[listing]
----
cluster::> iscsi connection show -vserver vs1 -lif data2
          Tpgroup        Conn  Local           Remote          TCP Recv
Vserver   Name     TSIH  ID    Address         Address         Size
--------- -------- ----- ----- --------------- --------------- --------
vs1       data         9     1 10.229.226.166  10.229.136.188    131400
----
.. 如果仍有任何啟動器登入原始節點、請從主機電腦登出工作階段。


. 顯示連接埠集清單、以判斷原始節點上的任何iSCSI或FC生命期是否屬於連接埠集：
+
「LUN portset show」

+
以下範例顯示「LUN portset show」命令的輸出：

+
[listing]
----
cluster:> lun portset show
Virtual
Server    Portset      Protocol Port Names              Igroups
--------- ------------ -------- ----------------------- ------------
js11      ps0          mixed    LIF1,                   igroup1
                                LIF2
          ps1          iscsi    LIF3                    igroup2
          ps2          fcp      LIF4                    -
3 entries were displayed.
----
. 如果原始節點上的任何iSCSIs或FC LIF是連接埠集的成員、請將其從連接埠集移除：
+
「LUN連接埠集移除-vserver _vserver_name_-portset _portset_name_-port-name _lif_name_`

. 刪除原始節點上的LIF：
+
網路介面刪除-vserver _vserver_name_-lif_lif_name_`





== 建立新的SAN生命體、或重新建立刪除的SAN生命體

視叢集環境需求而定、您可能會決定建立新的SAN LIF、或是重新建立先前在此程序中刪除的SAN LIF。您可以使用建立或重新建立SAN LIF https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/task_creating_network_interfaces.html["網路介面建立"^] 叢集管理中的程序（使用OnCommand SURE®System Manager_文件）。

.接下來呢？
link:upgrade-remove-original-nodes.html["從叢集中移除原始節點。"]
