---
permalink: upgrade/upgrade_migrate_lifs_aggregates_node2_to_node1.html 
sidebar: sidebar 
keywords: ndu, nondisruptive, upgrade, node1, node2, migrate, aggregates, lifs 
summary: 將 node2 上的邏輯介面（生命體）和資料集合體移轉至 node1 。 
---
= 將 node2 上的生命體和資料集合體移轉至 node1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在將 AFF A250 node2 轉換為磁碟機櫃之前、請先將 node2 上的邏輯介面（生命體）和資料集合體移轉至 node1 。

.開始之前
確認您符合下列要求：

* AFF A250 和 AFF A400 控制器執行相同的 ONTAP 版本和修補程式版本。
+
[NOTE]
====
** 您必須在每個 AFF A400 上以網路開機並安裝與 AFF A250 上執行的版本相同的 ONTAP 版本。
** 每個 AFF A400 的主要和備份開機映像都必須具有相同的 ONTAP 版本。
** 如果先前已設定 AFF A400 叢集、則必須執行來清除任何剩餘叢集組態 `wipeconfig` 從開機功能表。


====
* 兩個 AFF A400 控制器都會在載入程式提示時處於待命狀態。
* 您手邊有所有適當的纜線。


.關於這項工作
以下步驟是在 AFF A250 node1 上執行的。

.步驟
. 存取進階權限層級：
+
"進階權限"

. 停用儲存容錯移轉自動恢復：
+
`storage failover modify -node _node1_ -auto-giveback false`

. 停用 HA 配對兩個節點之間的自動還原：
+
`network interface modify -lif * -auto-revert false`

. 顯示所有資料網路生命的狀態：
+
`network interface show -role data`

. 顯示叢集管理階層的狀態：
+
`network interface show -role cluster_mgmt`

. 從節點 2 上託管的儲存虛擬機器移轉所有資料生命。
+
`network interface migrate -vserver _vserver_name_ -lif _lif_name_ -destination-node _node1_ -destination-port _port_name_`

+

NOTE: 此命令只會移轉非 SAN 的生命體。您無法使用它來移轉 iSCSI 和 FCP 生命。

. 顯示叢集中所有資料生命的狀態：
+
`network interface show -role data`

. 如果有任何生命中斷、請輸入下列命令、並針對每個LIF輸入一次、將該生命的管理狀態設定為「UP」：
+
「網路介面修改-vserver _vserver_name_-lif_lif_name_-stue-admin up」

. 顯示叢集中所有資料集合體的狀態：
+
`storage aggregate show`

. 顯示容錯移轉資格：
+
「容錯移轉顯示」

. 將 node2 上的資料集合體移轉至 node1 ：
+
`storage aggregate relocation start -aggregate _aggregate_name_ -node _node2_ -destination _node1_`

. 顯示叢集中所有資料集合體的狀態：
+
`storage aggregate show`

. 顯示叢集中所有資料磁碟區的狀態：
+
「Volume show」

. 顯示 `ha` epsilon 的狀態和擁有權：
+
「叢集展示」

. 停用 `cluster ha`：
+
「叢集ha modify -configured假」

. 顯示 `ha` epsilon 的狀態和擁有權：
+
「叢集展示」

. 停止節點2：
+
`halt -node _node2_ -inhibit-takeover true -ignore-quorum-warnings true`



.接下來呢？
link:upgrade_convert_node2_drive_shelf_connect_node4.html["將 node2 轉換為磁碟機櫃、並連線至 node4"]
