---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/aggregate_relocation_failures.html 
keywords: aggregate, relocation, failures, ARL 
summary: '疑難排解使用命令來升級執行 ONTAP 9.15.1 或更新版本的控制器時、可能發生的 Aggregate 重新定位故障 `system controller replace` 。' 
---
= Aggregate重新配置失敗
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在升級期間、Aggregate重新配置（ARL）可能會在不同的點失敗。



== 檢查Aggregate重新配置失敗

在程序期間、ARL可能會在階段2、階段3或階段5中失敗。

.步驟
. 輸入下列命令並檢查輸出：
+
《集合重遷秀》

+
「shorage aggregate regate regate regate show」命令會顯示哪些Aggregate已成功重新配置、哪些未重新配置、以及故障原因。

. 檢查主控台是否有任何EMS訊息。
. 請採取下列其中一項行動：
+
** 根據「儲存集合體重新定位show」命令的輸出和EMS訊息的輸出、採取適當的修正行動。
** 使用「overre-tetoes」選項或「superre-dite-checks」選項的「shorage aggregate regate or搬 移start」命令、強制重新配置集合體或集合體。


+
如需有關「強制集合重新定位開始」、「置換-否決」和「置換-目的地-檢查」選項的詳細資訊、請參閱 link:other_references.html["參考資料"] 若要連結至_Estrat9 ONTAP 8命令：手動頁面參考_。





== 在完成升級後、原本位於節點1上的Aggregate歸node4所有

在升級程序結束時、node3應該是集合體的新主節點、而該主節點原本是node1作為主節點。您可以在升級後重新配置。

.關於這項工作
在下列情況下、Aggregate可能無法正確重新定位、將node1當作其主節點、而非node3：

* 在第3階段期間、當Aggregate從節點2重新定位至節點3時。正在重新部署的部分集合體將node1當作其主節點。例如、此類Aggr_nnode_1可稱為Aggr_node_1。如果在第3階段重新配置aggr_node_1失敗、且無法強制重新配置、則會將Aggregate留在node2上。
* 在第4階段之後、節點2被節點4取代。當節點2被替換時、aggr_node_1會以node4做為主節點、而非node3連線。


在儲存容錯移轉啟用後、您可以完成下列步驟、在第6階段之後修正不正確的擁有權問題：

.步驟
. 輸入下列命令以取得Aggregate清單：
+
「torage Aggregate show -nodes _node4_-is hometrue」

+
若要識別未正確重新放置的集合體、請參閱您在一節中取得的節點1主擁有者之集合體清單 link:prepare_nodes_for_upgrade.html["準備節點以進行升級"] 並將其與上述命令的輸出進行比較。

. 將步驟1的輸出與您在區段中針對節點1擷取的輸出進行比較 link:prepare_nodes_for_upgrade.html["準備節點以進行升級"] 並記下任何未正確重新定位的集合體。
. [[auto_aggr_elocation_fe_Step3]]重新定位節點4上留下的集合體：
+
Check Alignment of PHs>將Agrage Aggregate重新定位從節點節點節點_node4_-aggr _node_1_-destate _node3_

+
在此重新定位期間、請勿使用「-ND-控制 器升級」參數。

. 確認node3現在是Aggregate的主擁有者：
+
「torage Aggregate show -Aggregate _aggr1、aggr2、aggr3..._-Fields home-name'

+
「_aggr1、aggr2、aggr3..._」是集合體清單、其中節點1是原始擁有者。

+
沒有node3做為主擁有者的Aggregate可以使用中相同的重新配置命令、將其重新定位至node3 <<auto_aggr_relocate_fail_Step3,步驟3.>>。


