---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/complete-preparation-for-upgrade.html 
keywords: ip, address, external, key, management, server, storage, encryption, upgrading, authentication 
summary: '使用命令升級執行 ONTAP 9.15.1 或更新版本的控制器時、請設定及管理儲存加密、管理驗證金鑰、以及靜態 SnapMirror 關係 `system controller replace` 。' 
---
= 完成升級準備工作
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
了解 ONTAP 授權以及如何使用 Onboard Key Manager (OKM) 管理儲存加密。您也可以選擇停止 SnapMirror 關係。



== 了解 ONTAP 授權

如需 ONTAP 授權的詳細資訊、請 https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html["授權管理"^]參閱。


NOTE: 在控制器上使用未獲授權的功能、可能會使您無法遵守授權合約。



== 使用 Onboard Key Manager 管理儲存加密

使用 Onboard Key Manager（OKM）來管理加密金鑰。如果您已設定 OKM，則必須在開始升級之前記錄通關密語和備份資料。

.步驟
. 記錄叢集範圍的複雜密碼。
+
這是使用 CLI 或 REST API 設定或更新 OKM 時所輸入的複雜密碼。

. 驗證通關密語和金鑰管理程式操作：
+
「安全金鑰管理程式內建同步」

+
出現提示時，輸入您在上一個步驟中記錄的叢集範圍 OKM 複雜密碼。

. 透過查看以下命令的輸出來驗證 cc-mode 是否已啟用：
+
`security key-manager config show`

. 備份金鑰管理器資訊：
+
「安全金鑰管理程式內建show Backup」





== 或者，也可以讓這些 SnapMirror 關係平靜下來

在繼續執行此程序之前、您必須確認所有SnapMirror關係均已靜止。當SnapMirror關係靜止時、它會在重新開機和容錯移轉之間保持靜止。

.步驟
. 驗證目的地叢集上的SnapMirror關係狀態：
+
「napmirror show」

+
[NOTE]
====
如果狀態為「Transferring（正在傳輸）」、您必須中止傳輸：「napmirror abort-destination-vserver _vserver_name_」

====
+
如果SnapMirror關係未處於「傳輸」狀態、則中止將會失敗。

. 停止叢集之間的所有關係：
+
`snapmirror quiesce -destination-vserver *`



.接下來呢？
準備升級後， link:relocate_non_root_aggr_nas_data_lifs_node1_node2.html["將節點 1 擁有的非根 Aggregate 和 NAS 資料 LIF 重新配置到節點 2"]。
