---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrading, controllers, ARL 
summary: '了解是否可以使用 `system controller replace`命令升級至 ONTAP 9.15.1 或更新版本中引入的控制器。' 
---
= 使用ARL升級控制器的準則
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
若要了解是否可以使用 ARL 升級至 ONTAP 9.15.1 或更新版本中引入的一對控制器，取決於平台以及原始控制器和替換控制器的組態。



[[supported-upgrades-for-arl]]
== 支援ARL升級

使用此 ARL 程序升級一對節點之前、請先檢閱下列需求、以確保您的組態受到支援：

* 確認可在原始控制器和更換控制器上執行 ARL 。
* 檢查原始系統所有已定義彙總的大小和支援的磁碟數量。然後，將彙總大小和支援的磁碟數量與新系統支援的 Aggregate 大小和磁碟數量進行比較。請參閱 link:other-references.html["參考資料"] 以連結至 _Hardware Universe_，其中提供了此資訊。新系統支援的 Aggregate 大小和磁碟數量必須等於或大於原始系統支援的 Aggregate 大小和磁碟數量。
* 在叢集混合規則中驗證，當原始控制器被替換時，新節點是否可以加入現有節點所在的叢集。如需叢集混合規則的詳細資訊，請參閱 link:other-references.html["參考資料"] 以連結至 _Hardware Universe_。
* 如果您的系統（例如 AFF 700 ）具有下列組態、請將叢集生命體移轉並重新主控至每個節點兩個叢集連接埠：
* 每個節點有兩個以上的叢集連接埠
* 在 SLOT4 中以中斷模式建立連接埠 E4A 、 e4b 、 e4c 和 e4d 的叢集互連卡、以及連接埠 e4e 、 e4f 、 e4g 和 e4H
+

NOTE: 在每個節點上執行超過兩個叢集連接埠的控制器升級、可能會導致新控制器在升級後遺失叢集生命體。

+
有關詳細信息，請參閱知識庫文章 link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_delete_unwanted_or_unnecessary_cluster_LIFs["如何刪除不需要或不必要的叢集生命"^]。



使用ARL的控制器升級支援使用SnapLock 「支援」的系統、這些系統均設定了「支援使用者支援使用者支援的功能」和SnapLock 「支援使用者支援



[[two-node-switchless-clusters]]
== 雙節點無交換式叢集

如果您要升級雙節點無交換式叢集中的節點、則可在執行升級時、將節點留在無交換器叢集中。您不需要將它們轉換成交換式叢集。



[[upgrades-not-supported-for-arl]]
== 不支援ARL升級

您無法升級不支援連接至原始控制器之磁碟櫃的替換控制器。

請參閱 link:other-references.html["參考資料"]，以連結至 _Hardware Universe_ 以取得磁碟支援資訊。

如果要升級具有內部磁碟機的入門層級控制器，請參閱 link:other-references.html["參考資料"] 以連結至「透過移動 Volume 或儲存設備進行升級」，然後前往「透過移動 Volume 升級執行叢集式 Data ONTAP 的一對節點」程序。



[[troubleshoot]]
== 疑難排解

如果在升級控制器過程中出現任何問題，請參閱link:aggregate_relocation_failures.html["疑難排解"]了解更多資訊和可能的解決方案。

如果您找不到解決所遇到問題的解決方案、請聯絡技術支援部門。

.接下來呢？
在查閱使用 ARL 升級控制器的準則後link:overview_of_the_arl_upgrade.html["瞭解 ARL 升級順序"]。
