---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/reboots_panics_or_power_cycles.html 
keywords: reboots, panics, power, cycles, node, crash 
summary: '當使用命令升級執行 ONTAP 9.15.1 或更新版本的控制器時、系統可能會在不同階段當機、例如重新開機、驚慌或是經歷關機循環 `system controller replace` 。' 
---
= 重新開機、出現問題或重新開機
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在升級的不同階段、系統可能會當機–重新開機、發生恐慌或經歷關機循環。

這些問題的解決方法取決於何時發生。



== 在預先檢查階段重新開機、出現問題或重新開機



=== 在HA配對仍啟用的預先檢查階段之前、節點1或節點2會當機

如果在預先檢查階段之前、節點1或節點2當機、則尚未重新放置任何集合體、而且HA配對組態仍處於啟用狀態。

.關於這項工作
接管和恢復可以正常進行。

.步驟
. 檢查主控台是否有系統可能發出的EMS訊息、並採取建議的修正行動。
. 繼續執行節點配對升級程序。




== 在第一個資源釋出階段中重新開機、出現問題或重新開機



=== 節點1在第一個資源釋出階段當機、但HA配對仍啟用

部分或全部的集合體已從節點1重新定位至節點2、但HA配對仍會啟用。節點2會接管節點1的根磁碟區、以及未重新放置的任何非根Aggregate。

.關於這項工作
移轉的集合體擁有權與因擁有者未變更而接管的非根集合體擁有權相同。

當節點1進入「等待恢復」狀態時、節點2會傳回所有節點1非根Aggregate。

.步驟
. 節點1開機後、節點1的所有非根Aggregate都會移回節點1。您必須手動將Aggregate從node1重新配置為node2：「torage Aggregate regate reg搬 移起始節點節點1 -目的地節點2 - Aggregate -list *-ndocu控制 器升級為true」
. 繼續執行節點配對升級程序。




=== 當HA配對停用時、節點1會在第一個資源釋出階段當機

節點2不會接管、但它仍在提供來自所有非根Aggregate的資料。

.步驟
. 啟動節點1。
. 繼續執行節點配對升級程序。




=== 節點2在第一個資源釋放階段失敗、HA配對仍啟用

節點1已將部分或全部的Aggregate重新放置到節點2。HA配對已啟用。

.關於這項工作
節點1會接管節點2的所有Aggregate、以及它已重新定位至節點2的任何專屬Aggregate。當節點2開機時、會自動完成Aggregate重新配置。

.步驟
. 啟動節點2。
. 繼續執行節點配對升級程序。




=== 節點2在第一個資源發行階段和停用HA配對之後當機

節點1不會接管。

.步驟
. 啟動節點2。
+
節點2開機時、所有集合體都會發生用戶端中斷。

. 繼續執行其餘的節點配對升級程序。




== 在第一次驗證階段重新開機、出現問題或重新開機



=== 在停用HA配對的第一個驗證階段、節點2當機

由於HA配對已停用、因此節點3不會在節點2當機後接管。

.步驟
. 啟動節點2。
+
節點2開機時、所有集合體都會發生用戶端中斷。

. 繼續執行節點配對升級程序。




=== 在停用HA配對的第一個驗證階段、節點3當機

節點2不會接管、但它仍在提供來自所有非根Aggregate的資料。

.步驟
. 啟動節點3。
. 繼續執行節點配對升級程序。




== 在第一個資源恢復階段重新開機、出現問題或重新開機



=== 節點2會在Aggregate重新配置期間的第一個資源重新取得階段當機

節點2已將部分或全部的Aggregate從節點1重新定位至節點3。node3可處理重新放置之集合體的資料。HA配對已停用、因此不會接管。

.關於這項工作
未重新部署的集合體發生用戶端中斷。在開機節點2時、節點1的集合體會重新定位至節點3。

.步驟
. 啟動節點2。
. 繼續執行節點配對升級程序。




=== 節點3會在Aggregate重新配置期間的第一個資源重新取得階段當機

如果節點3在節點2將Aggregate重新定位至節點3時當機、則該工作會在節點3開機後繼續執行。

.關於這項工作
節點2繼續提供其餘的Aggregate、但在節點3開機時、已重新放置到節點3的Aggregate會遇到用戶端中斷。

.步驟
. 啟動節點3。
. 繼續升級控制器。




== 在檢查後階段重新開機、出現問題或重新開機



=== 節點2或節點3會在檢查後階段當機

HA配對已停用、因此這不是接管。屬於重新開機節點的集合體發生用戶端中斷。

.步驟
. 開啟節點。
. 繼續執行節點配對升級程序。




== 在第二個資源釋出階段重新開機、出現問題或重新開機



=== 節點3在第二個資源釋出階段當機

如果節點3在節點2重新放置Aggregate時當機、則會在節點3開機後繼續執行工作。

.關於這項工作
節點2繼續提供其餘的Aggregate、但已重新放置到節點3的Aggregate、而節點3本身的Aggregate則會在節點3開機時遇到用戶端中斷。

.步驟
. 啟動節點3。
. 繼續執行控制器升級程序。




=== 節點2在第二個資源釋放階段當機

如果節點2在Aggregate重新配置期間當機、則不會接管節點2。

.關於這項工作
node3繼續提供已重新部署的集合體、但node2擁有的集合體會遭遇用戶端中斷。

.步驟
. 啟動節點2。
. 繼續執行控制器升級程序。




== 在第二個驗證階段重新開機、出現問題或重新開機



=== 節點3在第二個驗證階段當機

如果節點3在此階段當機、則不會發生接管、因為HA配對已停用。

.關於這項工作
在節點3重新開機之前、所有Aggregate都會發生用戶端中斷。

.步驟
. 啟動節點3。
. 繼續執行節點配對升級程序。




=== 節點4在第二個驗證階段當機

如果節點4在此階段當機、則不會發生接管。node3提供來自集合體的資料。

.關於這項工作
非根Aggregate發生中斷、在節點4重新開機之前、這些非根Aggregate已經重新部署。

.步驟
. 叫出節點4。
. 繼續執行節點配對升級程序。

