---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/stage_6_index.html 
keywords: complete upgrade, node, unified, target, storage, encryption, stage 6 
summary: '在執行 ONTAP 9.15.1 或更新版本的控制器上使用命令、進行 ARL 升級的第 6 階段程序順序 `system controller replace` 。' 
---
= 第 6 階段總覽
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在第6階段期間、您將確認新節點已正確設定、如果新節點已啟用加密、則您可以設定及設定儲存加密或NetApp Volume Encryption。您也應該取消委任舊節點、然後恢復SnapMirror作業。

.步驟
. link:manage-authentication-using-kmip-servers.html["使用KMIP伺服器管理驗證"]
. link:ensure_new_controllers_are_set_up_correctly.html["確認新的控制器已正確設定"]
. link:set_up_storage_encryption_new_module.html["在新的控制器模組上設定儲存加密"]
. link:set_up_netapp_volume_encryption_new_module.html["在新的控制器模組上設定NetApp Volume或Aggregate Encryption"]
. link:decommission_old_system.html["取消委任舊系統"]
. link:resume_snapmirror_operations.html["恢復SnapMirror作業"]


[NOTE]
====
AFF A20 ， AFF A50 ， AFF A70 ， AFF A90 ， AFF A1K ， FAS70 和 FAS90 系統共享 100GbE 網路連接埠，可同時用於叢集和 HA 連線。這些系統可支援 10GbE 或 25GbE 叢集連線至傳統叢集交換器；不過、 NetApp 建議在不再需要 10GbE 和 25GbE 交換器時、更新至 100GbE 叢集速度。如需詳細資訊、請參閱下列知識庫文章：

* link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_configure_10G_or_25G_cluster_ports_on_a_new_cluster_setup["如何在新的叢集設定上設定 10G 或 25G 叢集連接埠"^]
* link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_convert_existing_10G_or_25G_cluster_ports_to_40G_or_100G_cluster_ports["如何將現有 10G 或 25G 叢集連接埠轉換為 40G 或 100g 叢集連接埠"^]


AFF A20 系統可共用 10GbE 和 25GbE 網路連接埠，用於叢集和 HA 連線。這是 AFF A20 系統唯一支援的網路連接埠叢集連線。

如果無法將現有節點上的 e0a 或 e0b 叢集連接埠連結至新節點上的叢集連接埠、請參閱 link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-166978["NetApp Bug Online Bug ID CONTAP-166978"^]。

====