---
sidebar: sidebar 
permalink: upgrade-arl-auto/decide_to_use_the_aggregate_relocation_guide.html 
keywords: aggregate relocation, decide to use, upgrade, model, matrix, replacement, controller 
summary: 使用ONTAP 「系統控制器更換」命令、決定是否使用ARL來升級執行《SES9.5 to 9.7》的控制器。 
---
= 決定是否使用此聚合遷移程序
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
升級控制器硬體有多種聚合重定位 (ARL) 方法。此流程說明如何在執行 ONTAP 9.7、9.6 或 9.5 的系統上使用「系統控制器取代指令」透過 ARL 升級控制器硬體。只有經驗豐富的 ONTAP 管理員才應使用此複雜程序。

為了幫助您確定此 ARL 程式是否適合您的控制器硬體升級，您應該檢查以下所有情況以了解支援的升級：

* 您正在升級執行ONTAP S69.5、9.6或9.7的NetApp控制器。本文件不適用於ONTAP 升級至更新至更新版本。
* 您不想將新的控制器新增為叢集的新 HA 配對，並使用 Volume Moves 移轉資料。
* 您在管理ONTAP 方面經驗豐富、而且對於在診斷權限模式下工作的風險感到自在。
* 您的硬體升級組合列在<<sys_commands_95_97_supported_systems,支援模型矩陣>> 。
* 如果您要升級MetroCluster 的是一個版本為4節點或更高的FC組態、而且所有節點都執行ONTAP 的是版本號為32的9.6或9.7。


[NOTE]
====
* 如果您透過在同一機箱中交換控制器模組（例如AFF A800或AFF C800）來升級系統， NetApp強烈建議使用升級程序link:../upgrade-arl-auto-in-chassis/index.html["使用 ARL 升級控制器模型，保留現有的系統機殼和磁碟"]。此 ARL 流程包括在升級過程中移除和安裝控制器時確保內部磁碟在機箱中保持安全的步驟。
+
link:../upgrade-arl-auto-in-chassis/decide-to-use-the-aggregate-relocation-guide.html#supported-systems-in-chassis["了解使用 ARL 支援的系統升級組合，保留現有系統機箱和磁碟"]。

* 您可以在此程序中使用NetApp儲存加密（NSE）、NetApp Volume加密（NVE）和NetApp Aggregate加密（NAE）。


====


== 支援的系統升級組合

下表顯示了使用此 ARL 程式進行控制器升級所支援的型號矩陣。

[cols="50,50"]
|===
| 舊控制器 | 更換控制器 


| FAS8020、FAS8040、FAS8060、FAS8080 | FAS8200、FAS8300、FAS8700、FAS9000 


| AFF8020、AFF8040、AFF8060、AFF8080 | Exe300、ExeA400、Exe4A700^1^、AFF AFF AFF AFF ExA800^2^ 


| FAS8200 | FAS8700、FAS9000、FAS8300、4^^、^^5^ 


| 部分A300 AFF | Exe7700^1^、Ex4A800^2^^、^^3^、ExA400^4^、^^5^ AFF AFF AFF 
|===

NOTE: 如果您的控制器升級模式組合不在上表中、請聯絡技術支援部門。

支援針對AFF 該系統的^1^ARL自動升級ONTAP 功能、可從Ze 9.7P2取得。

^2^如果您要更新AFF 至支援內部和外部磁碟的FSIFA800或系統、則必須遵循內部NVMe磁碟上根Aggregate的特定指示。請參閱 link:set_fc_or_uta_uta2_config_on_node3.html#step14["檢查並設定節點3步驟14上的UTA/UTA2連接埠"] 和 link:set_fc_or_uta_uta2_config_node4.html#step14["檢查並設定節點4步驟14上的UTA/UTA2連接埠"]。

從AFF We 9.7P5 AFF 支援從32 A300自動升級至32 A800系統的^3^ARL ONTAP 。

從功能強大的支援功能、從功能完善的支援功能AFF 升級至AFF 功能完善的支援系統、從功能完善的功能升級至功能完善的功能ONTAP 、從功能完善的功能升級至功能完善的功能。

^5^如果您要在AFF 雙節點無交換式叢集組態中、從Sfzha300升級AFF 至Sf2 A400或FAS8200、則必須選擇暫用叢集連接埠來升級控制器。以乙太網路套裝組合形式提供兩種組態：夾層卡連接埠為乙太網路類型、夾層連接埠為FC類型、而以FC套裝組合形式提供夾層連接埠為FC類型。AFF

* 對於採用乙太網路類型組態的FASA400或FAS8300、您可以使用兩個夾層連接埠中的任何一個作為暫用叢集連接埠。AFF
* 若為AFF 採用FC類型組態的Arf-A400或FAS8300、您必須新增四埠10GbE網路介面卡（零件編號X1147A）、以提供暫用叢集連接埠。
* 使用暫用叢集連接埠完成控制器升級之後、您可以不中斷營運地將叢集LIF移轉至e3a和e3b、AFF 將100GbE連接埠移轉至ESIA400系統、以及將FAS8300系統上的e0c和e0d、100GbE連接埠。




== 選擇不同的硬體升級程序

* link:../upgrade-arl/index.html["查看可用於升級控制器硬體的替代 ARL 方法"]。
* 如果您偏好其他方法來升級控制器硬體、並願意進行Volume移動、請參閱 link:other_references.html["參考資料"] 若要透過移動磁碟區或儲存設備連結至_Upgrade。


.相關資訊
參考link:other_references.html["參考資料"]連結到_ONTAP 9 文件_。
