---
sidebar: sidebar 
permalink: upgrade-arl-auto/get_ip_address_of_external_kms_for_storage_encryption.html 
keywords: IP address, external, key management, server, storage encryption, kmip, onboard key management 
summary: 使用ONTAP 「系統控制器更換」命令、將執行版本資訊9.5的控制器升級至9.7時、請設定並管理儲存加密、管理驗證金鑰、以及靜止SnapMirror關係。 
---
= 取得外部金鑰管理伺服器的IP位址以進行儲存加密
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
升級後、您必須立即設定儲存加密、並建立全叢集驗證金鑰、以取代先前的節點層級驗證金鑰。

.步驟
. 安裝必要的用戶端和伺服器安全通訊端層（SSL）憑證、以與金鑰管理伺服器通訊：
+
「安全憑證安裝」

. 在每個節點上使用下列命令、在所有節點上設定儲存加密：
+
「安全的金鑰管理程式設定」

. 新增每個金鑰管理伺服器的IP位址：
+
「安全金鑰管理程式新增」

. 確認叢集中所有節點上都已設定並可使用相同的金鑰管理伺服器：
+
「安全金鑰管理程式顯示狀態」

. 建立新的全叢集驗證金鑰：
+
「安全金鑰管理程式建立金鑰」

. 記下新的驗證金鑰ID。
. 使用新的驗證金鑰重新輸入所有自我加密磁碟機的金鑰：
+
「torage加密磁碟modify -disk *-data-key-id _imalization_key_id_」





== 使用KMIP伺服器管理驗證

利用SKE9.5到9.7、您可以使用金鑰管理互通性傳輸協定（KMIP）伺服器來管理驗證金鑰。ONTAP

步驟

. 新增控制器：
+
「安全金鑰管理程式設定節點_new_manager_name_」

. 新增金鑰管理程式：
+
「安全金鑰管理程式- add _key_manager_server_ip_address_」

. 驗證金鑰管理伺服器是否已設定、且可供叢集中的所有節點使用：
+
「安全金鑰管理程式顯示狀態」

. 將驗證金鑰從所有連結的金鑰管理伺服器還原至新節點：
+
「安全金鑰管理程式還原-node_new_控制 器名稱_」

. 使用新的驗證金鑰重新輸入所有自我加密磁碟：
+
「torage加密磁碟修改磁碟*（-data-key-id nonMSID Ak）」

. 如果您使用聯邦資訊處理標準（FIPS）、請使用新的驗證金鑰重新鎖定所有自我加密磁碟：
+
「torage加密磁碟修改磁碟*（-fIPS-key-id nonMSID Ak）」





== 使用Onboard Key Manager管理儲存加密

您可以使用OKM來管理加密金鑰。如果您打算使用OKM、則必須在開始升級之前記錄密碼和備份資料。

.步驟
. 將通關密碼儲存至安全位置。
. 建立備份以供還原之用。執行下列命令並儲存輸出：
+
「金鑰管理程式內建展示備份」





== 使用Onboard Key Manager管理儲存加密

您可以使用OKM來管理加密金鑰。如果您打算使用OKM、則必須在開始升級之前記錄密碼和備份資料。

.步驟
. 將通關密碼儲存至安全位置。
. 建立備份以供還原之用。執行下列命令並儲存輸出：
+
「安全金鑰管理程式內建show Backup」





== 靜止SnapMirror關係（選用）

在繼續執行此程序之前、您必須確認所有SnapMirror關係均已靜止。當SnapMirror關係靜止時、它會在重新開機和容錯移轉之間保持靜止。

.步驟
. 驗證目的地叢集上的SnapMirror關係狀態：
+
「napmirror show」

+
[NOTE]
====
如果狀態為「Transferring（正在傳輸）」、您必須中止傳輸：「napmirror abort-destination-vserver _vserver_name_」

====
+
如果SnapMirror關係未處於「傳輸」狀態、則中止將會失敗。

. 停止叢集之間的所有關係：
+
「napmirror quiesce -destination-vserver _vserver_name_」


