---
sidebar: sidebar 
permalink: upgrade-arl-auto/install_boot_node3.html 
keywords: install, boot, node3 relocation, nodes, V-series, storage disks 
summary: 使用ONTAP 「系統控制器更換」命令、將執行ONTAP 版本號從9.5升級至9.7的控制器時、請安裝及開機節點3並安裝效益分析軟體。 
---
= 安裝及開機節點3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您必須在機架中安裝node3、將node1的連線傳輸至node3、開機node3及安裝ONTAP 支援。接著、您必須重新指派節點1的任何備用磁碟、屬於根磁碟區的任何磁碟、以及任何未在程序中稍早重新放置到節點2的非根Aggregate、如本節所述。

.關於這項工作
重新配置作業會在此階段開始時暫停。此程序大部分是自動化的；此作業會暫停、以便您檢查其狀態。您必須手動恢復作業。此外、您必須驗證SAN LIF是否已成功移至節點3。

如果netboot node3沒有ONTAP 安裝在node1上的相同版本的支援功能、您就需要netboot node3。安裝node3之後、請從ONTAP 儲存在Web伺服器上的Image9映像啟動節點3。接著、您可以依照中的指示、將正確的檔案下載到開機媒體裝置、以供後續系統開機 link:prepare_for_netboot.html["準備netboot"]。

.重要事項：
* 如果您要升級連接至儲存陣列的V系列系統、或是升級連接FlexArray 至儲存陣列的含有「虛擬化」軟體的系統、則必須完成 <<auto_install3_step1,步驟1.>> 透過 <<auto_install3_step21,步驟21>>、然後保留本節、並依照中的指示進行 link:set_fc_or_uta_uta2_config_on_node3.html#configure-fc-ports-on-node3["在節點3上設定FC連接埠"] 和 link:set_fc_or_uta_uta2_config_on_node3.html#check-and-configure-utauta2-ports-on-node3["檢查並設定節點3上的UTA/UTA2連接埠"] 視需要在維護模式中輸入命令。接著您必須返回本節並繼續 <<auto_install3_step23,步驟23>>。
* 如果您要升級具有儲存磁碟的系統、則必須完成此一整節、然後前往 link:set_fc_or_uta_uta2_config_on_node3.html#configure-fc-ports-on-node3["在節點3上設定FC連接埠"] 和 link:set_fc_or_uta_uta2_config_on_node3.html#check-and-configure-utauta2-ports-on-node3["檢查並設定節點3上的UTA/UTA2連接埠"] 區段、在叢集提示字元中輸入命令。


.步驟
. [[[auto_install3_step1]]請確定您有節點3的機架空間。
+
如果節點1和節點2位於不同的機箱中、您可以將節點3放在與節點1相同的機架位置。但是、如果節點1與節點2位於同一個機箱中、則您需要將節點3放入自己的機架空間、最好是靠近節點1的位置。

. [[[auto_install3_step2]]依照節點機型的安裝與設定指示_、在機架中安裝節點3。
+

NOTE: 如果您要升級到同一機箱中同時具有兩個節點的系統、請在機箱中安裝node4以及node3。如果沒有、當您開機節點3時、節點的行為就會如同雙機箱組態、當您開機節點4時、節點之間的互連就不會出現。

. [[auto_install3_step3]]纜線節點3、將連線從節點1移至節點3。
+
使用FlexArray 節點3平台的_安裝與設定說明_或_《_》《虛擬化安裝要求與參考_》、適當的磁碟櫃文件、以及_高可用度管理_來連接下列連線。

+
請參閱 link:other_references.html["參考資料"] 連結至_ FlexArray 《虛擬化安裝要求與參考資料》和_《高可用度管理》。

+
** 主控台（遠端管理連接埠）
** 叢集連接埠
** 資料連接埠
** 叢集與節點管理連接埠
** 儲存設備
** SAN組態：iSCSI乙太網路和FC交換器連接埠
+

NOTE: 您可能不需要將互連卡或叢集互連纜線連線從節點1移至節點3、因為大多數平台機型都有獨特的互連卡模式。若要進行支援、您需要將FC-VI纜線連線從節點1移至節點3。MetroCluster如果新主機沒有FC-VI卡、您可能需要移動FC-VI卡。



. [[auto_install3_step4]]開啟節點3的電源、然後在主控台終端按Ctrl-C存取開機環境提示字元、以中斷開機程序。
+
如果您要升級到同一機箱中同時具有兩個節點的系統、節點4也會重新開機。不過、您可以忽略node4開機、直到稍後再執行。

+

NOTE: 當您啟動節點3時、可能會看到下列警告訊息：

+
....
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
....
. [[auto_install3_step5]]如果您在中看到警告訊息 <<auto_install3_step4,步驟4.>>、請採取下列行動：
+
.. 檢查可能指出NVRAM電池電量不足以外問題的任何主控台訊息、並視需要採取任何必要的修正行動。
.. 讓電池充電並完成開機程序。
+

WARNING: *注意：請勿置換延遲；若不讓電池充電、可能導致資料遺失。*

+

NOTE: 請參閱 link:prepare_for_netboot.html["準備netboot"]。





. [[autoc9597_istall3_step6]]選擇下列其中一個動作來設定netboot連線。
+

NOTE: 您必須使用管理連接埠和IP做為netboot連線。請勿使用資料LIF IP、否則在執行升級時可能會發生資料中斷。

+
[cols="30,70"]
|===
| 如果動態主機組態傳輸協定（DHCP）是... | 然後... 


| 執行中 | 在開機環境提示字元中輸入下列命令、即可自動設定連線：「ifconfige0M -auto」 


| 未執行  a| 
在開機環境提示字元中輸入下列命令、手動設定連線：
`ifconfig e0M -addr=_filer_addr_ -mask=_netmask_ -gw=_gateway_ -dns=_dns_addr_ -domain=_dns_domain_`

`_filer_addr_` 為儲存系統的IP位址（必填）。
`_netmask_` 是儲存系統的網路遮罩（必填）。
`_gateway_` 是儲存系統的閘道。（必填）。
`_dns_addr_` 為網路上名稱伺服器的IP位址（選用）。
`_dns_domain_` 為網域名稱服務（DNS）網域名稱。如果使用此選用參數、則不需要netboot伺服器URL中的完整網域名稱；您只需要伺服器的主機名稱。


NOTE: 您的介面可能需要其他參數。在韌體提示字元中輸入「Help ifconfig」以取得詳細資料。

|===
. [[step7]]在節點3上執行netboot：
+
[cols="30,70"]
|===
| 適用於... | 然後... 


| FAS / AFF8000系列系統 | “netboot \http://<web_server_ip/path_to_web-accessible_directory>/netboot/kernel` 


| 所有其他系統 | “netboot \http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz` 
|===
+
「<path_to_the_web-易於 存取的目錄>」應該會引導您下載該節中的「<ONTAP_VERSION >_image.tgz」 link:prepare_for_netboot.html["準備netboot"]。

+

NOTE: 請勿中斷開機。

. [[step8]從開機功能表中選取選項「（7）Install new software first（先安裝新軟體）」。
+
此功能表選項會下載新ONTAP 的功能表映像、並將其安裝至開機裝置。

+
請忽略下列訊息：

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
本附註適用於ONTAP 不中斷營運的更新功能、不適用於控制器升級。

+

NOTE: 請務必使用netboot將新節點更新為所需映像。如果您使用其他方法在新控制器上安裝映像、可能會安裝不正確的映像。此問題適用於ONTAP 所有的版本。netboot程序與選項結合使用 `(7) Install new software` 清除開機媒體、並在ONTAP 兩個影像分割區上放置相同的版本。

. [[step9]如果系統提示您繼續此程序、請輸入「y」、並在系統提示您輸入套件時、輸入URL：
+
http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz`

. [[step10]完成下列子步驟以重新啟動控制器模組：
+
.. 當您看到下列提示時、請輸入「n」跳過備份恢復：
+
「您現在想要還原備份組態嗎？｛y | n｝

.. 當您看到下列提示時、請輸入「y」重新開機：
+
「必須重新啟動節點、才能開始使用新安裝的軟體。是否要立即重新開機？｛y | n｝

+
控制器模組會重新開機、但會在開機功能表停止、因為開機裝置已重新格式化、而且必須還原組態資料。



. [[step11]從開機功能表中選取維護模式「5」、然後在系統提示您繼續開機時輸入「y」。
. [[step12]驗證控制器和機箱是否設定為ha:
+
《ha-config show》

+
以下範例顯示「ha-config show」命令的輸出：

+
....
Chassis HA configuration: ha
Controller HA configuration: ha
....
+

NOTE: 無論系統是在HA配對或獨立組態中、都會記錄在PROm中。獨立式系統或HA配對內的所有元件的狀態必須相同。

. [[step13]如果控制器和機箱未設定為ha、請使用下列命令修正組態：
+
「ha-config modify控制器ha」

+
「ha-config modify機箱ha」

+
如果您使用MetroCluster 的是不含任何功能的組態、請使用下列命令來修改控制器和機箱：

+
「ha-config modify控制器MCC」

+
「ha-config modify機箱MCC」

. [[step14]結束維護模式：
+
《停止》

+
在開機環境提示字元按下「Ctrl-C」來中斷自動開機。

. [[step15]在節點2上、檢查系統日期、時間和時區：
+
'日期'

. [[step16]在node3上、在開機環境提示字元中使用下列命令檢查日期：
+
「如何日期」

. [[step17]如有必要、請在節點3上設定日期：
+
"et date _mm/dd/yed_"

. [[step18]在node3上、在開機環境提示字元中使用下列命令檢查時間：
+
「時間安排」

. [[step19]如有必要、請在節點3上設定時間：
+
"et time _hh：mm:ss_"

. [[step20]在開機載入程式中、在節點3上設定合作夥伴系統ID：
+
"etenv PARTNER-sysid _node2_sysid_"

+
對於node3、 `partner-sysid` 必須是node2的。

+
.. 儲存設定：
+
「aveenv」



. [[[auto_install3_step21]驗證 `partner-sysid` 對於節點3：
+
《prontenv合作夥伴sysid》

. [[step22]請採取下列其中一項行動：
+
[cols="30,70"]
|===
| 如果您的系統... | 說明 


| 具有磁碟、無後端儲存設備 | 前往 <<auto_install3_step23,步驟23>> 


| 是連接FlexArray 至儲存陣列的V系列系統或系統、其中含有與之相關的功能完善的虛擬化軟體  a| 
.. 前往章節 link:set_fc_or_uta_uta2_config_on_node3.html["在節點3上設定FC或UTA/UTA2組態"] 並完成本節的小節。
.. 返回本節、並完成其餘步驟、從開始 <<auto_install3_step23,步驟23>>。



IMPORTANT: 您必須重新設定FC內建連接埠、CNA內建連接埠和CNA卡、才能使用ONTAP 「支援虛擬化」軟體在V系列或系統上啟動FlexArray 。

|===
. [[auto_install3_step23]將新節點的FC啟動器連接埠新增至交換器區域。
+
如果您的系統有磁帶SAN、則需要將啟動器分區。如有需要、請參閱、將內建連接埠修改為啟動器 link:set_fc_or_uta_uta2_config_on_node3.html#configure-fc-ports-on-node3["在節點3上設定FC連接埠"]。請參閱儲存陣列與分區文件、以取得分區的進一步指示。

. [[step24]將FC啟動器連接埠新增至儲存陣列做為新主機、將陣列LUN對應至新主機。
+
請參閱儲存陣列與分區文件以取得相關指示。

. [[step25]修改與儲存陣列上陣列LUN相關之主機或磁碟區群組中的全球連接埠名稱（WWPN）值。
+
安裝新的控制器模組會變更與每個內建FC連接埠相關的WWPN值。

. [[step26]如果您的組態使用交換器型分區、請調整分區以反映新的WWPN值。


. 如果您已安裝 NetApp 儲存加密（ NSE ）磁碟機、請執行下列步驟。
+

NOTE: 如果您尚未在程序中稍早完成此作業、請參閱知識庫文章 https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["如何判斷磁碟機是否已通過 FIPS 認證"^] 以判斷使用中的自我加密磁碟機類型。

+
.. 設定 `bootarg.storageencryption.support` 至 `true` 或 `false`：
+
[cols="35,65"]
|===
| 如果下列磁碟機正在使用中… | 然後… 


| 符合 FIPS 140-2 第 2 級自我加密要求的 NSE 磁碟機 | `setenv bootarg.storageencryption.support *true*` 


| NetApp非FIPS SED | `setenv bootarg.storageencryption.support *false*` 
|===
+
[NOTE]
====
您無法在同一個節點或HA配對上混用FIPS磁碟機與其他類型的磁碟機。您可以在同一個節點或HA配對上混合使用SED與非加密磁碟機。

====
.. 如需還原內建金鑰管理資訊的協助、請聯絡 NetApp 支援部門。


. 開機節點進入開機功能表：
+
Boot_ONTAP功能表

+
如果您沒有FC或UTA/UTA2組態、請執行 link:set_fc_or_uta_uta2_config_node4.html#auto_check_node4_step15["檢查並設定節點4步驟15上的UTA/UTA2連接埠"] 因此節點4可以識別節點2的磁碟。

. [[[autos9597_istall3_step29]若需MetroCluster 包含連接FlexArray 至儲存陣列之「支援虛擬化」軟體的支援功能、請前往 link:set_fc_or_uta_uta2_config_on_node3.html#auto9597_check_node3_step15["檢查並設定節點3步驟15上的UTA/UTA2連接埠"]。

