---
sidebar: sidebar 
permalink: upgrade-arl-auto/map_ports_node1_node3.html 
keywords: map, port, node1, node3, settings, restore, cluster 
summary: 使用ONTAP 「系統控制器更換」命令、將執行版本資訊9.5的控制器升級至9.7時、請確認節點1上的實體連接埠正確對應至節點3。 
---
= 將連接埠從節點1對應至節點3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您必須驗證節點1上的實體連接埠是否正確對應至節點3上的實體連接埠、如此一來、節點3就能在升級後與叢集中的其他節點和網路進行通訊。

請參閱 link:other_references.html["參考資料"] 可鏈接到_SURE_ Hardware Universe 以獲取有關新節點上端口的信息。您將會使用本節稍後的資訊。

連接埠設定可能有所不同、視節點的機型而定。您必須讓原始節點上的連接埠和LIF組態與新節點的規劃用途和組態相容。這是因為新節點在開機時會重新執行相同的組態、也就是說、當您開機node3時ONTAP 、將會嘗試在節點1上使用的相同連接埠上裝載l生命。

因此、如果節點1上的實體連接埠未直接對應至節點3上的實體連接埠、則在開機後、需要變更軟體組態才能還原叢集、管理和網路連線。此外、如果節點1上的叢集連接埠未直接對應至節點3上的叢集連接埠、則節點3可能不會在重新開機時自動重新加入仲裁、直到您將軟體組態變更為在正確的實體連接埠上裝載叢集生命體為止。

.步驟
. 在表中記錄節點1、連接埠、廣播網域和IPspaces的所有節點1纜線資訊：
+
|===
| LIF | 節點1連接埠 | 節點1 IPspaces | 節點1廣播網域 | 節點3連接埠 | 節點3 IPspaces | 節點3廣播網域 


| 叢集1 |  |  |  |  |  |  


| 叢集2 |  |  |  |  |  |  


| 叢集3 |  |  |  |  |  |  


| 叢集4. |  |  |  |  |  |  


| 節點管理 |  |  |  |  |  |  


| 叢集管理 |  |  |  |  |  |  


| 資料1. |  |  |  |  |  |  


| 資料2. |  |  |  |  |  |  


| 資料3. |  |  |  |  |  |  


| 資料4. |  |  |  |  |  |  


| SAN |  |  |  |  |  |  


| 叢集間連接埠 |  |  |  |  |  |  
|===
. 在表中記錄節點3、連接埠、廣播網域和IPspaces的所有纜線資訊。
. 請遵循下列步驟、確認設定是否為雙節點無交換器叢集：
+
.. 將權限層級設為進階：
+
「叢集：>設定權限進階」

.. 確認設定是否為雙節點無交換器叢集：
+
「叢集：>網路選項switchless cluster show」

+
[listing]
----
cluster::*> network options switchless-cluster show

Enable Switchless Cluster: false/true
----
+
此命令輸出的值必須符合系統的實體狀態。

.. 返回管理權限層級：
+
[listing]
----
cluster::*> set -privilege admin

cluster::>
----


. 請遵循下列步驟、將節點3置於仲裁中：
+
.. 開機節點3。請參閱 link:install_boot_node3.html["安裝及開機節點3"] 如果您尚未啟動節點、請將其開機。
.. 確認新的叢集連接埠位於叢集廣播網域中：
+
「網路連接埠show -node>-port <port>-Fields broadcast網域」

+
以下範例顯示連接埠「e0a」位於節點3的叢集網域中：

+
[listing]
----
 cluster::> network port show -node <node3> -port e0a -fields broadcast-domain

 node       port broadcast-domain
 ---------- ---- ----------------
 node3      e0a  Cluster
----
.. 如果叢集連接埠不在叢集廣播網域中、請使用下列命令加以新增：
+
「broadcast網域附加連接埠-IPSpace叢集-broadcast網域叢集-ports <nodes:port>」

+
此範例在節點3上新增叢集連接埠「e1b」：

+
[listing]
----
network port modify -node node3 -port e1b -ipspace Cluster -mtu 9000
----
.. 將正確的連接埠新增至叢集廣播網域：
+
「網路連接埠修改-nodes -port -IPSpace叢集-MTU 9000」

+
此範例在節點4上新增叢集連接埠「e1b」：

+
[listing]
----
network port modify -node node4 -port e1b -ipspace Cluster -mtu 9000
----
.. 針對每個LIF、將叢集生命區移轉至新的連接埠一次：
+
「網路介面移轉-vserver叢集-lif<lif_name>-SOURation-node3>-dite-node<node3>-dite-port <port_name>」

.. 修改叢集lifs的主連接埠：
+
「網路介面修改-vserver叢集-lIF <lif_name>–home-port <port_name>'

.. 從叢集廣播網域移除舊連接埠：
+
「網路連接埠廣播網域移除連接埠」

+
下列命令會移除節點3上的連接埠「e0d」：

+
「網路連接埠廣播網域移除連接埠-IPSpace叢集-broadcast網域叢集-連接埠node3：e0d」

.. 驗證node3是否已重新加入仲裁：
+
「cluster show -node3 -Fields health」



. [[auto_map_3_step5]調整裝載叢集生命週期和節點管理/叢集管理生命週期的廣播網域。確認每個廣播網域都包含正確的連接埠。如果某個連接埠裝載LIF或主控LIF、則無法在廣播網域之間移動連接埠、因此您可能需要依照下列方式移轉及修改LIF：
+
.. 顯示LIF的主連接埠：
+
「網路介面顯示欄位主節點、主連接埠」

.. 顯示包含此連接埠的廣播網域：
+
「網路連接埠廣播網域show -port <node_name:port_name>'

.. 新增或移除廣播網域的連接埠：
+
「網路連接埠廣播網域附加連接埠」

+
「網路連接埠廣播網域移除連接埠」

.. 修改LIF的主連接埠：
+
「網路介面修改-vserver vserver -lIF <lif_name>–home-port <port_name>'



. 使用中所示的相同命令、調整叢集間LIF所用網路連接埠的廣播網域成員資格 <<auto_map_3_step5,步驟5.>>。
. 如有必要、請使用中所示的相同命令、調整任何其他廣播網域並移轉資料生命量 <<auto_map_3_step5,步驟5.>>。
. 如果節點1上有任何連接埠不再存在於節點3上、請依照下列步驟加以刪除：
+
.. 存取任一節點上的進階權限層級：
+
"進階權限"

.. 若要刪除連接埠：
+
「網路連接埠刪除節點<node_name>-port <port_name>」

.. 返回管理層級：
+
「et -priv. admin」



. 調整所有LIF容錯移轉群組：
+
「網路介面修改-容錯移轉群組<容錯移轉群組>-容錯移轉原則<容錯移轉原則>」

+
下列命令會將容錯移轉原則設定為「廣播網域範圍」、並使用容錯移轉群組「fg1」中的連接埠作為節點3上LIF「data1」的容錯移轉目標：

+
「網路介面修改-vserver node3 -lIF data1容錯移轉原則廣播網域範圍-容 錯移轉群組fg1」

+
請參閱 link:other_references.html["參考資料"] 如需ONTAP 詳細資訊、請連結至_網路管理_或_《_例》9命令：手冊頁參考_。

. 驗證節點3上的變更：
+
「網路連接埠show -node3」

. 每個叢集LIF都必須偵聽連接埠7700。驗證叢集LIF是否正在偵聽連接埠7700：
+
：「：>網路連線偵聽show -vserver叢集」

+
連接埠7700偵聽叢集連接埠是預期結果、如下列雙節點叢集範例所示：

+
[listing]
----
Cluster::> network connections listening show -vserver Cluster
Vserver Name     Interface Name:Local Port     Protocol/Service
---------------- ----------------------------  -------------------
Node: NodeA
Cluster          NodeA_clus1:7700               TCP/ctlopcp
Cluster          NodeA_clus2:7700               TCP/ctlopcp
Node: NodeB
Cluster          NodeB_clus1:7700               TCP/ctlopcp
Cluster          NodeB_clus2:7700               TCP/ctlopcp
4 entries were displayed.
----
. 如有必要、請針對未接聽連接埠7700的每個叢集LIF、將LIF的管理狀態設為「自己」、然後設定為「UP」：
+
：`:>net int modify -vserver cluster -lif<cluster－lif>-STATUS-admin down；net int modify -vserver cluster -lIF <cluster－lif>-STATUS-admin up（net int modify -vserver Cluster -lIF <cluster－lif>-STATUS-admin up）

+
重複步驟11、確認叢集LIF現在正在偵聽連接埠7700。


