---
sidebar: sidebar 
permalink: upgrade-arl-auto/map_ports_node1_node3.html 
keywords: map, port, node1, node3, settings, restore, cluster 
summary: 使用ONTAP 「系統控制器更換」命令、將執行版本資訊9.5的控制器升級至9.7時、請確認節點1上的實體連接埠正確對應至節點3。 
---
= 將連接埠從節點1對應至節點3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您必須驗證 node1 上的實體連接埠是否與 node3 上的實體連接埠正確對應。這樣才能確保升級後 node3 能夠與叢集中的其他節點以及網路進行通訊。

.關於這項工作
請參閱 link:other_references.html["參考資料"] 可鏈接到_SURE_ Hardware Universe 以獲取有關新節點上端口的信息。您將會使用本節稍後的資訊。

連接埠設定可能因節點型號而異。您必須確保原始節點上的連接埠和 LIF 組態與新節點的計畫用途和組態相容。這是因為新節點啟動時會重播相同的組態，這表示當您啟動 node3 時，ONTAP 會嘗試在與 node1 相同的連接埠上託管 LIF。

因此，如果 node1 上的實體連接埠與 node3 上的實體連接埠不直接對應，則需要進行軟體組態變更，才能在開機後還原叢集、管理和網路連線。此外，如果 node1 上的叢集連接埠與 node3 上的叢集連接埠不直接對應，則在 node3 重新開機後，除非您變更軟體組態以將叢集 LIF 託管在正確的實體連接埠上，否則 node3 可能不會自動重新加入仲裁。

.步驟
. 在表中記錄節點1、連接埠、廣播網域和IPspaces的所有節點1纜線資訊：
+
|===
| LIF | 節點1連接埠 | 節點1 IPspaces | 節點1廣播網域 | 節點3連接埠 | 節點3 IPspaces | 節點3廣播網域 


| 叢集1 |  |  |  |  |  |  


| 叢集2 |  |  |  |  |  |  


| 叢集3 |  |  |  |  |  |  


| 叢集4. |  |  |  |  |  |  


| 節點管理 |  |  |  |  |  |  


| 叢集管理 |  |  |  |  |  |  


| 資料1. |  |  |  |  |  |  


| 資料2. |  |  |  |  |  |  


| 資料3. |  |  |  |  |  |  


| 資料4. |  |  |  |  |  |  


| SAN |  |  |  |  |  |  


| 叢集間連接埠 |  |  |  |  |  |  
|===
. 在表中記錄節點3、連接埠、廣播網域和IPspaces的所有纜線資訊。
. 請遵循下列步驟、確認設定是否為雙節點無交換器叢集：
+
.. 將權限層級設為進階：
+
「叢集：>設定權限進階」

.. 確認設定是否為雙節點無交換器叢集：
+
「叢集：>網路選項switchless cluster show」

+
[listing]
----
cluster::*> network options switchless-cluster show

Enable Switchless Cluster: false/true
----
+
此命令輸出的值必須符合系統的實體狀態。

.. 返回管理權限層級：
+
[listing]
----
cluster::*> set -privilege admin

cluster::>
----


. 請遵循下列步驟、將節點3置於仲裁中：
+
.. 開機節點3。請參閱 link:install_boot_node3.html["安裝及開機節點3"] 如果您尚未啟動節點、請將其開機。
.. 確認新的叢集連接埠位於叢集廣播網域中：
+
「網路連接埠show -node-nodE_-port _port_-Fields廣播網域」

+
以下範例顯示連接埠「e0a」位於節點3的叢集網域中：

+
[listing]
----
 cluster::> network port show -node _node3_ -port e0a -fields broadcast-domain

 node       port broadcast-domain
 ---------- ---- ----------------
 node3      e0a  Cluster
----
.. 如果叢集連接埠不在叢集廣播網域中、請使用下列命令加以新增：
+
「broadcast網域附加連接埠-IPSpace叢集-broadcast網域叢集-ports _normal:port_」

+
此範例在節點3上新增叢集連接埠「e1b」：

+
[listing]
----
network port modify -node node3 -port e1b -ipspace Cluster -mtu 9000
----
.. 將正確的連接埠新增至叢集廣播網域：
+
「網路連接埠修改-nodes -port -IPSpace叢集-MTU 9000」

+
此範例在節點4上新增叢集連接埠「e1b」：

+
[listing]
----
network port modify -node node4 -port e1b -ipspace Cluster -mtu 9000
----
.. 針對每個LIF、將叢集生命區移轉至新的連接埠一次：
+
「網路介面移轉-vserver叢集-lif_lif_name_-source-node3_-dest-node3_-destation-port _port_name_」

.. 修改叢集lifs的主連接埠：
+
「網路介面修改-vserver叢集-lif_lif_name_–home-port _port_name_`

.. 從叢集廣播網域移除舊連接埠：
+
「網路連接埠廣播網域移除連接埠」

+
下列命令會移除節點3上的連接埠「e0d」：

+
「網路連接埠廣播網域移除連接埠-IPSpace叢集-broadcast網域叢集-連接埠node3：e0d」

.. 驗證node3是否已重新加入仲裁：
+
「cluster show -node3 -Fields health」



. [[auto_map_3_step5]調整裝載叢集生命週期和節點管理/叢集管理生命週期的廣播網域。確認每個廣播網域都包含正確的連接埠。如果某個連接埠裝載LIF或主控LIF、則無法在廣播網域之間移動連接埠、因此您可能需要依照下列方式移轉及修改LIF：
+
.. 顯示LIF的主連接埠：
+
「網路介面顯示欄位主節點、主連接埠」

.. 顯示包含此連接埠的廣播網域：
+
「網路連接埠廣播網域show -ports_node_name:port_name_'

.. 新增或移除廣播網域的連接埠：
+
「網路連接埠廣播網域附加連接埠」

+
「網路連接埠廣播網域移除連接埠」

.. 修改LIF的主連接埠：
+
「網路介面修改-vserver vserver -lif_lif_name_–home-port _port_name_`



. 使用中所示的相同命令、調整叢集間LIF所用網路連接埠的廣播網域成員資格 <<auto_map_3_step5,步驟5.>>。
. 如有必要、請使用中所示的相同命令、調整任何其他廣播網域並移轉資料生命量 <<auto_map_3_step5,步驟5.>>。
. 如果節點1上有任何連接埠不再存在於節點3上、請依照下列步驟加以刪除：
+
.. 存取任一節點上的進階權限層級：
+
"進階權限"

.. 若要刪除連接埠：
+
"network port delete -node_node_name_-port _port_name_"（網路連接埠刪除-node_node_name_-port _port_name_）

.. 返回管理層級：
+
「et -priv. admin」



. 調整所有LIF容錯移轉群組：
+
「網路介面修改-容錯移轉群組_容 錯移轉群組_-容錯移轉原則_容 錯移轉原則_」

+
下列命令會將容錯移轉原則設定為「廣播網域範圍」、並使用容錯移轉群組「fg1」中的連接埠作為節點3上LIF「data1」的容錯移轉目標：

+
「網路介面修改-vserver node3 -lIF data1容錯移轉原則廣播網域範圍-容 錯移轉群組fg1」

+
請參閱 link:other_references.html["參考資料"] 以連結至 _Network Management_ 或 _ONTAP 9 Command reference_ 以取得更多資訊。

. 驗證節點3上的變更：
+
「網路連接埠show -node3」

. 每個叢集LIF都必須偵聽連接埠7700。驗證叢集LIF是否正在偵聽連接埠7700：
+
：「：>網路連線偵聽show -vserver叢集」

+
連接埠7700偵聽叢集連接埠是預期結果、如下列雙節點叢集範例所示：

+
[listing]
----
Cluster::> network connections listening show -vserver Cluster
Vserver Name     Interface Name:Local Port     Protocol/Service
---------------- ----------------------------  -------------------
Node: NodeA
Cluster          NodeA_clus1:7700               TCP/ctlopcp
Cluster          NodeA_clus2:7700               TCP/ctlopcp
Node: NodeB
Cluster          NodeB_clus1:7700               TCP/ctlopcp
Cluster          NodeB_clus2:7700               TCP/ctlopcp
4 entries were displayed.
----
. 對於每個未在連接埠 7700 上接聽的叢集 LIF 、請將 LIF 的管理狀態設為 `down` 然後 `up`：
+
：`:>net int modify -vserver cluster -lif_cluster－lif_-stue-admin down；net int modify -vserver cluster -lif_cluster－lif_-stue-admin up（net int修改-vserver叢集-lif_cluster－lif_-stue-admin up）

+
重複步驟11、確認叢集LIF現在正在偵聽連接埠7700。


