---
sidebar: sidebar 
permalink: upgrade-arl-auto/move_non_root_aggr_and_nas_data_lifs_node2_from_node3_to_node4.html 
keywords: move, non-root, aggregates, nas, lif, node2, node3, node4 
summary: 使用ONTAP 「系統控制器更換」命令、將執行版本資訊9.5的控制器升級至9.7時、請將節點3上的節點2 NAS資料LIF從節點3移至節點4。 
---
= 將節點2擁有的非根Aggregate和NAS資料lifs從節點3移至節點4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
驗證node4安裝之後、在將Aggregate從node3重新定位至node4之前、您必須將屬於node2的NAS資料lIF（目前位於node3上）、從node3移至node4。您還需要驗證節點4上是否存在SAN生命週期。

在升級過程中、遠端LIF會處理SAN LUN的流量。在升級期間、移轉SAN LIF對於叢集或服務健全狀況並不必要。除非需要將SAN LIF對應至新連接埠、否則不會移動SAN LIF。將node4聯機後，您將驗證生命週年是否正常並位於適當的端口上。

.步驟
. 恢復重新定位作業：
+
「系統控制器更換恢復」

+
系統會執行下列工作：

+
** 叢集仲裁檢查
** 系統ID檢查
** 映像版本檢查
** 目標平台檢查
** 網路連線能力檢查


+
此作業會在網路連線能力檢查的這個階段暫停。

. 手動確認網路及所有VLAN、介面群組和廣播網域均已正確設定。
. 恢復重新定位作業：
+
「系統控制器更換恢復」

+
[listing]
----
To complete the "Network Reachability" phase, ONTAP network configuration must be manually adjusted to match the new physical network configuration of the hardware. This includes assigning network ports to the correct broadcast domains,creating any required ifgrps and VLANs, and modifying the home-port parameter of network interfaces to the appropriate ports.Refer to the "Using aggregate relocation to upgrade controller hardware on a pair of nodes running ONTAP 9.x" documentation, Stages 3 and 5. Have all of these steps been manually completed? [y/n]
----
. 輸入「y」繼續。
. 系統會執行下列檢查：
+
** 叢集健全狀況檢查
** 叢集LIF狀態檢查


+
執行這些檢查之後、系統會將節點2擁有的非根Aggregate和NAS資料lifs重新定位至新的控制器節點4。資源重新配置完成後、系統會暫停。

. 檢查集合體重新配置和NAS資料LIF移動作業的狀態：
+
「System Controller replace show-details」（系統控制器取代顯示詳細資料

. 手動驗證非根集合體和NAS資料生命週期是否已成功移至節點4。
+
如果有任何集合體無法重新定位或遭到否決、您必須手動重新定位集合體、或在必要時覆寫檢查結果或目的地檢查。請參閱一節 link:relocate_failed_or_vetoed_aggr.html["重新部署故障或被否決的集合體"] 以取得更多資訊。

. 完成下列子步驟、確認SAN LIF位於節點4上的正確連接埠：
+
.. 輸入下列命令並檢查其輸出：
+
「網路介面show -data-Protocol iscsiSCSI|FCP -home-Node <node4>'

+
系統會傳回類似下列範例的輸出：

+
[listing]
----
cluster::> net int show -data-protocol iscsi|fcp -home-node node3
        Logical    Status     Network           Current Current Is
Vserver Interface  Admin/Oper Address/Mask      Node    Port    Home
------- ---------- ---------- ----------------- ------- ------- ---
vs0
        a0a        up/down    10.63.0.53/24     node3   a0a     true
        data1      up/up      10.63.0.50/18     node3   e0c     true
        rads1      up/up      10.63.0.51/18     node3   e1a     true
        rads2      up/down    10.63.0.52/24     node3   e1b     true
vs1
        lif1       up/up      172.17.176.120/24 node3   e0c     true
        lif2       up/up      172.17.176.121/24 node3   e1a     true
----
.. 如果節點4的SAN生命週期或SAN生命週期群組位於節點2上不存在的連接埠、或需要對應至不同的連接埠、請完成下列子步驟、將其移至節點4上的適當連接埠：
+
... 輸入下列命令、將LIF狀態設為向下：
+
「網路介面修改-vserver <vserver_name>-lif<lif_name>-STATUS-admin DOUTE」

... 從連接埠集移除LIF：
+
「portset移除-vserver <vserver_name>-portset <portSet_name>-port-name <port_name>」

... 輸入下列其中一個命令：
+
**** 輸入下列命令來移動單一LIF：
+
「網路介面修改-vserver <vserver_name>-lif<lif_name>-home-port <new_home_port>`

**** 輸入下列命令、將單一不存在或不正確連接埠上的所有LIF移至新連接埠：
+
「網路介面修改｛-home-port <port_on_node1>-home-Node <node1>-role data｝-home-port <new_home_port_on_node3>'

**** 將lifs新增回連接埠集：
+
「portset add -vserver <vserver_name>-portset <portset_name>-port-name <port_name>'

+

NOTE: 您必須確認將SAN LIF移至與原始連接埠具有相同連結速度的連接埠。





.. 輸入下列命令、將所有lifs的狀態修改為「up」、以便lifs可以接受及傳送節點上的流量：
+
「網路介面修改-home-port <port_name>-home-node<node4>-lIF DATA -statusadmin up」

.. 輸入以下命令並檢查其輸出、確認已將l生命 移至正確的連接埠、並在任一節點上輸入下列命令、檢查輸出、確認l生命 狀態為「up」：
+
「網路介面show -home-Node <node4>-role data」

.. 如果有任何LIF當機、請輸入下列命令、將LIF的管理狀態設為UP（開啟）、每個LIF只需輸入一次：
+
「網路介面修改-vserver <vserver_name>-lif<lif_name>-STATUS-admin up」



. 繼續作業、以提示系統執行必要的POST檢查：
+
「系統控制器更換恢復」

+
系統會執行下列POST檢查：

+
** 叢集仲裁檢查
** 叢集健全狀況檢查
** 集合體重建檢查
** Aggregate狀態檢查
** 磁碟狀態檢查
** 叢集LIF狀態檢查



