---
sidebar: sidebar 
permalink: upgrade-arl-auto/overview_of_the_arl_upgrade.html 
keywords: aggregate relocation, upgrade, process, overview, stages 
summary: 瞭解ONTAP 如何使用「系統控制器更換」命令、將執行《SES9.5》的控制器升級至9.7。 
---
= ARL升級總覽
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在使用ARL升級節點之前、您應該先瞭解程序的運作方式。在本內容中、程序分為幾個階段。



== 升級節點配對

若要升級節點配對、您需要準備原始節點、然後在原始節點和新節點上執行一系列步驟。然後您可以取消委任原始節點。



== ARL升級順序總覽

在程序期間、您可以使用更換的控制器硬體（一次一個控制器）來升級原始控制器硬體、並利用HA配對組態來重新配置非根集合體的擁有權。所有非根Aggregate都必須經過兩次重新定位、才能到達最終目的地、這是正確的升級節點。

每個Aggregate都有一個擁有者和目前擁有者。主擁有者是該集合體的實際擁有者、而目前擁有者則是暫時擁有者。

下表說明您在每個階段中執行的高層工作、以及階段結束時的集合擁有權狀態。程序稍後會提供詳細步驟：

[cols="25,75"]
|===
| 階段 | 步驟 


| link:stage_1_index.html["第1階段：準備升級"]  a| 
在第1階段期間、您會執行預先檢查、並視需要修正Aggregate所有權。如果您使用 Onboard Key Manager 來管理儲存加密、則必須記錄特定資訊、而且您可以選擇靜止 SnapMirror 關係。

第1階段結束時的Aggregate所有權：

* node1是node1集合體的主擁有者和目前擁有者。
* node2是node2 Aggregate的主擁有者和目前擁有者。




| link:stage_2_index.html["第2階段：重新部署和淘汰節點1"]  a| 
在第2階段期間、您會將節點1非根Aggregate和NAS資料lifs重新部署至節點2。此程序大部分是自動化的；此作業會暫停、以便您檢查其狀態。您必須手動恢復作業。如果需要、您可以重新部署故障或被否決的集合體。您必須記錄必要的node1資訊、以便稍後在程序中使用、然後淘汰node1。您也可以在程序稍後的步驟中準備netboot node3和node4。

第2階段結束時的Aggregate所有權：

* node2是node1 Aggregate的目前擁有者。
* node2是node2 Aggregate的主擁有者和目前擁有者。




| link:stage_3_index.html["階段3.安裝及開機節點3"]  a| 
在第3階段期間、您會安裝並開機node3、將叢集和節點管理連接埠從node1對應至node3、然後驗證node3安裝。如果需要、您可以在節點3上設定FC或UTA/UTA2組態、並確認節點3已加入仲裁。您也可以將節點1 NAS資料lifs和非根Aggregate從節點2重新部署到節點3、並確認節點3上存在SAN lifs。

第3階段結束時的Aggregate所有權：

* node3是node1 Aggregate的主擁有者和目前擁有者。
* node2是node2 Aggregate的主擁有者和目前擁有者。




| link:stage_4_index.html["第4階段：重新部署和淘汰節點2"]  a| 
在第4階段期間、您將節點2非根集合體和非SAN資料生命週期重新部署到節點3。您也可以記錄必要的node2資訊、然後淘汰node2。

第4階段結束時的Aggregate所有權：

* node3是原屬於node1的Aggregate的主擁有者和目前擁有者。
* node2是node2 Aggregate的主擁有者。
* node3是node2 Aggregate的目前擁有者。




| link:stage_5_index.html["階段5.安裝及開機節點4"]  a| 
在第5階段期間、您會安裝並開機node4、將叢集和節點管理連接埠從node2對應至node4、然後驗證node4安裝。如果需要、您可以在節點4上設定FC或UTA/UTA2組態、並確認節點4已加入仲裁。您也可以將node2 NAS資料lifs和非根Aggregate從node3重新部署到node4、並驗證節點4上是否存在SAN lifs。

第5階段結束時的Aggregate所有權：

* node3是原屬於node1的集合體的主擁有者和目前擁有者。
* Node4是原屬於節點2的Aggregate主擁有者和目前擁有者。




| link:stage_6_index.html["階段6.完成升級"]  a| 
在第6階段期間、您將確認新節點已正確設定、如果新節點已啟用加密、則您可以設定及設定儲存加密或NetApp Volume Encryption。您也應該取消委任舊節點、然後恢復SnapMirror作業。

|===