---
sidebar: sidebar 
permalink: upgrade-arl-auto/recreate_vlans_ifgrps_broadcast_domains_node3.html 
keywords: node3, interface group, VLANs, broadcast domains, re-create 
summary: 使用ONTAP 「系統控制器更換」命令、將執行版本資訊9.5的控制器升級至9.7時、請在節點3上重新建立節點1的VLAN、介面群組和廣播網域。 
---
= 在節點3上重新建立VLAN、介面群組和廣播網域
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在您確認node3處於仲裁狀態並可與node2通訊之後、您必須在node3上重新建立node1的VLAN、介面群組和廣播網域。您也必須將node3連接埠新增至新重新建立的廣播網域。

如需建立及重新建立VLAN、介面群組及廣播網域的詳細資訊、請參閱 link:other_references.html["參考資料"] 並連結至_網路管理_。

.步驟
. 使用中記錄的節點1資訊、在節點3上重新建立VLAN link:relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html["將節點1擁有的非根Aggregate和NAS資料lifs重新部署到節點2"] 區段：
+
「網路連接埠VLAN create -node_node_name_-vlan _vlan-names _」

. 使用中記錄的node1資訊、在node3上重新建立介面群組 link:relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html["將節點1擁有的非根Aggregate和NAS資料lifs重新部署到節點2"] 區段：
+
「網路連接埠ifgrp create -node_node_name_-ifgrp _port_ifgrp_name_-distr-func'

. 使用中記錄的節點1資訊、在節點3上重新建立廣播網域 link:relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html["將節點1擁有的非根Aggregate和NAS資料lifs重新部署到節點2"] 區段：
+
「網路連接埠廣播網域建立-IPSpace預設值-broadcast網域_broadcast網域名稱_-MTU _MTU大小_-連接埠_node_name:port_name、node_name:port_name_」

. 將node3連接埠新增至新重新建立的廣播網域：
+
「網路連接埠廣播網域附加連接埠-broadcast網域_broadcast網域名稱_-連接埠_norme_name:port_name、node_name:port_name_」


