---
sidebar: sidebar 
permalink: upgrade-arl-auto/relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html 
keywords: relocate, non-root, aggregates, nas, lif, node2, node3 
summary: 使用ONTAP 「系統控制器更換」命令、將執行E9.5的控制器升級至9.7的控制器時、請將節點2的非根Aggregate重新定位至節點3。 
---
= 將非根Aggregate和NAS資料LIF從節點2重新定位至節點3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您必須先將節點2擁有的非根Aggregate重新定位至節點3、才能將節點2取代為節點4。

完成上一階段的檢查後、節點2的資源版本會自動啟動。非根Aggregate和非SAN資料LIF會從節點2移轉至節點3。

在升級過程中、遠端LIF會處理SAN LUN的流量。在升級期間、移轉SAN LIF對於叢集或服務健全狀況並不必要。

在移轉集合體和lifs之後、此作業會暫停以供驗證之用。在此階段、您必須驗證是否所有非根Aggregate和非SAN資料生命體都移轉至節點3。


NOTE: 不會修改集合體和lifs的主擁有者、只會修改目前擁有者。

.步驟
. 驗證所有非根Aggregate均處於線上狀態、以及節點3上的狀態：
+
「torage Aggregate show -node3>-state online -root假」

+
以下範例顯示節點2上的非根Aggregate處於線上狀態：

+
....
cluster::> storage aggregate show -node node3 state online -root false

Aggregate      Size         Available   Used%   State   #Vols  Nodes  RAID     Status
----------     ---------    ---------   ------  -----   -----  ------ -------  ------
aggr_1         744.9GB      744.8GB      0%     online  5      node2  raid_dp  normal
aggr_2         825.0GB      825.0GB      0%     online  1      node2  raid_dp  normal
2 entries were displayed.
....
+
如果Aggregate已離線或成為節點3上的外部節點、請在節點3上使用下列命令將其上線、每個Aggregate一次：

+
「torage Aggregate online -gregate <agger_name>」

. 在node3上使用以下命令並檢查輸出、以確認節點3上的所有磁碟區都已上線：
+
「Volume show -node3>-state offline」（Volume show -node3>-state offline）

+
如果節點3上有任何磁碟區離線、請在節點3上使用下列命令將其上線、每個磁碟區一次：

+
「Volume online -vserver <vserver_name>-volume <volume <volume．name>'

+
與此命令搭配使用的「<vserver_name>」可在先前的「Volume show」命令輸出中找到。

. 驗證是否已將lifs移至正確的連接埠、且狀態為「up」。如果有任何生命中斷、請輸入下列命令、並針對每個LIF輸入一次、將該生命的管理狀態設定為「UP」：
+
「網路介面修改-vserver <vserver_name>- lif<lif_name>-home-node<node_name>- STATUS-admin up」

. 如果新硬體上不存在目前裝載資料生命體的連接埠、請將其從廣播網域中移除：
+
「網路連接埠廣播網域移除連接埠」



. [[step5]]輸入下列命令並檢查輸出、確認節點2上沒有剩餘的資料lifs：
+
「network interface show -curr-node-node2>-role data」（網路介面顯示-curr-node-node2>-role data）

. 如果已設定介面群組或VLAN、請完成下列子步驟：
+
.. 記錄VLAN和介面群組資訊、以便在節點3開機後、在節點3上重新建立VLAN和介面群組。
.. 從介面群組移除VLAN：
+
「網路連接埠VLAN刪除節點<節點名稱>-連接埠<ifgrp>-vlan-id <vlan_ID>」

.. 輸入下列命令並檢查其輸出、檢查節點上是否有任何已設定的介面群組：
+
「network port ifgrp show -node2>-ifgrp <ifgrp_name>-instance'

+
系統會顯示節點的介面群組資訊、如下列範例所示：

+
[listing]
----
cluster::> network port ifgrp show -node node2 -ifgrp a0a -instance
                 Node: node3
 Interface Group Name: a0a
Distribution Function: ip
        Create Policy: multimode_lacp
          MAC Address: 02:a0:98:17:dc:d4
   Port Participation: partial
        Network Ports: e2c, e2d
             Up Ports: e2c
           Down Ports: e2d
----
.. 如果節點上已設定任何介面群組、請記錄這些群組的名稱及指派給它們的連接埠、然後輸入下列命令刪除連接埠、每個連接埠一次：
+
「network port ifgrp remove-port -node<nodename>-ifgrp <ifgrp_name>-port <netport>'




