---
sidebar: sidebar 
permalink: upgrade-arl-auto/set_fc_or_uta_uta2_config_node4.html 
keywords: fc configuration, uta configuration, UTA2 configuration, configure FC ports, UTA/UTA2 card, node4, target, adapter, ports 
summary: 使用ONTAP 「系統控制器更換」命令、將執行《更新》9.5的控制器升級至9.7時、請設定node4內建FC連接埠、UTA/UTA2連接埠或UTA/UTA2卡。 
---
= 在節點4上設定FC或UTA/UTA2組態
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
如果node4具有內建FC連接埠、內建統一化目標介面卡（UTA/UTA2）連接埠或UTA/UTA2卡、則必須先設定這些設定、才能完成其餘程序。

.關於這項工作
您可能需要完成<<在節點4上設定FC連接埠>>或者<<檢查並設定節點4上的UTA/UTA2連接埠>>或兩個部分。

[NOTE]
====
如果 node4 沒有板載 FC 端口，板載 UTA/UTA2 端口或 UTA/ UTA2 卡，並且您要升級帶有存儲磁盤的系統，則可以跳至link:reassign-node2-disks-to-node4.html["將 node2 磁碟重新指派給 node4"]。

確定節點4有足夠的機架空間。如果node4與node2位於不同的機箱中、您可以將node4放在與node3相同的位置。如果節點2和節點4位於同一個機箱中、則節點4已位於適當的機架位置。

====


== 在節點4上設定FC連接埠

如果節點 4 具有 FC 連接埠（無論是板載的還是附加 FC 適配器上的），則必須在節點投入使用之前設定其連接埠配置，因為系統出廠時未預先配置連接埠。如果您沒有按要求配置端口，則可能會遇到服務中斷。

.開始之前
您必須擁有儲存在區段中節點2的FC連接埠設定值 link:prepare_nodes_for_upgrade.html["準備節點以進行升級"]。

.關於這項工作
如果您的系統沒有FC組態、您可以跳過本節。如果您的系統有內建UTA/UTA2連接埠或UTA/UTA2介面卡、請在中進行設定 <<檢查並設定節點4上的UTA/UTA2連接埠>>。


IMPORTANT: 在維護模式 shell 提示字元下輸入本節中的命令。

.步驟
. 顯示系統上所有 FC 和融合網路適配器的資訊：
+
「系統節點硬體統一連線展示」

. 比較節點4上的FC設定與先前從節點1擷取的設定。
. 視需要修改節點4上的FC連接埠：
+
** 要作為目標連接埠進行程式設計：
+
「ucadmin modify -m sfc-t target _adapter-'」

+
例如： `ucadmin modify -m fc -t target 2a`

** 設定啟動器連接埠：
+
「ucadmin modify -m光纖通道-t啟動器_adapter-'」

+
「-t」是FC4類型：目標或啟動器。

+
例如： `ucadmin modify -m fc -t initator 2b`



. 停止節點：
+
《停止》

. 從載入程式提示字元啟動系統：
+
Boot_ONTAP功能表

. 輸入命令後、請等待系統在開機環境提示字元停止。
. 從開機功能表中選取「5」選項以進行維護模式。


. [[step8]]跳過此部分並轉到link:reassign-node2-disks-to-node4.html["將 node2 磁碟重新指派給 node4"]如果 node4 沒有 UTA/UTA2 卡或 UTA/UTA2 板載連接埠。




== 檢查並設定節點4上的UTA/UTA2連接埠

如果節點4內建UTA/UTA2連接埠或UTA/UTA2A卡、您必須檢查連接埠的組態並加以設定、視您要使用升級系統的方式而定。

.開始之前
UTA/UTA2連接埠必須具備正確的SFP+模組。

.關於這項工作
UTA/UTA2連接埠可設定為原生FC模式或UTA/UTA2A模式。FC模式支援FC啟動器和FC目標；UTA/UTA2模式可讓並行NIC和FCoE流量共用相同的10GbE SFP+介面、並支援FC目標。


NOTE: NetApp行銷資料可能會使用UTA2一詞來指稱CNA介面卡和連接埠。不過、CLI使用「CNA」一詞。

UTA/UTA2連接埠可能位於介面卡或控制器上、且具有下列組態：

* UTA/UTA2卡與控制器一起訂購、在出貨前已設定為符合您要求的特性。
* 與控制器分開訂購的UTA/UTA2卡會隨附預設FC目標特性。
* 新控制器上的內建UTA/UTA2連接埠已設定（出貨前）、以符合您要求的特性。


不過、您應該檢查節點4上UTA/UTA2連接埠的組態、並視需要加以變更。


WARNING: 在維護模式 shell 提示字元下輸入本節中的命令。

.步驟
. 檢查 node4 上連接埠的目前配置：
+
「系統節點硬體統一連線展示」

+
系統會顯示類似下列範例的輸出：

+
....
*> ucadmin show
                Current  Current    Pending   Pending   Admin
Node   Adapter  Mode     Type       Mode      Type      Status
----   -------  ---      ---------  -------   --------  -------
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
*>
....
. 如果目前的SFP+模組不符合所需用途、請更換為正確的SFP+模組。
+
請聯絡您的NetApp代表、以取得正確的SFP+模組。

. 驗證設定：
+
「ucadmin show」

+
檢查「ucadmin show」命令的輸出、判斷UTA/UTA2連接埠是否具有您想要的特性。

+
以下範例的輸出顯示FC4類型的介面卡「1b」正在變更為「啟動器」、介面卡「2a」和「2b」的模式正在變更為「cna」：

+
....
*> ucadmin show
Node  Adapter  Current Mode  Current Type  Pending Mode  Pending Type  Admin Status
----  -------  ------------  ------------  ------------  ------------  ------------
f-a   1a       fc             initiator    -             -             online
f-a   1b       fc             target       -             initiator     online
f-a   2a       fc             target       cna           -             online
f-a   2b       fc             target       cna           -             online
4 entries were displayed.
*>
....
. 請採取下列其中一項行動：
+
[cols="30,70"]
|===
| 如果CNA連接埠... | 然後… 


| 沒有您想要的特性 | 前往 <<auto_check_4_step5,步驟5.>>。 


| 擁有您想要的個人風格 | 跳過步驟 5 至步驟 9，然後轉到<<auto_check_4_step10,步驟10>>。 
|===
. [[auto_check_4_step5]]請採取下列其中一項行動：
+
[cols="30,70"]
|===
| 如果您正在設定... | 然後… 


| UTA/UTA2卡上的連接埠 | 前往<<auto_check_4_step6,步驟6.>> 


| 內建UTA/UTA2連接埠 | 跳過第 6 步並轉到<<auto_check_4_step7,步驟7.>>。 
|===
. [[auto_check_4_step6]]如果轉接器處於啟動器模式，且 UTA/UTA2 連接埠處於線上狀態，則將 UTA/UTA2 連接埠離線：
+
「停用介面卡_adapter_name_」

+
目標模式中的介面卡會在維護模式中自動離線。

. [[auto_check_4_step7]]如果目前的組態與所需用途不符、請視需要變更組態：
+
`ucadmin modify -m fc|cna -t initiator|target <adapter_name>`

+
** 「-m」是個人化模式、FC或10GbE UTA。
** "-t"是FC4類型、"target（目標）"或"initiator（啟動器）"。
+

NOTE: 您必須對磁帶機和MetroCluster配置使用 FC 啟動器。您必須對 SAN 用戶端使用 FC 目標。



. 輸入以下命令（每個連接埠一次），使任何目標連接埠連線：
+
`storage enable adapter <adapter_name>`

. 連接連接埠。


. [[auto_check_4_step10]]退出維護模式：
+
《停止》

. 將節點開機至開機功能表：
+
Boot_ONTAP功能表



.接下來呢？
* 如果您要升級至 AFF A800 系統，請前往link:reassign-node2-disks-to-node4.html#auto_check_4_step9["將 node2 磁碟重新指派給 node4 ，步驟 9"]。
* 對於所有其他系統升級，請訪問link:reassign-node2-disks-to-node4.html["將 node2 磁碟重新指派給 node4 ，步驟 1"]。

