---
sidebar: sidebar 
permalink: upgrade-arl-auto/stage_6_index.html 
keywords: complete upgrade, node, unified, target, storage, encryption, MetroCluster, stage 6 
summary: ARL升級的第6階段程序順序、使用「系統控制器更換」命令、在執行ONTAP 版本號從9.5到9.7的控制器上執行。 
---
= 第 6 階段總覽
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在第6階段期間、您將確認新節點已正確設定、如果新節點已啟用加密、則您可以設定及設定儲存加密或NetApp Volume Encryption。您也應該取消委任舊節點、然後恢復SnapMirror作業。

.步驟
. link:manage-authentication-using-kmip-servers.html["使用KMIP伺服器管理驗證"]
. link:ensure_new_controllers_are_set_up_correctly.html["確認新的控制器已正確設定"]
. link:set_up_storage_encryption_new_module.html["在新的控制器模組上設定儲存加密"]
. link:set_up_netapp_volume_encryption_new_module.html["在新的控制器模組上設定NetApp Volume或Aggregate Encryption"]
. link:decommission_old_system.html["取消委任舊系統"]
. link:resume_snapmirror_operations.html["恢復SnapMirror作業"]


.精選FC組態MetroCluster
在 MetroCluster FC 組態中、您必須盡快更換災難恢復 / 容錯移轉站台節點。不支援不支援在支援範圍內不相符的控制器機型MetroCluster 、因為控制器機型不相符可能導致災難恢復鏡像離線。當您在第二個站台更換節點時、請使用 `-skip-metrocluster-check true` 命令略過 MetroCluster 檢查。
