---
sidebar: sidebar 
permalink: upgrade-arl-auto/verify_node3_installation.html 
keywords: install, boot, node3, join quorum, restore, key, manager 
summary: 使用ONTAP 「系統控制器更換」命令、將執行更新至9.7的控制器升級時、請確認節點3加入仲裁、重新建立節點1的VLAN、介面群組和廣播網域、並還原金鑰管理程式組態。 
---
= 驗證node3安裝
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
安裝並開機節點3之後、您必須驗證節點是否已正確安裝。您必須等待節點3加入仲裁、然後繼續重新配置作業。

.關於這項工作
在此過程中、當節點3加入仲裁時、作業將暫停。

.步驟
. 驗證node3是否已加入仲裁：
+
「cluster show -node3 -Fields health」

. 驗證node3是否與node2屬於同一個叢集、而且它是否正常：
+
「叢集展示」

. 檢查作業狀態、並確認節點3的組態資訊與節點1相同：
+
「System Controller replace show-details」（系統控制器取代顯示詳細資料

+
如果節點3的組態不同、則稍後可能會發生系統中斷。

. 檢查所更換的控制器是否已正確設定MetroCluster 為執行故障恢復組態、MetroCluster 應將故障恢復至正常狀態、而非切換模式。請參閱 link:verify_health_of_metrocluster_config.html["驗MetroCluster 證整個過程的效能狀況"]。




== 在節點3上重新建立VLAN、介面群組和廣播網域

在您確認node3處於仲裁狀態並可與node2通訊之後、您必須在node3上重新建立node1的VLAN、介面群組和廣播網域。您也必須將node3連接埠新增至新重新建立的廣播網域。

.關於這項工作
如需建立及重新建立VLAN、介面群組及廣播網域的詳細資訊、請參閱 link:other_references.html["參考資料"] 並連結至_網路管理_。

.步驟
. 使用中記錄的節點1資訊、在節點3上重新建立VLAN link:relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html["將節點1擁有的非根Aggregate和NAS資料lifs重新部署到節點2"] 區段：
+
「網路連接埠VLAN create -node_node_name_-vlan _vlan-names _」

. 使用中記錄的node1資訊、在node3上重新建立介面群組 link:relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html["將節點1擁有的非根Aggregate和NAS資料lifs重新部署到節點2"] 區段：
+
「網路連接埠ifgrp create -node_node_name_-ifgrp _port_ifgrp_name_-distr-func'

. 使用中記錄的節點1資訊、在節點3上重新建立廣播網域 link:relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html["將節點1擁有的非根Aggregate和NAS資料lifs重新部署到節點2"] 區段：
+
「網路連接埠廣播網域建立-IPSpace預設值-broadcast網域_broadcast網域名稱_-MTU _MTU大小_-連接埠_node_name:port_name、node_name:port_name_」

. 將node3連接埠新增至新重新建立的廣播網域：
+
「網路連接埠廣播網域附加連接埠-broadcast網域_broadcast網域名稱_-連接埠_norme_name:port_name、node_name:port_name_」





== 還原節點3上的金鑰管理程式組態

如果您使用NetApp Aggregate Encryption（NAE）或NetApp Volume Encryption（NVE）來加密升級系統上的磁碟區、則加密組態必須同步至新節點。如果您沒有還原金鑰管理程式、當您使用ARL將節點1集合體從節點2重新定位至節點3時、加密的磁碟區將會離線。

.步驟
. 若要同步Onboard Key Manager的加密組態、請在叢集提示字元中執行下列命令：
+
|===
| 對於此ONTAP 版本… | 使用此命令... 


| 部分9.6或9.7 ONTAP | 「安全金鑰管理程式內建同步」 


| 版本9.5 ONTAP | 「安全金鑰管理程式設定節點_norme_name_」 
|===
. 輸入Onboard Key Manager的全叢集密碼。

