= 
:allow-uri-read: 



NOTE: 不會修改集合體和lifs的主擁有者、只會修改目前擁有者。

.步驟
. 恢復Aggregate重新定位和NAS資料LIF移動作業：
+
「系統控制器更換恢復」

+
所有非根Aggregate和NAS資料lifs都會從節點1移轉至節點2。

+
此作業會暫停、以便您確認是否已將所有節點1非根Aggregate和非SAN資料lIF移轉至節點2。

. 檢查集合體重新配置和NAS資料LIF移動作業的狀態：
+
「System Controller replace show-details」（系統控制器取代顯示詳細資料

. 在作業仍暫停的情況下、確認節點2上的所有非根Aggregate狀態均處於線上狀態：
+
「torage Aggregate show -node2_-state online -root假」

+
以下範例顯示節點2上的非根Aggregate處於線上狀態：

+
[listing]
----
cluster::> storage aggregate show -node node2 state online -root false

Aggregate  Size     Available  Used%  State  #Vols  Nodes  RAID Status
---------  -------  ---------  -----  ------ -----  ------ --------------
aggr_1     744.9GB  744.8GB    0%     online     5  node2  raid_dp,normal
aggr_2     825.0GB  825.0GB    0%     online     1  node2  raid_dp,normal
2 entries were displayed.
----
+
如果Aggregate已離線或成為節點2上的外部節點、請在節點2上使用下列命令將其上線、每個Aggregate一次：

+
'線上儲存Aggregate -Agggr_name_'

. 在節點2上使用下列命令並檢查其輸出、以確認節點2上的所有磁碟區都已上線：
+
「Volume show -node2_-state offline」

+
如果節點2上有任何磁碟區離線、請在節點2上使用下列命令將其上線、每個磁碟區一次：

+
"Volume online -vserver _vserver_name_-volume _volume _name_"

+
與此命令一起使用的"_vserver_name_"可在先前的"volume show"命令輸出中找到。


