= 檢查並設定節點3上的UTA/UTA2連接埠
:allow-uri-read: 




== 檢查並設定節點3上的UTA/UTA2連接埠

如果節點3內建UTA/UTA2連接埠或UTA/UTA2卡、您必須檢查連接埠的組態、並視您要使用升級系統的方式而可能重新設定。

.開始之前
UTA/UTA2連接埠必須具備正確的SFP+模組。

.關於這項工作
如果您要使用統一化目標介面卡（UTA/ UTA2）連接埠來連接FC、必須先確認連接埠的設定方式。


NOTE: NetApp行銷資料可能會使用UTA2一詞來指稱CNA介面卡和連接埠。不過、CLI使用「CNA」一詞。

您可以使用 `ucadmin show`命令查看或驗證目前連接埠配置，如以下範例輸出所示：

....
*> ucadmin show
         Current  Current    Pending   Pending      Admin
Adapter  Mode     Type       Mode      Type         Status
-------  -------  -------    --------  ----------   --------
0e      fc        target     -         initiator    offline
0f      fc        target     -         initiator    offline
0g      fc        target     -         initiator    offline
0h      fc        target     -         initiator    offline
1a      fc        target     -         -            online
1b      fc        target     -         -            online
6 entries were displayed.
....
UTA/UTA2連接埠可設定為原生FC模式或UTA/UTA2模式。FC模式支援FC啟動器和FC目標；UTA/UTA2模式允許同時NIC和FCoE流量共用相同的10GbE SFP+介面、並支援FC目標。

UTA/UTA2 連接埠可能位於附加適配器或控制器主機板上，並具有以下配置，但您應該檢查節點 3 上的 UTA/UTA2 連接埠的配置並在必要時進行變更：

* 訂購控制器時所訂購的UTA/UTA2卡、在出貨前已設定為具有您要求的特性設定。
* 與控制器分開訂購的UTA/UTA2卡會隨附預設FC目標特性。
* 新控制器上的內建UTA/UTA2連接埠會在出貨前設定、以符合您要求的特性設定。
+

WARNING: 您必須處於維護模式才能設定 UTA/UTA2 連接埠。在維護模式 shell 提示字元下輸入本節中的命令。



.步驟
. 如果目前的SFP+模組不符合所需用途、請更換為正確的SFP+模組。
+
請聯絡您的NetApp代表、以取得正確的SFP+模組。

. 驗證 UTA/UTA2 連接埠設定：
+
「ucadmin show」

+
檢查輸出並確定 UTA/UTA2 連接埠是否具有您想要的個性。

+
以下範例中的輸出顯示適配器“1b”的類型正在變更為啟動器，並且適配器“2a”和“2b”的模式正在變更為“cna”。  CNA 模式可讓您將該卡用作網路介面卡。

+
[listing]
----
*> ucadmin show
         Current    Current     Pending  Pending     Admin
Adapter  Mode       Type        Mode     Type        Status
-------  --------   ----------  -------  --------    --------
1a       fc         initiator   -        -           online
1b       fc         target      -        initiator   online
2a       fc         target      cna      -           online
2b       fc         target      cna      -           online
*>
----
. 請採取下列其中一項行動：
+
[cols="30,70"]
|===
| 如果UTA/UTA2連接埠... | 然後… 


| 沒有您想要的特性 | 前往<<auto_check3_step4,步驟4.>>。 


| 擁有您想要的個人風格 | 跳過步驟 4 至步驟 8，然後轉到<<auto_check3_step9,步驟9.>>。 
|===
. [[auto_check3_step4]]請執行下列其中一項操作：
+
[cols="30,70"]
|===
| 如果您正在設定... | 然後… 


| UTA/UTA2卡上的連接埠 | 前往<<auto_check3_step5,步驟5.>> 


| 內建UTA/UTA2連接埠 | 跳過步驟 5 並轉到<<auto_check3_step6,步驟6.>>。 
|===
. [[auto_check3_step5]]如果轉接器處於啟動器模式，且 UTA/UTA2 連接埠處於線上狀態，則將 UTA/UTA2 連接埠離線：
+
`storage disable adapter <adapter_name>`

+
目標模式中的介面卡會在維護模式中自動離線。

. [[auto_check3_step6]]如果目前配置與所需用途不匹配，請根據需要變更配置：
+
`ucadmin modify -m fc|cna -t initiator|target <adapter_name>`

+
** 「m」是指個人化模式、「光纖通道」或「cna」。
** "-t"是FC4類型、"target（目標）"或"initiator（啟動器）"。
+

NOTE: 您必須對磁帶機和MetroCluster配置使用 FC 啟動器。您必須對 SAN 用戶端使用 FC 目標。



. 透過為每個連接埠輸入以下命令，將所有目標連接埠置於線上狀態：
+
`storage enable adapter <adapter_name>`

. 連接連接埠。

