= 檢查並設定節點4上的UTA/UTA2連接埠
:allow-uri-read: 




== 檢查並設定節點4上的UTA/UTA2連接埠

如果節點4內建UTA/UTA2連接埠或UTA/UTA2A卡、您必須檢查連接埠的組態並加以設定、視您要使用升級系統的方式而定。

.開始之前
UTA/UTA2連接埠必須具備正確的SFP+模組。

.關於這項工作
UTA/UTA2連接埠可設定為原生FC模式或UTA/UTA2A模式。FC模式支援FC啟動器和FC目標；UTA/UTA2模式可讓並行NIC和FCoE流量共用相同的10GbE SFP+介面、並支援FC目標。


NOTE: NetApp行銷資料可能會使用UTA2一詞來指稱CNA介面卡和連接埠。不過、CLI使用「CNA」一詞。

UTA/UTA2連接埠可能位於介面卡或控制器上、且具有下列組態：

* UTA/UTA2卡與控制器一起訂購、在出貨前已設定為符合您要求的特性。
* 與控制器分開訂購的UTA/UTA2卡會隨附預設FC目標特性。
* 新控制器上的內建UTA/UTA2連接埠已設定（出貨前）、以符合您要求的特性。


不過、您應該檢查節點4上UTA/UTA2連接埠的組態、並視需要加以變更。


WARNING: 在維護模式 shell 提示字元下輸入本節中的命令。

.步驟
. 檢查 node4 上連接埠的目前配置：
+
「系統節點硬體統一連線展示」

+
系統會顯示類似下列範例的輸出：

+
....
*> ucadmin show
                Current  Current    Pending   Pending   Admin
Node   Adapter  Mode     Type       Mode      Type      Status
----   -------  ---      ---------  -------   --------  -------
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
*>
....
. 如果目前的SFP+模組不符合所需用途、請更換為正確的SFP+模組。
+
請聯絡您的NetApp代表、以取得正確的SFP+模組。

. 驗證設定：
+
「ucadmin show」

+
檢查「ucadmin show」命令的輸出、判斷UTA/UTA2連接埠是否具有您想要的特性。

+
以下範例的輸出顯示FC4類型的介面卡「1b」正在變更為「啟動器」、介面卡「2a」和「2b」的模式正在變更為「cna」：

+
....
*> ucadmin show
Node  Adapter  Current Mode  Current Type  Pending Mode  Pending Type  Admin Status
----  -------  ------------  ------------  ------------  ------------  ------------
f-a   1a       fc             initiator    -             -             online
f-a   1b       fc             target       -             initiator     online
f-a   2a       fc             target       cna           -             online
f-a   2b       fc             target       cna           -             online
4 entries were displayed.
*>
....
. 請採取下列其中一項行動：
+
[cols="30,70"]
|===
| 如果CNA連接埠... | 然後… 


| 沒有您想要的特性 | 前往 <<auto_check_4_step5,步驟5.>>。 


| 擁有您想要的個人風格 | 跳過步驟 5 至步驟 9，然後轉到<<auto_check_4_step10,步驟10>>。 
|===
. [[auto_check_4_step5]]請採取下列其中一項行動：
+
[cols="30,70"]
|===
| 如果您正在設定... | 然後… 


| UTA/UTA2卡上的連接埠 | 前往<<auto_check_4_step6,步驟6.>> 


| 內建UTA/UTA2連接埠 | 跳過第 6 步並轉到<<auto_check_4_step7,步驟7.>>。 
|===
. [[auto_check_4_step6]]如果轉接器處於啟動器模式，且 UTA/UTA2 連接埠處於線上狀態，則將 UTA/UTA2 連接埠離線：
+
「停用介面卡_adapter_name_」

+
目標模式中的介面卡會在維護模式中自動離線。

. [[auto_check_4_step7]]如果目前的組態與所需用途不符、請視需要變更組態：
+
`ucadmin modify -m fc|cna -t initiator|target <adapter_name>`

+
** 「-m」是個人化模式、FC或10GbE UTA。
** "-t"是FC4類型、"target（目標）"或"initiator（啟動器）"。
+

NOTE: 您必須對磁帶機和MetroCluster配置使用 FC 啟動器。您必須對 SAN 用戶端使用 FC 目標。



. 輸入以下命令（每個連接埠一次），使任何目標連接埠連線：
+
`storage enable adapter <adapter_name>`

. 連接連接埠。

