= 
:allow-uri-read: 


. [[auto_check_4_step17]在自動開機期間按下「Ctrl-C」、即可在「loader>」提示字元下停止節點。
. 在載入程式提示下、進入維護模式：
+
Boot_ONTAP maint

. 在維護模式中、顯示所有先前設定的啟動器連接埠、這些連接埠現在都處於目標模式：
+
「ucadmin show」

+
將連接埠改回啟動器模式：

+
「ucadmin modify -m fs -t initiator -f _Adapter name_'」

. 確認連接埠已變更為啟動器模式：
+
「ucadmin show」

. 結束維護模式：
+
《停止》

+
[NOTE]
====
如果您要從支援外部磁碟的系統升級至也支援外部磁碟的系統、請前往 <<auto_check_4_step22,步驟22>>。

如果您要從使用外部磁碟的系統升級至同時支援內部和外部磁碟的系統、例如AFF 、一個支援內部和外部磁碟的系統、請前往 <<auto_check_4_step23,步驟23>>。

====
. [[auto_check_4_step22]在載入程式提示下、開機：
+
Boot_ONTAP功能表

+
現在、在開機時、節點可以偵測先前指派給它的所有磁碟、並可依預期開機。

+
當您要更換的叢集節點使用根磁碟區加密時、ONTAP 無法從磁碟讀取磁碟區資訊。還原根磁碟區的金鑰：

+
.. 返回特殊的開機功能表：
`LOADER> boot_ontap menu`
+
[listing]
----
Please choose one of the following:
(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.

Selection (1-11)? 10
----
.. 選取*（10）Set Onboard Key Manager恢復機密*
.. 輸入 `y` 出現下列提示：
+
`This option must be used only in disaster recovery procedures. Are you sure? (y or n): y`

.. 在提示字元下、輸入金鑰管理程式的通關密碼。
.. 出現提示時輸入備份資料。
+

NOTE: 您必須已取得中的通關密碼和備份資料 link:prepare_nodes_for_upgrade.html["準備節點以進行升級"] 本程序的一節。

.. 系統重新開機至特殊開機功能表後、請執行選項*（1）正常開機*
+

NOTE: 您可能會在這個階段遇到錯誤。如果發生錯誤、請重複中的子步驟 <<auto_check_4_step22,步驟22>> 直到系統正常開機為止。




