= 
:allow-uri-read: 


您必須在機架中安裝node3、將node1的連線傳輸至node3、開機node3及安裝ONTAP 支援。接著、您必須重新指派節點1的任何備用磁碟、屬於根磁碟區的任何磁碟、以及任何未在程序中稍早重新放置到節點2的非根Aggregate、如本節所述。

.關於這項工作
重新配置作業會在此階段開始時暫停。此程序大部分是自動化的；此作業會暫停、以便您檢查其狀態。您必須手動恢復作業。此外、您必須驗證SAN LIF是否已成功移至節點3。

如果netboot node3沒有ONTAP 安裝在node1上的相同版本的支援功能、您就需要netboot node3。安裝node3之後、請從ONTAP 儲存在Web伺服器上的Image9映像啟動節點3。接著、您可以依照中的指示、將正確的檔案下載到開機媒體裝置、以供後續系統開機 link:prepare_for_netboot.html["準備netboot"]。

[IMPORTANT]
====
* 對於AFF A800或AFF C800控制器升級，在移除節點 1 之前，必須確保機箱中的所有驅動器都牢固地固定在中板上。有關詳細信息，請參閱 link:../upgrade-arl-auto-in-chassis/replace-node1-affa800.html["更換 AFF A800 或 AFF C800 控制器模組"]。
* 如果您要升級具有儲存磁碟的系統、則必須完成此一整節、然後前往 link:set_fc_or_uta_uta2_config_on_node3.html#configure-fc-ports-on-node3["在節點3上設定FC連接埠"] 和 link:set_fc_or_uta_uta2_config_on_node3.html#check-and-configure-utauta2-ports-on-node3["檢查並設定節點3上的UTA/UTA2連接埠"] 區段、在叢集提示字元中輸入命令。


====
.步驟
. [[[auto_install3_step1]]請確定您有節點3的機架空間。
+
如果節點1和節點2位於不同的機箱中、您可以將節點3放在與節點1相同的機架位置。但是、如果節點1與節點2位於同一個機箱中、則您需要將節點3放入自己的機架空間、最好是靠近節點1的位置。

. [[[auto_install3_step2]]依照節點機型的安裝與設定指示_、在機架中安裝節點3。
+

NOTE: 如果要升級到兩個節點都在同一個機箱中的系統，請將節點 4 和節點 3 安裝到機箱中。如果兩個節點沒有安裝在同一機箱中，啟動節點 3 時，它的行為就像是在雙機箱配置中一樣；而啟動節點 4 時，節點之間的互連將無法建立。

. [[auto_install3_step3]]纜線節點3、將連線從節點1移至節點3。
+
使用 node3 平台的《安裝與設定說明》、對應的磁碟架文件和《HA 對管理》文件連接以下連線。

+
參考link:other_references.html["參考資料"]連結到_HA 對管理_。

+
** 主控台（遠端管理連接埠）
** 叢集連接埠
** 資料連接埠
** 叢集與節點管理連接埠
** 儲存設備
** SAN組態：iSCSI乙太網路和FC交換器連接埠
+

NOTE: 您可能不需要將互連卡或叢集互連纜線連線從節點1移至節點3、因為大多數平台機型都有獨特的互連卡模式。若要進行支援、您需要將FC-VI纜線連線從節點1移至節點3。MetroCluster如果新主機沒有FC-VI卡、您可能需要移動FC-VI卡。



. [[auto_install3_step4]]開啟節點3的電源、然後在主控台終端按Ctrl-C存取開機環境提示字元、以中斷開機程序。
+
如果您要升級到同一機箱中同時具有兩個節點的系統、節點4也會重新開機。不過、您可以忽略node4開機、直到稍後再執行。

+

NOTE: 當您啟動節點3時、可能會看到下列警告訊息：

+
....
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
....
. [[auto_install3_step5]]如果您在中看到警告訊息 <<auto_install3_step4,步驟4.>>、請採取下列行動：
+
.. 檢查可能指出NVRAM電池電量不足以外問題的任何主控台訊息、並視需要採取任何必要的修正行動。
.. 讓電池充電並完成開機程序。
+

WARNING: *請勿超越延遲；如果電池無法充電，可能會導致資料遺失。 *

+

NOTE: 請參閱 link:prepare_for_netboot.html["準備netboot"]。




