= 
:allow-uri-read: 


. 將FC啟動器連接埠新增至儲存陣列做為新主機、將陣列LUN對應至新主機。
+
請參閱儲存陣列與分區文件以取得相關指示。

. 修改與儲存陣列上陣列LUN相關的主機或磁碟區群組中的全球連接埠名稱（WWPN）值。
+
安裝新的控制器模組會變更與每個內建FC連接埠相關的WWPN值。

. 如果您的組態使用交換器型分區、請調整分區以反映新的WWPN值。
. [[step27]設定 `bootarg.storageencryption.support` 和 `kmip.init.maxwait` 在節點2組態載入後、避免開機迴圈的變數。
+
如果您尚未在程序中稍早完成此作業、請參閱知識庫文章 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/How_to_tell_I_have_FIPS_drives_installed["如何判斷我安裝了FIPS磁碟機"^] 以判斷使用中的自我加密磁碟機類型。

+
[cols="35,65"]
|===
| 如果下列磁碟機正在使用中… | 然後… 


| 符合FIPS 140-2第2級自我加密要求的NetApp儲存加密（NSE）磁碟機  a| 
** `setenv bootarg.storageencryption.support *true*`
** 「kmip.init.maxwait關」




| NetApp非FIPS SED  a| 
** `setenv bootarg.storageencryption.support *false*`
** 「kmip.init.maxwait關」


|===
+

WARNING: *只要在HA配對上完成控制器升級、您就必須取消設定 `kmip.init.maxwait` 變動。請參閱 link:ensure_new_controllers_are_set_up_correctly.html#unset_maxwait_system_commands["請確認新控制器的設定正確、步驟12"]。如果發生停電、否則可能導致資料遺失。*

+
[NOTE]
====
您無法在同一個節點或HA配對上混用FIPS磁碟機與其他類型的磁碟機。

您可以在同一個節點或HA配對上混合使用SED與非加密磁碟機。

====
. 開機節點進入開機功能表：
+
Boot_ONTAP功能表

+
如果您沒有FC或UTA/UTA2組態、請執行 link:set_fc_or_uta_uta2_config_node4.html#auto_check_node4_step15["檢查並設定節點4步驟15上的UTA/UTA2連接埠"] 因此節點4可以識別節點2的磁碟。


