= 在節點3上設定FC連接埠
:allow-uri-read: 




== 在節點3上設定FC連接埠

如果節點3具有FC連接埠（內建或FC介面卡上）、您必須先在節點上設定連接埠組態、才能將其投入服務、因為連接埠並未預先設定。如果未設定連接埠、可能會導致服務中斷。

.開始之前
您必須擁有儲存在區段中節點1的FC連接埠設定值 link:prepare_nodes_for_upgrade.html["準備節點以進行升級"]。

.關於這項工作
如果您的系統沒有FC組態、您可以跳過本節。如果您的系統內建UTA/UTA2連接埠或UTA/UTA2卡、請在中設定 <<檢查並設定節點3上的UTA/UTA2連接埠>>。


IMPORTANT: 如果您的系統有儲存磁碟、請在叢集提示字元下輸入本節中的命令。如果您有「V系列系統」或有FlexArray 「支援虛擬化軟體」、並且已連線至儲存陣列、請在「維護」模式中輸入本節中的命令。

. [[step1]]比較節點3上的FC設定與先前從節點1擷取的設定。
. [[step2]]請採取下列其中一項行動：
+
[cols="30,70"]
|===
| 如果您要升級的系統... | 然後… 


| 具有儲存磁碟  a| 
在維護模式（開機功能表中的選項5）中、視需要修改節點3上的FC連接埠：

** 若要設定目標連接埠：


「ucadmin modify -m sfc-t target _adapter-'」

** 設定啟動器連接埠：


「ucadmin modify -m光纖通道-t啟動器_adapter-'」

「-t」是FC4類型：目標或啟動器。



| 是V系列系統、或具有FlexArray 「支援虛擬化的軟體」、並連接至儲存陣列  a| 
在維護模式（開機功能表中的選項5）中、視需要修改節點3上的FC連接埠：

`ucadmin modify -m fc -t initiator -f _adapter_port_name_`

`-t` 為FC4類型、目標或啟動器。


NOTE: FC連接埠必須設定為啟動器。

|===
. [[step3]請採取下列其中一項行動：
+
[cols="30,70"]
|===
| 如果您要升級的系統... | 然後… 


| 具有儲存磁碟 | 使用下列命令確認新設定、並檢查輸出「ucadmin show」 


| 是V系列系統、或具有FlexArray 「支援虛擬化的軟體」、並連接至儲存陣列 | 使用下列命令確認新設定、並檢查輸出「ucadmin show」 
|===
. [[step4]]結束維護模式：
+
《停止》

. 從載入程式提示字元啟動系統：
+
Boot_ONTAP功能表

. [[step6]輸入命令後、請等到系統在開機環境提示字元停止。
. 從開機功能表中選取「5」選項以進行維護模式。

