= 
:allow-uri-read: 


如果節點 4 上的ONTAP版本與節點 2 上的ONTAP版本不同，則需要對節點 4 進行網路啟動。安裝 node4 後，從儲存在 Web 伺服器上的ONTAP 9 映像啟動它。然後，您可以按照說明將正確的檔案下載到啟動媒體設備，以便後續系統啟動。 link:prepare_for_netboot.html["準備netboot"]。

[IMPORTANT]
====
* 對於AFF A800或AFF C800控制器升級，在移除節點 2 之前，必須確保機箱中的所有驅動器都牢固地固定在中板上。有關詳細信息，請參閱 link:../upgrade-arl-auto-in-chassis/replace-node1-affa800.html["更換 AFF A800 或 AFF C800 控制器模組"]。
* 如果您要升級具有儲存磁碟的系統，則必須完成整個部分，然後繼續link:set_fc_or_uta_uta2_config_node4.html["在節點4上設定FC或UTA/UTA2組態"] ，在群集提示符下輸入命令。


====
.步驟
. [[[auto_install4_step1]]請確定node4有足夠的機架空間。
+
如果node4與node2位於不同的機箱中、您可以將node4放在與node3相同的位置。如果節點2和節點4位於同一個機箱中、則節點4已位於適當的機架位置。

. 按照節點機型的安裝與設定說明_中的指示、在機架中安裝節點4。
. 纜線節點4、將連線從節點2移至節點4。
+
使用 node4 平台的《安裝與設定說明》、對應的磁碟架文件和《HA 對管理》文件連接以下連線。

+
參考link:other_references.html["參考資料"]連結到_HA 對管理_。

+
** 主控台（遠端管理連接埠）
** 叢集連接埠
** 資料連接埠
** 叢集與節點管理連接埠
** 儲存設備
** SAN組態：iSCSI乙太網路和FC交換器連接埠
+

NOTE: 您可能不需要將互連卡/FC-VI卡或互連/FC-VI纜線連線從節點2移至節點4、因為大多數平台機型都有獨特的互連卡機型。若要進行此功能、您必須將FC-VI纜線連線從節點2移至節點4。MetroCluster如果新主機沒有FC-VI卡、您可能需要移動FC-VI卡。



. 開啟節點4的電源、然後在主控台終端按Ctrl-C來存取開機環境提示字元、以中斷開機程序。
+

NOTE: 當您啟動節點4時、可能會看到下列警告訊息：

+
....
WARNING: The battery is unfit to retain data during a power outage. This is likely
         because the battery is discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will complete
         and services will be engaged. To override this delay, press 'c' followed
         by 'Enter'
....
. 如果您在步驟4中看到警告訊息、請採取下列行動：
+
.. 檢查可能指出NVRAM電池電量不足以外問題的任何主控台訊息、並視需要採取任何必要的修正行動。
.. 讓電池充電並完成開機程序。
+

WARNING: *請勿超越延遲；如果電池無法充電，可能會導致資料遺失。 *

+

NOTE: 請參閱 link:prepare_for_netboot.html["準備netboot"]。




