= 
:allow-uri-read: 


. [[man_install3_step17]如果ONTAP 安裝在節點3上的版本與ONTAP 安裝在節點1上的版本相同或更新、請列出磁碟並重新指派給新節點3：
+
Boot_ONTAP

+

WARNING: 如果此新節點曾經用於任何其他叢集或HA配對、您必須執行 `wipeconfig` 繼續之前。否則可能導致服務中斷或資料遺失。如果先前使用的是替換控制器、請聯絡技術支援部門、特別是當控制器以ONTAP 7-Mode執行時。

. [[man_install3_step18]按下CTRL－C以顯示開機功能表。
. [[man_install3_step19]執行下列其中一項動作：
+
[cols="35,65"]
|===
| 如果您要升級的系統... | 然後... 


| 節點3上是否有正確或最新ONTAP 的版本 | 前往 <<man_install3_step20,步驟20>>。 


| 節點3上有正確或最新版本ONTAP 的資訊 | 前往 <<man_install3_step25,步驟25>>。 
|===
. [[man_install3_step20]]選擇下列其中一項動作來設定netboot連線。
+

NOTE: 您必須使用管理連接埠和IP做為netboot連線。請勿使用資料LIF IP、否則在執行升級時可能會發生資料中斷。

+
[cols="35,65"]
|===
| 如果動態主機組態傳輸協定（DHCP）是... | 然後... 


| 執行中 | 在開機環境提示字元中輸入下列命令、即可自動設定連線：「ifconfige0M -auto」 


| 未執行  a| 
在開機環境提示字元中輸入下列命令、手動設定連線：
`ifconfig e0M -addr=_filer_addr_ -mask=_netmask_ -gw=_gateway_ -dns=_dns_addr_ -domain=_dns_domain_`

`_filer_addr_` 為儲存系統的IP位址（必填）。
`_netmask_` 是儲存系統的網路遮罩（必填）。
`_gateway_` 是儲存系統的閘道（必填）。
`_dns_addr_` 為網路上名稱伺服器的IP位址（選用）。
`_dns_domain_` 為網域名稱服務（DNS）網域名稱。如果使用此選用參數、則不需要netboot伺服器URL中的完整網域名稱；您只需要伺服器的主機名稱。


NOTE: 您的介面可能需要其他參數。在韌體提示字元中輸入「Help ifconfig」以取得詳細資料。

|===
. [[man_install3_step21]]在節點3上執行netboot：
+
[cols="35,65"]
|===
| 適用於... | 然後... 


| FAS / AFF8000系列系統 | “netboot \http://<web_server_ip>/<path_to_webaccessible_directory>/netboot/kernel` 


| 所有其他系統 | “netboot \http://<web_server_ip>/<path_to_webaccessible_directory>/<ontap_version>_image.tgz` 
|===
+
您可以在其中下載「<ONTAP_VERSION >_image.tgz」 link:prepare_for_netboot.html#man_netboot_Step1["步驟1."] 在_Prepare for netboot_一節中。

+

NOTE: 請勿中斷開機。

. [[man_install3_step22]從開機功能表中、選取選項*（7）「Install new software* first（先安裝新軟體*）」。
+
此功能表選項會下載新ONTAP 的功能表映像、並將其安裝至開機裝置。

+
請忽略下列訊息：

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
本附註適用於ONTAP 不中斷營運的更新功能、不適用於控制器升級。

+

NOTE: 請務必使用netboot將新節點更新為所需映像。如果您使用另一種方法在新控制器上安裝映像、可能會安裝錯誤的映像。此問題適用於ONTAP 所有版本的更新版本。netboot程序與選項結合使用 `(7) Install new software` 將開機媒體擦除、並將相同ONTAP 的版本ONTAP 資訊區放置在兩個影像分割區上。

. [[man_install3_step23]如果系統提示您繼續此程序、請輸入「y」、並在系統提示您輸入套件時、輸入下列URL：
+
http://<web_server_ip>/<path_to_web-accessible_directory>/<ontap_version_image>.tgz`

. [[man_install3_step24]完成下列子步驟：
+
.. 當您看到下列提示時、請輸入「n」跳過備份恢復：
+
[listing]
----
Do you want to restore the backup configuration now? {y|n}
----
.. 當您看到下列提示時、輸入「y」重新開機：
+
[listing]
----
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
----
+
控制器模組會重新開機、但會在開機功能表停止、因為開機裝置已重新格式化、需要還原組態資料。



. [[man_install3_step25]輸入「5」選取*（5）維護模式開機*、然後在提示繼續開機時輸入「y」。
. [[man_install3_step26]在繼續之前、請前往 link:set_fc_uta_uta2_config_node3.html["在節點3上設定FC或UTA/UTA2組態"] 可對節點上的FC或UTA/UTA2連接埠進行必要的變更。
+
進行這些區段中建議的變更、重新啟動節點、然後進入維護模式。

. [[man_install3_step27]尋找節點3的系統ID：
+
「展示-A'」

+
系統會顯示節點的系統ID及其磁碟的相關資訊、如下列範例所示：

+
[listing]
----
 *> disk show -a
 Local System ID: 536881109
 DISK     OWNER                    POOL  SERIAL   HOME          DR
 HOME                                    NUMBER
 -------- -------------            ----- -------- ------------- -------------
 0b.02.23 nst-fas2520-2(536880939) Pool0 KPG2RK6F nst-fas2520-2(536880939)
 0b.02.13 nst-fas2520-2(536880939) Pool0 KPG3DE4F nst-fas2520-2(536880939)
 0b.01.13 nst-fas2520-2(536880939) Pool0 PPG4KLAA nst-fas2520-2(536880939)
 ......
 0a.00.0               (536881109) Pool0 YFKSX6JG              (536881109)
 ......
----
+

NOTE: 您可能會在輸入命令後看到「磁碟顯示：沒有磁碟符合選項-A.」訊息。這不是錯誤訊息、因此您可以繼續執行程序。

. [[man_install3_step28]重新指派node1的備援磁碟、屬於根的任何磁碟、以及先前未重新部署至節點2的任何非根Aggregate link:relocate_non_root_aggr_node1_node2.html["將非根Aggregate從節點1重新部署到節點2"]。
+
根據您的系統是否有共享磁碟、輸入適當形式的「磁碟重新指派」命令：

+

NOTE: 如果您的系統上有共享磁碟、混合式Aggregate或兩者、則必須使用正確的 `disk reassign` 下表中的命令。

+
[cols="35,65"]
|===
| 如果磁碟類型為... | 然後執行命令... 


| 共享磁碟 | "Disk reassign-s _node1_sysid_-d _node3_sysid_-p _nod2_sysid_" 


| 無共享磁碟 | "Disk reassign-s _node1_sysid_-d _node3_sysid_" 
|===
+
如需「節點1_sysid_」值、請使用中擷取的資訊 link:record_node1_information.html["記錄node1資訊"]。若要取得「_node3_sysid_」的值、請使用「sysconfig」命令。

+

NOTE: 只有在存在共享磁碟時、維護模式才需要使用「-p」選項。

+
"disk reassign"命令只重新分配當前擁有者是"_node1_sysid_"的磁碟。

+
系統會顯示下列訊息：

+
[listing]
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)?
----
. [[man_install3_step29]輸入「n」。
+
系統會顯示下列訊息：

+
[listing]
----
After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)?
----
. [[man_install3_step30]輸入「y」
+
系統會顯示下列訊息：

+
[listing]
----
Disk ownership will be updated on all disks previously belonging to Filer with sysid <sysid>.
Do you want to continue (y/n)?
----
. [[man_install3_step3]]輸入「y」。
. [[man_install3_step32]]如果您要從具有外部磁碟的系統升級至支援內部和外部磁碟AFF 的系統（例如、E4A800系統）、請將node1 Aggregate設為root、以確認node3從節點1的根Aggregate開機。
+

WARNING: *警告*：您必須依照所示的確切順序執行下列子步驟；否則可能導致中斷運作、甚至資料遺失。

+
下列程序會將node3設定為從節點1的根Aggregate開機：

+
.. 檢查node1 Aggregate的RAID、plex和Checksum資訊：
+
「aggr狀態-r」

.. 檢查node1 Aggregate的狀態：
+
「aggr狀態」

.. 必要時使node1 Aggregate上線：
+
"aggr_online _root_aggr_from節點1_"

.. 防止節點3從其原始根Aggregate開機：「aggr offline _root_aggr_on_node3_」
.. 將node1根Aggregate設為節點3的新根Aggregate：
+
"aggr options _aggr_from節點1_root"

.. 確認節點3的根Aggregate為離線狀態、且從節點1移轉的磁碟根Aggregate為線上狀態、並設定為root：
+
「aggr狀態」

+

NOTE: 如果無法執行上一個子步驟、可能會導致節點3從內部根Aggregate開機、或是導致系統假設有新的叢集組態存在、或提示您識別一個。

+
以下是命令輸出的範例：



+
[listing]
----
 ---------------------------------------------------------------
      Aggr State               Status          Options
 aggr0_nst_fas8080_15 online   raid_dp, aggr   root, nosnap=on
                               fast zeroed
                               64-bit

   aggr0 offline               raid_dp, aggr   diskroot
                               fast zeroed
                               64-bit
 ----------------------------------------------------------------------
----
. [[man_install3_step33]確認控制器和機箱設定為「ha」：
+
《ha-config show》

+
以下範例顯示ha-config show命令的輸出：

+
[listing]
----
 *> ha-config show
    Chassis HA configuration: ha
    Controller HA configuration: ha
----
+
系統會記錄在可程式化的ROM（Prom）中、無論是HA配對或獨立組態。獨立式系統或HA配對內的所有元件的狀態必須相同。

+
如果控制器和機箱未設定為「ha」、請使用下列命令修正組態：

+
「ha-config modify控制器ha」

+
「ha-config modify機箱ha」

+
如果您使用MetroCluster 的是不含任何功能的組態、請使用下列命令來修改控制器和機箱：

+
「ha-config modify控制器MCC」

+
「ha-config modify機箱MCC」

. [[man_install3_step34]銷毀節點3上的信箱：
+
《破壞本地的信箱》

+
主控台會顯示下列訊息：

+
[listing]
----
Destroying mailboxes forces a node to create new empty mailboxes, which clears any takeover state, removes all knowledge of out-of-date plexes of mirrored volumes, and will prevent management services from going online in 2-node cluster HA configurations. Are you sure you want to destroy the local mailboxes?
----
. [[man_install3_step35]在提示字元輸入「y」、確認您要銷毀本機信箱。
. [[man_install3_step36]結束維護模式：
+
《停止》

+
系統會在開機環境提示字元停止。

. [[man_install3_step37]在節點2上、檢查系統日期、時間和時區：
+
'日期'

. [[man_install3_step38]在節點3上、請在開機環境提示字元中檢查日期：
+
「如何日期」

. [[man_install3_step39]如有必要、請在節點3上設定日期：
+
"et date _mm/dd/yed_"

. [[man_install3_step40]在節點3上、檢查開機環境提示字元的時間：
+
「時間安排」

. [[man_install3_step41]如有必要、請在節點3上設定時間：
+
"et time _hh：mm:ss_"

. [[man_install3_step42]]確認合作夥伴系統ID設定正確、如所述 <<man_install3_step28,步驟28>> 在-p交換器下：
+
《prontenv合作夥伴sysid》

. [[man_install3_step43]如有必要、請在節點3上設定合作夥伴系統ID：
+
"etenv PARTNER-sysid _node2_sysid_"

+
儲存設定：

+
「aveenv」

. [[man_install3_step44]在開機環境提示字元下存取開機功能表：
+
Boot_ONTAP功能表

. [[man_install3_step45]在開機功能表中、在提示字元中輸入「6」、選取選項*（6）Update flash from Backup config*（從備份組態更新Flash）。
+
系統會顯示下列訊息：

+
[listing]
----
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?:
----
. [[man_install3_step46]在提示字元中輸入「y」。
+
開機會正常進行、然後系統會要求您確認系統ID不相符。

+

NOTE: 系統可能會重新開機兩次、然後才顯示不相符的警告。

. [[man_install3_step47]確認不相符的情形、如下列範例所示：
+
[listing]
----
WARNING: System id mismatch. This usually occurs when replacing CF or NVRAM cards!
Override system id (y|n) ? [n] y
----
+
在正常開機之前、節點可能會經過一輪重新開機。

. [[man_install3_step48]登入節點3。

