= 
:allow-uri-read: 


您必須在機架中安裝node4、將node2連線傳輸至node4和開機node4。您也必須重新指派任何節點2備援磁碟、屬於根的任何磁碟、以及先前未重新部署至節點3的任何非根Aggregate。

.關於這項工作
如果節點 4 上安裝的 ONTAP 9 版本與節點 2 上安裝的 ONTAP 9 版本不同，則必須安裝node4之後、請從ONTAP 儲存在Web伺服器上的Image9映像啟動節點3。透過網路啟動節點 4。然後，您可以按照link:prepare_for_netboot.html["準備netboot"] 。

但是，如果 node4 上安裝的 ONTAP 9 與 node2 上安裝的相同或更高版本，則無需透過網路啟動 node4。

[IMPORTANT]
====
* 對於 AFF A800 或 AFF C800 控制器升級，在移除節點 2 之前，必須確保機殼內的所有磁碟機都牢固地固定在中板上。如需更多資訊、請參閱 link:../upgrade-arl-auto-affa900/replace-node1-affa800.html["更換 AFF A800 或 AFF C800 控制器模組"]。
* 如果您要升級具有儲存磁碟的系統，則必須完成整個部分，然後繼續執行下一節link:set_fc_uta_uta2_config_node4.html["在節點4上設定FC或UTA/UTA2組態"] ，在群集提示符下輸入命令。


====
.步驟
. [[man_install4_Step1]]請採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果node4將位於... | 然後... 


| 與節點3分開的機箱 | 前往 <<man_install4_Step2,步驟2>>。 


| 同一個機箱與節點3 | 跳過步驟2和3、前往 <<man_install4_Step4,步驟4.>>。 
|===
. [[man_install4_Step2]]請確定節點4有足夠的機架空間。
+
如果node4與node3位於不同的機箱中、您可以將node4放在與node2相同的位置。如果節點3和節點4位於同一個機箱中、則節點4已位於適當的機架位置。

. 按照節點機型的安裝與設定說明_中的指示、在機架中安裝節點4。
. [[man_install4_stip4]]纜線節點4、將連線從節點2移至節點4。
+
下列參考資料可協助您建立適當的纜線連線。前往 link:other_references.html["參考資料"] 以連結至他們。

+
** node4 平台的_安裝與設定說明_
** 適當的磁碟櫃程序
** _HA 配對管理 _ 文件
+
纜線連接下列連接：

** 主控台（遠端管理連接埠）
** 叢集連接埠
** 資料連接埠
** 叢集與節點管理連接埠
** 儲存設備
** SAN組態：iSCSI乙太網路和FC交換器連接埠


+

NOTE: 您不需要將互連卡/FC_VI卡或互連/FC_VI纜線連線從節點2移至節點4、因為大多數平台機型都有獨特的互連卡機型。

. 請採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果節點4位於... | 然後... 


| 與節點3相同的機箱 | 前往 <<man_install4_Step8,步驟8.>>。 


| 與節點3分開的機箱 | 前往 <<man_install4_Step6,步驟6.>>。 
|===
. [[man_install4_Step6]] 開啟 node4 的電源、然後按 Ctrl-C 存取開機環境提示來中斷開機。
+

NOTE: 當您啟動節點4時、可能會看到下列訊息：

+
[listing]
----
WARNING: The battery is unfit to retain data during a power
         outage. This is likely because the battery is
         discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will
         complete and services will be engaged.
         To override this delay, press 'c' followed by 'Enter'
----
. [[man_install4_stept7]]如果您在步驟6中看到警告訊息、請採取下列行動：
+
.. 檢查可能指出NVRAM電池電量不足以外問題的任何主控台訊息、並視需要採取任何必要的修正行動。
.. 讓電池充電並完成開機程序。
+

WARNING: *不要覆蓋延遲。如果電池無法充電，可能會導致資料遺失。 *



. [[man_install4_Step8]]在維護模式提示下，輸入以下命令：
+
《停止》

+
系統會在開機環境提示字元停止。

. 設定node4 ONTAP 以供使用：
+
「預設值」


