= 檢查並設定節點4上的UTA/UTA2連接埠
:allow-uri-read: 




== 檢查並設定節點4上的UTA/UTA2連接埠

如果節點4內建UTA/UTA2連接埠或UTA/UTA2A卡、您必須檢查連接埠的組態並加以設定、視您要使用升級系統的方式而定。

.開始之前
UTA/UTA2連接埠必須具備正確的SFP+模組。

.關於這項工作
UTA/UTA2連接埠可設定為原生FC模式或UTA/UTA2A模式。FC模式支援FC啟動器和FC目標；UTA/UTA2模式可讓並行NIC和FCoE流量共用相同的10GbE SFP+介面、並支援FC目標。


NOTE: NetApp行銷資料可能會使用UTA2一詞來指稱CNA介面卡和連接埠。不過、CLI使用「CNA」一詞。

UTA/UTA2連接埠可能位於介面卡或控制器上、且具有下列組態：

* UTA/UTA2卡與控制器一起訂購、在出貨前已設定為符合您要求的特性。
* 與控制器分開訂購的UTA/UTA2卡會隨附預設FC目標特性。
* 新控制器上的內建UTA/UTA2連接埠已設定（出貨前）、以符合您要求的特性。


不過、您可以檢查節點4上UTA/UTA2連接埠的組態、並視需要加以變更。


WARNING: 除非指示進入維護模式，否則請在叢集提示字元下輸入本節中的命令。如果您有MetroCluster FC 系統，則必須處於維護模式才能設定 UTA/UTA2 連接埠。

.步驟
. 檢查 node4 上連接埠的目前配置：
+
「系統節點硬體統一連線展示」

. 如果目前的SFP+模組不符合所需用途、請更換為正確的SFP+模組。
+
請聯絡您的NetApp代表、以取得正確的SFP+模組。

. 檢查「系統節點硬體統一連線show」或「ucadmin show」命令的輸出、判斷UTA/UTA2連接埠是否具有您想要的特性。
. 請採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果CNA連接埠... | 然後... 


| 沒有您想要的特性 | 前往 <<man_check_4_Step5,步驟5.>>。 


| 擁有您想要的個人風格 | 跳過步驟5至步驟12、前往 <<man_check_4_Step13,步驟13>>。 
|===
. [[man_check_4_Step5]]如果系統有儲存磁碟並且正在執行Data ONTAP 8.3，則啟動 node4 並進入維護模式：
+
Boot_ONTAP maint

. 輸入下列命令並檢查其輸出、以驗證設定：
+
「ucadmin show」

. 請採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果您正在設定... | 然後... 


| UTA/UTA2A卡上的連接埠 | 前往<<man_check_4_Step8,步驟8.>>。 


| 內建UTA/UTA2連接埠 | 跳過第 8 步並轉到<<man_check_4_Step9,步驟9.>>。 
|===
. [[man_check_4_Step8]]如果轉接器處於啟動器模式，且 UTA/UTA2 連接埠處於線上狀態，則將 UTA/UTA2 連接埠離線：
+
「停用介面卡_adapter_name_」

+
目標模式中的介面卡會在維護模式中自動離線。

. [[man_check_4_Step9]]如果目前配置與所需用途不匹配，請輸入以下命令根據需要更改配置：
+
「ucadmin modify -m fc|cna -t啟動器| target _adapter_name_」

+
** 「-m」是個人化模式：FC或10GbE UTA。
** 「-t」是FC4類型：目標或啟動器。


+

NOTE: 您必須對磁帶驅動器使用 FC 啟動器，對 SAN 用戶端使用 FC 目標。

. 如果系統有儲存磁碟，請輸入以下命令：
+
《停止》

+
系統會在開機環境提示字元停止。

+
.. 輸入下列命令：
+
Boot_ONTAP



. 如果系統有儲存磁碟，請輸入以下命令：
+
「系統節點硬體統一連線展示」

+
以下範例的輸出顯示FC4類型的介面卡「1b」正在變更為「啟動器」、介面卡「2a」和「2b」的模式正在變更為「cna」。

+
[listing]
----
cluster1::> system node hardware unified-connect show
               Current  Current   Pending  Pending    Admin
Node  Adapter  Mode     Type      Mode     Type       Status
----  -------  -------  --------- -------  -------    -----
f-a    1a      fc       initiator -        -          online
f-a    1b      fc       target    -        initiator  online
f-a    2a      fc       target    cna      -          online
f-a    2b      fc       target    cna      -          online
4 entries were displayed.
----
. 針對每個連接埠輸入下列其中一個命令、將任何目標連接埠置於線上：
+
網路FCP介面卡修改-node_node_name_-介 面卡_adapter_name_-state up

. [[man_inCheck _4_Step13]連接連接埠。

