= 
:allow-uri-read: 


在將 node2 替換爲 node4 之前，您需要爲 node2 發送 AutoSupport 消息，然後將 node2 擁有的非根聚合重新定位到 node3 。

[[sysconfig-a-command]]
.步驟
. 確認已在 node2 和 node3 上正確設定合作夥伴系統 ID ：
+
** `system node run -node _node2_ -command sysconfig -a`
** `system node run -node _node3_ -command sysconfig -a`
+
系統會顯示類似下列範例的輸出：

+
[listing, subs="+quotes"]
----
NetApp Release 9.16.1: Mon Feb 10 07:55:45 EST 2025
System ID: _system-ID_; *partner ID: _partner-system-ID_*
System Serial Number: _system-serial-number_
System Rev: A0
System Storage Configuration: Mixed-Path HA
----
+
如果 node2 或 node3 的「合作夥伴 ID 」不正確：

+
... 以不正確的值重新啟動節點。
... 重新執行中的命令<<sysconfig-a-command,步驟1.>>，確認「合作夥伴 ID 」已變更為正確的值。




. 傳送 AutoSupport 訊息至 NetApp for node2 ：
+
「系統節點AutoSupport 無法叫用-node_node2_-type all -messing _node2_ from _platform _old_ to _platform _new_」（將_node2_從_platform _old_升級為_platform _new_）。

. 驗AutoSupport 證是否已傳送此訊息：
+
「系統節點AutoSupport 實體show -node2_-instance」

+
「Last Subject sent：」（上次傳送主旨：）和「Last Time sent：」（上次傳送時間：）欄位包含上次傳送訊息的訊息標題、以及訊息傳送時間。

. 重新部署非根集合體：
+
.. 將權限層級設為進階：
+
"進階權限"

.. 列出節點2擁有的Aggregate：
+
「torage Aggregate show -Owner-name _node2_」

.. 開始進行Aggregate重新配置：
+
「torage Aggregate regate or搬 移開始節點節點節點節點2 _-destate _node3_-Aggregate-list *-n控制器升級true」

+

NOTE: 此命令只會尋找非根Aggregate。

.. 出現提示時、請輸入「y」。
+
重新配置會在背景中進行。重新部署集合體可能需要幾秒鐘到幾分鐘的時間。時間包括用戶端中斷和非中斷部分。此命令不會重新定位任何離線或受限制的集合體。

.. 返回管理權限層級：
+
「et -priv. admin」



. 驗證node2的重新定位狀態：
+
「torage Aggregate regate reg搬 移顯示-node2_」

+
在重新定位集合之後，輸出會顯示「完成」。

+

NOTE: 您必須等到節點2所擁有的所有集合體都重新放置到節點3之後、才能繼續下一步。

. 請採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果重新配置... | 然後... 


| 所有集合體都成功 | 前往 <<man_relocate_2_3_step7,步驟7.>>。 


| 任何Aggregate都失敗或遭否決  a| 
.. 顯示詳細的狀態訊息：
+
「torage Aggregate show -instance」

+
您也可以檢查EMS記錄、查看所需的修正行動。

+

NOTE: 「EVENT log show」命令會列出發生的任何錯誤。

.. 執行修正行動。
.. 將權限層級設為進階：
+
"進階權限"

.. 重新部署任何故障或被否決的集合體：
+
「torage Aggregate regate regate orocationstart -node2_-destate _node3_-Aggregate-list *-n控制器升級true」

.. 出現提示時、請輸入「y」。
.. 返回管理權限層級：
+
「et -priv. admin」



如有必要、您可以使用下列其中一種方法強制重新配置：

** 透過壓倒性的否決檢查：
+
「torage aggregate regate regate regate reg搬 移開始- overre-tetoes true -n控制器升級」

** 覆寫目的地檢查：
+
「torage Aggregate regate regate regate regate reg搬 移開始- overre-destination-checkstrue -ndocn控制 器升級」



如需儲存Aggregate重新配置命令的詳細資訊、請前往 link:other_references.html["參考資料"] 若要使用CLCLI和_例ONTAP 9命令連結至_磁碟和集合管理：手冊頁參考_。

|===
. [[man_region_2_3_step7]] 驗證節點 3 上的所有非根集合體是否均為線上：
+
「torage Aggregate show -node3_-state offline -root false」

+
如果有任何Aggregate已經離線或變成外部、您必須將其上線、每個Aggregate一次：

+
'線上儲存Aggregate -Agggr_name_'

. 驗證節點3上的所有磁碟區是否都處於線上狀態：
+
「Volume show -node3_-state offline」

+
如果節點3上有任何磁碟區離線、您必須將其上線、每個磁碟區一次：

+
「Volume online -vserver _vserver-name_-volume _volume名稱_」

. 確認 node2 沒有任何線上非根集合體：
+
「torage Aggregate show -Owner-name _node2_-ha-policy SFO -state online」

+
命令輸出不應顯示線上非根Aggregate、因為所有非根線上Aggregate都已重新部署至節點3。


