= 
:allow-uri-read: 


. 記錄兩個節點的機型、系統ID和序號：
+
「系統節點show -node1、node2_-instance」

+

NOTE: 您將使用此資訊重新指派磁碟、並取消委任原始節點。

. 在節點1和節點2上輸入下列命令、並從輸出中記錄磁碟櫃、每個磁碟櫃的磁碟數目、Flash儲存詳細資料、記憶體、NVRAM和網路卡的相關資訊：
+
"run -node_node_name_ sysconfig"

+

NOTE: 您可以使用此資訊來識別可能要傳輸至節點3或節點4的零件或配件。如果您不知道節點是V系列系統、或是使用FlexArray 了「支援虛擬化」軟體、也可以從輸出中學習。

. 在節點1和節點2上輸入下列命令、並記錄兩個節點上線上的Aggregate：
+
「torage Aggregate show -node_node_name_-state online」

+

NOTE: 您可以使用此資訊和下列子步驟中的資訊、在整個程序中驗證集合體和磁碟區是否保持線上狀態、但在重新配置期間離線的短暫期間除外。

. [man準備節點_step19]在節點1和節點2上輸入下列命令、並記錄兩個節點上離線的磁碟區：
+
「Volume show -node_node_name_-st態offline」

+

NOTE: 升級之後、您將再次執行命令、並將此步驟的輸出與輸出進行比較、以查看是否有任何其他磁碟區離線。

+
.. 輸入下列命令、查看是否在節點1或節點2上設定任何介面群組或VLAN：
+
「網路連接埠ifgrp show」

+
「網路連接埠VLAN show」

+
記下是在節點1或節點2上設定介面群組或VLAN、您需要在下一步及後續程序中提供這些資訊。

.. 在節點1和節點2上完成下列子步驟、以確認稍後程序中的實體連接埠可以正確對應：


. 輸入下列命令、查看節點上是否有「clusterwide」以外的容錯移轉群組：
+
「網路介面容錯移轉群組顯示」

+
容錯移轉群組是系統上的一組網路連接埠。由於升級控制器硬體可能會變更實體連接埠的位置、因此在升級期間可能會不慎變更容錯移轉群組。

+
系統會在節點上顯示容錯移轉群組、如下列範例所示：

+
....
cluster::> network interface failover-groups show

Vserver             Group             Targets
------------------- ----------------- ----------
Cluster             Cluster           node1:e0a, node1:e0b
                                      node2:e0a, node2:e0b

fg_6210_e0c         Default           node1:e0c, node1:e0d
                                      node1:e0e, node2:e0c
                                      node2:e0d, node2:e0e

2 entries were displayed.
....
. 如果故障切換群組並非「clusterwide」、請記錄故障切換群組名稱和屬於故障切換群組的連接埠。
. 輸入下列命令、查看節點上是否已設定任何VLAN：
+
「網路連接埠VLAN show -node_node_name_」

+
VLAN是透過實體連接埠進行設定。如果實體連接埠有所變更、則稍後將需要重新建立VLAN。

+
系統會顯示節點上設定的VLAN、如下列範例所示：

+
....
cluster::> network port vlan show

Network Network
Node    VLAN Name Port    VLAN ID MAC Address
------  --------- ------- ------- ------------------
node1   e1b-70    e1b     70      00:15:17:76:7b:69
....
. 如果節點上已設定VLAN、請記下每個網路連接埠和VLAN ID配對。
+
.. 請採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果介面群組或VLAN ... | 然後... 


| 在節點1或節點2上 | 完成 <<man_prepare_nodes_step23,步驟23>> 和 <<man_prepare_nodes_step24,步驟24>>。 


| 不在節點1或節點2上 | 前往 <<man_prepare_nodes_step24,步驟24>>。 
|===
.. [man準備節點_step23]如果您不知道節點1和節點2是否位於SAN或非SAN環境中、請輸入下列命令並檢查其輸出：
+
「網路介面show -vserver _vserver_name_-data-protocol iscsiSCSI|FCP」

+
如果未針對SVM設定iSCSI或FC、則命令會顯示類似下列範例的訊息：

+
....
cluster::> network interface show -vserver Vserver8970 -data-protocol iscsi|fcp
There are no entries matching your query.
....
+
您可以使用「network interface show」命令搭配「-data傳輸協定NFS|CIFS」參數、確認節點是否位於NAS環境中。

+
如果已為SVM設定iSCSI或FC、則命令會顯示類似下列範例的訊息：

+
....
cluster::> network interface show -vserver vs1 -data-protocol iscsi|fcp

         Logical    Status     Network            Current  Current Is
Vserver  Interface  Admin/Oper Address/Mask       Node     Port    Home
-------- ---------- ---------- ------------------ -------- ------- ----
vs1      vs1_lif1   up/down    172.17.176.20/24   node1    0d      true
....
.. [man準備節點_step24]完成下列子步驟、確認叢集中的所有節點都處於仲裁狀態：


. 輸入進階權限層級：
+
"進階權限"

+
系統會顯示下列訊息：

+
....
Warning: These advanced commands are potentially dangerous; use them only when directed to do so by NetApp personnel.
Do you wish to continue? (y or n):
....
. 輸入「y」。
. 針對每個節點、驗證核心中的叢集服務狀態一次：
+
「叢集核心服務展示」

+
系統會顯示類似下列範例的訊息：

+
....
cluster::*> cluster kernel-service show

Master        Cluster       Quorum        Availability  Operational
Node          Node          Status        Status        Status
------------- ------------- ------------- ------------- -------------
node1         node1         in-quorum     true          operational
              node2         in-quorum     true          operational

2 entries were displayed.
....
+
叢集中的節點在大多數節點狀況良好且能夠彼此通訊時、都處於仲裁狀態。如需詳細資訊、請參閱 link:other_references.html["參考資料"] 連結至_System Administration Reference。

. 返回管理權限層級：
+
「et -priv. admin」

+
.. 請採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果叢集... | 然後... 


| 已設定SAN | 前往 <<man_prepare_nodes_step26,步驟26>>。 


| 未設定SAN | 前往 <<man_prepare_nodes_step29,步驟29>>。 
|===
.. [[man_prepe_node_step26]]輸入下列命令並檢查其輸出、驗證節點1和節點2上是否有已啟用SAN iSCSI或FC服務的每個SVM的SAN LIF：
+
「網路介面show -data-Protocol iscsiSCSI|FCP -home-node_node_name_」

+
此命令會顯示節點1和節點2的SAN LIF資訊。下列範例顯示「Status admin/Oper（狀態管理/操作）」欄中的狀態為「up / up（開/開）」、表示已啟用SAN iSCSI和FC服務：

+
....
cluster::> network interface show -data-protocol iscsi|fcp
            Logical    Status     Network                  Current   Current Is
Vserver     Interface  Admin/Oper Address/Mask             Node      Port    Home
----------- ---------- ---------- ------------------       --------- ------- ----
a_vs_iscsi  data1      up/up      10.228.32.190/21         node1     e0a     true
            data2      up/up      10.228.32.192/21         node2     e0a     true

b_vs_fcp    data1      up/up      20:09:00:a0:98:19:9f:b0  node1     0c      true
            data2      up/up      20:0a:00:a0:98:19:9f:b0  node2     0c      true

c_vs_iscsi_fcp data1   up/up      20:0d:00:a0:98:19:9f:b0  node2     0c      true
            data2      up/up      20:0e:00:a0:98:19:9f:b0  node2     0c      true
            data3      up/up      10.228.34.190/21         node2     e0b     true
            data4      up/up      10.228.34.192/21         node2     e0b     true
....
+
或者、您也可以輸入下列命令來檢視更詳細的LIF資訊：

+
「網路介面顯示-instance -data傳輸協定isciSCSI|FCP」

.. 輸入下列命令並記錄系統的輸出、以擷取原始節點上任何FC連接埠的預設組態：
+
「ucadmin show」

+
命令會顯示叢集中所有FC連接埠的相關資訊、如下列範例所示：

+
....
cluster::> ucadmin show

                Current Current   Pending Pending   Admin
Node    Adapter Mode    Type      Mode    Type      Status
------- ------- ------- --------- ------- --------- -----------
node1   0a      fc      initiator -       -         online
node1   0b      fc      initiator -       -         online
node1   0c      fc      initiator -       -         online
node1   0d      fc      initiator -       -         online
node2   0a      fc      initiator -       -         online
node2   0b      fc      initiator -       -         online
node2   0c      fc      initiator -       -         online
node2   0d      fc      initiator -       -         online
8 entries were displayed.
....
+
您可以在升級後使用這些資訊來設定新節點上的FC連接埠組態。

.. 如果您要升級V系列系統或使用FlexArray NetApp虛擬化軟體的系統、請輸入下列命令並記錄輸出、以擷取有關原始節點拓撲的資訊：
+
「torage Array config show -switch'」

+
系統會顯示拓撲資訊、如下列範例所示：

+
....
cluster::> storage array config show -switch

      LUN LUN                                  Target Side Initiator Side Initi-
Node  Grp Cnt Array Name    Array Target Port  Switch Port Switch Port    ator
----- --- --- ------------- ------------------ ----------- -------------- ------
node1 0   50  I_1818FAStT_1
                            205700a0b84772da   vgbr6510a:5  vgbr6510s164:3  0d
                            206700a0b84772da   vgbr6510a:6  vgbr6510s164:4  2b
                            207600a0b84772da   vgbr6510b:6  vgbr6510s163:1  0c
node2 0   50  I_1818FAStT_1
                            205700a0b84772da   vgbr6510a:5  vgbr6510s164:1  0d
                            206700a0b84772da   vgbr6510a:6  vgbr6510s164:2  2b
                            207600a0b84772da   vgbr6510b:6  vgbr6510s163:3  0c
                            208600a0b84772da   vgbr6510b:5  vgbr6510s163:4  2a
7 entries were displayed.
....
.. [[man_prepe_node_step29]完成下列子步驟：


. 在其中一個原始節點上輸入下列命令、並記錄輸出：
+
「ervice處理器show -Node *-instance」

+
系統會在兩個節點上顯示有關SP的詳細資訊。

. 確認SP狀態為「線上」。
. 確認已設定SP網路。
. 記錄有關SP的IP位址和其他資訊。
+
您可能想要重複使用遠端管理裝置的網路參數、在此案例中、SP會從原始系統、針對新節點上的SP。如需SP的詳細資訊、請參閱 link:other_references.html["參考資料"] 若要連結至_系統管理參考_和_還原ONTAP 9命令：手冊頁參考_。

+
.. [man準備節點_step30]如果您希望新節點擁有與原始節點相同的授權功能、請輸入下列命令、以查看原始系統上的叢集授權：
+
「系統授權顯示擁有者*」

+
下列範例顯示叢集1的站台授權：

+
....
system license show -owner *
Serial Number: 1-80-000013
Owner: cluster1

Package           Type    Description           Expiration
----------------- ------- --------------------- -----------
Base              site    Cluster Base License  -
NFS               site    NFS License           -
CIFS              site    CIFS License          -
SnapMirror        site    SnapMirror License    -
FlexClone         site    FlexClone License     -
SnapVault         site    SnapVault License     -
6 entries were displayed.
....
.. 在_NetApp Support Site_取得新節點的新授權金鑰。請參閱 link:other_references.html["參考資料"] 連結至_NetApp支援網站_。
+
如果網站沒有您需要的授權金鑰、請聯絡您的NetApp銷售代表。

.. 在AutoSupport 每個節點上輸入下列命令並檢查其輸出、以檢查原始系統是否已啟用Efis:
+
「系統節點AutoSupport 不支援show -node1、node2_」

+
命令輸出會顯示AutoSupport 是否啟用了功能性、如下列範例所示：

+
....
cluster::> system node autosupport show -node node1,node2

Node             State     From          To                Mail Hosts
---------------- --------- ------------- ----------------  ----------
node1            enable    Postmaster    admin@netapp.com  mailhost

node2            enable    Postmaster    -                 mailhost
2 entries were displayed.
....
.. 請採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果原始系統... | 然後... 


| 已啟用此功能... AutoSupport  a| 
... 前往 <<man_prepare_nodes_step34,步驟34>>。
... 移至區段 link:get_address_key_management_server_encryption.html["取得外部金鑰管理伺服器的IP位址以進行儲存加密"]。




| 未啟用任何功能... AutoSupport  a| 
... 請遵循_系統管理參考_中的指示來啟用AutoSupport 支援。（請參閱 link:other_references.html["參考資料"] 連結至_System Administration Reference。）
+
*注意：* AutoSupport 當您第一次設定儲存系統時、預設會啟用此功能。雖然AutoSupport 您可以隨時停用不支援、但仍應保持啟用狀態。啟用AutoSupport 功能可在儲存系統發生問題時、大幅協助識別問題與解決方案。

... 前往 link:get_address_key_management_server_encryption.html["取得外部金鑰管理伺服器的IP位址以進行儲存加密"] 區段。


|===
.. [[man_prepe_node_step34]] AutoSupport 在兩個原始節點上輸入下列命令、並檢查輸出、以驗證是否已設定正確的郵件主機詳細資料和收件者電子郵件ID：
+
「系統節點AutoSupport 不完整地顯示節點node_name -instance」

+
如需AutoSupport 有關功能的詳細資訊、請參閱 link:other_references.html["參考資料"] 若要連結至_系統管理參考_和_還原ONTAP 9命令：手冊頁參考_。

.. [[man_prepe_node_step35、Step 35] AutoSupport 輸入下列命令、將節點1的支援資訊傳送給NetApp：
+
「系統節點AutoSupport 無法叫用節點節點節點1 -輸入all -messing node1 from platfore_old to platform _new」（將節點1從platfore_old升級為platform _new）

+

NOTE: 此時請勿傳送AutoSupport 適用於節點2的消息給NetApp；稍後請在程序中進行。

.. [[man_prepe_node_step36、Step 36] AutoSupport 輸入下列命令並檢查其輸出、以驗證是否已傳送此資訊：
+
「系統節點AutoSupport 不支援show -node1_-instance」

+
欄位「Last Subject sent：」（上次傳送主旨：）和「Last Time sent：」（上次傳送時間：）包含上次傳送訊息的標題、以及傳送訊息的時間。

.. 如果您的系統使用自我加密磁碟機、請參閱知識庫文章 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/How_to_tell_I_have_FIPS_drives_installed["如何判斷我安裝了FIPS磁碟機"^] 以判斷您要升級的HA配對所使用的自我加密磁碟機類型。支援兩種自我加密磁碟機的支援ONTAP ：
+
--
*** FIPS認證的NetApp儲存加密（NSE）SAS或NVMe磁碟機
*** 非FIPS自我加密NVMe磁碟機（SED）


[NOTE]
====
您無法在同一個節點或HA配對上混用FIPS磁碟機與其他類型的磁碟機。

您可以在同一個節點或HA配對上混合使用SED與非加密磁碟機。

====
https://docs.netapp.com/us-en/ontap/encryption-at-rest/support-storage-encryption-concept.html#supported-self-encrypting-drive-types["深入瞭解支援的自我加密磁碟機"^]。

--



