= 
:allow-uri-read: 


. [[man_lif_VERIF_3_step6]]輸入下列命令、將每個NAS資料LIF移轉至節點3、每個LIF一次：
+
「網路介面移轉-vserver _vserver_name_-lIF _LIF_name_-dest-node-node3_-dest-port _netport|ifgrp_」

. [[man_lif_VERIF_3_step7]請確定資料移轉持續進行：
+
「網路介面修改-vserver _vserver_name_-lif_lif_name_-home-port _netport|ifgrp_-home-node3_」

. [[man_lif_firm_3_step8]確認SAN LIF位於節點3上的正確連接埠：
+
.. 輸入下列命令並檢查其輸出：
+
「網路介面show -data傳輸協定iscsiSCSI|FCP -home-node3_」

+
系統會傳回類似下列範例的輸出：

+
[listing]
----
cluster::> net int show -data-protocol iscsi|fcp -home-node node3
              Logical     Status      Network             Current        Current  Is
 Vserver      Interface   Admin/Oper  Address/Mask        Node           Port     Home
 -----------  ----------  ----------  ------------------  -------------  -------  ----
 vs0
              a0a         up/down     10.63.0.53/24       node3          a0a      true
              data1       up/up       10.63.0.50/18       node3          e0c      true
              rads1       up/up       10.63.0.51/18       node3          e1a      true
              rads2       up/down     10.63.0.52/24       node3          e1b      true
 vs1
              lif1        up/up       172.17.176.120/24   node3          e0c      true
              lif2        up/up       172.17.176.121/24   node3          e1a      true
----
.. 將「FCP介面卡show」命令的輸出與您在工作表中記錄的組態資訊進行比較、確認新的「介面卡」和「切換連接埠」組態正確無誤 ,步驟2。
+
在節點3上列出新的SAN LIF組態：

+
「FCP介面卡顯示欄位交換器連接埠、fc-WWPN」

+
系統會傳回類似下列範例的輸出：

+
[listing]
----
cluster1::> fcp adapter show -fields switch-port,fc-wwpn
  (network fcp adapter show)
node        adapter fc-wwpn                 switch-port
----------- ------- ----------------------- -------------
cluster1-01 0a      50:0a:09:82:9c:13:38:00 ACME Switch:0
cluster1-01 0b      50:0a:09:82:9c:13:38:01 ACME Switch:1
cluster1-01 0c      50:0a:09:82:9c:13:38:02 ACME Switch:2
cluster1-01 0d      50:0a:09:82:9c:13:38:03 ACME Switch:3
cluster1-01 0e      50:0a:09:82:9c:13:38:04 ACME Switch:4
cluster1-01 0f      50:0a:09:82:9c:13:38:05 ACME Switch:5
cluster1-01 1a      50:0a:09:82:9c:13:38:06 ACME Switch:6
cluster1-01 1b      50:0a:09:82:9c:13:38:07 ACME Switch:7
cluster1-02 0a      50:0a:09:82:9c:6c:36:00 ACME Switch:0
cluster1-02 0b      50:0a:09:82:9c:6c:36:01 ACME Switch:1
cluster1-02 0c      50:0a:09:82:9c:6c:36:02 ACME Switch:2
cluster1-02 0d      50:0a:09:82:9c:6c:36:03 ACME Switch:3
cluster1-02 0e      50:0a:09:82:9c:6c:36:04 ACME Switch:4
cluster1-02 0f      50:0a:09:82:9c:6c:36:05 ACME Switch:5
cluster1-02 1a      50:0a:09:82:9c:6c:36:06 ACME Switch:6
cluster1-02 1b      50:0a:09:82:9c:6c:36:07 ACME Switch:7
16 entries were displayed
----
+

NOTE: 如果新組態中的SAN LIF不在仍連接至相同「切換連接埠」的介面卡上、則當您重新啟動節點時、可能會導致系統中斷。

.. 如果節點3的SAN生命體或SAN生命體群組位於節點1上不存在的連接埠、或需要對應至不同連接埠、請完成下列子步驟、將其移至節點3上的適當連接埠：
+
... 將LIF狀態設為「向下」：
+
「網路介面修改-vserver _vserver_name_-lif_lif_name_-stue-admin down」

... 從連接埠集移除LIF：
+
「portset移除-vserver _vserver_name_-portset _portset_name_-port-name _port_name_」

... 輸入下列其中一個命令：
+
**** 移動單一LIF：
+
「網路介面修改-vserver _vserver_name_-lif_lif_name_-home-port _new_home_port_」

**** 將單一不存在或不正確連接埠上的所有LIF移至新連接埠：
+
「網路介面修改｛-home-port _port_on_node1_-home-node_node1_-role data｝-home-port _new_home_port_on_node3_」

**** 將lifs新增回連接埠集：
+
「portset add -vserver _vserver_name_-portset _portset_name_-port-name _port_name_」

+

NOTE: 您必須將SAN LIF移至連結速度與原始連接埠相同的連接埠。







. 將所有生命期的狀態修改為「up」、以便生命期可以接受及傳送節點上的流量：
+
「網路介面修改-home-port _port_name_-home-node3_-lIF DATA -STATUS-admin up」

. 在任一節點上輸入下列命令、檢查其輸出、確認已將l生命 移至正確的連接埠、並在任一節點上輸入下列命令、檢查輸出結果、以確認lIF的狀態為「up」：
+
「網路介面show -home-node-node3_-role data」

. [[man_lif_VERIF_3_step11]如果有任何lifs當機、請輸入下列命令將lifs的管理狀態設為「up」、每個LIF一次：
+
「網路介面修改-vserver _vserver_name_-lif_lif_name_-stue-admin up」

. 將升級後AutoSupport 的支援資訊訊息傳送給NetApp for node1：
+
「系統節點AutoSupport 無法叫用-node_node3_-type all -messed "node1 Successfully eved from _platform _old_ to _platform _new_"（系統節點無法叫用-node_node3_-輸入all -messed "node


