= 
:allow-uri-read: 


在升級過程中、遠端LIF會處理SAN LUN的流量。在升級期間、移轉SAN LIF對於叢集或服務健全狀況並不必要。除非需要將SAN LIF對應至新連接埠、否則不會移動SAN LIF。將node3聯機後，您將驗證生命期是否正常並位於適當的端口上。

.步驟
. [[step1]]在任一節點上輸入下列命令並擷取輸出、列出節點2未擁有的所有NAS資料生命量：
+
「網路介面show -role data -curr-node2_-is主目錄假-home-node3_」

. [[Worksheet_step2]]如果叢集是針對SAN lifs進行設定、請在此記錄SAN lifs「介面卡」和「切換連接埠」組態資訊 link:worksheet_information_before_moving_san_lifs_node3.html["工作表"] 以供稍後的程序使用。
+
.. 列出節點2上的SAN LIF並檢查輸出：
+
「網路介面show -data傳輸協定fc*」

+
系統會傳回類似下列範例的輸出：

+
[listing]
----
cluster1::> net int show -data-protocol fc*
  (network interface show)
             Logical     Status     Network            Current        Current Is
Vserver      Interface   Admin/Oper Address/Mask       Node           Port    Home
-----------  ----------  ---------- ------------------ -------------  ------- ----
svm2_cluster1
             lif_svm2_cluster1_340
                         up/up      20:02:00:50:56:b0:39:99
                                                       cluster1-01    1b      true
             lif_svm2_cluster1_398
                         up/up      20:03:00:50:56:b0:39:99
                                                       cluster1-02    1a      true
             lif_svm2_cluster1_691
                         up/up      20:01:00:50:56:b0:39:99
                                                       cluster1-01    1a      true
             lif_svm2_cluster1_925
                         up/up      20:04:00:50:56:b0:39:99
                                                       cluster1-02    1b      true
4 entries were displayed.
----
.. 列出現有組態並檢查輸出：
+
「FCP介面卡顯示欄位交換器連接埠、fc-WWPN」

+
系統會傳回類似下列範例的輸出：

+
[listing]
----
cluster1::> fcp adapter show -fields switch-port,fc-wwpn
  (network fcp adapter show)
node         adapter  fc-wwpn                  switch-port
-----------  -------  -----------------------  -------------
cluster1-01  0a       50:0a:09:82:9c:13:38:00  ACME Switch:0
cluster1-01  0b       50:0a:09:82:9c:13:38:01  ACME Switch:1
cluster1-01  0c       50:0a:09:82:9c:13:38:02  ACME Switch:2
cluster1-01  0d       50:0a:09:82:9c:13:38:03  ACME Switch:3
cluster1-01  0e       50:0a:09:82:9c:13:38:04  ACME Switch:4
cluster1-01  0f       50:0a:09:82:9c:13:38:05  ACME Switch:5
cluster1-01  1a       50:0a:09:82:9c:13:38:06  ACME Switch:6
cluster1-01  1b       50:0a:09:82:9c:13:38:07  ACME Switch:7
cluster1-02  0a       50:0a:09:82:9c:6c:36:00  ACME Switch:0
cluster1-02  0b       50:0a:09:82:9c:6c:36:01  ACME Switch:1
cluster1-02  0c       50:0a:09:82:9c:6c:36:02  ACME Switch:2
cluster1-02  0d       50:0a:09:82:9c:6c:36:03  ACME Switch:3
cluster1-02  0e       50:0a:09:82:9c:6c:36:04  ACME Switch:4
cluster1-02  0f       50:0a:09:82:9c:6c:36:05  ACME Switch:5
cluster1-02  1a       50:0a:09:82:9c:6c:36:06  ACME Switch:6
cluster1-02  1b       50:0a:09:82:9c:6c:36:07  ACME Switch:7
16 entries were displayed
----


. [[step3]請採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果節點1... | 然後... 


| 已設定介面群組或VLAN | 前往 ,步驟4.。 


| 未設定介面群組或VLAN | 跳過步驟4、前往 ,步驟5.。 
|===
. [[man_lif_VERIF_3_step3]]執行下列子步驟、將原本位於節點1上的介面群組和VLAN上裝載的任何NAS資料LIF、從節點2移轉至節點3：
+
.. [[man_lif_VERIF_3_substepa]將先前屬於介面群組節點1的節點2上裝載的任何資料LIF移轉至節點3上的連接埠、只要輸入下列命令、即可在同一個網路上裝載LIF：
+
「網路介面移轉-vserver _vserver_name_-lIF _LIF_name_-dest-node-node3_–dest-port _netport|ifgrp_」

.. 在中修改LIF的主連接埠和主節點 ,子步驟A 輸入下列命令、針對每個LIF輸入一次、即可移至目前裝載lifs的連接埠和節點：
+
「網路介面修改-vserver _vserver_name_-lif_lif_name_-home-node3_-home-port _netport|ifgrp_」

.. [[man_lif_VERIF_3_substepc]將先前屬於VLAN連接埠節點1的節點2上裝載的任何資料LIF移轉至節點3上的連接埠、只要輸入下列命令、即可在同一個網路上裝載LIF：
+
「網路介面移轉-vserver _vserver_name_-lIF _LIF_name_-dest-node-node3_–dest-port _netport|ifgrp_」

.. 修改中的lifs主連接埠和主節點 ,子步驟c 輸入下列命令、針對每個LIF輸入一次、即可移至目前裝載lifs的連接埠和節點：
+
「網路介面修改-vserver _vserver_name_-lif_lif_name_-home-node3_-home-port _netport|ifgrp_」



. [[man_lif_VERIF_3_step4]請採取下列其中一項行動：
+
[cols="25,75"]
|===
| 如果叢集設定為... | 然後... 


| NAS | 完成 ,步驟6. 和 ,步驟7.、跳過步驟8、然後完成 ,步驟9. 透過 ,步驟12.。 


| SAN | 停用節點上的所有SAN LIF、以便進行升級：「網路介面修改-vserver _vserver_name_-lif_lif_name_-home-node-node_to _upgrade _-home-port _netport|ifgrp_-stuse-admin drod' 
|===

