= 
:allow-uri-read: 


您必須在機架中安裝node3、將node1的連線傳輸至node3、開機node3及安裝ONTAP 支援。您也必須重新指派節點1的任何備用磁碟、屬於根磁碟區的任何磁碟、以及先前未重新定位至節點2的任何非根Aggregate。

.關於這項工作
如果 node3 上沒有安裝與 node1 上相同版本的 ONTAP 9，則必須透過網路啟動 node3。安裝node3之後、請從ONTAP 儲存在Web伺服器上的Image9映像啟動節點3。然後、您可以將正確的檔案下載到開機媒體裝置、以供後續系統開機。請參閱。 link:prepare_for_netboot.html["準備netboot"]

但是，如果 node3 上安裝的 ONTAP 9 與 node1 上安裝的 ONTAP 9 相同或更高版本，則無需透過網路啟動 node3。

[IMPORTANT]
====
* 對於 AFF A800 或 AFF C800 控制器升級，在移除節點 1 之前，必須確保機殼內的所有磁碟機都牢固地固定在中板上。如需更多資訊、請參閱 link:../upgrade-arl-auto-affa900/replace-node1-affa800.html["更換 AFF A800 或 AFF C800 控制器模組"]。
* 如果您要升級連接至儲存陣列的V系列系統、或是使用FlexArray 連接至儲存陣列的支援功能之非功能性虛擬化軟體的系統、則必須完成 <<man_install3_step1,步驟1.>> 透過 <<man_install3_step5,步驟5.>>請將本節保留在 <<man_install3_step6,步驟6.>> 並遵循中的指示 link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["在節點3上設定FC連接埠"] 和 link:set_fc_uta_uta2_config_node3.html#uta-ports-node3["檢查並設定節點3上的UTA/UTA2連接埠"] 視需要在維護模式中輸入命令。接著您必須返回本節並繼續 <<man_install3_step7,步驟7.>>。
* 如果您要升級具有儲存磁碟的系統，則必須完成整個部分，然後前往link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["在節點3上設定FC連接埠"]和link:set_fc_uta_uta2_config_node3.html#uta-ports-node3["檢查並設定節點3上的UTA/UTA2連接埠"] ，在群集提示符下輸入命令。


====
.步驟
. [[man_install3_step1]]確定您有節點3的機架空間。
+
如果節點1和節點2位於不同的機箱中、您可以將節點3放在與節點1相同的機架位置。不過、如果 node1 位於與 node2 相同的機箱中、則您必須將 node3 放入自己的機架空間、最好是靠近 node1 的位置。

. [[step2]]Install node3 in the rack、遵照節點機型的安裝與設定指示_。
+

NOTE: 如果您要升級到同一機箱中同時具有兩個節點的系統、請在機箱中安裝node4以及node3。如果沒有、當您開機節點3時、節點的行為就會如同雙機箱組態、當您開機節點4時、節點之間的互連就不會出現。

. [[step3]]纜 線節點3、將連線從節點1移至節點3。
+
下列參考資料可協助您建立適當的纜線連線。前往 link:other_references.html["參考資料"] 以連結至他們。

+
** _Installation and Setup Instructions（安裝與設定說明）_或_Estratested FlexArray Virtualization Installation Requirements and Reference（_針對節點3平台的虛擬化安裝要求與參考資料）
** 適當的磁碟櫃程序
** _HA 配對管理 _ 文件


+
纜線連接下列連接：

+
** 主控台（遠端管理連接埠）
** 叢集連接埠
** 資料連接埠
** 叢集與節點管理連接埠
** 儲存設備
** SAN組態：iSCSI乙太網路和FC交換器連接埠
+

NOTE: 您可能不需要將互連卡或叢集互連纜線連線從節點1移至節點3、因為大多數平台機型都有獨特的互連卡模式。對於 MetroCluster 組態、您必須將 FC-VI 纜線連線從 node1 移至 node3 。如果新主機沒有FC-VI卡、您可能需要移動FC-VI卡。



. [[man_install3_step4]]開啟節點3的電源、然後在主控台終端按Ctrl-C存取開機環境提示字元、以中斷開機程序。
+
如果您要升級到同一機箱中同時具有兩個節點的系統、節點4也會重新開機。不過、您可以忽略node4開機、直到稍後再執行。

+

NOTE: 當您啟動節點3時、可能會看到下列警告訊息：

+
[listing]
----
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
----
. [[man_install3_step5]如果您在中看到警告訊息 <<man_install3_step4,步驟4.>>、請採取下列行動：
+
.. 檢查可能指出NVRAM電池電量不足以外問題的任何主控台訊息、並視需要採取任何必要的修正行動。
.. 讓電池充電並完成開機程序。
+

NOTE: *注意*：請勿置換延遲；若不允許電池充電、可能導致資料遺失。



. [[man_install3_step6]]採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果您的系統... | 然後... 


| 具有磁碟、無後端儲存設備 | 跳過步驟7至步驟12、前往 <<man_install3_step13,步驟13>>。 


| 是連接FlexArray 至儲存陣列的V系列系統或系統、其中含有與之相關的功能完善的虛擬化軟體  a| 
.. 前往 link:set_fc_uta_uta2_config_node3.html["在節點3上設定FC或UTA/UTA2組態"] 並完成這些小節 link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["在節點3上設定FC連接埠"] 和 link:set_fc_uta_uta2_config_node3.html#uta-ports-node3["檢查並設定節點3上的UTA/UTA2連接埠"]（視系統而定）。
.. 返回本節、並完成其餘步驟、從開始 <<man_install3_step7,步驟7.>>。



IMPORTANT: 您必須重新設定FC內建連接埠、CNA內建連接埠和CNA卡、才能使用ONTAP 「支援虛擬化」軟體在V系列或系統上啟動FlexArray 。

|===
. [[man_install3_step7]將新節點的FC啟動器連接埠新增至交換器區域。
+
如果您的系統有磁帶SAN、則需要將啟動器分區。請參閱儲存陣列與分區文件以取得相關指示。

. [[man_install3_step8]將FC啟動器連接埠新增至儲存陣列做為新主機、將陣列LUN對應至新主機。
+
請參閱儲存陣列與分區文件以取得相關指示。

. [[man_install3_step9]]修改與儲存陣列上陣列LUN相關之主機或磁碟區群組中的全球連接埠名稱（WWPN）值。
+
安裝新的控制器模組會變更與每個內建FC連接埠相關的WWPN值。

. [[man_install3_step10]如果您的組態使用交換器型分區、請調整分區以反映新的WWPN值。
. [[man_install3_step11]確認節點3現在可以看到陣列LUN：
+
"syssconfig -v"

+
系統會顯示每個FC啟動器連接埠可見的所有陣列LUN。如果陣列LUN不可見、您將無法在本節稍後的部分、將磁碟從節點1重新指派至節點3。

. [[man_install3_step12]按Ctrl-C顯示開機功能表、然後選取維護模式。
. [[man_install3_step13]在維護模式提示字元下、輸入下列命令：
+
《停止》

+
系統會在開機環境提示字元停止。

. [[man_install3_step14]執行下列其中一項動作：
+
[cols="35,65"]
|===
| 如果您要升級的系統位於... | 然後... 


| 雙機箱組態（控制器位於不同機箱） | 前往 <<man_install3_step15,步驟15>>。 


| 單一機箱組態（控制器位於同一個機箱中）  a| 
.. 將主控台纜線從節點3切換至節點4。
.. 開啟節點4的電源、然後在主控台終端按Ctrl-C來存取開機環境提示字元、以中斷開機程序。
+
如果兩個控制器位於同一個機箱中、則電源應該已經開啟。

+

NOTE: 在開機環境提示字元中保留node4、您將返回中的node4 link:install_boot_node4.html["安裝及開機節點4"]。

.. 如果您在中看到警告訊息 <<man_install3_step4,步驟4.>>、請依照中的指示進行 <<man_install3_step5,步驟5.>>
.. 將主控台纜線從節點4切換回節點3。
.. 前往 <<man_install3_step15,步驟15>>。


|===
. [[man_install3_step15]]<設定ONTAP 節點3以供參考：
+
「預設值」


