= 
:allow-uri-read: 


您必須在機架中安裝node3、將node1的連線傳輸至node3、開機node3及安裝ONTAP 支援。您也必須重新指派節點1的任何備用磁碟、屬於根磁碟區的任何磁碟、以及先前未重新定位至節點2的任何非根Aggregate。

.關於這項工作
如果 node3 上沒有安裝與 node1 上相同版本的 ONTAP 9，則必須透過網路啟動 node3。安裝node3之後、請從ONTAP 儲存在Web伺服器上的Image9映像啟動節點3。然後、您可以將正確的檔案下載到開機媒體裝置、以供後續系統開機。請參閱。 link:prepare_for_netboot.html["準備netboot"]

但是，如果 node3 上安裝的 ONTAP 9 與 node1 上安裝的 ONTAP 9 相同或更高版本，則無需透過網路啟動 node3。

[IMPORTANT]
====
* 對於AFF A800或AFF C800控制器升級，在移除節點 1 之前，必須確保機箱中的所有驅動器都牢固地固定在中板上。有關詳細信息，請參閱 link:../upgrade-arl-auto-in-chassis/replace-node1-affa800.html["更換 AFF A800 或 AFF C800 控制器模組"]。
* 如果您要升級具有儲存磁碟的系統，則必須完成整個部分，然後前往link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["在節點3上設定FC連接埠"]和link:set_fc_uta_uta2_config_node3.html#uta-ports-node3["檢查並設定節點3上的UTA/UTA2連接埠"] ，在群集提示符下輸入命令。


====
.步驟
. [[man_install3_step1]]確定您有節點3的機架空間。
+
如果節點1和節點2位於不同的機箱中、您可以將節點3放在與節點1相同的機架位置。不過、如果 node1 位於與 node2 相同的機箱中、則您必須將 node3 放入自己的機架空間、最好是靠近 node1 的位置。

. [[step2]]Install node3 in the rack、遵照節點機型的安裝與設定指示_。
+

NOTE: 如果您要升級到同一機箱中同時具有兩個節點的系統、請在機箱中安裝node4以及node3。如果沒有、當您開機節點3時、節點的行為就會如同雙機箱組態、當您開機節點4時、節點之間的互連就不會出現。

. [[step3]]纜 線節點3、將連線從節點1移至節點3。
+
下列參考資料可協助您建立適當的纜線連線。前往 link:other_references.html["參考資料"] 以連結至他們。

+
** node3 平台的_安裝與設定說明_
** 適當的磁碟櫃程序
** _HA 配對管理 _ 文件


+
纜線連接下列連接：

+
** 主控台（遠端管理連接埠）
** 叢集連接埠
** 資料連接埠
** 叢集與節點管理連接埠
** 儲存設備
** SAN組態：iSCSI乙太網路和FC交換器連接埠
+

NOTE: 您可能不需要將互連卡或叢集互連纜線連線從節點1移至節點3、因為大多數平台機型都有獨特的互連卡模式。對於 MetroCluster 組態、您必須將 FC-VI 纜線連線從 node1 移至 node3 。如果新主機沒有FC-VI卡、您可能需要移動FC-VI卡。



. [[man_install3_step4]]開啟節點3的電源、然後在主控台終端按Ctrl-C存取開機環境提示字元、以中斷開機程序。
+
如果您要升級到同一機箱中同時具有兩個節點的系統、節點4也會重新開機。不過、您可以忽略node4開機、直到稍後再執行。

+

NOTE: 當您啟動節點3時、可能會看到下列警告訊息：

+
[listing]
----
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
----
. [[man_install3_step5]如果您在中看到警告訊息 <<man_install3_step4,步驟4.>>、請採取下列行動：
+
.. 檢查可能指出NVRAM電池電量不足以外問題的任何主控台訊息、並視需要採取任何必要的修正行動。
.. 讓電池充電並完成開機程序。
+

WARNING: *請勿超越延遲；如果電池無法充電，可能會導致資料遺失。 *



. 在維護模式提示下，輸入以下命令：
+
《停止》

+
系統會在開機環境提示字元停止。

. 請採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果您要升級的系統位於... | 然後... 


| 雙機箱組態（控制器位於不同機箱） | 前往<<man_install3_step8,步驟8.>>。 


| 單一機箱組態（控制器位於同一個機箱中）  a| 
.. 將主控台纜線從節點3切換至節點4。
.. 開啟節點4的電源、然後在主控台終端按Ctrl-C來存取開機環境提示字元、以中斷開機程序。
+
如果兩個控制器位於同一個機箱中、則電源應該已經開啟。

+

NOTE: 在開機環境提示字元中保留node4、您將返回中的node4 link:install_boot_node4.html["安裝及開機節點4"]。

.. 如果您在中看到警告訊息 <<man_install3_step4,步驟4.>>、請依照中的指示進行 <<man_install3_step5,步驟5.>>
.. 將主控台纜線從節點4切換回節點3。
.. 前往<<man_install3_step8,步驟8.>>。


|===
. [[man_install3_step8]]為ONTAP設定 node3：
+
「預設值」


