= 在節點4上設定FC連接埠
:allow-uri-read: 




== 在節點4上設定FC連接埠

如果節點4具有FC連接埠（內建或FC介面卡上）、您必須先在節點上設定連接埠組態、才能將其投入服務、因為連接埠並未預先設定。如果未設定連接埠、可能會導致服務中斷。

.開始之前
您必須擁有儲存在區段中節點2的FC連接埠設定值 link:prepare_nodes_for_upgrade.html["準備節點以進行升級"]。

.關於這項工作
如果您的系統沒有FC組態、您可以跳過本節。如果您的系統有內建UTA/UTA2連接埠或UTA/UTA2介面卡、請在中進行設定 <<檢查並設定節點4上的UTA/UTA2連接埠>>。


IMPORTANT: 在群集提示符下輸入本節中的命令。

.步驟
. 顯示系統上所有 FC 和融合網路適配器的資訊：
+
「系統節點硬體統一連線展示」

. 比較新節點上的FC設定與先前從原始節點擷取的設定。
. 視需要修改節點4上的FC連接埠：
+
** 若要設定目標連接埠：
+
`system node hardware unified-connect modify -type \| -t target -adapter _port_name_`

** 設定啟動器連接埠：
+
`system node unified-connect modify type \| -t initiator -adapter _port_name_`

+
「-type」是FC4類型、目標或啟動器。



. 輸入以下命令並檢查輸出來驗證新設定：
+
`system node unified-connect show`

. 請採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果新節點上的預設FC設定為... | 然後… 


| 與您在原始節點上擷取的相同 | 前往<<man_config_4_Step9,步驟9.>>。 


| 與您在原始節點上擷取的不同 | 前往<<man_config_4_Step6,Step6>>。 
|===
. [[man_config_4_Step6]]退出維護模式：
+
《停止》

. 輸入命令後、請等待系統在開機環境提示字元停止。
. 在啟動環境提示字元下輸入以下命令來啟動 node4：
+
Boot_ONTAP

. [[man_config_4_Step9]]執行下列其中一項操作：
+
** 前往 <<檢查並設定節點4上的UTA/UTA2連接埠>> 如果節點4有UTA/UTA2A卡或UTA/UTA2內建連接埠。
** 跳過一節、前往 link:map_ports_node2_node4.html["將連接埠從節點2對應至節點4"] 如果節點4沒有UTA/UTA2卡或UTA/UTA2內建連接埠。



