---
sidebar: sidebar 
permalink: upgrade-arl-manual/guidelines_upgrade_with_arl.html 
keywords: guidelines, upgrade, controllers, arl, aggregate, relocation 
summary: 瞭解您是否可以使用手動ARL程序來執行ONTAP 一對執行版本為9.7或更早版本的控制器。 
---
= 使用ARL升級控制器的準則
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
若要瞭ONTAP 解您是否可以使用Aggregate重新配置（ARL）來升級執行支援版的一對控制器、需視平台和原始控制器和更換控制器的組態而定。



[[supported-upgrades-for-arl]]
== 支援ARL升級

在下列情況下、您可以使用ARL來升級一對節點：

* 在ONTAP 升級之前、原始控制器和更換的控制器都必須執行相同版本的還原9.x。
* 更換的控制器容量必須等於或高於原始控制器。容量等於或大於容量是指NVRAM大小、Volume、LUN或Aggregate數限制等屬性、也指新節點的最大Volume或Aggregate大小。
* 您可以升級下列類型的系統：
+
** 從一個系統到一個系統。FAS FAS
** 從一個系統到一個系統的整個過程。AFF AFF





NOTE: 在執行AFF 更新版的功能之前、您必須先升級ONTAP 版本的功能以發佈版本9.3P12、9.4P6或9.5P1或更新版本。成功升級需要這些版本層級。

* 對於某些ARL控制器升級、您可以使用替換控制器上的暫用叢集連接埠進行升級。例如、如果您從AFF 某個顯示器升級至AFF 某個顯示器、視AFF 乎該顯示器A400組態而定、您可以使用兩個夾層連接埠中的任一端口、或是新增四埠10GbE網路介面卡、以提供暫用叢集連接埠。使用暫用叢集連接埠完成控制器升級之後、您可以在不中斷營運的情況下、將叢集移轉至替換控制器上的100GbE連接埠。
* 如果您使用ONTAP 的是版本號為6、P11、9.7P8或更新版本、建議啟用連線功能、活動功能及可用性監控（恢復）、以便在發生特定節點故障時、將叢集恢復成仲裁。「kernel-service」命令需要進階權限層級存取。如需詳細資訊、請參閱： https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU436["NetApp知識庫文章SU436：恢復接管預設組態已變更"^]。
* 使用ARL的控制器升級支援使用SnapLock 「支援」的系統、這些系統均設定了「支援使用者支援使用者支援的功能」和SnapLock 「支援使用者支援


您必須驗證是否可以在原始控制器和替換控制器上執行 ARL。您必須檢查原始系統支援的所有已定義彙總的大小和磁碟數量。然後，將其與新系統支援的 Aggregate 大小和磁碟數量進行比較。若要存取此資訊，請參閱 link:other-references.html["參考資料"] 以連結至 _Hardware Universe_。新系統支援的 Aggregate 大小和磁碟數量必須等於或大於原始系統支援的 Aggregate 大小和磁碟數量。

您必須在叢集混合規則中驗證，當原始控制器被替換時，新節點是否可以加入現有節點所在的叢集。有關叢集混合規則的詳細資訊，請參閱link:other-references.html["參考資料"]以連結至 _Hardware Universe_。


NOTE: 這兩種系統都是高可用度（HA）或非HA。兩個節點都必須啟用或停用特性設定；您無法將已啟用「All Flash Optimized」特性設定的節點與未在同一個HA配對中啟用特性設定的節點合併。如果身分不同、請聯絡技術支援部門。


NOTE: 如果新系統的插槽比原始系統少，或者其連接埠較少或不同，您可能需要向新系統新增介面卡。請參閱 link:other-references.html["參考資料"] 連結至 NetApp 支援網站上的 _Hardware Universe_，以取得特定平台的詳細資訊。



[[upgrades-not-supported-for-arl]]
== 不支援ARL升級

您無法執行下列升級：

* 無法執行ONTAP 版本從ONTAP 功能從功能從功能更新到ONTAP 功能升級到功能升級到功能升級到功能更新的控制器。
+
有關在 7-Mode 下運行 Data ONTAP 的系統控制器升級資訊，請參閱 link:other-references.html["參考資料"] 以連結至 _NetApp Support Site_。

* 更換不支援連接至原始控制器之磁碟櫃的控制器。
+
有關磁碟支援資訊，請參閱 link:other-references.html["參考資料"] 以連結至 _Hardware Universe_。

* 從內部磁碟機上具有根集合體或資料集合體的控制器。
+
如果要升級內部磁碟機上含根目錄彙總或資料彙總的控制器，請參閱 link:other-references.html["參考資料"] 以連結至「透過移動 Volume 或儲存設備進行升級」，然後前往「透過移動 Volume 升級執行叢集式 Data ONTAP 的一對節點」程序。

+

NOTE: 如果要升級叢集中節點上的 ONTAP，請參閱 link:other-references.html["參考資料"] 以連結至 _Upgrade ONTAP_。





[[assumptions-and-terminology]]
== 假設和術語

本文檔採用以下假設編寫：

* 更換的控制器硬體是新的、尚未使用。
+

WARNING: 準備二手控制器所需的步驟 `wipeconfig`本程式不包含指令，因為本程式假定更換的控制器硬體是全新的，且未使用過。如果之前使用過替換控制器硬件，則必須聯絡技術支持，尤其是當控制器在 7 模式下運行Data ONTAP時。

* 您已閱讀並瞭解升級節點配對的準則。
+

WARNING: 不要嘗試清除NVRAM內容。如果需要清除NVRAM的內容，請聯絡NetApp技術支援。

* 您在執行「modify」命令前後執行適當的命令、並比較兩個「show」命令的輸出、以驗證「modify」命令是否成功。
* 如果您有SAN組態、則HA配對上的每個儲存虛擬機器（SVM）都有本機和合作夥伴的生命生命。如果您沒有每個SVM的本機和合作夥伴LIF、則在開始升級之前、應該在該SVM的遠端和本機節點上新增SAN資料LIF。
* 如果SAN組態中有連接埠集、則必須確認HA配對中每個節點的每個連接埠集至少包含一個LIF。


此程序使用術語_boot enEnvironment prompt_來參照節點上的提示、您可以從中執行某些工作、例如重新開機節點、列印或設定環境變數。此提示有時被非正式地稱為_boot loader"提示字元_。

開機環境提示字元如下所示：

[listing]
----
LOADER>
----


[[licensing-in-ontap-9-7-or-earlier]]
== 以更新版本的版本取得授權ONTAP

某些功能需要授權、以包含一或多項功能的 _packags_ 形式發出。叢集中的每個節點都必須擁有自己的金鑰、才能在叢集中使用每個功能。

如果您沒有新的授權金鑰、新的控制器就能使用叢集中目前已授權的功能、並將繼續運作。但是、在控制器上使用未獲授權的功能可能會使您違反授權合約、因此您必須在升級完成後、為新的控制器安裝新的授權金鑰或金鑰。

所有授權金鑰的長度均為 28 個大寫字母字元。請參閱link:other-references.html["參考資料"]以連結至 _NetApp Support Site_，取得適用於 ONTAP 9.7 或更早版本的 28 字元新授權金鑰。金鑰位於 _My Support_ 區段的 _Software licenses_ 下。如果站台沒有您所需的授權金鑰，請聯絡您的 NetApp 銷售代表。

有關授權的詳細資訊，請前往 link:other-references.html["參考資料"] 以連結至《系統管理參考》。



[[storage-encryption]]
== 儲存加密

原始節點或新節點可能已啟用儲存加密功能。在這種情況下、您必須採取此程序的其他步驟、以驗證儲存加密的設定是否正確。

如果您要使用儲存加密、則與節點相關的所有磁碟機都必須擁有自我加密磁碟機。



[[two-node-switchless-clusters]]
== 雙節點無交換式叢集

如果您要升級雙節點無交換式叢集中的節點、則可在執行升級時、將節點留在無交換器叢集中。您不需要將它們轉換成交換式叢集。



[[troubleshoot]]
== 疑難排解

升級節點配對時可能會發生故障。節點可能會當機、集合體可能不會重新部署、或是生命體可能無法移轉。故障原因及其解決方案取決於升級程序期間何時發生故障。

如果升級控制器時出現任何問題，請參閱link:aggregate_relocation_failures.html["疑難排解"]部分。有關可能發生的故障的資訊按過程階段列出，位於link:arl_upgrade_workflow.html["ARL 升級序列"] 。

如果您找不到解決所遇到問題的解決方案、請聯絡技術支援部門。
