---
sidebar: sidebar 
permalink: upgrade-arl-manual/map_ports_node1_node3.html 
keywords: map, ports, node1, node3, cluster, home port, vlan ports, broadcast domain, connectivity 
summary: 在執行ONTAP 版本更新的控制器上手動升級ARL時、請確認節點1上的實體連接埠正確對應至節點3。 
---
= 將連接埠從節點1對應至節點3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您必須確定節點1上的實體連接埠正確對應至節點3上的實體連接埠、以便節點3在升級後與叢集中的其他節點和網路進行通訊。

您必須已經取得有關_E__新節點上連接埠的資訊Hardware Universe 。（請前往 link:other_references.html["參考資料"] 以連結至_SURE_ Hardware Universe ）。您可以使用本節稍後和中的資訊 link:map_ports_node2_node4.html["將連接埠從節點2對應至節點4"]。

node3的軟體組態必須符合node3的實體連線能力、而且必須先還原IP連線、才能繼續升級。

連接埠設定可能有所不同、視節點的機型而定。

您必須使原始節點的連接埠和LIF組態與您計畫新節點的組態相容。這是因為新節點在開機時會重新執行相同的組態、也就是說、當您開機node3時ONTAP 、將會嘗試在節點1上使用的相同連接埠上裝載l生命。

因此、如果節點1上的實體連接埠未直接對應至節點3上的實體連接埠、則在開機後、需要變更軟體組態才能還原叢集、管理和網路連線。此外、如果節點1上的叢集連接埠未直接對應至節點3上的叢集連接埠、則在軟體組態變更以將叢集生命體裝載到正確的實體連接埠之前、節點3可能不會在重新開機時自動重新加入仲裁。

.步驟
. [[step1]]請在下表中記錄節點1、連接埠、廣播網域和IPspaces的所有節點1纜線資訊：
+
[cols=""35"]
|===
| LIF | 節點1連接埠 | 節點1 IPspaces | 節點1廣播網域 | 節點3連接埠 | 節點3連接埠 | 節點3廣播網域 


| 叢集1 |  |  |  |  |  |  


| 叢集2 |  |  |  |  |  |  


| 叢集3 |  |  |  |  |  |  


| 叢集4. |  |  |  |  |  |  


| 叢集5. |  |  |  |  |  |  


| 叢集6. |  |  |  |  |  |  


| 節點管理 |  |  |  |  |  |  


| 叢集管理 |  |  |  |  |  |  


| 資料1. |  |  |  |  |  |  


| 資料2. |  |  |  |  |  |  


| 資料3. |  |  |  |  |  |  


| 資料4. |  |  |  |  |  |  


| SAN |  |  |  |  |  |  


| 叢集間連接埠 |  |  |  |  |  |  
|===
+
請參閱 link:record_node1_information.html["記錄node1資訊"] 取得此資訊的步驟。

. [[step2]]使用中的相同程序、記錄上表中節點3、連接埠、廣播網域和IPspaces的所有纜線資訊 link:record_node1_information.html["記錄node1資訊"]。
. [[step3]]請依照下列步驟、確認設定是否為雙節點無交換式叢集：
+
.. 將權限層級設為進階：
+
「叢集：>設定權限進階」

.. 確認設定是否為雙節點無交換器叢集：
+
「網路選項、無交換式叢集展示」

+
[listing]
----
 cluster::*> network options switchless-cluster show
 Enable Switchless Cluster: false/true
----
+
此命令的值必須符合系統的實體狀態。

.. 返回管理權限層級：
+
[listing]
----
 cluster::*> set -privilege admin
 cluster::>
----


. [[step4]]執行下列步驟、將節點3變成仲裁：
+
.. 開機節點3。請參閱 link:install_boot_node3.html["安裝及開機節點3"] 如果您尚未啟動節點、請將其開機。
.. 確認新的叢集連接埠位於叢集廣播網域中：
+
「網路連接埠show -node-name>-port <port-name>-Fields broadcast Domain」

+
下列範例顯示連接埠「e0a」位於節點3的「叢集」網域中：

+
[listing]
----
 cluster::> network port show -node node3 -port e0a -fields broadcast-domain

 node       port broadcast-domain
 ---------- ---- ----------------
 node3      e1a  Cluster
----
.. 將正確的連接埠新增至叢集廣播網域：
+
「網路連接埠修改-node-name>-port <port-name>-IPSpace Cluster -MTU 9000」

+
此範例在節點3上新增叢集連接埠「e1b」：

+
[listing]
----
 network port modify -node node3 -port e1b -ipspace Cluster -mtu 9000
----
+

NOTE: 對於VMware組態、您可能無法變更連接埠的廣播網域、因為它與裝載同步目的地SVM LIF的連接埠相關聯、並看到類似但不限於下列訊息的錯誤：MetroCluster

+
[listing]
----
command failed: This operation is not permitted on a Vserver that is configured as the destination of a MetroCluster Vserver relationship.
----
+
從遠端站台上對應的sync-sSource SVM輸入下列命令、將sync-destination LIF重新分配至適當的連接埠：

+
「MetroCluster 功能伺服器重新同步-vserver <vserver-name>」

.. 針對每個LIF、將叢集生命區移轉至新的連接埠一次：
+
「網路介面移轉-vserver叢集-lIF <LIF-name>-SOURation-node<node3>-destite-node<node3>-destite-port <port-name>」

.. 修改叢集lifs的主連接埠：
+
「網路介面修改-vserver叢集-lif<lif-name>–home-port <port-name>」

.. 如果叢集連接埠不在叢集廣播網域中、請新增它們：
+
「網路連接埠廣播網域附加連接埠-IPSpace叢集-broadcast網域叢集-ports <nodes:port>」

.. 從叢集廣播網域移除舊連接埠：
+
「網路連接埠廣播網域移除連接埠」

+
下列範例會移除節點3上的連接埠「e0d」：

+
[listing]
----
network port broadcast-domain remove-ports -ipspace Cluster -broadcast-domain Cluster ‑ports <node3:e0d>
----
.. 驗證node3是否已重新加入仲裁：
+
「cluster show -node3>-Fields health」



. [[man_map_1_step5]]調整裝載叢集生命週年和節點管理及/或叢集管理生命週年的廣播網域。確認每個廣播網域都包含正確的連接埠。如果某個連接埠裝載LIF或主控LIF、則無法在廣播網域之間移動連接埠、因此您可能需要依照下列方式移轉及修改LIF：
+
.. 顯示LIF的主連接埠：
+
「網路介面show -功能 變數<home-node, home-port>'

.. 顯示包含此連接埠的廣播網域：
+
「網路連接埠廣播網域show -port <node_name:port_name>'

.. 新增或移除廣播網域的連接埠：
+
「網路連接埠廣播網域附加連接埠」

+
「網路連接埠廣播網域移除連接埠」

.. 修改LIF的主連接埠：
+
「網路介面修改-vserver <vserver-name>-lif<lif-name>–home-port <port-name>」



. [[man_map_1_step6]]調整叢集間的廣播網域、並視需要使用中所示的相同命令來移轉叢集間的LIF <<man_map_1_step5,步驟5.>>。
. [[step7]]必要時、請使用中所示的相同命令、調整任何其他廣播網域並移轉資料生命週年 <<man_map_1_step5,步驟5.>>。
. [[step8]如果節點1上有任何連接埠不再存在於節點3上、請依照下列步驟加以刪除：
+
.. 存取任一節點上的進階權限層級：
+
"進階權限"

.. 刪除連接埠：
+
「網路連接埠刪除節點<節點名稱>-port <連接埠名稱>」

.. 返回管理層級：
+
「et -priv. admin」



. [[step9]]調整所有LIF容錯移轉群組：
+
「網路介面修改-容錯移轉群組<容錯移轉群組>-容錯移轉原則<容錯移轉原則>」

+
下列範例將容錯移轉原則設定為「廣播網域範圍」、並使用容錯移轉群組「fg1」中的連接埠作為「節點3」上LIF「data1」的容錯移轉目標：

+
[listing]
----
network interface modify -vserver node3 -lif data1 failover-policy broadcast-domainwide -failover-group fg1
----
+
前往 link:other_references.html["參考資料"] 如需ONTAP 詳細資訊、請連結至_網路管理_或_《_例》9命令：手冊頁參考_。

. 驗證節點3上的變更：
+
「網路連接埠show -node3」

. 每個叢集LIF都必須偵聽連接埠7700。驗證叢集LIF是否正在偵聽連接埠7700：
+
：「：>網路連線偵聽show -vserver叢集」

+
連接埠7700偵聽叢集連接埠是預期結果、如下列雙節點叢集範例所示：

+
[listing]
----
Cluster::> network connections listening show -vserver Cluster
Vserver Name     Interface Name:Local Port     Protocol/Service
---------------- ----------------------------  -------------------
Node: NodeA
Cluster          NodeA_clus1:7700               TCP/ctlopcp
Cluster          NodeA_clus2:7700               TCP/ctlopcp
Node: NodeB
Cluster          NodeB_clus1:7700               TCP/ctlopcp
Cluster          NodeB_clus2:7700               TCP/ctlopcp
4 entries were displayed.
----
. 如有必要、請針對未接聽連接埠7700的每個叢集LIF、將LIF的管理狀態設為「自己」、然後設定為「UP」：
+
：`:>net int modify -vserver cluster -lif<cluster－lif>-STATUS-admin down；net int modify -vserver cluster -lIF <cluster－lif>-STATUS-admin up（net int modify -vserver Cluster -lIF <cluster－lif>-STATUS-admin up）

+
重複步驟11、確認叢集LIF現在正在偵聽連接埠7700。


