---
sidebar: sidebar 
permalink: upgrade-arl-manual/move_nas_lifs_node2_from_node3_node4_verify_san_lifs_node4.html 
keywords: move, aggregates, nas, lif, node2, node3, node4 
summary: 在執行ONTAP 更新版本的控制器上手動升級ARL時、將節點3上的節點2 NAS資料lifs、從節點3移至節點4。 
---
= 將節點2擁有的NAS資料生命週期從節點3移至節點4、並驗證節點4上的SAN生命週期
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
驗證node4安裝之後、在將node2 Aggregate從node3重新定位至node4之前、您必須將node2目前在node3上擁有的NAS資料lifs、從node3移至node4。您還需要驗證節點4上的SAN LIF。

在升級過程中、遠端LIF會處理SAN LUN的流量。在升級期間、移轉SAN LIF對於叢集或服務健全狀況並不必要。除非需要將SAN LIF對應至新連接埠、否則不會移動SAN LIF。將node4聯機後，您將驗證lifs是否正常並位於適當的端口上。

.步驟
. 在任一節點上輸入下列命令並擷取輸出、以列出節點3未擁有的所有NAS資料lifs：
+
「網路介面show -role data -curr-node3 -is主目錄錯誤」

. [[Worksheet_step2_node2]]如果叢集是針對SAN lifs進行設定、請在此記錄SAN lifs和現有的組態資訊 link:worksheet_information_before_moving_san_lifs_node4.html["工作表"] 以供稍後的程序使用。
+
.. 列出節點3上的SAN LIF並檢查輸出：
+
「網路介面show -data傳輸協定fc*」

+
系統會傳回類似下列範例的輸出：

+
[listing]
----
cluster1::> net int show -data-protocol fc*
  (network interface show)
             Logical     Status     Network            Current        Current Is
Vserver      Interface   Admin/Oper Address/Mask       Node           Port    Home
-----------  ----------  ---------- ------------------ -------------  ------- ----
svm2_cluster1
             lif_svm2_cluster1_340
                         up/up      20:02:00:50:56:b0:39:99
                                                       cluster1-01    1b      true
             lif_svm2_cluster1_398
                         up/up      20:03:00:50:56:b0:39:99
                                                       cluster1-02    1a      true
             lif_svm2_cluster1_691
                         up/up      20:01:00:50:56:b0:39:99
                                                       cluster1-01    1a      true
             lif_svm2_cluster1_925
                         up/up      20:04:00:50:56:b0:39:99
                                                       cluster1-02    1b      true
4 entries were displayed.
----
.. 列出現有組態並檢查輸出：
+
「FCP介面卡顯示欄位交換器連接埠、fc-WWPN」

+
系統會傳回類似下列範例的輸出：

+
[listing]
----
cluster1::> fcp adapter show -fields switch-port,fc-wwpn
  (network fcp adapter show)
node         adapter  fc-wwpn                  switch-port
-----------  -------  -----------------------  -------------
cluster1-01  0a       50:0a:09:82:9c:13:38:00  ACME Switch:0
cluster1-01  0b       50:0a:09:82:9c:13:38:01  ACME Switch:1
cluster1-01  0c       50:0a:09:82:9c:13:38:02  ACME Switch:2
cluster1-01  0d       50:0a:09:82:9c:13:38:03  ACME Switch:3
cluster1-01  0e       50:0a:09:82:9c:13:38:04  ACME Switch:4
cluster1-01  0f       50:0a:09:82:9c:13:38:05  ACME Switch:5
cluster1-01  1a       50:0a:09:82:9c:13:38:06  ACME Switch:6
cluster1-01  1b       50:0a:09:82:9c:13:38:07  ACME Switch:7
cluster1-02  0a       50:0a:09:82:9c:6c:36:00  ACME Switch:0
cluster1-02  0b       50:0a:09:82:9c:6c:36:01  ACME Switch:1
cluster1-02  0c       50:0a:09:82:9c:6c:36:02  ACME Switch:2
cluster1-02  0d       50:0a:09:82:9c:6c:36:03  ACME Switch:3
cluster1-02  0e       50:0a:09:82:9c:6c:36:04  ACME Switch:4
cluster1-02  0f       50:0a:09:82:9c:6c:36:05  ACME Switch:5
cluster1-02  1a       50:0a:09:82:9c:6c:36:06  ACME Switch:6
cluster1-02  1b       50:0a:09:82:9c:6c:36:07  ACME Switch:7
16 entries were displayed
----


. 請採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果node2... | 說明 


| 已設定介面群組或VLAN | 前往 <<man_lif_verify_4_Step3,步驟4.>>。 


| 未設定介面群組或VLAN | 跳過步驟4、前往 <<man_lif_verify_4_Step4,步驟5.>>。 
|===
. [[man_lif_VERIF_4_Step3]]請採取下列步驟、將原本位於節點2上的介面群組和VLAN上裝載的任何NAS資料LIF、從節點3移轉至節點4。
+
.. [[man_lif_VERIF_4_substepa]將先前屬於介面群組節點2的節點3上裝載的任何LIF移轉至節點4上的連接埠、以便在同一個網路上裝載LIF、方法是針對每個LIF輸入下列命令一次：
+
「網路介面移轉-vserver _vserver_name_-lif_lif_name_-dest-node4–dest-port _netport|ifgrp_」

.. 修改中的lifs主連接埠和主節點 <<man_lif_verify_4_substepa,子步驟A>> 輸入下列命令、針對每個LIF輸入一次、即可移至目前裝載lifs的連接埠和節點：
+
「網路介面修改-vserver _vserver_name_-lif_datalif_name_-home-Node node4 home-port _netport|ifgrp_」

.. [[man_lif_VERIF_4_substepc]將先前屬於VLAN連接埠節點2的節點3上裝載的任何LIF移轉至節點4上的連接埠、以便在同一個網路上裝載LIF、方法是輸入下列命令（每個LIF一次）：
+
「網路介面移轉-vserver _vserver_name_-lif_datalif_name_-dest-Node node4–dest-port _netport|ifgrp_」

.. 修改中的lifs主連接埠和主節點 <<man_lif_verify_4_substepc,子步驟c>> 輸入下列命令、針對每個LIF輸入一次、即可移至目前裝載lifs的連接埠和節點：
+
「網路介面修改-vserver _vserver_name_-lif_datalif_name_-home-node-node4_ home-port _netport|ifgrp_」



. [[man_lif_VERIF_4_Step4]請採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果叢集設定為... | 然後... 


| NAS | 完成 <<man_lif_verify_4_Step5,步驟6.>> 透過 <<man_lif_verify_4_Step8,步驟9.>>、跳過步驟10、然後完成 <<man_lif_verify_4_Step10,步驟11.>> 透過 <<man_lif_verify_4_Step13,步驟14>>。 


| SAN | 跳過步驟6至步驟9、然後完成 <<man_lif_verify_4_Step9,步驟10>> 透過 <<man_lif_verify_4_Step13,步驟14>>。 


| NAS和SAN | 完成 <<man_lif_verify_4_Step5,步驟6.>> 透過 <<man_lif_verify_4_Step13,步驟14>>。 
|===
. [[man_lif_VERIF_4_Step5]]如果您的平台上有不同的資料連接埠、請輸入下列命令、將連接埠新增至廣播網域：
+
「網路連接埠廣播網域附加連接埠-IPSpace _IPspace_name_-broadcast網域管理連接埠_node:port_」

+
下列範例將節點「6280-1」上的連接埠「e0a」和節點「8060-1」上的連接埠「e0i」新增至IPspace預設中的廣播網域管理：

+
[listing]
----
cluster::> network port broadcast-domain add-ports -ipspace Default  -broadcast-domain mgmt -ports 6280-1:e0a, 8060-1:e0i
----
. 輸入下列命令、將每個NAS資料LIF移轉至節點4、每個LIF一次：
+
「網路介面移轉-vserver _vserver-name_-lif_datalif-name_-dest-node-node4_-dest-port _netport|ifgrp_-home-node-node4_」

. 確保資料移轉持續進行：
+
「網路介面修改-vserver _vserver_name_-lif_datalif_name_-home-port _netport|ifgrp_」

. [[man_lif_verify_4_step8]輸入下列命令、以列出所有網路連接埠並檢查其輸出、驗證所有連結的狀態為「up」：
+
「網路連接埠展示」

+
以下範例顯示「網路連接埠show」命令的輸出、其中一些lifs up和其他lifs down：

+
[listing]
----
cluster::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- -----------
node3
       a0a       Default      -                up       1500  auto/1000
       e0M       Default      172.17.178.19/24 up       1500  auto/100
       e0a       Default      -                up       1500  auto/1000
       e0a-1     Default      172.17.178.19/24 up       1500  auto/1000
       e0b       Default      -                up       1500  auto/1000
       e1a       Cluster      Cluster          up       9000  auto/10000
       e1b       Cluster      Cluster          up       9000  auto/10000
node4
       e0M       Default      172.17.178.19/24 up       1500  auto/100
       e0a       Default      172.17.178.19/24 up       1500  auto/1000
       e0b       Default      -                up       1500  auto/1000
       e1a       Cluster      Cluster          up       9000  auto/10000
       e1b       Cluster      Cluster          up       9000  auto/10000
12 entries were displayed.
----
. [[man_lif_VERIF_4_stept9]]如果「網路連接埠show」命令的輸出顯示新節點中沒有可用的網路連接埠、且存在於舊節點中、請完成下列子步驟、刪除舊的網路連接埠：
+
.. 輸入下列命令、輸入進階權限等級：
+
"進階權限"

.. 針對每個舊的網路連接埠輸入下列命令一次：
+
"network port delete -node_node_name_-port _port_name_"（網路連接埠刪除-node_node_name_-port _port_name_）

.. 輸入下列命令即可返回管理員層級：
+
「et -priv. admin」



. [[man_lif_firm_4_Step10]完成下列子步驟、確認節點4上的SAN LIF連接埠是否正確：
+
.. 輸入下列命令並檢查其輸出：
+
「網路介面show -data傳輸協定iscsiSCSI|FCP -home-Node node4」

+
系統會傳回類似下列範例的輸出：

+
[listing]
----
cluster::> network interface show -data-protocol iscsi|fcp -home-node node4
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
vs0
            a0a          up/down  10.63.0.53/24      node4         a0a     true
            data1        up/up    10.63.0.50/18      node4         e0c     true
            rads1        up/up    10.63.0.51/18      node4         e1a     true
            rads2        up/down  10.63.0.52/24      node4         e1b     true
vs1
            lif1         up/up    172.17.176.120/24  node4         e0c     true
            lif2         up/up    172.17.176.121/24  node4
----
.. 將「FCP介面卡show」命令的輸出與工作表中記錄的新組態資訊進行比較、確認新的「介面卡」和「切換連接埠」組態正確無誤 <<worksheet_step2_node2,步驟2>>。
+
在節點4上列出新的SAN LIF組態：

+
「FCP介面卡顯示欄位交換器連接埠、fc-WWPN」

+
系統會傳回類似下列範例的輸出：

+
[listing]
----
cluster1::> fcp adapter show -fields switch-port,fc-wwpn
  (network fcp adapter show)
node         adapter  fc-wwpn                  switch-port
-----------  -------  -----------------------  -------------
cluster1-01  0a       50:0a:09:82:9c:13:38:00  ACME Switch:0
cluster1-01  0b       50:0a:09:82:9c:13:38:01  ACME Switch:1
cluster1-01  0c       50:0a:09:82:9c:13:38:02  ACME Switch:2
cluster1-01  0d       50:0a:09:82:9c:13:38:03  ACME Switch:3
cluster1-01  0e       50:0a:09:82:9c:13:38:04  ACME Switch:4
cluster1-01  0f       50:0a:09:82:9c:13:38:05  ACME Switch:5
cluster1-01  1a       50:0a:09:82:9c:13:38:06  ACME Switch:6
cluster1-01  1b       50:0a:09:82:9c:13:38:07  ACME Switch:7
cluster1-02  0a       50:0a:09:82:9c:6c:36:00  ACME Switch:0
cluster1-02  0b       50:0a:09:82:9c:6c:36:01  ACME Switch:1
cluster1-02  0c       50:0a:09:82:9c:6c:36:02  ACME Switch:2
cluster1-02  0d       50:0a:09:82:9c:6c:36:03  ACME Switch:3
cluster1-02  0e       50:0a:09:82:9c:6c:36:04  ACME Switch:4
cluster1-02  0f       50:0a:09:82:9c:6c:36:05  ACME Switch:5
cluster1-02  1a       50:0a:09:82:9c:6c:36:06  ACME Switch:6
cluster1-02  1b       50:0a:09:82:9c:6c:36:07  ACME Switch:7
16 entries were displayed
----
+

NOTE: 如果新組態中的SAN LIF不在仍連接至相同「切換連接埠」的介面卡上、則當您重新啟動節點時、可能會導致系統中斷。

.. 如果節點4的SAN生命週期或SAN生命週期群組位於節點2上不存在的連接埠上、請輸入下列其中一個命令、將它們移至節點4上的適當連接埠：
+
... 將LIF狀態設為「關閉」：
+
「網路介面修改-vserver _vserver_name_-lif_lif_name_-stue-admin down」

... 從連接埠集移除LIF：
+
「portset移除-vserver _vserver_name_-portset _portset_name_-port-name _port_name_」

... 輸入下列其中一個命令：
+
**** 移動單一LIF：
+
「網路介面修改-lif_lif_name_-home-port _new_home_port_」

**** 將單一不存在或不正確連接埠上的所有LIF移至新連接埠：
+
「網路介面修改｛-home-port _port_on_node2_-home-node_node2_-role data｝-home-port _new_home_port_on_node4_」

**** 將lifs新增回連接埠集：
+
「portset add -vserver _vserver_name_-portset _portset_name_-port-name _port_name_」







+

NOTE: 您必須將SAN LIF移至連結速度與原始連接埠相同的連接埠。

. 輸入下列命令、將所有lifs的狀態修改為「up」、以便lifs可以接受及傳送節點上的流量：
+
「網路介面修改-vserver _vserver_name_-home-port _port_name_-home-node_node4_ lif_lif_name_-stue-admin up」

. 在任一節點上輸入以下命令並檢查輸出、以確認任何SAN LIF都已移至正確的連接埠、而且該LIF的狀態為「up」（啟動）：
+
「網路介面show -home-node-node4_-role data」

. [[man_lif_VERIF_4_Step13]如果有任何LIF當機、請輸入下列命令、將LIF的管理狀態設為「UP」、每個LIF一次：
+
「網路介面修改-vserver _vserver_name_-lif_lif_name_-stue-admin up」


