---
sidebar: sidebar 
permalink: upgrade-arl-manual/prepare_for_netboot.html 
keywords: prepare, netboot, rack, node3, node4 
summary: 在執行ONTAP Esce9.7或更早版本的控制器上進行手動ARL升級時、準備netboot node3和node4。 
---
= 準備netboot
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
當您在程序稍後的實體機架節點3和節點4之後、可能需要將它們以網路開機。「_netboot_」一詞是指您從ONTAP 儲存在遠端伺服器上的支援影像進行開機。準備網路開機時、您必須將ONTAP 一份《支援》9開機映像複本放到系統可以存取的網路伺服器上。

.開始之前
* 確認您可以使用系統存取HTTP伺服器。
* 請參閱 link:other_references.html["參考資料"] 連結至_NetApp支援網站_、並下載適用於您平台及ONTAP 正確版本之更新程式的必要系統檔案。


.關於這項工作
如果新的控制器ONTAP 上安裝的版本與原控制器上安裝的版本不相同、則必須以網路開機。安裝每個新的控制器之後、您可以從ONTAP 儲存在Web伺服器上的Image9映像來啟動系統。然後、您可以將正確的檔案下載到開機媒體裝置、以供後續系統開機。

不過、如果ONTAP 控制器上安裝的版本與原始控制器相同、則不需要對控制器進行網路開機。如果是、您可以跳過本節並繼續 link:install_boot_node3.html["階段3：安裝和開機節點3"]。

.步驟
. [[man_netboot_Step1]]請存取NetApp支援網站、下載用於執行系統網路開機的檔案。
. 請ONTAP 從NetApp支援網站的軟體下載區段下載適當的支援軟體、並將「<ONTAP_VERW>_image.tgz」檔案儲存在可從網路存取的目錄中。
. 切換至網路存取目錄、並確認您所需的檔案可用。
+
[cols="35,65"]
|===
| 適用於... | 然後... 


| FAS / AFF8000系列系統  a| 
擷取的內容 `<ontap_version>_image.tgz` 檔案至目標目錄：

`tar -zxvf <ontap_version>_image.tgz`


NOTE: 如果要在Windows上解壓縮內容、請使用7-Zip或WinRAR擷取netboot映像。

您的目錄清單應包含一個含有核心檔案的netboot資料夾：

`netboot/kernel`



| 所有其他系統 | 您的目錄清單應包含下列檔案： `<ontap_version>_image.tgz`附註：您不需要擷取的內容 `<ontap_version>_image.tgz` 檔案： 
|===
+
您將使用目錄中的信息link:install_boot_node3.html["階段3."] 。


