---
sidebar: sidebar 
permalink: upgrade-arl-manual/reboots_panics_power_cycles.html 
keywords: crash, reboot, node1, node2, node3, node4, upgrade 
summary: 系統可能會在執行ONTAP 更新版本的控制器上、在手動升級ARL的不同階段中當機、例如重新開機、發生緊急情況、或是經歷電源循環。 
---
= 重新開機、出現問題或重新開機
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在升級的不同階段、系統可能會當機–重新開機、發生恐慌或經歷關機循環。這些問題的解決方法取決於何時發生。



== 在階段2期間重新開機、出現問題或重新開機

當機可能發生在階段2之前、期間或之後、在此期間、您可以將Aggregate從節點1重新定位至節點2、將節點1擁有的資料生命期和SAN生命期移至節點2、記錄節點1資訊、以及淘汰節點1。



=== 節點1或節點2在HA仍啟用的第2階段之前當機

如果節點1或節點2在第2階段之前當機、則尚未重新放置任何集合體、而且HA組態仍處於啟用狀態。

.關於這項工作
接管和恢復可以正常進行。

.步驟
. 檢查主控台是否有系統可能發出的EMS訊息、並採取建議的修正行動。
. 繼續執行節點配對升級程序。




=== 節點1在第2階段期間或之後當機、但HA仍處於啟用狀態

部分或全部的集合體已從節點1重新定位至節點2、但HA仍處於啟用狀態。node2將接管node1的根Volume和未重新定位的任何非根Aggregate。

.關於這項工作
移轉的集合體擁有權與因擁有者未變更而接管的非根集合體擁有權相同。當節點1進入「等待恢復狀態」時、node2會歸還所有node1非根Aggregate。

.步驟
. 完成 link:relocate_non_root_aggr_node1_node2.html#step1["步驟1."] 在_重新將非根Aggregate從節點1重新部署到節點2_一節中。
. 繼續執行節點配對升級程序。




=== 停用HA時、節點1會在第2階段之後當機

節點2不會接管、但它仍在提供來自所有非根Aggregate的資料。

.步驟
. 啟動節點1。
. 繼續執行節點配對升級程序。
+
您可能會看到「儲存容錯移轉show」命令的輸出有一些變更、但這是典型的、不會影響程序。請參閱疑難排解一節 link:issues_multiple_stages_of_procedure.html#Unexpected-storage-failover-show-command-output["非預期的儲存容錯移轉show命令輸出"]。





=== 在仍啟用HA的情況下、節點2會在階段2期間或之後失敗

節點1已將部分或全部的Aggregate重新放置到節點2。HA已啟用。

.關於這項工作
節點1將接管節點2的所有集合體、以及它已重新定位到節點2的任何專屬集合體。當節點2進入「Waiting for Giveback」（正在等待恢復）狀態時、節點1會傳回節點2的所有集合體。

.步驟
. 完成 link:relocate_non_root_aggr_node1_node2.html#step1["步驟1."] 在_重新將非根Aggregate從節點1重新部署到節點2_一節中。
. 繼續執行節點配對升級程序。




=== 在停用HA之後、節點2會在第2階段之後當機

節點1不會接管。

.步驟
. 啟動節點2。
+
節點2開機時、所有的Aggregate都會發生用戶端中斷。

. 繼續執行其餘的節點配對升級程序。




== 在階段3期間重新開機、出現問題或重新開機

在安裝和引導node3的階段3期間或之後可能會立即發生故障、將節點1的連接埠對應至node3、將屬於node1和node2的資料lifs和SAN lifs移至node3、並將節點2的所有Aggregate重新定位至node3。



=== 在停用HA的情況下、以及在重新部署任何Aggregate之前、節點2會在第3階段當機

由於HA已停用、因此節點2當機後、節點3將不會接管。

.步驟
. 啟動節點2。
+
節點2開機時、所有的Aggregate都會發生用戶端中斷。

. 繼續執行節點配對升級程序。




=== 節點2在重新放置部分或全部集合體之後、在第3階段當機

節點2已將部分或全部的Aggregate重新放置到節點3、節點3將提供重新放置之集合體的資料。HA已停用。

.關於這項工作
未重新部署的集合體將會發生用戶端中斷。

.步驟
. 啟動節點2。
. 完成後重新部署其餘的集合體 link:relocate_non_root_aggr_node2_node3.html#step1["步驟1."] 透過 link:relocate_non_root_aggr_node2_node3.html#step3["步驟3."] 在_將非根Aggregate從node2重新部署到node3_一節中。
. 繼續執行節點配對升級程序。




=== 節點3在第3階段和節點2重新放置任何集合體之前當機

節點2不會接管、但它仍在提供來自所有非根Aggregate的資料。

.步驟
. 啟動節點3。
. 繼續執行節點配對升級程序。




=== 在Aggregate重新配置期間、節點3會在第3階段當機

如果節點3在節點2將Aggregate重新定位到節點3時當機、則節點2會中止任何其他Aggregate的重新定位。

.關於這項工作
節點2繼續提供其餘的Aggregate、但在節點3開機時、已重新放置到節點3的Aggregate會遇到用戶端中斷。

.步驟
. 啟動節點3。
. 完成 link:relocate_non_root_aggr_node2_node3.html#step3["步驟3."] 同樣地、請參閱_將非根Aggregate從節點2重新部署到節點3_一節。
. 繼續執行節點配對升級程序。




=== 節點3在第3階段當機後無法開機

由於災難性故障、節點3在第3階段當機之後無法開機。

.步驟
. 聯絡技術支援。




=== 節點2在第3階段之後但在第5階段之前當機

node3繼續為所有Aggregate提供資料。HA配對已停用。

.步驟
. 啟動節點2。
. 繼續執行節點配對升級程序。




=== 節點3在第3階段之後但在第5階段之前當機

節點3在第3階段之後但在第5階段之前當機。HA配對已停用。

.步驟
. 啟動節點3。
+
所有集合體都會發生用戶端中斷。

. 繼續執行節點配對升級程序。




== 在階段5期間重新開機、出現問題或重新開機

在階段5（即安裝和引導節點4的階段）、將節點2的連接埠對應至節點4、將屬於節點2的資料生命週期和SAN生命週期從節點3移至節點4、以及將節點2的所有集合體從節點3重新部署至節點4時、可能會發生當機。



=== 節點3在階段5期間當機

節點3已將部分或全部節點2的Aggregate重新放置到節點4。Node4不會接管、但會繼續為節點3已重新定位的非根Aggregate提供服務。HA配對已停用。

.關於這項工作
其餘的Aggregate會中斷運作、直到節點3重新開機為止。

.步驟
. 啟動節點3。
. 重複重新定位屬於節點2的其餘集合體 link:relocate_node2_non_root_aggr_node3_node4.html#Step1["步驟1."] 透過 link:relocate_node2_non_root_aggr_node3_node4.html#step3["步驟3."] 在_重新部署節點2的非根Aggregate從節點3到節點4_一節中。
. 繼續執行節點配對升級程序。




=== Node4在階段5期間當機

節點3已將部分或全部節點2的Aggregate重新放置到節點4。node3不會接管、而是繼續提供節點3擁有的非根Aggregate、以及未重新定位的非根Aggregate。HA已停用。

.關於這項工作
非根Aggregate發生中斷、這些非根Aggregate已重新部署、直到節點4重新開機為止。

.步驟
. 叫出節點4。
. 再次完成、重新定位屬於節點2的其餘集合體 link:relocate_node2_non_root_aggr_node3_node4.html#Step1["步驟1."] 透過 link:relocate_node2_non_root_aggr_node3_node4.html#step3["步驟3."] 在_重新定位節點2的非根Aggregate、從節點3移至節點4 _。
. 繼續執行節點配對升級程序。

