---
sidebar: sidebar 
permalink: upgrade-arl-manual/relocate_non_root_aggr_node2_node3.html 
keywords: node2, node3, node2, aggregates, autosupport 
summary: 針對AutoSupport 節點2傳送一個資訊區訊息、並在ONTAP 執行更新版本的控制器上手動進行ARL升級時、將節點2的非根Aggregate重新定位至節點3。 
---
= 將非根Aggregate從節點2重新部署到節點3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在將 node2 替換爲 node4 之前，您需要爲 node2 發送 AutoSupport 消息，然後將 node2 擁有的非根聚合重新定位到 node3 。


CAUTION: 在此過程中，請勿將集合體從 node3 重新定位至 node2 。如此一來，集合體就會離線，而移轉的集合體則會發生資料中斷。

[[verify-partner-sys-id]]
.步驟
. 請確認節點3上的合作夥伴系統ID設定是否正確：
+
.. 輸入進階權限層級：
+
"進階權限"

.. 在 node3 上顯示合作夥伴系統 ID ：
+
`ha interconnect config show -node <node3-node1>`

+
系統會顯示類似下列範例的輸出：

+
.顯示範例
[%collapsible]
====
[listing]
----
cluster::*> ha interconnect config show -node <node>
  (system ha interconnect config show)

                       Node: node3-node1
          Interconnect Type: RoCE
            Local System ID: <node3-system-id>
          Partner System ID: <node2-system-id>
       Connection Initiator: local
                  Interface: external

Port   IP Address
----   -----------------
e4a-17   0.0.0.0
e4b-18   0.0.0.0
----
====


. 如果 node3 的「合作夥伴系統 ID 」不正確：
+
.. 停止 node3 ：
+
《停止》

.. 在 Loader 提示字元下，設定正確的「合作夥伴 - 系統」值。
+
node3 "合作 夥伴 -sysid" 是 node2<<verify-partner-sys-id,步驟1.>> 的系統 ID ，您可以在的輸出中找到 `ha interconnect config show`。

.. 儲存設定：
+
「aveenv」

.. 在 Loader 提示符下，將 node3 引導至引導菜單：
+
Boot_ONTAP功能表

.. 登入 node3 。


. 傳送 AutoSupport 訊息至 NetApp for node2 ：
+
`system node autosupport invoke -node <node2> -type all -message "Upgrading <node2> from <platform_old> to <platform_new>"`

. 驗AutoSupport 證是否已傳送此訊息：
+
`system node autosupport show -node <node2> -instance`

+
「Last Subject sent：」（上次傳送主旨：）和「Last Time sent：」（上次傳送時間：）欄位包含上次傳送訊息的訊息標題、以及訊息傳送時間。

. [[relocate-step5]]重新定位非根聚合：
+
.. 將權限層級設為進階：
+
"進階權限"

.. 列出節點2擁有的Aggregate：
+
`storage aggregate show -owner-name <node2>`

.. 開始進行Aggregate重新配置：
+
`storage aggregate relocation start -node <node2> -destination <node3> -aggregate-list * -ndo-controller-upgrade true`

+

NOTE: 此命令只會尋找非根Aggregate。

.. 出現提示時、請輸入「y」。
+
重新配置會在背景中進行。重新部署集合體可能需要幾秒鐘到幾分鐘的時間。時間包括用戶端中斷和非中斷部分。此命令不會重新定位任何離線或受限制的集合體。

.. 返回管理權限層級：
+
「et -priv. admin」



. 驗證node2的重新定位狀態：
+
`storage aggregate relocation show -node <node2>`

+
在重新定位集合之後，輸出會顯示「完成」。

+

NOTE: 您必須等到節點2所擁有的所有集合體都重新放置到節點3之後、才能繼續下一步。

. 請採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果重新配置... | 然後... 


| 所有集合體都成功 | 前往 <<man_relocate_2_3_step8,步驟8.>>。 


| 任何Aggregate都失敗或遭否決  a| 
.. 顯示詳細的狀態訊息：
+
「torage Aggregate show -instance」

+
您也可以檢查EMS記錄、查看所需的修正行動。

+

NOTE: 「EVENT log show」命令會列出發生的任何錯誤。

.. 執行修正行動。
.. 將權限層級設為進階：
+
"進階權限"

.. 重新部署任何故障或被否決的集合體：
+
`storage aggregate relocation start -node <node2> -destination <node3> -aggregate-list * -ndo-controllerupgrade true`

.. 出現提示時、請輸入「y」。
.. 返回管理權限層級：
+
「et -priv. admin」



如有必要、您可以使用下列其中一種方法強制重新配置：

** 透過壓倒性的否決檢查：
+
「torage aggregate regate regate regate reg搬 移開始- overre-tetoes true -n控制器升級」

** 覆寫目的地檢查：
+
「torage Aggregate regate regate regate regate reg搬 移開始- overre-destination-checkstrue -ndocn控制 器升級」



如需儲存Aggregate重新配置命令的詳細資訊、請前往 link:other_references.html["參考資料"] 若要使用CLCLI和_例ONTAP 9命令連結至_磁碟和集合管理：手冊頁參考_。

|===
. [[man_region_2_3_step8]] 驗證節點 3 上的所有非根集合體是否均為線上：
+
`storage aggregate show -node <node3> -state offline -root false`

+
如果有任何Aggregate已經離線或變成外部、您必須將其上線、每個Aggregate一次：

+
`storage aggregate online -aggregate <aggregate_name>`

. 驗證節點3上的所有磁碟區是否都處於線上狀態：
+
`volume show -node <node3> -state offline`

+
如果節點3上有任何磁碟區離線、您必須將其上線、每個磁碟區一次：

+
`volume online -vserver <Vserver-name> -volume <volume-name>`

. 確認 node2 沒有任何線上非根集合體：
+
`storage aggregate show -owner-name <node2> -ha-policy sfo -state online`

+
命令輸出不應顯示線上非根Aggregate、因為所有非根線上Aggregate都已重新部署至節點3。


