---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/ensure_new_controllers_are_set_up_correctly.html 
keywords: confirm, controllers, set up, ha, node3, node4, node2, lif, cluster, high, availability 
summary: 啟用HA配對、驗證node3和node4儲存設備存取、並ONTAP 使用「系統控制器更換」命令、在升級執行版本號為32或更新版本的控制器之後、確認Aggregate擁有權。 
---
= 確認新的控制器已正確設定
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
若要確認設定正確、您必須啟用HA配對。您也必須驗證node3和node4是否可以存取彼此的儲存設備、以及它們是否擁有屬於叢集上其他節點的資料LIF。此外、您必須確認node3擁有node1的Aggregate、而node4擁有node2的Aggregate、而且兩個節點的磁碟區都在線上。

.步驟
. 對節點2進行檢查後、會啟用節點2叢集的儲存容錯移轉和叢集HA配對。完成作業後、兩個節點都會顯示為已完成、系統會執行一些清除作業。
. 確認已啟用儲存容錯移轉：
+
「容錯移轉顯示」

+
下列範例顯示啟用儲存容錯移轉時命令的輸出：

+
....
cluster::> storage failover show
                  Takeover
Node     Partner  Possible   State Description
-------- -----    -------    ------------------
node3    node4    true       Connected to node4
node4    node3    true       Connected to node3
....
. 使用下列命令檢查輸出、確認node3和node4屬於同一個叢集：
+
「叢集展示」

. 使用下列命令檢查輸出、確認節點3和節點4可以存取彼此的儲存設備：
+
「torage容錯移轉顯示-欄位、本機磁碟遺失、合作夥伴磁碟遺失」

. 使用下列命令檢查輸出、確認節點3和節點4都不擁有叢集中其他節點所擁有的資料lifs主目錄：
+
「網路介面展示」

+
如果節點3或節點4都不擁有叢集中其他節點所擁有的資料生命週期、請將資料生命週期還原為其主擁有者：

+
網路介面回復

. 驗證node3是否擁有node1的集合體、以及node4是否擁有node2的集合體：
+
`storage aggregate show -owner-name <node3>`

+
`storage aggregate show -owner-name <node4>`

. 判斷是否有任何磁碟區離線：
+
`volume show -node <node3> -state offline`

+
`volume show -node <node4> -state offline`

. 如果有任何磁碟區離線、請將它們與您在一節中擷取的離線磁碟區清單進行比較 link:prepare_nodes_for_upgrade.html["準備節點以進行升級"]並在每個Volume上使用一次下列命令、視需要將任何離線磁碟區上線：
+
`volume online -vserver <vserver_name> -volume <volume_name>`

. 針對每個節點使用下列命令、安裝新節點的新授權：
+
`system license add -license-code <license_code,license_code,license_code…>`

+
授權代碼參數接受28個大寫字母字元金鑰的清單。您可以一次新增一個授權、也可以一次新增多個授權、以英文分隔每個授權金鑰。

. 使用下列其中一個命令、從原始節點移除所有舊授權：
+
「系統授權清除-未使用-過期」

+
`system license delete -serial-number <node_serial_number> -package <licensable_package>`

+
--
** 刪除所有過期的授權：
+
「系統授權清除-過期」

** 刪除所有未使用的授權：
+
「系統授權清理-未使用」

** 在節點上使用下列命令、從叢集刪除特定授權：
+
`system license delete -serial-number <node1_serial_number> -package *`

+
`system license delete -serial-number <node2_serial_number> -package *`



--
+
將顯示下列輸出：

+
....
Warning: The following licenses will be removed:
<list of each installed package>
Do you want to continue? {y|n}: y
....
+
輸入「y」以移除所有套件。

. 使用下列命令並檢查輸出、確認已正確安裝授權：
+
「系統授權展示」

+
您可以比較輸出與您在區段中擷取的輸出 link:prepare_nodes_for_upgrade.html["準備節點以進行升級"]。

. [[unset_mastwait_system_commands]]如果在組態中使用自我加密磁碟機、且您已設定 `kmip.init.maxwait` 變數至 `off` （例如、in link:install_boot_node4.html#auto_install4_step27["安裝並開機節點4、步驟27"]）、您必須取消設定變數：
+
「et diag; systemShell -node_node_name_-command sudo kenv -u -p kmip.init.maxwait`」



. [[Step13]在兩個節點上使用下列命令來設定SP：
+
「系統服務處理器網路修改-node_node_name_」

+
請參閱 link:other_references.html["參考資料"] 如需SP及_SURE9.8 ONTAP 命令的相關資訊、請連結至_System Administration Reference（系統管理參考資料）：Manual Page Reference（手冊頁參考）_、以取得有關係統「服務處理器網路修改」命令的詳細資訊。

. 如果您要在新節點上設定無交換器叢集、請參閱 link:other_references.html["參考資料"] 若要連結至_NetApp支援網站_、請遵循_移轉至雙節點無交換器叢集_中的指示。


.完成後
如果節點3和節點4上已啟用儲存加密、請完成一節 link:set_up_storage_encryption_new_module.html["在新的控制器模組上設定儲存加密"]。否則、請完成本節 link:decommission_old_system.html["取消委任舊系統"]。
