---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/index.html 
keywords: aggregate, relocation, controller, hardware, aggregates, metrocluster, terminology 
summary: 您可以ONTAP 使用「系統控制器更換」命令來升級執行效能不完全的控制器硬體、重新配置非根集合體的擁有權。 
---
= 了解 ARL 升級程序
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
升級控制器硬體有多種聚合重定位 (ARL) 方法。此流程說明如何在執行 ONTAP 9.8 或更高版本的系統上使用聚合重定位 (ARL) 和「系統控制器替換命令」升級控制器硬體。

在過程中、您會使用更換的控制器硬體來升級原始的控制器硬體、以重新定位非根集合體的擁有權。您可以多次從節點移轉Aggregate至節點、以確認在整個升級程序中、至少有一個節點正在處理來自集合體的資料。您也可以移轉資料邏輯介面（LIF）、並在繼續進行時將新控制器上的網路連接埠指派給介面群組。

.本資訊所使用的術語
在此資訊中、原始節點稱為「node1」和「node2」、新節點稱為「node3」和「node4」。在上述過程中、node1會由node3取代、node2則會由node4取代。

術語「node1」、「node2」、「node3」和「node4」僅用於區分原始節點和新節點。執行此程序時、您必須取代原始節點和新節點的真實名稱。但是實際上、節點名稱並未變更：節點3的名稱為node1、而節點4的名稱為node2（控制器硬體已升級）。

.重要資訊：
* 此程序相當複雜、假設您具備進階ONTAP 的功能不完整的管理技能。您還必須閱讀並理解link:guidelines_for_upgrading_controllers_with_arl.html["使用 ARL 升級控制器的指南"]和link:overview_of_the_arl_upgrade.html["ARL 升級序列"]在開始升級之前。
* 此程序假設更換的控制器硬體是新的、而且尚未使用。此程序不包含使用wpeconfig命令準備已用控制器所需的步驟。如果先前使用的是更換控制器硬體、您必須聯絡技術支援部門、尤其是在控制器以Data ONTAP 7-Mode執行時。
* 您可以使用ARL來執行不中斷營運的簡化控制器升級、以升級至執行更新ONTAP 版本的新控制器、而非升級叢集上執行的版本。舊版與新版控制器的版次組合取決於更新版本的NDU Cadence模式。ONTAP ONTAP例如、如果您的控制器執行ONTAP 的是功能不全的版本號、而該控制器是最後支援的版本、則您可以升級至執行ONTAP 更新ONTAP 版本不高於功能不全的版本號的更新控制器。
+
此升級程序主要適用於您要更換的控制器機型不支援更新ONTAP 版本的升級案例、以及新控制器不支援舊ONTAP 版的版本。

* 您可以使用此程序來升級具有兩個以上節點之叢集中的控制器硬體、不過您需要針對叢集中的每個高可用度（HA）配對分別執行此程序。
* 此程序適用於FAS系統和AFF系統。
* 此程序適用於執行4節點NetApp MetroCluster 功能更新組態的系統。由於這個組態站台可位於兩個實體位置、因此必須在每個站台個別執行自動化控制器升級、才能進行HA配對。MetroCluster MetroCluster
* 對於非MetroCluster系統（例如HA叢集）、ARL升級是唯一受支援的程序。
* 如果您要從AFF 某個不支援的A320系統進行升級、您可以使用Volume Moves來升級控制器硬體、或聯絡技術支援部門。請參閱 link:other_references.html["參考資料"] 若要透過移動磁碟區或儲存設備連結至_Upgrade。

