---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/install_boot_node3.html 
keywords: installing, booting, node3, ontap 
summary: 使用ONTAP 「系統控制器更換」命令、在升級執行ONTAP 版本號為E9、8或更新版本的控制器時、安裝並啟動節點3並安裝更新軟體。 
---
= 安裝及開機節點3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您必須在機架中安裝node3、將node1的連線傳輸至node3、開機node3及安裝ONTAP 支援。接著、您必須重新指派節點1的任何備用磁碟、屬於根磁碟區的任何磁碟、以及任何未在程序中稍早重新放置到節點2的非根Aggregate、如本節所述。

.關於這項工作
重新配置作業會在此階段開始時暫停。此程序大部分是自動化的；此作業會暫停、以便您檢查其狀態。您必須手動恢復作業。此外、您必須驗證SAN LIF是否已成功移至節點3。

如果netboot node3沒有ONTAP 安裝在node1上的相同版本的支援功能、您就需要netboot node3。安裝node3之後、請從ONTAP 儲存在Web伺服器上的Image9映像啟動節點3。接著、您可以依照中的指示、將正確的檔案下載到開機媒體裝置、以供後續系統開機 link:prepare_for_netboot.html["準備netboot"]。

[IMPORTANT]
====
* 對於 AFF A800 或 AFF C800 控制器升級，在移除節點 1 之前，必須確保機殼內的所有磁碟機都牢固地固定在中板上。如需更多資訊、請參閱 link:../upgrade-arl-auto-affa900/replace-node1-affa800.html["更換 AFF A800 或 AFF C800 控制器模組"]。
* 如果您要升級具有儲存磁碟的系統、則必須完成此一整節、然後前往 link:set_fc_or_uta_uta2_config_on_node3.html#configure-fc-ports-on-node3["在節點3上設定FC連接埠"] 和 link:set_fc_or_uta_uta2_config_on_node3.html#check-and-configure-utauta2-ports-on-node3["檢查並設定節點3上的UTA/UTA2連接埠"] 區段、在叢集提示字元中輸入命令。


====
.步驟
. [[[auto_install3_step1]]請確定您有節點3的機架空間。
+
如果節點1和節點2位於不同的機箱中、您可以將節點3放在與節點1相同的機架位置。但是、如果節點1與節點2位於同一個機箱中、則您需要將節點3放入自己的機架空間、最好是靠近節點1的位置。

. [[[auto_install3_step2]]依照節點機型的安裝與設定指示_、在機架中安裝節點3。
+

NOTE: 如果您要升級到同一機箱中同時具有兩個節點的系統、請在機箱中安裝node4以及node3。如果不這樣做，當您啟動 node3 時，該節點的行為將如同處於雙底盤配置中，而當您啟動 node4 時，節點之間的互連將不會出現。

. [[auto_install3_step3]]纜線節點3、將連線從節點1移至節點3。
+
使用 node3 平台的《安裝與設定說明》、對應的磁碟架文件和《HA 對管理》文件連接以下連線。

+
參考link:other_references.html["參考資料"]連結到_HA 對管理_。

+
** 主控台（遠端管理連接埠）
** 叢集連接埠
** 資料連接埠
** 叢集與節點管理連接埠
** 儲存設備
** SAN組態：iSCSI乙太網路和FC交換器連接埠
+

NOTE: 您可能不需要將互連卡或叢集互連纜線連線從節點1移至節點3、因為大多數平台機型都有獨特的互連卡模式。若要進行支援、您需要將FC-VI纜線連線從節點1移至節點3。MetroCluster如果新主機沒有FC-VI卡、您可能需要移動FC-VI卡。



. [[auto_install3_step4]]開啟節點3的電源、然後在主控台終端按Ctrl-C存取開機環境提示字元、以中斷開機程序。
+
如果您要升級到同一機箱中同時具有兩個節點的系統、節點4也會重新開機。不過、您可以忽略node4開機、直到稍後再執行。

+

NOTE: 當您啟動節點3時、可能會看到下列警告訊息：

+
....
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
....
. [[auto_install3_step5]]如果您在中看到警告訊息 <<auto_install3_step4,步驟4.>>、請採取下列行動：
+
.. 檢查可能指出NVRAM電池電量不足以外問題的任何主控台訊息、並視需要採取任何必要的修正行動。
.. 讓電池充電並完成開機程序。
+

WARNING: *請勿超越延遲；如果電池無法充電，可能會導致資料遺失。 *

+

NOTE: 請參閱 link:prepare_for_netboot.html["準備netboot"]。





. [[step6]]選擇下列其中一項動作來設定netboot連線。
+

NOTE: 您必須使用管理連接埠和IP做為netboot連線。請勿使用資料 LIF IP ，否則在執行升級時可能會發生資料中斷。

+
[cols="30,70"]
|===
| 如果動態主機組態傳輸協定（DHCP）是... | 然後... 


| 執行中 | 在開機環境提示字元中使用下列命令自動設定連線：「ifconfige0M -auto」 


| 未執行  a| 
在開機環境提示字元中使用下列命令手動設定連線：
`ifconfig e0M -addr=_filer_addr_ -mask=_netmask_ -gw=_gateway_ -dns=_dns_addr_ -domain=_dns_domain_`

`_filer_addr_` 為儲存系統的IP位址（必填）。
`_netmask_` 是儲存系統的網路遮罩（必填）。
`_gateway_` 是儲存系統的閘道（必填）。
`_dns_addr_` 為網路上名稱伺服器的IP位址（選用）。
`_dns_domain_` 為網域名稱服務（DNS）網域名稱（選用）。


NOTE: 您的介面可能需要其他參數。在韌體提示字元中輸入「Help ifconfig」以取得詳細資料。

|===
. [[step7]]在節點3上執行netboot：
+
[cols="30,70"]
|===
| 適用於... | 然後... 


| FAS / AFF8000系列系統 | “netboot \http://<web_server_ip/path_to_web-accessible_directory>/netboot/kernel` 


| 所有其他系統 | “netboot \http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz` 
|===
+
「<path_to_the_web-易於 存取的目錄>」應該會引導您下載該節中的「<ONTAP_VERSION >_image.tgz」 link:prepare_for_netboot.html["準備netboot"]。

+

NOTE: 請勿中斷開機。

. [[step8]從開機功能表中選取選項「（7）Install new software first（先安裝新軟體）」。
+
此功能表選項會下載新ONTAP 的功能表映像、並將其安裝至開機裝置。

+
請忽略下列訊息：

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
本附註適用於ONTAP 不中斷營運的更新功能、不適用於控制器升級。

+

NOTE: 請務必使用netboot將新節點更新為所需映像。如果您使用其他方法在新控制器上安裝映像、可能會安裝不正確的映像。此問題適用於ONTAP 所有的版本。netboot程序與選項結合使用 `(7) Install new software` 清除開機媒體、並在ONTAP 兩個影像分割區上放置相同的版本。

. [[step9]如果系統提示您繼續此程序、請輸入「y」、並在系統提示您輸入套件時、輸入URL：
+
http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz`

. [[step10]完成下列子步驟以重新啟動控制器模組：
+
.. 當您看到下列提示時、請輸入「n」跳過備份恢復：
+
「您現在想要還原備份組態嗎？｛y | n｝

.. 當您看到下列提示時、請輸入「y」重新開機：
+
「必須重新啟動節點、才能開始使用新安裝的軟體。是否要立即重新開機？｛y | n｝

+
控制器模組會重新開機、但會在開機功能表停止、因為開機裝置已重新格式化、而且必須還原組態資料。



. [[step11]從開機功能表中選取維護模式「5」、然後在系統提示您繼續開機時輸入「y」。
. [[step12]驗證控制器和機箱是否設定為ha:
+
《ha-config show》

+
以下範例顯示「ha-config show」命令的輸出：

+
....
Chassis HA configuration: ha
Controller HA configuration: ha
....
+

NOTE: 無論系統是在HA配對或獨立組態中、都會記錄在PROm中。獨立式系統或HA配對內的所有元件的狀態必須相同。

. [[step13]如果控制器和機箱未設定為ha、請使用下列命令修正組態：
+
「ha-config modify控制器ha」

+
「ha-config modify機箱ha」

+
如果您使用MetroCluster 的是不含任何功能的組態、請使用下列命令來修改控制器和機箱：

+
「ha-config modify控制器MCC」

+
「ha-config modify機箱MCC」

. [[step14]結束維護模式：
+
《停止》

+
在開機環境提示時按 Ctrl-C 來中斷自動開機。

. [[step15]在節點2上、檢查系統日期、時間和時區：
+
'日期'

. [[step16]在node3上、在開機環境提示字元中使用下列命令檢查日期：
+
「如何日期」

. [[step17]如有必要、請在節點3上設定日期：
+
"et date _mm/dd/yed_"

. [[step18]在node3上、在開機環境提示字元中使用下列命令檢查時間：
+
「時間安排」

. [[step19]如有必要、請在節點3上設定時間：
+
"et time _hh：mm:ss_"

. [[step20]在開機載入程式中、在節點3上設定合作夥伴系統ID：
+
"etenv PARTNER-sysid _node2_sysid_"

+
對於node3、 `partner-sysid` 必須是node2的。

+
.. 儲存設定：
+
「aveenv」



. [[[auto_install3_step21]驗證 `partner-sysid` 對於節點3：
+
《prontenv合作夥伴sysid》



[[auto_install3_step22]]
. 如果您安裝了 NetApp 儲存加密 (NSE) 驅動器，請執行下列步驟：
+

NOTE: 如果您尚未在程序中稍早完成此作業、請參閱知識庫文章 https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["如何判斷磁碟機是否已通過 FIPS 認證"^] 以判斷使用中的自我加密磁碟機類型。

+
.. 設定 `bootarg.storageencryption.support` 至 `true` 或 `false`：
+
[cols="35,65"]
|===
| 如果下列磁碟機正在使用中… | 然後… 


| 符合 FIPS 140-2 第 2 級自我加密要求的 NSE 磁碟機 | `setenv bootarg.storageencryption.support *true*` 


| NetApp非FIPS SED | `setenv bootarg.storageencryption.support *false*` 
|===
+
[NOTE]
====
您無法在同一個節點或HA配對上混用FIPS磁碟機與其他類型的磁碟機。您可以在同一個節點或HA配對上混合使用SED與非加密磁碟機。

====
.. 前往特殊開機功能表並選取選項 `(10) Set Onboard Key Manager recovery secrets`。
+
輸入您先前記錄的複雜密碼和備份資訊。請參閱 link:manage_storage_encryption_using_okm.html["使用 Onboard Key Manager 管理儲存加密"]。



. 將節點開機至開機功能表：
+
Boot_ONTAP功能表



.接下來呢？
* 如果您的系統具有 FC 或 UTA/UTA2 配置，link:set_fc_or_uta_uta2_config_on_node3.html["設定並配置節點 3 上的 FC 或 UTA/UTA2 連接埠"] 。
* 如果您沒有 FC 或 UTA/UTA2 配置，link:reassign-node1-disks-to-node3.html#reassign-node1-node3-app-step1["將 node1 磁碟重新分配給 node3，步驟 1"]這樣node3就可以辨識node1的磁碟。
* 如果您有MetroCluster配置，link:set_fc_or_uta_uta2_config_on_node3.html["設定並配置節點 3 上的 FC 或 UTA/UTA2 連接埠"]檢測連接到節點的磁碟。

