---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/move_non_root_aggr_and_nas_data_lifs_node2_from_node3_to_node4.html 
keywords: move, non-root, aggregates, nas, lif, node2, node3, node4 
summary: 使用ONTAP 「系統控制器更換」命令、升級執行《Se 9.8或更新版本》的控制器時、請確認節點3上的節點2 NAS資料LIF、已從節點3重新定位至節點4。 
---
= 將節點2擁有的非根Aggregate和NAS資料lifs從節點3移至節點4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在驗證節點 4 上的網路配置後，需要將節點 2 擁有的 NAS 資料 LIF 從節點 3 遷移到節點 4，並確認 SAN LIF 存在於節點 4 上。

.關於這項工作
遠端 LIF 在升級過程中處理到 SAN LUN 的流量。升級過程中，遷移 SAN LIF 對叢集或服務運作狀況並非必要。除非需要將 SAN LIF 對應到新端口，否則不會移動它們。

在節點 4 上線後，您需要驗證 LIF 是否健康並位於正確的連接埠上。


NOTE: 如果您要變更 T6 型乙太網路介面卡或主機板連接埠的連接埠速度、您可能會發現在速度轉換之後收到格式錯誤的封包。請參閱 https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1570339["NetApp Bug Online Bug ID 1570339"^] 以及知識庫文章 https://kb.netapp.com/onprem/ontap/hardware/CRC_errors_on_T6_ports_after_converting_from_40GbE_to_100GbE["從 40GbE 轉換為 100GbE 後、 T6 連接埠發生 CRC 錯誤"^] 以取得指引。

.步驟
. 恢復重新定位作業：
+
[source, cli]
----
system controller replace resume
----
+
系統會執行下列工作：

+
** 叢集仲裁檢查
** 系統ID檢查
** 映像版本檢查
** 目標平台檢查
** 網路連線能力檢查


+
系統在網路可達性檢查階段暫停操作。

. 恢復重新定位作業：
+
[source, cli]
----
system controller replace resume
----
+
系統會執行下列檢查：

+
** 叢集健全狀況檢查
** 叢集LIF狀態檢查


+
執行這些檢查之後、系統會將節點2擁有的非根Aggregate和NAS資料lifs重新定位至新的控制器節點4。資源重新配置完成後、控制器更換作業會暫停。

. 檢查集合體重新配置和NAS資料LIF移動作業的狀態：
+
[source, cli]
----
system controller replace show-details
----
+
如果控制器更換程序暫停、請檢查並修正錯誤（如果有）、然後發出「推入」以繼續操作。

. 如有必要，恢復和還原已移位的 LIF，或手動遷移和修改未能自動遷移到 node4 的 node2 LIF。
+
[role="tabbed-block"]
====
.恢復和還原移位的 LIF
--
.. 列出所有已移位的 LIF：
+
[source, cli]
----
cluster controller-replacement network displaced-interface show
----
.. 如果有任何生命週期被移除、請將主節點還原回節點4：
+
[source, cli]
----
cluster controller-replacement network displaced-interface restore-home-node -node <node4_nodename> -vserver <vserver name> -lif-name <lif_name>
----


--
.手動遷移和修改 LIF 文件
--
.. 將未能自動遷移到節點 4 的 LIF 遷移：
+
[source, cli]
----
network interface migrate -vserver <vserver name> -lif <lif_name> -destination-node <node4_nodename> -destination-port <port_on_node4>
----
.. 修改已遷移 LIF 的來源節點和來源連接埠：
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <data_lif_name> -home-node <node4_nodename> -home-port <home_port>
----


--
====
. 繼續作業、以提示系統執行必要的POST檢查：
+
[source, cli]
----
system controller replace resume
----
+
系統會執行下列POST檢查：

+
** 叢集仲裁檢查
** 叢集健全狀況檢查
** 集合體重建檢查
** Aggregate狀態檢查
** 磁碟狀態檢查
** 叢集LIF狀態檢查
** Volume檢查



