---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/move_non-root_aggr_and_nas_data_lifs_node1_from_node2_to_node3.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2, node3 
summary: '使用升級執行ONTAP 支援功能的控制器時、請確認節點2上的節點1 NAS資料lifs已從節點2重新定位至節點3 `system controller replace` 命令。' 
---
= 將節點1擁有的非根Aggregate和NAS資料lifs從節點2移至節點3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在驗證節點3上的網路組態之後、在將Aggregate從節點2重新定位至節點3之前、您必須驗證屬於節點1的NAS資料lifs目前位於節點2上、是否已從節點2重新定位至節點3。您還必須驗證節點3上是否存在SAN lifs。

.關於這項工作
在升級過程中、遠端LIF會處理SAN LUN的流量。在升級期間、移轉SAN LIF對於叢集或服務健全狀況並不必要。除非需要將SAN LIF對應至新連接埠、否則不會移動SAN LIF。將node3聯機後，您將驗證生命期是否正常並位於適當的端口上。


NOTE: 如果您要變更 T6 型乙太網路介面卡或主機板連接埠的連接埠速度、您可能會發現在速度轉換之後收到格式錯誤的封包。請參閱 https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1570339["NetApp Bug Online Bug ID 1570339"^] 以及知識庫文章 https://kb.netapp.com/onprem/ontap/hardware/CRC_errors_on_T6_ports_after_converting_from_40GbE_to_100GbE["從 40GbE 轉換為 100GbE 後、 T6 連接埠發生 CRC 錯誤"^] 以取得指引。

.步驟
. 恢復重新定位作業：
+
[source, cli]
----
system controller replace resume
----
+
系統會執行下列工作：

+
** 叢集仲裁檢查
** 系統ID檢查
** 映像版本檢查
** 目標平台檢查
** 網路連線能力檢查


+
此作業會在網路連線能力檢查的這個階段暫停。

. 恢復重新定位作業：
+
[source, cli]
----
system controller replace resume
----
+
系統會執行下列檢查：

+
** 叢集健全狀況檢查
** 叢集LIF狀態檢查


+
執行這些檢查之後、系統會將節點1擁有的非根Aggregate和NAS資料lifs重新定位至新的控制器節點3。資源重新配置完成後、控制器更換作業會暫停。

. 檢查集合體重新配置和NAS資料LIF移動作業的狀態：
+
[source, cli]
----
system controller replace show-details
----
+
如果控制器更換程序暫停、請檢查並修正錯誤（如果有）、然後發出「推入」以繼續操作。

. 如有必要，恢復和還原已移位的 LIF，或手動遷移和修改未能自動遷移到 node3 的 node1 LIF。
+
[role="tabbed-block"]
====
.恢復和還原移位的 LIF
--
.. 列出所有已移位的 LIF：
+
[source, cli]
----
cluster controller-replacement network displaced-interface show
----
.. 如果有任何生命段被移除、請將主節點還原回節點3：
+
[source, cli]
----
cluster controller-replacement network displaced-interface restore-home-node -node <node3_nodename> -vserver <vserver name> -lif-name <lif_name>
----


--
.手動遷移和修改 LIF 文件
--
.. 將未能自動遷移到節點3的LIF遷移：
+
[source, cli]
----
network interface migrate -vserver <vserver name> -lif <lif_name> -destination-node <node3_nodename> -destination-port <port_on_node3>
----
.. 修改已遷移 LIF 的來源節點和來源連接埠：
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <data_lif_name> -home-node <node3_nodename> -home-port <home_port>
----


--
====
. 繼續作業、以提示系統執行必要的POST檢查：
+
[source, cli]
----
system controller replace resume
----
+
系統會執行下列POST檢查：

+
** 叢集仲裁檢查
** 叢集健全狀況檢查
** 集合體重建檢查
** Aggregate狀態檢查
** 磁碟狀態檢查
** 叢集LIF狀態檢查
** Volume檢查



