---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/overview_of_the_arl_upgrade.html 
keywords: overview, arl, upgrade, owner, controller, hardware 
summary: 瞭解使用ONTAP 「系統控制器更換」命令來升級執行《知識》9.8或更新版本的控制器的程序如何運作。 
---
= 了解 ARL 升級順序
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在使用ARL升級節點之前、您應該先瞭解程序的運作方式。在本內容中、程序分為幾個階段。



== 升級節點配對

若要升級節點配對、您需要準備原始節點、然後在原始節點和新節點上執行一系列步驟。然後您可以取消委任原始節點。



== ARL升級順序總覽

在程序期間、您可以使用更換的控制器硬體（一次一個控制器）來升級原始控制器硬體、並利用HA配對組態來重新配置非根集合體的擁有權。所有非根Aggregate都必須經過兩次重新定位、才能到達最終目的地、這是正確的升級節點。

每個Aggregate都有一個擁有者和目前擁有者。主擁有者是該集合體的實際擁有者、而目前擁有者則是暫時擁有者。

下表說明您在每個階段中執行的高層工作、以及階段結束時的集合擁有權狀態。程序稍後會提供詳細步驟：

[cols="35,65"]
|===
| 階段 | 說明 


| link:prepare_nodes_for_upgrade.html["第1階段：準備升級"]  a| 
在第1階段期間、您會執行預先檢查、並視需要修正Aggregate所有權。如果您使用 OKM 管理儲存加密、則必須記錄特定資訊、而且您可以選擇靜止 SnapMirror 關係。

第1階段結束時的Aggregate所有權：

* node1是node1集合體的主擁有者和目前擁有者。
* node2是node2 Aggregate的主擁有者和目前擁有者。




| link:relocate_non_root_aggr_nas_data_lifs_node1_node2.html["第2階段：重新部署和淘汰節點1"]  a| 
在第2階段期間、您會將節點1非根Aggregate和NAS資料lifs重新部署至節點2。此程序大部分是自動化的；此作業會暫停、以便您檢查其狀態。您必須手動恢復作業。如果需要、您可以重新部署故障或被否決的集合體。在淘汰node1之前、請先記錄node1資訊以供稍後的程序使用。您也可以在程序稍後的步驟中準備netboot node3和node4。

第2階段結束時的Aggregate所有權：

* node2是node1 Aggregate的目前擁有者。
* node2是node2 Aggregate的主擁有者和目前擁有者。




| link:install_boot_node3.html["階段3.安裝及開機節點3"]  a| 
在第 3 階段中，您將安裝並開機 node3 ，檢查 node1 的叢集和節點管理連接埠是否已在 node3 上上線，將 node1 磁碟重新指派至 node3 ，並驗證 node3 安裝。如果您使用的是NetApp Volume Encryption（NVE）、則會還原金鑰管理程式組態。如果需要、您可以在節點3上設定FC或UTA/UTA2組態。您也可以將節點1 NAS資料lifs和非根Aggregate從節點2重新部署到節點3、並確認節點3上存在SAN lifs。

第3階段結束時的Aggregate所有權：

* node3是node1 Aggregate的主擁有者和目前擁有者。
* node2是node2 Aggregate的主擁有者和目前擁有者。




| link:relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html["第4階段：重新部署和淘汰節點2"]  a| 
在第4階段期間、您將非根Aggregate和NAS資料lifs從節點2重新部署到節點3。您也可以記錄node2資訊、以便在程序中稍後使用、然後再將node2淘汰。

第4階段結束時的Aggregate所有權：

* node3是原屬於node1的Aggregate的主擁有者和目前擁有者。
* node2是node2 Aggregate的主擁有者。
* node3是node2 Aggregate的目前擁有者。




| link:install_boot_node4.html["階段5.安裝及開機節點4"]  a| 
在第 5 階段中，您將安裝並開機 node4 ，檢查 node2 的叢集和節點管理連接埠是否已在 node4 上上線，將 node2 磁碟重新指派至 node4 ，並驗證 node4 安裝。如果您使用NVE、則會還原金鑰管理程式組態。如果需要、您可以在節點4上設定FC或UTA/UTA2組態。您也可以將節點2 NAS資料lifs和非根Aggregate從節點3重新部署到節點4、並確認節點4上存在SAN lifs。

第5階段結束時的Aggregate所有權：

* node3是原屬於node1的集合體的主擁有者和目前擁有者。
* Node4是原屬於節點2的Aggregate主擁有者和目前擁有者。




| link:manage-authentication-using-kmip-servers.html["階段6.完成升級"]  a| 
在第6階段期間、您會確認新節點已正確設定、如果新節點已啟用加密、則您可以設定及設定儲存加密或NVE。您也應該取消委任舊節點、然後恢復SnapMirror作業。

|===