---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/reassign-node1-disks-to-node3.html 
keywords: setting, fc, uta, uta2 configuration, node 
summary: '使用命令升級執行 ONTAP 9.8 或更新版本的控制器時，您需要將屬於 node1 的磁碟重新指派給 node3 `system controller replace` 。' 
---
= 將 node1 磁碟重新指派給 node3
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在驗證 node3 安裝之前，您需要將屬於 node1 的磁盤重新分配給 node3 。

.步驟
. [[reassign-node1-node3-app-step1]]驗證 node1 是否已在啟動選單處停止。將node1的磁碟重新分配給node3：
+
`boot_after_controller_replacement`

+
短暫延遲之後、系統會提示您輸入要取代的節點名稱。如果有共享磁碟（也稱為進階磁碟分割（ADP）或分割磁碟）、系統會提示您輸入HA合作夥伴的節點名稱。

+
這些提示可能會被隱藏在主控台訊息中。如果您未輸入節點名稱或輸入不正確的名稱、系統會提示您再次輸入名稱。

+
.展開主控台輸出範例
[%collapsible]
====
....
LOADER-A> boot_ontap menu
.
<output truncated>
.
All rights reserved.
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
.
<output truncated>
.
Please choose one of the following:
(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 22/7
(22/7) Print this secret List
(25/6) Force boot with multiple filesystem disks missing.
(25/7) Boot w/ disk labels forced to clean.
(29/7) Bypass media errors.
(44/4a) Zero disks if needed and create new flexible root volume.
(44/7) Assign all disks, Initialize all disks as SPARE, write DDR labels
.
<output truncated>
.
(wipeconfig)                        Clean all configuration on boot device
(boot_after_controller_replacement) Boot after controller upgrade
(boot_after_mcc_transition)         Boot after MCC transition
(9a)                                Unpartition all disks and remove their ownership information.
(9b)                                Clean configuration and initialize node with partitioned disks.
(9c)                                Clean configuration and initialize node with whole disks.
(9d)                                Reboot the node.
(9e)                                Return to main boot menu.
The boot device has changed. System configuration information could be lost. Use option (6) to restore the system configuration, or option (4) to initialize all disks and setup a new system.
Normal Boot is prohibited.
Please choose one of the following:
(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? boot_after_controller_replacement
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?: yes
.
<output truncated>
.
Controller Replacement: Provide name of the node you would like to replace:<nodename of the node being replaced>
Controller Replacement: Provide High Availability partner of node1: <nodename of the partner of the node being replaced>
Changing sysid of node node1 disks.
Fetched sanown old_owner_sysid = 536940063 and calculated old sys id = 536940063
Partner sysid = 4294967295, owner sysid = 536940063
.
<output truncated>
.
varfs_backup_restore: restore using /mroot/etc/varfs.tgz
varfs_backup_restore: attempting to restore /var/kmip to the boot device
varfs_backup_restore: failed to restore /var/kmip to the boot device
varfs_backup_restore: attempting to restore env file to the boot device
varfs_backup_restore: successfully restored env file to the boot device wrote key file "/tmp/rndc.key"
varfs_backup_restore: timeout waiting for login
varfs_backup_restore: Rebooting to load the new varfs
Terminated
<node reboots>
System rebooting...
.
Restoring env file from boot media...
copy_env_file:scenario = head upgrade
Successfully restored env file from boot media...
Rebooting to load the restored env file...
.
System rebooting...
.
<output truncated>
.
WARNING: System ID mismatch. This usually occurs when replacing a boot device or NVRAM cards!
Override system ID? {y|n} y
.
Login:
....
====
+

NOTE: 在上述主控台輸出範例中、ONTAP 如果系統使用進階磁碟分割（ADP）磁碟、則會提示您輸入合作夥伴節點名稱。

. 如果系統進入重新啟動循環並顯示以下訊息 `no disks found`，表示系統已將 FC 或 UTA/UTA2 連接埠重設回目標模式，因此無法看到任何磁碟。選擇以下任務之一來解決此問題：
+
** 執行<<reassign-node1-node3-app-step3,步驟3.>>到<<reassign-node1-node3-app-step8,步驟8.>>在節點3上
** 前往章節link:verify_node3_installation.html["驗證node3安裝"]


. [[reassign-node1-node3-app-step3]] 自動開機期間按 Ctrl-C 在 Loader > 提示下停止節點。
. 在載入程式提示下、進入維護模式：
+
Boot_ONTAP maint

. 在維護模式中、顯示所有先前設定的啟動器連接埠、這些連接埠現在都處於目標模式：
+
「ucadmin show」

+
將連接埠改回啟動器模式：

+
「ucadmin modify -m fs -t initiator -f _Adapter name_'」

. 確認連接埠已變更為啟動器模式：
+
「ucadmin show」

. 結束維護模式：
+
《停止》

+
[NOTE]
====
如果您要從支援外部磁碟的系統升級到也支援外部磁碟的系統，請前往<<reassign-node1-node3-app-step8,步驟8.>>。

如果您要從支援外部磁碟的系統升級到同時支援內部和外部磁碟的系統，例如 AFF A800 系統，請前往<<reassign-node1-node3-app-step9,步驟9.>>。

====
. [[reassign-node1-node3-app-step8]] 在 Loader 提示下，開機：
+
Boot_ONTAP功能表

+
現在、在開機時、節點可以偵測先前指派給它的所有磁碟、並可依預期開機。

+
當您要取代的叢集節點使用根磁碟區加密時、 ONTAP 無法從磁碟讀取磁碟區資訊。還原根磁碟區的金鑰。

+

NOTE: 這僅適用於根磁碟區使用 NetApp 磁碟區加密時。

+
.. 返回特殊的開機功能表：
+
`LOADER> boot_ontap menu`

+
[listing]
----
Please choose one of the following:
(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.

Selection (1-11)? 10
----
.. 選取*（10）Set Onboard Key Manager恢復機密*
.. 輸入 `y` 出現下列提示：
+
`This option must be used only in disaster recovery procedures. Are you sure? (y or n): y`

.. 在提示字元下、輸入金鑰管理程式的通關密碼。
.. 出現提示時輸入備份資料。
+

NOTE: 您必須已取得中的通關密碼和備份資料 link:prepare_nodes_for_upgrade.html["準備節點以進行升級"] 本程序的一節。

.. 系統重新開機至特殊開機功能表後、請執行選項*（1）正常開機*
+

NOTE: 您可能會在這個階段遇到錯誤。如果發生錯誤、請重複中的子步驟、 <<reassign-node1-node3-app-step8,步驟8.>> 直到系統正常開機。



. [[reassign-node1-node3-app-step9]] 如果您要從具有外部磁碟的系統升級到支援內部和外部磁碟的系統（例如 AFF A800 系統），請將 node1 Aggregate 設為根 Aggregate ，以確認 node3 是從 node1 的根 Aggregate 開機。若要設定根 Aggregate ，請前往開機功能表並選取選項 `5`以進入維護模式。
+

CAUTION: *您必須依照所示的確切順序執行下列子步驟；否則可能導致中斷運作、甚至資料遺失。*

+
下列程序會將node3設定為從節點1的根Aggregate開機：

+
.. 進入維護模式：
+
Boot_ONTAP maint

.. 檢查node1 Aggregate的RAID、plex和Checksum資訊：
+
「aggr狀態-r」

.. 檢查node1 Aggregate的狀態：
+
「aggr狀態」

.. 如有必要、請將node1 Aggregate上線：
+
"aggr_online root_aggr_from __node1__（aggr_online root_aggr_from __node1__）"

.. 防止節點3從其原始根Aggregate開機：
+
「aggr offline _root_aggr_on_node3_」

.. 將node1根Aggregate設為節點3的新根Aggregate：
+
"aggr options aggr_fe__ node1__ root"

.. 確認節點3的根Aggregate為離線狀態、且從節點1移轉的磁碟根Aggregate為線上狀態、並設定為root：
+
「aggr狀態」

+

NOTE: 如果無法執行上一個子步驟、可能會導致節點3從內部根Aggregate開機、或是導致系統假設有新的叢集組態存在、或提示您識別一個。

+
以下是命令輸出的範例：

+
[listing]
----
 -----------------------------------------------------------------
 Aggr                 State    Status             Options

 aggr0_nst_fas8080_15 online   raid_dp, aggr      root, nosnap=on
                               fast zeroed
                               64-bit

 aggr0                offline  raid_dp, aggr      diskroot
                               fast zeroed
                               64-bit
 -----------------------------------------------------------------
----



