---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/set_fc_or_uta_uta2_config_on_node3.html 
keywords: setting, fc, uta, uta2 configuration, node 
summary: 使用ONTAP 「系統控制器更換」命令來升級執行《更新版本》9.8或更新版本的控制器時、請設定node3內建FC連接埠、UTA/UTA2連接埠或UTA/UTA2卡。 
---
= 在節點3上設定FC或UTA/UTA2組態
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
如果節點3具有內建FC連接埠、內建統一化目標介面卡（UTA/UTA2）連接埠或UTA/UTA2卡、則必須先設定設定、才能完成其餘程序。

.關於這項工作
您可能需要完成本節 <<在節點3上設定FC連接埠>>章節 <<檢查並設定節點3上的UTA/UTA2連接埠>>或這兩個區段。


NOTE: NetApp行銷資料可能會使用「UTA2」一詞來指代整合式網路卡（CNA）介面卡和連接埠。不過、CLI使用「CNA」一詞。

如果節點 3 沒有板載 FC 連接埠、板載 UTA/UTA2 連接埠或 UTA/UTA2 卡（例如，從ONTAP 9.15.1 開始引入的AFF和FAS系統），並且您正在升級具有儲存磁碟的系統，則可以跳至link:reassign-node1-disks-to-node3.html["將 node1 磁碟重新指派給 node3"]。



== 在節點3上設定FC連接埠

如果節點 3 具有 FC 連接埠（無論是板載的還是附加 FC 適配器上的），則必須在節點投入使用之前設定其連接埠配置，因為系統出廠時未預先配置連接埠。如果您不配置端口，則可能會遇到服務中斷。

.開始之前
您必須擁有儲存在區段中節點1的FC連接埠設定值 link:prepare_nodes_for_upgrade.html["準備節點以進行升級"]。

.關於這項工作
如果您的系統沒有FC組態、您可以跳過本節。如果您的系統內建UTA/UTA2連接埠或UTA/UTA2卡、請在中設定 <<檢查並設定節點3上的UTA/UTA2連接埠>>。


IMPORTANT: 在維護模式 shell 提示字元下輸入本節中的命令。

.步驟
. 將節點 3 上的 FC 設定與您先前從節點 1 擷取的設定進行比較。
. 根據需要執行下列操作之一來修改節點 3 上的 FC 連接埠：
+
在維護模式下（啟動選單中的選項 5）：

+
** 要作為目標連接埠進行程式設計：
+
`ucadmin modify -m fc -t target <adapter>`

+
例如： `ucadmin modify -m fc -t target 2a`

** 設定啟動器連接埠：
+
`ucadmin modify -m fc -t initiator <adapter>`

+
例如： `ucadmin modify -m fc -t initator 2b`



. 使用以下命令並檢查輸出來驗證新設定：
+
「ucadmin show」

. 停止節點：
+
《停止》

. 從載入程式提示字元啟動系統：
+
Boot_ONTAP功能表

. 輸入命令後、請等待系統在開機環境提示字元停止。
. 從開機功能表中選取「5」選項以進行維護模式。


. [[auto_checks3_step8]請採取下列其中一項行動：
+
[cols="30,70"]
|===
| 如果節點 3... | 然後... 


| 具有 UTA/UTA2 卡或 UTA/UTA2 板載端口 | 前往<<檢查並設定節點3上的UTA/UTA2連接埠>> 


| 沒有 UTA/UTA2 卡或 UTA/UTA2 板載端口 | 跳過_檢查並配置節點 3 上的 UTA/UTA2 連接埠_並前往link:reassign-node1-disks-to-node3.html["將 node1 磁碟重新指派給 node3"]。 
|===




== 檢查並設定節點3上的UTA/UTA2連接埠

如果節點3內建UTA/UTA2連接埠或UTA/UTA2卡、您必須檢查連接埠的組態、並視您要使用升級系統的方式而可能重新設定。

.開始之前
UTA/UTA2連接埠必須具備正確的SFP+模組。

.關於這項工作
如果您要使用統一化目標介面卡（UTA/ UTA2）連接埠來連接FC、必須先確認連接埠的設定方式。


NOTE: NetApp行銷資料可能會使用UTA2一詞來指稱CNA介面卡和連接埠。不過、CLI使用「CNA」一詞。

您可以使用 `ucadmin show`命令查看或驗證目前連接埠配置，如以下範例輸出所示：

....
*> ucadmin show
         Current  Current    Pending   Pending      Admin
Adapter  Mode     Type       Mode      Type         Status
-------  -------  -------    --------  ----------   --------
0e      fc        target     -         initiator    offline
0f      fc        target     -         initiator    offline
0g      fc        target     -         initiator    offline
0h      fc        target     -         initiator    offline
1a      fc        target     -         -            online
1b      fc        target     -         -            online
6 entries were displayed.
....
UTA/UTA2連接埠可設定為原生FC模式或UTA/UTA2模式。FC模式支援FC啟動器和FC目標；UTA/UTA2模式允許同時NIC和FCoE流量共用相同的10GbE SFP+介面、並支援FC目標。

UTA/UTA2 連接埠可能位於附加適配器或控制器主機板上，並具有以下配置，但您應該檢查節點 3 上的 UTA/UTA2 連接埠的配置並在必要時進行變更：

* 訂購控制器時所訂購的UTA/UTA2卡、在出貨前已設定為具有您要求的特性設定。
* 與控制器分開訂購的UTA/UTA2卡會隨附預設FC目標特性。
* 新控制器上的內建UTA/UTA2連接埠會在出貨前設定、以符合您要求的特性設定。
+

WARNING: 您必須處於維護模式才能設定 UTA/UTA2 連接埠。在維護模式 shell 提示字元下輸入本節中的命令。



.步驟
. 如果目前的SFP+模組不符合所需用途、請更換為正確的SFP+模組。
+
請聯絡您的NetApp代表、以取得正確的SFP+模組。

. 驗證 UTA/UTA2 連接埠設定：
+
「ucadmin show」

+
檢查輸出並確定 UTA/UTA2 連接埠是否具有您想要的個性。

+
以下範例中的輸出顯示適配器“1b”的類型正在變更為啟動器，並且適配器“2a”和“2b”的模式正在變更為“cna”。  CNA 模式可讓您將該卡用作網路介面卡。

+
[listing]
----
*> ucadmin show
         Current    Current     Pending  Pending     Admin
Adapter  Mode       Type        Mode     Type        Status
-------  --------   ----------  -------  --------    --------
1a       fc         initiator   -        -           online
1b       fc         target      -        initiator   online
2a       fc         target      cna      -           online
2b       fc         target      cna      -           online
*>
----
. 請採取下列其中一項行動：
+
[cols="30,70"]
|===
| 如果UTA/UTA2連接埠... | 然後… 


| 沒有您想要的特性 | 前往<<auto_check3_step4,步驟4.>>。 


| 擁有您想要的個人風格 | 跳過步驟 4 至步驟 8，然後轉到<<auto_check3_step9,步驟9.>>。 
|===
. [[auto_check3_step4]]請執行下列其中一項操作：
+
[cols="30,70"]
|===
| 如果您正在設定... | 然後… 


| UTA/UTA2卡上的連接埠 | 前往<<auto_check3_step5,步驟5.>> 


| 內建UTA/UTA2連接埠 | 跳過步驟 5 並轉到<<auto_check3_step6,步驟6.>>。 
|===
. [[auto_check3_step5]]如果轉接器處於啟動器模式，且 UTA/UTA2 連接埠處於線上狀態，則將 UTA/UTA2 連接埠離線：
+
`storage disable adapter <adapter_name>`

+
目標模式中的介面卡會在維護模式中自動離線。

. [[auto_check3_step6]]如果目前配置與所需用途不匹配，請根據需要變更配置：
+
`ucadmin modify -m fc|cna -t initiator|target <adapter_name>`

+
** 「m」是指個人化模式、「光纖通道」或「cna」。
** "-t"是FC4類型、"target（目標）"或"initiator（啟動器）"。
+

NOTE: 您必須對磁帶機和MetroCluster配置使用 FC 啟動器。您必須對 SAN 用戶端使用 FC 目標。



. 透過為每個連接埠輸入以下命令，將所有目標連接埠置於線上狀態：
+
`storage enable adapter <adapter_name>`

. 連接連接埠。


[[auto_check3_step9]]
. 結束維護模式：
+
《停止》

. [[step14]] 將節點開機至開機功能表：
+
Boot_ONTAP功能表



.接下來呢？
* 如果您要升級到AFF A800系統，請前往link:reassign-node1-disks-to-node3.html#reassign-node1-node3-app-step9["將 node1 磁碟重新指派給 node3 ，步驟 9"]。
* 對於所有其他系統升級，請訪問link:reassign-node1-disks-to-node3.html["將 node1 磁碟重新指派給 node3 ，步驟 1"]。

