---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/verify_node4_installation.html 
keywords: verify, node4, installation, physical ports, node2, node, LIF, MetroCluster 
summary: 使用ONTAP 「系統控制器更換」命令、升級執行版本號為「更新」的控制器時、請確認節點2的實體連接埠正確對應至節點4、並還原節點4上的網路組態。 
---
= 驗證node4安裝
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您必須驗證節點2的實體連接埠是否正確對應至節點4上的實體連接埠。這將使node4能夠在升級後與叢集中的其他節點和網路進行通訊。

請參閱 link:other_references.html["參考資料"] 可鏈接到_SURE_ Hardware Universe 以獲取有關新節點上端口的信息。您將會使用本節稍後的資訊。

實體連接埠配置可能有所不同、視節點的機型而定。當新節點開機時ONTAP 、為了自動進入仲裁、S庫 會嘗試判斷哪些連接埠應該裝載叢集生命期。

如果節點2上的實體連接埠未直接對應至節點4上的實體連接埠、請參閱後續章節 <<Restore network configuration on node4>> 必須用於修復網路連線。

安裝並開機節點4之後、您必須驗證節點是否已正確安裝。您必須等待節點4加入仲裁、然後繼續重新配置作業。

在此過程中、當節點4加入仲裁時、作業將暫停。

.步驟
. 驗證node4是否已加入仲裁：
+
「cluster show -node4 -Fields health」

+
保健領域的產出應該是真的。

. 驗證node4是否與node3屬於同一個叢集、而且它是否正常：
+
「叢集展示」

. 每個叢集LIF都必須偵聽連接埠7700。驗證叢集LIF是否正在偵聽連接埠7700：
+
：「：>網路連線偵聽show -vserver叢集」

+
連接埠7700偵聽叢集連接埠是預期結果、如下列雙節點叢集範例所示：

+
[listing]
----
Cluster::> network connections listening show -vserver Cluster
Vserver Name     Interface Name:Local Port     Protocol/Service
---------------- ----------------------------  -------------------
Node: NodeA
Cluster          NodeA_clus1:7700               TCP/ctlopcp
Cluster          NodeA_clus2:7700               TCP/ctlopcp
Node: NodeB
Cluster          NodeB_clus1:7700               TCP/ctlopcp
Cluster          NodeB_clus2:7700               TCP/ctlopcp
4 entries were displayed.
----
. 如有必要、請針對未接聽連接埠7700的每個叢集LIF、將LIF的管理狀態設為「自己」、然後設定為「UP」：
+
：`:>net int modify -vserver cluster -lif<cluster－lif>-STATUS-admin down；net int modify -vserver cluster -lIF <cluster－lif>-STATUS-admin up（net int modify -vserver Cluster -lIF <cluster－lif>-STATUS-admin up）

+
重複步驟3、確認叢集LIF現在正在偵聽連接埠7700。

. 切換至進階權限模式：
+
《進階設定》

. 檢查控制器更換作業的狀態、並確認它處於暫停狀態、且狀態與節點2停止之前的狀態相同、以執行安裝新控制器和移動纜線的實體工作：
+
「System Controller replace show」（系統控制器更換顯示）

+
「System Controller replace show-details」（系統控制器取代顯示詳細資料

. 如果您使用MetroCluster 的是一個發揮作用的系統、請確認已更換的控制器已正確設定MetroCluster 為符合該功能的組態；MetroCluster 該功能應該處於正常狀態。請參閱 link:verify_health_of_metrocluster_config.html["驗MetroCluster 證整個過程的效能狀況"]。
+
重新設定MetroCluster 叢集間的LIF on the Synestate node4、然後檢查叢集對等、以恢復MetroCluster 在各個節點之間的通訊、再繼續進行 <<auto_verify_4_Step6,步驟6.>>。

+
檢查MetroCluster 此節點狀態：

+
「不一樣的秀」MetroCluster

. [[[auto_Verify（自動驗證）_4_Step6]繼續控制器更換作業：
+
「系統控制器更換恢復」

. 控制器更換將暫停以進行介入、並顯示下列訊息：
+
....
Cluster::*> system controller replace show
Node             Status                       Error-Action
---------------- ------------------------     ------------------------------------
Node2(now node4) Paused-for-intervention      Follow the instructions given in
                                              Step Details
Node2

Step Details:
--------------------------------------------
To complete the Network Reachability task, the ONTAP network configuration must be
manually adjusted to match the new physical network configuration of the hardware.
This includes:

1. Re-create the interface group, if needed, before restoring VLANs. For detailed
commands and instructions, refer to the "Re-creating VLANs, ifgrps, and broadcast
domains" section of the upgrade controller hardware guide for the ONTAP version
running on the new controllers.
2. Run the command "cluster controller-replacement network displaced-vlans show"
to check if any VLAN is displaced.
3. If any VLAN is displaced, run the command "cluster controller-replacement
network displaced-vlans restore" to restore the VLAN on the desired port.
2 entries were displayed.
....
+

NOTE: 在此程序中、_重新建立VLAN、ifgrps和廣播網域_一節已重新命名為_在節點4_上還原網路組態。

. 在控制器更換處於暫停狀態時、請繼續執行本文件的下一節、以還原節點上的網路組態。




== 還原節點4上的網路組態

確認node4處於仲裁狀態並可與node3通訊之後、請確認節點2的VLAN、介面群組和廣播網域是否顯示在node4上。此外、請確認所有節點4網路連接埠都已設定在正確的廣播網域中。

如需建立及重新建立VLAN、介面群組及廣播網域的詳細資訊、請參閱 link:other_references.html["參考資料"] 連結至_網路管理_。

.步驟
. 列出升級節點2（稱為節點4）上的所有實體連接埠：
+
「網路連接埠show -node4」

+
此時會顯示節點上的所有實體網路連接埠、VLAN連接埠和介面群組連接埠。從這個輸出中、您可以看到ONTAP 任何實體連接埠、這些連接埠已透過下列步驟移入「叢集」廣播網域。您可以使用此輸出來協助決定哪些連接埠應做為介面群組成員連接埠、VLAN基礎連接埠或獨立實體連接埠來裝載lifs。

. 列出叢集上的廣播網域：
+
《廣播網域節目》

. 列出節點4上所有連接埠的網路連接埠可連線性：
+
「網路連接埠連線能力顯示」

+
命令的輸出類似於下列範例：

+
....
clusterA::*> reachability show -node node2_node4
  (network port reachability show)
Node         Port       Expected Reachability       Reachability Status
---------    --------  ---------------------------  ---------------------
node2_node4
             a0a        Default:Default             no-reachability
             a0a-822    Default:822                 no-reachability
             a0a-823    Default:823                 no-reachability
             e0M        Default:Mgmt                ok
             e0a        Cluster:Cluster             misconfigured-reachability
             e0b        Cluster:Cluster             no-reachability
             e0c        Cluster:Cluster             no-reachability
             e0d        Cluster:Cluster             no-reachability
             e0e        Cluster:Cluster             ok
             e0e-822    -                           no-reachability
             e0e-823    -                           no-reachability
             e0f        Default:Default             no-reachability
             e0f-822    Default:822                 no-reachability
             e0f-823    Default:823                 no-reachability
             e0g        Default:Default             misconfigured-reachability
             e0h        Default:Default             ok
             e0h-822    Default:822                 ok
             e0h-823    Default:823                 ok
18 entries were displayed.
....
+
在上述範例中、節點2_node4是在更換控制器之後才開機。它有數個連接埠無法連線、且正在等待連線能力掃描。

. [[auto_reest_4_Step4]]修復節點4上每個連接埠的連線狀態、其連線狀態並非「OK」。先在任何實體連接埠上執行下列命令、然後在任何VLAN連接埠上執行一次一個：
+
"network port re連通 性修復-node_node_name_-port _port_name_"

+
輸出內容如下所示：

+
....
Cluster ::> reachability repair -node node2_node4 -port e0h
....
+
....
Warning: Repairing port "node2_node4: e0h" may cause it to move into a different broadcast domain, which can cause LIFs to be re-homed away from the port. Are you sure you want to continue? {y|n}:
....
+
如前所示、對於連線狀態可能不同於目前所在廣播網域之連線狀態的連接埠、預期會出現一則警告訊息。

+
檢視連接埠的連線能力、並視需要回答「y」或「n」。

+
驗證所有實體連接埠的可連線性是否符合預期：

+
「網路連接埠連線能力顯示」

+
執行可連線性修復時ONTAP 、嘗試將連接埠放在正確的廣播網域中。但是、如果無法判斷連接埠的連線能力、而且不屬於任何現有的廣播網域、ONTAP 則無法使用這些連接埠來建立新的廣播網域。

. 如果介面群組組態與新的控制器實體連接埠配置不符、請使用下列步驟加以修改。
+
.. 您必須先從其廣播網域成員資格中移除應該是介面群組成員連接埠的實體連接埠。您可以使用下列命令來執行此作業：
+
「網路連接埠、廣播網域、移除連接埠、廣播網域、廣播網域、網域名稱、連接埠、節點名稱、連接埠名稱、連接埠名稱_」

.. 將成員連接埠新增至介面群組：
+
「網路連接埠ifgrp add-port -node_node_name_-ifgrp _ifgrp_-port _port_name_」

.. 介面群組會在新增第一個成員連接埠約一分鐘後自動新增至廣播網域。
.. 確認介面群組已新增至適當的廣播網域：
+
「網路連接埠可連線性」顯示-node_node_name_-port _ifgrp_

+
如果介面群組的連線狀態不是「正常」、請將其指派給適當的廣播網域：

+
「網路連接埠廣播網域附加連接埠-broadcast網域_broadcast網域_domain_name_-ports _norme:port_」



. 將適當的實體連接埠指派給「叢集（Cluster）”廣播網域：
+
.. 確定哪些連接埠可連線至「叢集（叢集）”廣播網域：
+
「網路連接埠可連線性顯示-可連線至廣播網域叢集：叢集」

.. 如果「叢集」廣播網域的連線狀態不是「正常」、請修復任何可連線的連接埠：
+
"network port re連通 性修復-node_node_name_-port _port_name_"



. 使用下列其中一項命令、將其餘的實體連接埠移至正確的廣播網域：
+
"network port re連通 性修復-node_node_name_-port _port_name_"

+
「網路連接埠廣播網域移除連接埠」

+
「網路連接埠廣播網域附加連接埠」

+
確認沒有無法連線或非預期的連接埠。使用下列命令檢查所有實體連接埠的連線狀態、並檢查輸出以確認狀態為「OK」（正常）：

+
「網路連接埠連線能力顯示-詳細資料」

. 使用下列步驟還原任何可能已被取代的VLAN：
+
.. 列出已移離的VLAN：
+
「顯示虛擬區域網路」

+
應顯示如下輸出：

+
....
Cluster::*> displaced-vlans show
(cluster controller-replacement network displaced-vlans show)
            Original
Node        Base Port     VLANs
---------   ---------     ------------------------------------------------------
Node1       a0a           822, 823
            e0e           822, 823
....
.. 還原從先前基礎連接埠移出的VLAN：
+
「Dis放置VLAN還原」

+
以下是將已從介面群組a0a移出的VLAN還原回相同介面群組的範例：

+
....
Cluster::*> displaced-vlans restore -node node2_node4 -port a0a -destination-port a0a
....
+
以下是將連接埠「e0e」上的已移轉VLAN還原為「e0小時」的範例：

+
....
Cluster::*> displaced-vlans restore -node node2_node4 -port e0e -destination-port e0h
....
+
當VLAN還原成功時、會在指定的目的地連接埠上建立移出的VLAN。如果目的地連接埠是介面群組的成員、或目的地連接埠當機、則VLAN還原會失敗。

+
等待約一分鐘、將新還原的VLAN放入適當的廣播網域。

.. 如果VLAN連接埠不在「dis放置VLAN show」輸出中、但應在其他實體連接埠上設定、請視需要建立新的VLAN連接埠。


. 完成所有連接埠修復後、請刪除任何空白的廣播網域：
+
「廣播網域刪除-broadcast網域_broadcast網域_網域名稱_」

. 驗證連接埠可連線性：
+
「網路連接埠連線能力顯示」

+
當所有連接埠均已正確設定並新增至正確的廣播網域時、「network port re連通 性show」命令會針對所有連接的連接埠、將連線狀態報告為「ok」、對於沒有實體連線的連接埠、狀態應顯示為「不可到達性」。如果有任何連接埠報告這兩個以外的狀態、請依照中的指示執行連線能力修復、並新增或移除廣播網域中的連接埠 <<auto_restore_4_Step4,步驟4.>>。

. 確認所有連接埠均已置入廣播網域：
+
「網路連接埠展示」

. 確認廣播網域中的所有連接埠均已設定正確的最大傳輸單元（MTU）：
+
「網路連接埠廣播網域節目」

. 還原LIF主連接埠、指定需要還原的Vserver和LIF主連接埠（如果有）：
+
.. 列出任何已移出的生命：
+
「顯示介面」

.. 還原LIF主連接埠：
+
「顯示介面還原主節點節點節點_norme_name_-vserver _vserver_name_-lif-name _lif_name_」



. 驗證所有生命段是否都有主連接埠、且是否以管理方式啟動：
+
「網路介面顯示欄位主連接埠、狀態管理」


