---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: 決定是否使用可升級同一機箱中控制器機型的 ARL 程序。 
---
= 決定是否使用Aggregate重新配置程序
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
本內容說明如何在 HA 配對中升級儲存控制器、同時保留所有現有資料和磁碟。這是一個複雜的程序、只能由經驗豐富的系統管理員使用。

請在下列情況下使用此程序：

* 您正在執行下列其中一項控制器升級：
+
[cols="50,50"]
|===
| 舊控制器 | 更換控制器 


| AFF A220 已設定為 ASA | ASA A150 


| AFF A220 、 AFF A200 或 AFF C190 | 解答150 AFF 


| FAS2620 或 FAS2720 | FAS2820 


| AFF A700 設定為 ASA | ASA A900 


| AFF A700 | 解答900 AFF 


| FAS9000 | FAS9500 
|===
* 您已向 NetApp 銷售代表確認您已收到用於控制器升級的硬體：
+
** ASA A150 、 AFF A150 或 FAS2820 控制器
** ASA A900 、 AFF A900 或 FAS9500 控制器和 NVRAM 模組、以及升級所需的零件


* 您正在執行升級所需的最低 ONTAP 版本。如需詳細資訊、請參閱 link:index.html["總覽"]。
* 您不想將新的控制器新增為叢集的新HA配對、也不想使用Volume Moves來移轉資料。
* 您在管理ONTAP 方面經驗豐富、而且對於在診斷權限模式下工作的風險感到自在。


請*不要*在下列情況下使用此程序：

* 您正在FlexArray 使用的是AFF 功能不實的虛擬化軟體來搭配使用於功能不實的A700或FAS9000系統。
* 您使用的是共享交換器、用於叢集互連和乙太網路附加儲存設備。


如需升級 AFF A700 或 FAS9000 系統上的 Fabric MetroCluster 或 MetroCluster IP 組態、請參閱 link:other_references.html["參考資料"] 連結至_E不明MetroCluster Upgrade and Expansion內容。


NOTE: 您可以在此程序中使用NetApp儲存加密（NSE）、NetApp Volume加密（NVE）和NetApp Aggregate加密（NAE）。

如果您偏好其他方法來升級控制器硬體、並願意進行Volume移動、請參閱 link:other_references.html["參考資料"] 若要透過移動磁碟區或儲存設備連結至_Upgrade。

請參閱 link:other_references.html["參考資料"] 連結至_SURF9 ONTAP 文件中心_、您可在此存取ONTAP VMware產品文件。
