---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: 決定是否使用可升級同一機箱中控制器機型的 ARL 程序。 
---
= 決定是否使用此聚合遷移程序
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
升級控制器硬體有多種聚合重定位 (ARL) 方法。本內容說明如何透過將現有系統轉換為替換系統（保留現有系統機箱和磁碟）來升級 HA 對中的儲存控制器。只有經驗豐富的 ONTAP 管理員才應使用此複雜程序。

為了幫助您確定此 ARL 程式是否適合您的控制器硬體升級，您應該檢查以下所有支援和不支援升級的情況。



== 支援此 ARL 升級

您可以在以下情況下使用此 ARL 程式：

* 您的控制器升級列在<<supported-systems,支援的系統對照表>> 。
* 您已向 NetApp 銷售代表確認您已收到控制器升級所需的硬體：
+
** 兩個 AFF A90 ， AFF A70 或 AFF C80 控制器，以及所有 I/O 模組。所需長度的 100GbE 纜線。
** 兩個 AFF A50 ， AFF A30 ， AFF C30 或 AFF C60 控制器和 I/O 模組，以及所需的纜線
** ASA A150 、 AFF A150 或 FAS2820 控制器
** ASA A900 ， AFF A900 或 FAS9500 控制器和 NVRAM 模組及零件


* 您正在執行升級所需的最低 ONTAP 版本。如需詳細資訊、請<<supported-systems,支援的系統升級組合>>參閱。
* 您有管理 ONTAP 的經驗，而且很熟悉在診斷權限模式下工作的風險。
* 您的系統執行 ONTAP 9.15.1 或更新版本，而且使用乙太網路交換器來連線至乙太網路附加儲存設備。



NOTE: 您可以在此程序中使用NetApp儲存加密（NSE）、NetApp Volume加密（NVE）和NetApp Aggregate加密（NAE）。



== 不支援此 ARL 升級

您不能在以下情況下使用此 ARL 程式：

* 您想要將新控制器新增為叢集的新 HA 配對，並使用 Volume Moves 移轉資料。
* 您正在升級的現有系統上使用 FlexArray 虛擬化軟體。
* 您正在升級 MetroCluster IP 組態。
+
若要升級 MetroCluster IP 組態，請參閱link:other_references.html["參考資料"]連結至 MetroCluster 升級與擴充內容。





== 支援的系統升級組合

下表顯示了透過將現有系統轉換為替換系統並保留現有系統機箱和磁碟來執行控制器升級所支援的系統矩陣。


CAUTION: 此程序嚴格適用於下列升級組態。請勿使用此程序在任何其他系統組合之間執行升級。對於所有其他控制器機型，請參閱link:other_references.html["參考資料"]連結至 _ 使用「系統控制器更換」命令來升級執行 ONTAP 9.8 或更新版本的控制器硬體 _ ，以及 _ 使用集合重新定位來手動升級執行 ONTAP 9.8 或更新版本的控制器硬體 _ 。

[cols="20,20,40"]
|===
| 現有系統 | 更換系統 | 支援 ONTAP 的支援版本 


| AFF C250 ^1^ | AFF C30 、 AFF C60 | 9.16.1. 


| AFF A250 ^1^ | AFF A30 、 AFF A50 | 9.16.1. 


| AFF C800 ^1^ | AFF C80 | 9.16.1. 


| AFF A800 ^1^ | AFF A90 或 AFF A70 | 9.15.1 及更新版本 


| AFF A220 設定為全 SAN 陣列（ ASA ） | ASA A150 | 9.13.1P1 及更新版本 


| VA220 AFF | 解答150 AFF | 9.10.1 P15 、 9.11.1P11 、 9.12.1P5 及更新版本 


| 解答200 AFF | 解答150 AFF  a| 
9.10.1P15 、 9.11.1P11 及更新版本 ^2^



| C190 AFF | 解答150 AFF | 9.10.1 P15 、 9.11.1P11 、 9.12.1P5 及更新版本 


| FAS2620 | FAS2820  a| 
9.11.1P7 或更新版本的修補程式發行版（ FAS2620 ） ^2^

9.13.1 及更新版本（ FAS2820 ）



| FAS2720 | FAS2820 | 9.13.1 及更新版本 


| AFF A700 設定為 ASA | ASA A900 | 9.13.1P1 及更新版本 


| AFF A700 | 解答900 AFF | 9.10.1 P10 、 9.11.1P6 及更新版本 


| FAS9000 | FAS9500 | 9.10.1 P10 、 9.11.1P6 及更新版本 
|===
^1^ 當您升級至 ONTAP 9.15.1 或更新版本所推出的系統時， ONTAP 會轉換所有現有精簡配置磁碟區的儲存效率，包括不使用儲存效率的磁碟區，並套用利用硬體卸載功能的新儲存效率功能。這是一個自動背景程序、對系統沒有明顯的效能影響。 https://docs.netapp.com/us-en/ontap/concepts/builtin-storage-efficiency-concept.html["深入瞭解"^]

^2^ AFF A200 和 FAS2620 系統不支援高於 9.11.1 的 ONTAP 版本。

[NOTE]
====
NetApp 強烈建議您在舊系統和更換系統上使用相同的 ONTAP 版本。

上述表格中的 ONTAP 最低版本為必填。這些 ONTAP 版本具有服務處理器或主機板管理控制器（ BMC ）韌體版本、可在升級期間支援機箱內的混合控制器類型。

====


== 選擇不同的硬體升級程序

* link:../upgrade-arl/index.html["查看可用於升級控制器硬體的替代 ARL 方法"]。
* 如果您偏好其他方法來升級控制器硬體、並願意進行Volume移動、請參閱 link:other_references.html["參考資料"] 若要透過移動磁碟區或儲存設備連結至_Upgrade。


.相關資訊
參考link:other_references.html["參考資料"]連結到_ONTAP 9 文件_。
