---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/get_ip_address_of_external_kms_for_storage_encryption.html 
keywords: storage, encryption, authentication, key, manager, external 
summary: 在AFF 從靜止A700 AFF 升級到靜止A900的過程中、設定及管理儲存加密、管理驗證金鑰、以及靜止SnapMirror關係。 
---
= 取得外部金鑰管理伺服器的IP位址以進行儲存加密
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
升級後、您必須立即設定儲存加密、並建立全叢集驗證金鑰、以取代先前的節點層級驗證金鑰。

.步驟
. 安裝必要的用戶端和伺服器安全通訊端層（SSL）憑證、以與金鑰管理伺服器通訊：
+
「安全憑證安裝」

. 在每個節點上使用下列命令、在所有節點上設定儲存加密：
+
「安全金鑰管理程式外部啟用」

. 新增每個金鑰管理伺服器的IP位址：
+
「安全金鑰管理程式外部附加伺服器-金鑰伺服器_key_manager_server_ip_address_」

. 確認叢集中所有節點上都已設定並可使用相同的金鑰管理伺服器：
+
「安全金鑰管理程式外部顯示狀態」

. 建立新的全叢集驗證金鑰：
+
「安全金鑰管理程式金鑰建立」

. 記下新的驗證金鑰ID。
. 使用新的驗證金鑰重新輸入所有自我加密磁碟機的金鑰：
+
「torage加密磁碟modify -disk *-data-key-id _imalization_key_id_」





== 使用KMIP伺服器管理驗證

從ONTAP 功能更新至功能更新至功能更新、您可以使用金鑰管理互通性傳輸協定（KMIP）伺服器來管理驗證金鑰。

.步驟
. 新增控制器：
+
「安全金鑰管理程式外部啟用」

. 新增金鑰管理程式：
+
「安全金鑰管理程式外部附加伺服器-金鑰伺服器_key_manager_server_ip_address_」

. 驗證金鑰管理伺服器是否已設定、且可供叢集中的所有節點使用：
+
「安全金鑰管理程式外部顯示狀態」

. 將驗證金鑰從所有連結的金鑰管理伺服器還原至新節點：
+
「安全金鑰管理程式外部還原-node_new_控制 器名稱_」

. 使用新的驗證金鑰重新輸入所有自我加密磁碟：
+
「torage加密磁碟修改磁碟*（-data-key-id nonMSID Ak）」

. 如果您使用聯邦資訊處理標準（FIPS）、請使用新的驗證金鑰重新鎖定所有自我加密磁碟：
+
「torage加密磁碟修改磁碟*（-fIPS-key-id nonMSID Ak）」


