---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrade, aff, a900, a700, ontap, controllers 
summary: 瞭解您是否可以使用ARL將AFF 某個地方的版號升級至AFF 某個地方的版號。 
---
= 升級控制器的準則
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在下列系統組態中使用ARL來升級一對控制器：

* 將AFF 一對用作「更新AFF 版本」的「功能」的「功能性」控制器升級至執行ONTAP 「功能性」的「功能性」系統
* 將一對FAS9000控制器升級至執行ONTAP SHor9.10.1P3或更新版本的FAS9500系統




== 支援ARL升級

支援AFF 的組合包括控制器從功能不完整的A700升級至AFF 功能不完整的A900、或從FAS9000升級至FAS9500、使用ARL和NVRAM模組。如果您已收到AFF 全新的整套系統（包括新機箱）、請參閱 link:other_references.html["參考資料"] 若要連結至_、請使用「系統控制器更換」命令來升級執行ONTAP 《Estrs9.8或更新版本》內容的控制器硬體。


WARNING: 此程序嚴格適用於AFF 執行下列項目的從Ar1A700升級AFF 到Ar1A900、ONTAP 以及執行從更新版本的FAS9.10.1或更高版本、以及執行9.10.1P3或更新版本的FAS9000升級到FAS9500。請勿使用此程序在任何其他系統組合之間執行升級。

使用ARL的控制器升級支援使用SnapLock 「支援」的系統、這些系統均設定了「支援使用者支援使用者支援的功能」和SnapLock 「支援使用者支援



== 雙節點無交換式叢集

如果您要升級雙節點無交換式叢集中的節點、則可在執行升級時、將節點留在無交換器叢集中。您不需要將它們轉換成交換式叢集。



== 疑難排解

如果在升級控制器時發生任何問題、請參閱 link:troubleshoot_index.html["疑難排解"] 本節將於程序結束時提供更多資訊和可能的解決方案。

如果您找不到解決所遇到問題的解決方案、請聯絡技術支援部門。
