---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrade, ontap, controllers, old, system, chassis, disk, disks 
summary: 瞭解您是否可以使用 ARL 、保留舊的系統機箱和磁碟來進行升級組態。 
---
= 升級控制器的準則
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
若要瞭解是否可以使用 Aggregate 重定位（ ARL ）、請保留舊的系統機箱和磁碟、這取決於系統升級組態和 ONTAP 版本。



== 支援ARL升級

某些系統組態支援控制器升級。若要檢視支援的系統和最低 ONTAP 版本清單、請參閱 link:index.html["總覽"]。

如果您收到新的 AFF A30 ， AFF A50 ， AFF A70 ， AFF ， AFF A150 ， AFF A900 ， AFF A90 C30 ， AFF C60 ， AFF C80 ， FAS2820 或 FAS9500 作為完整系統，包括新機箱，請參閱link:other_references.html["參考資料"]連結至 _ 使用「系統控制器更換」命令來升級執行 ONTAP 9.8 或更新版本的控制器硬體 _ 。

使用ARL的控制器升級支援使用SnapLock 「支援」的系統、這些系統均設定了「支援使用者支援使用者支援的功能」和SnapLock 「支援使用者支援



== 雙節點無交換式叢集

如果您要升級雙節點無交換式叢集中的節點、則可在執行升級時、將節點留在無交換器叢集中。您不需要將它們轉換成交換式叢集。



== 切換附加叢集

如果您要在連接至叢集交換器的叢集中升級節點、則必須確認交換器上執行的 make 、 model 、韌體版本、 RCF 和 ONTAP 版本、與升級後在替換控制器上執行的版本相同。如有必要，您必須先執行交換器升級，才能使用 ARL 升級控制器。

如需更多資訊、請參閱 link:upgrade-arl-auto-affa900/cable-node1-for-shared-cluster-HA-storage.html#connect-switch-attached-cluster["連線至交換器連接的叢集"]。



== 疑難排解

如果在升級控制器時發生任何問題、請參閱 link:troubleshoot_index.html["疑難排解"] 本節將於程序結束時提供更多資訊和可能的解決方案。

如果您找不到解決所遇到問題的解決方案、請聯絡技術支援部門。
