---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/index.html 
keywords: aggregate, relocation, controller, hardware, aggregates, flexarray, metrocluster, terminology, old, system, chassis, disk, disks 
summary: 您可以將舊系統轉換為更換系統、以保留舊的系統機箱和磁碟、藉此升級控制器硬體。 
---
= 了解 ARL 升級程序
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
升級控制器硬體有多種聚合重定位 (ARL) 方法。此過程介紹如何透過將現有系統轉換為替換系統（保留現有系統機箱和磁碟）來升級 HA 對中的儲存控制器。

ARL 利用 HA 組態和叢集互連通訊。這可讓您將非根集合體的擁有權從一個節點移至另一個節點，前提是它們共用同一個叢集內的儲存設備。

在過程中、您會使用更換的控制器硬體來升級原始的控制器硬體、以重新定位非根集合體的擁有權。您可以在舊控制器節點之間移轉非根集合體。安裝替換節點之後，您可以將非根節點集合體從舊控制器節點移轉至替換的控制器節點。您可以在升級程序期間存取所升級節點上的資料。您也可以在繼續進行時、在叢集中的節點之間移轉資料生命量。

您所更換的控制器硬體取決於現有的系統機型類型：

[cols="30,70"]
|===
| 如果您現有的系統 ... | 然後... 


| AFF A250 、 AFF C250 | 將兩個 AFF A250 或 AFF C250 控制器交換為新的控制器和 I/O 模組。 


| AFF A800 、 AFF C800 | 將兩個 AFF A800 或 AFF C800 控制器交換為新的控制器和 I/O 模組。 


| AFF A220 、 AFF A200 、 AFF C190 、 FAS2620 或 FAS2720 | 將舊控制器上每個節點上的控制器模組換成新模組。 


| AFF A700 或 FAS9000 | 將舊控制器上每個節點上的控制器和 NVRAM 模組交換為新模組。* 注意 * ：您不需要移動，中斷或重新連接 I/O 卡，資料纜線，磁碟櫃和磁碟。 
|===

NOTE: 術語* node1*和* node2*僅用作本文檔中的節點名稱參考。在遵循程序時、您必須以節點的實際名稱來取代。



== 要求與限制

在開始升級過程之前，您需要考慮一些重要因素。


NOTE: 在開始升級過程之前，您必須查看以下所有重要資訊。

* 此程序相當複雜、假設您具備進階ONTAP 的功能不完整的管理技能。您還應該閱讀並理解link:guidelines_for_upgrading_controllers_with_arl.html["控制器升級指南"]和link:overview_of_the_arl_upgrade.html["ARL 升級序列"]在開始升級之前。
* 此程序假設更換的控制器硬體是新的、並未在其他系統中使用。此程序不包含使用wpeconfig命令準備已用控制器所需的步驟。如果更換的控制器硬體先前是用作另一個ONTAP 支撐叢集的一部分、或是用作獨立的單一節點系統、您必須聯絡技術支援部門。
* 您可以使用此程序來升級具有兩個以上節點之叢集中的控制器硬體、但是您需要針對叢集中的每個HA配對分別執行程序。
* 如果您的交換器不受 ONTAP 版本支援、且您要升級的替換系統不受支援、請參閱 link:other_references.html["參考資料"] 以連結至_SURE_ Hardware Universe 。
* AFF A250 和 AFF C250 系統使用 10/25 GbE 板載埠進行群集互連。若要將 AFF A250 或 AFF C250 系統的雙節點無交換器叢集升級至 AFF A50、AFF A30、AFF C60 或 AFF C30 系統，必須在兩個節點的插槽 1 使用 X60132A 4 連接埠 10/25 GbE 卡。這為叢集 LIF 提供了與目標平台上臨時連接埠的叢集互連。
* AFF A30 ， AFF A50 ， AFF A70 ， AFF A90 ， AFF A1K ， AFF C30 ， AFF C60 ， AFF C80 ， FAS70 和 FAS90 系統共用 100GbE 網路連接埠，可同時用於叢集和 HA 連線。這些系統可支援 10GbE 或 25GbE 叢集連線至傳統叢集交換器；不過、 NetApp 建議在不再需要 10GbE 和 25GbE 交換器時、更新至 100GbE 叢集速度。如需詳細資訊、請參閱下列知識庫文章：
+
--
** link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_configure_10G_or_25G_cluster_ports_on_a_new_cluster_setup["如何在新的叢集設定上設定 10G 或 25G 叢集連接埠"^]
** link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_convert_existing_10G_or_25G_cluster_ports_to_40G_or_100G_cluster_ports["如何將現有 10G 或 25G 叢集連接埠轉換為 40G 或 100g 叢集連接埠"^]


--
+
如果您無法將現有節點上的 e0a 或 e0b 叢集連接埠連結至新節點上的叢集連接埠，請參閱下列內容以取得更多資訊：

+
** link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-166978["NetApp Bug Online Bug ID CONTAP-166978"^]
** https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1127315["NetApp錯誤線上錯誤編號1127315"^]


* ASA A900 、 AFF A900 和 FAS9500 系統僅支援高線電力（ 200V 至 240V ）。如果AFF 您的FASA700或FAS9000系統是以低線電源（100V至120V）執行、則在AFF 使用此程序之前、您必須先將該功能轉換成使用該功能的電源供應器或FAS9000輸入電源。
* 如果您是從現有系統升級<<supported-systems-in-chassis,支援的系統對照表>>，但中包含停機時間，您可以移動儲存設備或聯絡技術支援部門，來升級控制器硬體。請參閱 link:other_references.html["參考資料"] 以連結至 _ 透過移動磁碟區或儲存設備進行升級 _ 。




== 自動化控制器升級程序

此程序提供自動化程序的步驟、此程序使用自動磁碟指派和網路連接埠連線檢查來簡化控制器升級體驗。
