---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/index.html 
keywords: aggregate, relocation, controller, hardware, aggregates, flexarray, metrocluster, terminology, old, system, chassis, disk, disks 
summary: 您可以將舊系統轉換為更換系統、以保留舊的系統機箱和磁碟、藉此升級控制器硬體。 
---
= 總覽
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
本程序說明如何使用 Aggregate 重定位（ ARL ）、在 HA 配對上不中斷地升級控制器硬體、以進行下列系統組態。此程序會將舊系統轉換為更換系統、保留舊系統機箱和磁碟。


WARNING: 此程序嚴格適用於下列升級組態。請勿 * 使用此程序在任何其他系統組合之間執行升級。

[cols="20,20,40"]
|===
| 舊系統 | 更換系統 | 支援 ONTAP 的支援版本 


| VA220 AFF | 解答150 AFF | 9.10.1 P15 、 9.11.1P11 、 9.12.1P5 及更新版本 


| 解答200 AFF | 解答150 AFF  a| 
9.10.1 P15 、 9.11.1P11 及更新版本（ AFF A200 及 AFF A150 ）


NOTE: AFF A200 不支援早於 9.11.1 的 ONTAP 版本。



| C190 AFF | 解答150 AFF | 9.10.1 P15 、 9.11.1P11 、 9.12.1P5 及更新版本 


| FAS2620 | FAS2820  a| 
9.11.1P7 及更新版本（ FAS2620 ）


NOTE: FAS2620 不支援早於 9.11.1 的 ONTAP 版本。

9.13.1 及更新版本（ FAS2820 ）



| FAS2720 | FAS2820 | 9.13.1 及更新版本 


| AFF A700 | 解答900 AFF | 9.10.1 P10 、 9.11.1P6 及更新版本 


| FAS9000 | FAS9500 | 9.10.1 P10 、 9.11.1P6 及更新版本 
|===
[NOTE]
====
NetApp 建議您在舊系統和更換系統上使用相同的 ONTAP 版本。

上述表格中的 ONTAP 最低版本為必填。這些 ONTAP 版本具有服務處理器或主機板管理控制器（ BMC ）韌體版本、可在升級期間支援機箱內的混合控制器類型。

====
在程序期間、您會在舊控制器節點之間移轉非根集合體。安裝之後、您可以將非根集合體從舊的控制器節點移轉到替換的控制器節點。您可以在升級程序期間存取所升級節點上的資料。

.關於這項工作
在此控制器升級程序期間、您將執行下列其中一項升級：

* 將 AFF A220 、 AFF A200 或 AFF C190 系統上每個節點上的控制器模組更換為新的 AFF A150 模組。
* 將 FAS2620 或 FAS2720 系統上每個節點上的控制器模組換成新的 FAS2820 模組。
* 將 AFF A700 或 FAS9000 系統上每個節點上的兩個控制器和 NVRAM 模組交換為新的 AFF A900 或 FAS9500 模組。



NOTE: 您不需要移動、拔下或重新連接I/O卡、資料纜線、磁碟櫃和磁碟。

此程序使用稱為Aggregate資源移轉（ARL）的方法、可利用HA組態、讓您將非根集合體的擁有權從一個節點移至另一個節點（如果它們共用同一個叢集內的儲存設備）。

在過程中、您會使用更換的控制器硬體來升級原始的控制器硬體、以重新定位非根集合體的擁有權。您可以多次從節點移轉Aggregate至節點、以確認在整個升級程序中、至少有一個節點正在處理來自集合體的資料。您也可以在繼續進行時、在叢集中的節點之間移轉資料生命量。


NOTE: 術語* node1*和* node2*僅用作本文檔中的節點名稱參考。執行此程序時、您必須替換節點的真實名稱。

.重要資訊
* 此程序相當複雜、假設您具備進階ONTAP 的功能不完整的管理技能。您也應該閱讀並瞭解 link:guidelines_for_upgrading_controllers_with_arl.html["升級控制器的準則"] 和 link:overview_of_the_arl_upgrade.html["ARL升級總覽"] 開始升級之前的章節。
* 此程序假設更換的控制器硬體是新的、並未在其他系統中使用。此程序不包含使用wpeconfig命令準備已用控制器所需的步驟。如果更換的控制器硬體先前是用作另一個ONTAP 支撐叢集的一部分、或是用作獨立的單一節點系統、您必須聯絡技術支援部門。
* 您可以使用此程序來升級具有兩個以上節點之叢集中的控制器硬體、但是您需要針對叢集中的每個HA配對分別執行程序。
* 如果您的交換器不受 ONTAP 版本支援、且您要升級的替換系統不受支援、請參閱 link:other_references.html["參考資料"] 以連結至_SURE_ Hardware Universe 。
* 此程序僅適用於 AFF A200 、 AFF A220 、 AFF C190 、 FAS2620 、 FAS2720 、 AFF A700 和 FAS9000 系統。如需升級至 AFF A150 、 FAS2820 、 AFF A900 或 FAS9500 系統的所有其他控制器機型、請參閱 link:other_references.html["參考資料"] 若要連結至 _ 、請使用「系統控制器置換」命令來升級執行 ONTAP 9.8 或更新版本的控制器硬體、以及 _ 使用 Aggregate 重定位來手動升級執行 ONTAP 9.8 或更新版本內容的控制器硬體。
* 支援高速線路電源（200V至240V）的支援僅有支援FAS900和FAS9500系統。AFF如果AFF 您的FASA700或FAS9000系統是以低線電源（100V至120V）執行、則在AFF 使用此程序之前、您必須先將該功能轉換成使用該功能的電源供應器或FAS9000輸入電源。
* 如果您是從 AFF A200 、 AFF A220 、 AFF C190 、 FAS2620 、 FAS2720 、 AFF A700 或 FAS9000 系統停機、您可以移動儲存設備或聯絡技術支援部門、來升級控制器硬體。請參閱 link:other_references.html["參考資料"] 若要透過移動磁碟區或儲存設備連結至_Upgrade。




== 自動化控制器升級程序

此程序提供自動化程序的步驟、此程序使用自動磁碟指派和網路連接埠連線檢查來簡化控制器升級體驗。
