---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/install_a900_nvs_and_controller_on_node2.html 
keywords: install, NVRAM, aff, a900, node2, controller, module 
summary: ARL控制器升級程序期間、關於Ar4A900 NVRAM模組和控制器模組的安裝說明AFF 。 
---
= 在AFF 節點2上安裝E4A900 NVRAM模組和控制器模組
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您必須在AFF 節點2上安裝收到的用於升級的EsceA900 NVRAM模組和控制器模組。節點2是位於機箱右側的控制器B、可從系統背面查看控制器。

如果您尚未接地、請正確接地。



== 安裝AFF VA900 NVRAM模組

請使用下列程序、將AFF E4A900 NVRAM模組安裝在節點2的插槽6中。

.步驟
. 將NVRAM模組對齊插槽6中機箱開孔的邊緣。
. 將NVRAM模組輕推入插槽、直到帶有字母和編號的I/O CAM栓開始與I/O CAM銷接合、然後將I/O CAM栓完全推入、將NVRAM模組鎖定到位。




== 在AFF 節點2中安裝E4A900控制器模組。

請使用下列程序、在AFF 節點2中安裝EsceA900控制器模組。

.步驟
. 將控制器模組的一端對準機箱中的托架B、然後將控制器模組輕推至系統的一半。
+

TIP: 機箱標籤位於控制器模組正上方的機箱上。

+

NOTE: 在程序稍後指示您將控制器模組完全插入機箱之前、請勿將其完全插入機箱。

. 將管理和主控台連接埠連接至節點2控制器模組。
+

NOTE: 由於機箱已開啟電源、因此節點2一旦完全就位、就會立即開始開機。為避免節點2開機、建議您先將主控台和管理纜線連接至節點2控制器模組、再將控制器模組完全插入插槽。

. 將控制器模組穩固地推入機箱、直到它與中間板完全接入。
+
控制器模組完全就位時、鎖定鎖定鎖定會上升。

+

WARNING: 為避免損壞連接器、請勿在將控制器模組滑入機箱時過度施力。

. 只要模組就位、請立即連接序列主控台、並準備好中斷節點1的自動開機。
. 中斷自動開機之後、node2會在載入程式提示字元停止。如果您未準時中斷自動開機、且節點2開始開機、請等待提示、然後按* Ctrl-C*進入開機功能表。節點停止在開機功能表後、請使用選項「8」重新啟動節點、並在重新開機期間中斷自動開機。

