---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/move_non_root_aggr_nas_lifs_node1_from_node2_to_upgraded_node1.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2 
summary: 使用 ARL 將同一機箱中的控制器機型升級時、請確認 node2 上的 node1 NAS 資料生命體已從 node2 重新定位至 node1 。 
---
= 將節點1擁有的非根Aggregate和NAS資料lifs從節點2移至升級的節點1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在您驗證 node1 上的網路組態、並在將 node2 的集合體重新放置到 node1 之前、請先確認屬於 node1 的 NAS 資料生命體目前位於 node2 上、已從 node2 重新放置到 node1 。您還必須驗證節點1上是否存在SAN lifs。

.關於這項工作
在升級過程中、遠端LIF會處理SAN LUN的流量。在升級期間、移轉SAN LIF對於叢集或服務健全狀況並不必要。除非需要將SAN LIF對應至新連接埠、否則不會移動SAN LIF。將節點1上線後、您必須確認該生命區是否正常、並位於適當的連接埠上。

.步驟
. 恢復重新定位作業：
+
「系統控制器更換恢復」

+
系統會執行下列工作：

+
--
** 叢集仲裁檢查
** 系統ID檢查
** 映像版本檢查
** 目標平台檢查
** 網路連線能力檢查


--
+
此作業會在網路連線能力檢查的這個階段暫停。

. 執行網路連線檢查：
+
「網路連接埠可連線性show -node1」

+
確認所有連接的連接埠（包括介面群組和VLAN連接埠）都顯示為「OK（正常）」狀態。

. 若要將 AFF A800 升級至 AFF A70 或 AFF A90 、您必須重新指派 FCP SAN 生命體。對於所有其他系統升級、請前往 <<resume_relocation_step4,步驟4.>>：
+
.. 將用於 FCP 或 FC-NVMe 資料存取的 FCP SAN 生命體重新指派給正確的主連接埠：
+
`network interface show -vserver <vserver_hosting_fcp_lifs>`

.. 對於目前節點為升級節點 1 的生命週期、而目前的連接埠會將「狀態 oper 」報告為「 - 」（因為連接埠存在於 AFF A800 節點上、但不存在於 AFF A90 節點上）、請先修改目前的連接埠、然後再將其上線。
+
驗證是否已建立實體連線至需要移動 FC LIF 的 FC 目標連接埠：

+
... 將LIF狀態設為「向下」：
+
`network interface modify -vserver <vserver_name> -lif <lif_name>  -status-admin down`

... 修改 LIF 的主連接埠：
+
`network interface modify -vserver <vserver_name> -lif <lif_name> - home-node <node1> -home-port <FC_target_port>`

... 將 LIF 狀態設定為「 UP 」：
+
`network interface modify -vserver <vserver> -lif <lif_name>  -status-admin up`





+
對節點 1 上的每個主目錄 FC SAN LIF 重複執行子步驟 a 和 b 。

. [[resume_gress_step4]] 恢復重新定位作業：
+
「系統控制器更換恢復」

+
系統會執行下列檢查：

+
--
** 叢集健全狀況檢查
** 叢集LIF狀態檢查


--
+
執行這些檢查之後、系統會將節點1擁有的非根Aggregate和NAS資料lifs重新定位至新節點1。

+
資源重新配置完成後、控制器更換作業會暫停。

. 檢查集合體重新配置和NAS資料LIF移動作業的狀態：
+
「System Controller replace show-details」（系統控制器取代顯示詳細資料

+
如果控制器更換程序暫停、請檢查並修正錯誤（如果有）、然後發出「推入」以繼續操作。

. 如有必要、請還原並還原任何已移轉的生命。列出任何已移出的生命生命：
+
「叢集控制器更換網路置換介面show」

+
如果有任何生命期被移除、請將主節點還原回節點1：

+
「叢集控制器更換網路置換介面還原主節點」

. 繼續作業、以提示系統執行必要的POST檢查：
+
「系統控制器更換恢復」

+
系統會執行下列POST檢查：

+
** 叢集仲裁檢查
** 叢集健全狀況檢查
** 集合體重建檢查
** Aggregate狀態檢查
** 磁碟狀態檢查
** 叢集LIF狀態檢查
** Volume檢查



