---
sidebar: sidebar 
permalink: /upgrade-arl-auto-affa900/move_non_root_aggr_and_nas_data_lifs_back_to_node2.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2 
summary: 驗證節點1上的節點2的NAS資料LIF在AFF 進行從節點1到節點2 AFF 的升級時、是否已從節點1重新定位至節點2。 
---
= 將非根Aggregate和NAS資料lifs移回節點2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在驗證節點2上的網路組態之後、在將Aggregate從節點1重新定位至節點2之前、您必須驗證屬於節點2的NAS資料lifs目前位於節點1上、是否已從節點1重新定位至節點2。您還必須驗證節點2上是否存在SAN lifs。

.關於這項工作
在升級過程中、遠端LIF會處理SAN LUN的流量。在升級期間、移轉SAN LIF對於叢集或服務健全狀況並不必要。除非需要將SAN LIF對應至新連接埠、否則不會移動SAN LIF。將node2聯機後，必須驗證該生命段是否正常且位於適當的端口上。

.步驟
. 恢復重新定位作業：
+
「系統控制器更換恢復」

+
系統會執行下列工作：

+
--
** 叢集仲裁檢查
** 系統ID檢查
** 映像版本檢查
** 目標平台檢查
** 網路連線能力檢查


--
+
此作業會在網路連線能力檢查的這個階段暫停。

. 恢復重新定位作業：
+
「系統控制器更換恢復」

+
系統會執行下列檢查：

+
--
** 叢集健全狀況檢查
** 叢集LIF狀態檢查


--
+
執行這些檢查之後、系統會將非根集合體和NAS資料lip重新定位回節點2、節點2現在正在AFF 執行於E4A900或FAS9500控制器上。

+
資源重新配置完成後、控制器更換作業會暫停。

. 檢查集合體重新配置和NAS資料LIF移動作業的狀態：
+
「System Controller replace show-details」（系統控制器取代顯示詳細資料

+
如果控制器更換程序暫停、請檢查並修正錯誤（如果有）、然後發出「推入」以繼續操作。

. 如有必要、請還原並還原任何已移轉的生命。列出任何已移出的生命生命：
+
「叢集控制器更換網路置換介面show」

+
如果有任何生命段被移除、請將主節點還原回節點2：

+
「叢集控制器更換網路置換介面還原主節點」

. 繼續作業、以提示系統執行必要的POST檢查：
+
「系統控制器更換恢復」

+
系統會執行下列POST檢查：

+
** 叢集仲裁檢查
** 叢集健全狀況檢查
** 集合體重建檢查
** Aggregate狀態檢查
** 磁碟狀態檢查
** 叢集LIF狀態檢查
** Volume檢查



