---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/overview_of_the_arl_upgrade.html 
keywords: overview, arl, upgrade, owner, controller, hardware 
summary: 瞭解AFF 如何AFF 執行從NetApp A700升級到Ar900 ARL控制器的程序。 
---
= ARL升級總覽
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在使用ARL升級節點之前、您應該先瞭解程序的運作方式。在本內容中、程序分為幾個階段。



== 升級節點配對

若要升級節點配對、您需要準備原始節點、然後在原始節點和新節點上執行一系列步驟。然後您可以取消委任原始節點。



== ARL升級順序總覽

在程序期間、您可以使用更換的控制器硬體（一次一個控制器）來升級原始控制器硬體、並利用HA配對組態來重新配置非根集合體的擁有權。所有非根Aggregate都必須經過兩次重新定位、才能到達最終目的地、這是正確的升級節點。

每個Aggregate都有一個擁有者和目前擁有者。主擁有者是該集合體的實際擁有者、而目前擁有者則是暫時擁有者。

下表說明您在每個階段中執行的高層工作、以及階段結束時的集合擁有權狀態。程序稍後會提供詳細步驟：

[cols="35,65"]
|===
| 階段 | 步驟 


| link:stage_1_index.html["階段1：準備升級"]  a| 
在第2階段期間、您會將節點1非根Aggregate和NAS資料lifs重新部署至節點2。此程序大部分是自動化的；此作業會暫停、以便您檢查其狀態。您必須手動恢復作業。如果需要、您可以重新部署故障或被否決的集合體。您必須記錄必要的node1資訊、以便稍後在程序中使用、然後交換對應的node1控制器和NVRAM模組、淘汰node1、並在升級的node1上執行netboot。

第1階段結束時的Aggregate所有權：

* node1是node1集合體的主擁有者和目前擁有者
* node2是node2 Aggregate的主擁有者和目前擁有者




| link:stage_2_index.html["第2階段：從節點1重新部署資源、並淘汰AFF EsceA700或FAS9000節點1"]  a| 
在第2階段期間、您會將節點1非根Aggregate和NAS資料lifs重新部署至節點2。此程序大部分是自動化的；此作業會暫停、以便您檢查其狀態。您必須手動恢復作業。如果需要、您可以重新部署故障或被否決的集合體。在淘汰node1之前、請先記錄node1資訊以供稍後的程序使用。您也可以稍後在程序中準備netboot node1。

第2階段結束時的Aggregate所有權：

* node2是node1 Aggregate的目前擁有者
* node2是node2 Aggregate的主擁有者和目前擁有者




| link:stage_3_index.html["第3階段：使用AFF 支援E4A900或FAS9500控制器和NVRAM模組的開機節點1"]  a| 
在第3階段期間、您會使用升級的控制器和NVRAM模組來開機node1、並驗證升級的node1安裝。如果您使用的是NetApp Volume Encryption（NVE）、則會還原金鑰管理程式組態。您也可以將node1非根Aggregate和NAS資料lIF從node2重新部署到升級的node1、並確認節點1上存在SAN lIF。

第3階段結束時的Aggregate所有權：

* 升級AFF 版的E4A900或FAS9500節點1是node1 Aggregate的主擁有者和目前擁有者
* node2是node2 Aggregate的主擁有者和目前擁有者




| link:stage_4_index.html["階段4：從節點2重新部署資源、並淘汰節點2"]  a| 
在第4階段期間、您將非根Aggregate和NAS資料lifs從節點2重新部署到升級的節點1、然後淘汰節點2。

第4階段結束時的Aggregate所有權：

* 升級的node1是原屬於node1的Aggregate的主擁有者和目前擁有者
* 升級的node1是node2 Aggregate的目前擁有者




| link:stage_5_index.html["第5階段：在AFF 節點2上安裝EFASA900或FAS9500 NVRAM和控制器模組"]  a| 
在第5階段期間、您會安裝新的NVRAM和控制器模組、這些模組會針對升級的node2、然後再安裝netboot node2。

第5階段結束時的Aggregate所有權：

* 升級的node1是原屬於node1的Aggregate的主擁有者和目前擁有者。
* 升級的node2是原屬於node2的Aggregate的主擁有者和目前擁有者。




| link:stage_6_index.html["第6階段：使用AFF E4A900或FAS9500控制器和NVRAM模組來開機節點2"]  a| 
在第6階段期間、您會使用升級的控制器和NVRAM模組來開機node2、並驗證升級的node2安裝。如果您使用NVE、則會還原金鑰管理程式組態。您也可以將節點1非根Aggregate和NAS資料lifs從節點1重新部署到升級的節點2、並確認節點2上存在SAN lifs。



| link:stage_7_index.html["第7階段：完成升級"]  a| 
在第7階段期間、您會確認新節點已正確設定、如果新節點已啟用加密、則您可以設定及設定儲存加密或NVE。您也應該取消委任舊節點、然後恢復SnapMirror作業。

|===