---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/prepare_nodes_for_upgrade.html 
keywords: preparing, prepare, nodes, upgrade, stage 1, prechecks, old, system, chassis, disk, disks 
summary: 使用 ARL 升級同一機箱中的控制器機型時、請準備節點並執行一系列預先檢查。 
---
= 準備節點以進行升級
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
控制器更換程序從一系列預先檢查開始。您也可以收集原始節點的相關資訊、以便稍後在程序中使用、並視需要判斷使用中的自我加密磁碟機類型。

.步驟
. 列出在舊控制器上執行的服務處理器（ SP ）或主機板管理控制器（ BMC ）韌體版本：
+
`service-processor show`

+
確認您擁有支援的 SP 或 BMC 韌體版本：

+
[cols="30,35,35"]
|===
| 舊控制器 | SP 或 BMC | 最低韌體版本 


| 解答800 AFF | BMC | 10.9 


| VA220 AFF | BMC | 11.9P1 


| 解答200 AFF | SP | 5.11P1 


| C190 AFF | BMC | 11.9P1 


| FAS2620 | SP | 5.11P1 


| FAS2720 | BMC | 11.9P1 
|===
. 在ONTAP 指令行的進階權限模式中輸入下列命令、開始控制器更換程序：
+
"進階權限"

+
「System Controller replace start -nodes _norme_names」（系統控制器取代start節點_node_names）

+
您會看到類似下列範例的輸出。輸出會顯示叢集上執行的 ONTAP 版本：

+
....
Warning:
1. Current ONTAP version is 9.15.1

2. Verify that NVMEM or NVRAM batteries of the new nodes are charged, and charge them if they are not. You need to physically check the new nodes to see if the NVMEM or NVRAM  batteries are charged. You can check the battery status either by connecting to a serial console or using SSH, logging into the Service Processor (SP) or Baseboard Management Controller (BMC) for your system, and use the system sensors to see if the battery has a sufficient charge.

Attention: Do not try to clear the NVRAM contents. If there is a need to clear the contents of NVRAM, contact NetApp technical support.

3. If a controller was previously part of a different cluster, run wipeconfig before using it as the replacement controller.

4. Note: This is not a MetroCluster configuration. Controller replacement supports only ARL based procedures.

Do you want to continue? {y|n}: y
....
. 選取「y」。您會看到下列輸出：
+
....
Controller replacement operation: Prechecks in progress.
Controller replacement operation has been paused for user intervention.
....
+
在預先檢查階段、系統會在背景執行下列檢查清單。

+
[cols="35,65"]
|===
| 預先檢查 | 說明 


| 叢集健全狀況檢查 | 檢查叢集中的所有節點、以確認其正常運作。 


| Aggregate重新配置狀態檢查 | 檢查集合體重新配置是否已在進行中。如果另一個集合體重新配置正在進行中、則檢查會失敗。 


| 模型名稱檢查 | 檢查此程序是否支援控制器機型。如果不支援模型、工作就會失敗。 


| 叢集仲裁檢查 | 檢查要替換的節點是否處於仲裁狀態。如果節點不在仲裁中、則工作會失敗。 


| 映像版本檢查 | 檢查要更換的節點是否執行相同版本ONTAP 的Sof Sof。如果ONTAP 不相同的版本、工作就會失敗。新節點上ONTAP 必須安裝相同版本的還原9.x、並安裝在原始節點上。如果新節點ONTAP 安裝了不同版本的支援功能、則安裝新的控制器之後、您必須以網路開機。如需有關如何升級ONTAP 功能的說明、請參閱 link:other_references.html["參考資料"] 連結至_Upgrade ONTAP 


| HA狀態檢查 | 檢查要更換的兩個節點是否都是高可用度（HA）配對組態。如果控制器未啟用儲存容錯移轉、工作就會失敗。 


| Aggregate狀態檢查 | 如果要替換自己的Aggregate、但這些節點不是主擁有者、則工作會失敗。節點不應擁有任何非本機Aggregate。 


| 磁碟狀態檢查 | 如果要更換的任何節點有遺失或故障的磁碟、則工作會失敗。如果有任何磁碟遺失、請參閱 link:other_references.html["參考資料"] 若要使用CLI連結至_磁碟與集合管理、使用CLI進行_邏輯儲存管理、以及_高可用度管理_、以設定HA配對的儲存設備。 


| 資料LIF狀態檢查 | 檢查要更換的任何節點是否具有非本機資料生命量。節點不應包含任何非主擁有者的資料LIF。如果其中一個節點包含非本機資料LIF、則工作會失敗。 


| 叢集LIF狀態 | 檢查兩個節點的叢集生命點是否都正常運作。如果叢集LIF已關閉、工作就會失敗。 


| ASUP狀態檢查 | 如果AutoSupport 未設定顯示功能通知、工作就會失敗。在AutoSupport 開始更換控制器之前、您必須先啟用支援功能。 


| CPU使用率檢查 | 檢查要更換的任何節點的CPU使用率是否超過50%。如果CPU使用率在一段相當長的時間內超過50%、工作就會失敗。 


| Aggregate Reconstruction Check | 檢查是否在任何資料集合體上進行重建。如果正在進行Aggregate重建、工作就會失敗。 


| 節點關聯工作檢查 | 檢查是否有任何節點關聯工作正在執行。如果節點關聯工作正在執行、則檢查會失敗。 
|===
. 在控制器更換作業開始並完成預先檢查之後、作業會暫停、以便您收集稍後在控制器升級程序中可能需要的輸出資訊。
. 依照系統主控台的控制器更換程序指示、執行下列命令集。
+
從連接至每個節點的序列連接埠執行命令、分別執行及儲存命令的輸出：

+
** 「Vserver服務名稱服務DNS節目」
** `network interface show -curr-node _local_ -role cluster,intercluster,node-mgmt,cluster-mgmt,data`
** `network port show -node _local_ -type physical`
** `service-processor show -node _local_ -instance`
** `network fcp adapter show -node _local_`
** `network port ifgrp show -node _local_`
** `system node show -instance -node _local_`
** `run -node _local_ sysconfig`
** `run -node local sysconfig -ac`
** `run -node local aggr status -r`
** `vol show -fields type`
** `run local aggr options _data_aggregate_name_`
** `vol show -fields type , space-guarantee`
** `storage aggregate show -node _local_`
** `volume show -node _local_`
** 「torage Array config show -switch_switch_name_」
** `system license show -owner _local_`
** 「torage加密磁碟顯示」
** 「安全金鑰管理程式內建show Backup」
** 「安全關鍵經理外部秀」
** 「安全金鑰管理程式外部顯示狀態」
** `network port reachability show -detail -node _local_`
+

NOTE: 如果使用內建金鑰管理程式的 NetApp Volume Encryption （ NVE ）或 NetApp Aggregate Encryption （ NAE ）正在使用中、請在稍後的程序中、將金鑰管理程式複雜密碼保留為完成金鑰管理程式重新同步。



. 如果您的系統使用自我加密磁碟機、請參閱知識庫文章 https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["如何判斷磁碟機是否已通過 FIPS 認證"^] 以判斷您要升級的HA配對所使用的自我加密磁碟機類型。支援兩種自我加密磁碟機的支援ONTAP ：
+
--
** FIPS認證的NetApp儲存加密（NSE）SAS或NVMe磁碟機
** 非FIPS自我加密NVMe磁碟機（SED）


[NOTE]
====
您無法在同一個節點或HA配對上混用FIPS磁碟機與其他類型的磁碟機。

您可以在同一個節點或HA配對上混合使用SED與非加密磁碟機。

====
https://docs.netapp.com/us-en/ontap/encryption-at-rest/support-storage-encryption-concept.html#supported-self-encrypting-drive-types["深入瞭解支援的自我加密磁碟機"^]。

--




== 如果ARL預先檢查失敗、請修正Aggregate所有權

如果Aggregate Status Check失敗、您必須將合作夥伴節點擁有的Aggregate傳回主擁有者節點、然後再次啟動預先檢查程序。

.步驟
. 將合作夥伴節點目前擁有的Aggregate傳回主擁有者節點：
+
「torage Aggregate regate or搬 移開始節點_source_node_-destination-node_-aggregation-list *」

. 驗證node1和node2是否仍擁有當前擁有者（但不是主擁有者）的Aggregate：
+
「torage Aggregate show -nodes _norme_name_-is主目錄錯誤欄位擁有者名稱、主目錄名稱、狀態」

+
以下範例顯示當節點同時是Aggregate的目前擁有者和主擁有者時、命令的輸出：

+
[listing]
----
cluster::> storage aggregate show -nodes node1 -is-home true -fields owner-name,home-name,state
aggregate   home-name  owner-name  state
---------   ---------  ----------  ------
aggr1       node1      node1       online
aggr2       node1      node1       online
aggr3       node1      node1       online
aggr4       node1      node1       online

4 entries were displayed.
----




=== 完成後

您必須重新啟動控制器更換程序：

「System Controller replace start -nodes _norme_names」（系統控制器取代start節點_node_names）



== 授權

叢集中的每個節點都必須有自己的 NetApp 授權檔案（ NLF ）。

如果您沒有 NLF 、則叢集中目前授權的功能可用於新的控制器。不過、在控制器上使用未經授權的功能可能會使您不遵守授權合約、因此您應該在升級完成後、為新控制器安裝 NLF 。

請參閱 link:other_references.html["參考資料"] 連結至可 NetApp 支援網站 取得 NLF 的 _NLF 。NLF 可在 _ 軟體授權 _ 下方的 _ 我的支援 _ 區段中找到。如果網站沒有您需要的 NLF 、請聯絡您的 NetApp 銷售代表。

如需授權的詳細資訊、請參閱 link:other_references.html["參考資料"] 連結至_System Administration Reference。
