---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html 
keywords: relocating, non-root, aggregates, nas, data, lif, node1, node2, NVRAM, controller, module, modules 
summary: 將非根集合體和 NAS 資料生命體從 node1 移至 node2 、並在使用 ARL 升級相同機箱中的控制器機型時、還原 node1 的資源。 
---
= 將節點1擁有的非根Aggregate和NAS資料lifs重新部署到節點2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您必須先將非根集合體和 NAS 資料生命體從 node1 移回 node2 、然後才能將 node1 資源還原回替換系統上執行的 node1 上、才能將 node1 取代為系統升級的替換模組。此程序大部分是自動化的；此作業會暫停、以便您檢查其狀態。

.開始之前
當您開始工作時、該作業應該已經暫停；您必須手動恢復該作業。

.關於這項工作
在升級過程中、遠端LIF會處理SAN LUN的流量。您不需要在升級期間移動SAN LIF來維持叢集或服務健全狀況。將 node1 作為替換系統上線後、您必須確認生命體健全且位於適當的連接埠上。


NOTE: 不會修改集合體和lifs的主擁有者、只會修改目前擁有者。

.步驟
. 恢復Aggregate重新定位和NAS資料LIF移動作業：
+
「系統控制器更換恢復」

+
所有非根Aggregate和NAS資料lifs都會從節點1移轉至節點2。

+
此作業會暫停、以便您確認是否已將所有節點1非根Aggregate和非SAN資料lIF移轉至節點2。

. 檢查集合體重新配置和NAS資料LIF移動作業的狀態：
+
「System Controller replace show-details」（系統控制器取代顯示詳細資料

. 在作業仍暫停的情況下、確認節點2上的所有非根Aggregate狀態均處於線上狀態：
+
「torage Aggregate show -node2_-state online -root假」

+
以下範例顯示節點2上的非根Aggregate處於線上狀態：

+
[listing]
----
cluster::> storage aggregate show -node node2 state online -root false

Aggregate  Size     Available  Used%  State  #Vols  Nodes  RAID Status
---------  -------  ---------  -----  ------ -----  ------ --------------
aggr_1     744.9GB  744.8GB    0%     online     5  node2  raid_dp,normal
aggr_2     825.0GB  825.0GB    0%     online     1  node2  raid_dp,normal
2 entries were displayed.
----
+
如果Aggregate已離線或成為節點2上的外部節點、請在節點2上使用下列命令將其上線、每個Aggregate一次：

+
'線上儲存Aggregate -Agggr_name_'

. 在節點2上使用下列命令並檢查其輸出、以確認節點2上的所有磁碟區都已上線：
+
「Volume show -node2_-state offline」

+
如果節點2上有任何磁碟區離線、請在節點2上使用下列命令將其上線、每個磁碟區一次：

+
"Volume online -vserver _vserver_name_-volume _volume _name_"

+
與此命令一起使用的"_vserver_name_"可在先前的"volume show"命令輸出中找到。



. [[step5]]如果有任何生命週期中斷、請使用下列命令將生命週期的管理狀態設為「up」（上）、每個LIF一次：
+
「網路介面修改-vserver _vserver_name_-lif_lif_name_-home-nodeame_-stue-admin up」


