---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/ensure_controllers_set_up_correctly.html 
keywords: set up, controllers, correctly, ha pair, lif, aggregate, node, failover 
summary: 啟用HA配對、驗證node3和node4儲存設備存取、並在執行ONTAP 《支援升級》9.8或更新版本的控制器上進行手動ARL升級後、確認Aggregate擁有權。 
---
= 確認新的控制器已正確設定
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
若要確認正確的設定、請啟用 HA 配對。您也可以驗證 node3 和 node4 是否可以存取彼此的儲存設備、以及它們是否都不擁有屬於叢集上其他節點的資料生命週期。此外、您還會確認 node3 擁有 node1 的集合體、 node4 擁有 node2 的集合體、而且兩個節點的磁碟區都在線上。

.步驟
. 在其中一個節點上輸入下列命令以啟用儲存容錯移轉：
+
「torage容錯移轉修改啟用的true -node3_」

. 確認已啟用儲存容錯移轉：
+
「容錯移轉顯示」

+
下列範例顯示啟用儲存容錯移轉時命令的輸出：

+
[listing]
----
cluster::> storage failover show
                              Takeover
Node           Partner        Possible State Description
-------------- -------------- -------- ------------------
node3          node4          true     Connected to node4
node4          node3          true     Connected to node3
----
. 請採取下列其中一項行動：
+
|===
| 如果叢集是... | 說明 


| 雙節點叢集 | 在任一節點上輸入下列命令、即可啟用叢集高可用度：「cluster ha modify -configured true」 


| 具有兩個以上節點的叢集 | 前往 <<man_ensure_setup_Step4,步驟4.>>。 
|===
. [[man_ensure_setup_Step4]]輸入下列命令並檢查輸出、確認node3和node4屬於同一個叢集：
+
「叢集展示」

. 輸入下列命令並檢查輸出、確認node3和node4能夠存取彼此的儲存設備：
+
「torage容錯移轉顯示欄位local-missing磁碟、合作夥伴遺失磁碟」

. 輸入下列命令並檢查輸出、以確認節點3和節點4都不擁有叢集中其他節點所擁有的資料lifs主目錄：
+
「網路介面展示」

+
如果node3或node4擁有叢集中其他節點所擁有的資料lifs主目錄、請使用「network interface revert」命令、將資料lifs還原為其主目錄擁有者。

. 驗證node3是否擁有node1的集合體、以及node4是否擁有node2的集合體：
+
"torage Aggregate show -Owner-name _node3_'"storage aggregate show -Owner-name _node4_"

. 判斷是否有任何磁碟區離線：
+
「Volume show -node3_-state offline」（Volume show -node4_-state offline）

. 如果有任何磁碟區離線、請將它們與您在中擷取的離線磁碟區清單進行比較  link:prepare_nodes_for_upgrade.html#man_prepare_nodes_step19["步驟19（d）"] 在_準備要升級的節點_中、輸入下列命令（針對每個Volume一次）、並視需要將任何離線磁碟區上線：
+
"Volume online -vserver _vserver_name_-volume _volume _name_"

. 為每個節點輸入下列命令、以安裝新節點的新授權：
+
「系統授權新增-授權碼_license代碼、license代碼、license代碼、license代碼..._」

+
授權代碼參數接受28個大寫字母字元金鑰的清單。您可以一次新增一個授權、也可以一次新增多個授權、每個授權金鑰都以逗號分隔。

. [[unset_mastwait_manipal]]如果在組態中使用自我加密磁碟機、且您已設定 `kmip.init.maxwait` 變數至 `off` （例如、in link:install_boot_node3.html#man_install3_step16["步驟16"] 在_Install and boot node3_）中、您必須取消設定變數：
+
「et diag; systemShell -node_node_name_-command sudo kenv -u -p kmip.init.maxwait`」

. 若要從原始節點移除所有舊授權、請輸入下列其中一個命令：
+
「系統授權清理-未使用的-過期」「系統授權刪除-序號_normite_sSerial_number_-套件_licensee_package_」

+
** 若要刪除所有過期的授權、請輸入：
+
「系統授權清除-過期」

** 若要刪除所有未使用的授權、請輸入：
+
「系統授權清理-未使用」

** 若要從叢集刪除特定授權、請在節點上輸入下列命令：
+
「系統授權刪除-序號_node1_sSerial_number_-package *」「系統授權刪除-序號_node2_sSerial_number_-package *」

+
將顯示下列輸出：

+
[listing]
----
Warning: The following licenses will be removed:
<list of each installed package>
Do you want to continue? {y|n}: y
----
+
輸入「y」以移除所有套件。



. 輸入下列命令並檢查其輸出、確認授權已正確安裝：
+
「系統授權展示」

+
您可以將輸出與擷取的輸出進行比較 link:prepare_nodes_for_upgrade.html#man_prepare_nodes_step30["步驟30"] （_準備節點以進行升級_）。

. 在兩個節點上執行下列命令來設定SP：
+
「系統服務處理器網路修改-node_node_name_」

+
前往 link:other_references.html["參考資料"] 如需SP和_SUR9 ONTAP 命令的相關資訊、請連結至_System Administration Reference（系統管理參考）：Manual Page Reference（手冊頁參考）_、以取得有關「系統服務-處理器網路修改」命令的詳細資訊。

. 如果您要在新節點上設定無交換器叢集、請前往 link:other_references.html["參考資料"] 若要連結至_網路支援站台_、請遵循_移轉至雙節點無交換器叢集_中的指示。


.完成後
如果節點3和節點4上已啟用儲存加密、請完成中的步驟 link:set_up_storage_encryption_new_controller.html["在新的控制器模組上設定儲存加密"]。否則、請完成中的步驟 link:decommission_old_system.html["取消委任舊系統"]。
