---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/index.html 
keywords: controller, aggregate, relocation, flexarray, manual, upgrade, metrocluster 
summary: 使用手動ARL升級程序來升級執行ONTAP 不含更新版本的控制器硬體、重新定位非根集合體的擁有權。 
---
= 總覽
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
本程序說明如何針對下列系統組態、使用Aggregate重新定位（ARL）來升級控制器硬體：

[cols="20,20,60"]
|===
| 方法 | 版本ONTAP | 支援的系統 


| 使用ARL手動升級 | 9.8或更新版本  a| 
* 從系統到系統FAS FAS
* 將系統支援至採用「虛擬化軟體」或「V系列」系統的系統FAS FlexArray
* 從系統到系統AFF AFF
* 系統若採用FlexArray 「支援虛擬化的軟體FAS 」或「V系列」系統、則只要配備FlexArray 「支援虛擬化的軟體」或「V系列」系統的系統沒有陣列LUN即可。
* V系列系統移轉至採用FlexArray 「虛擬化軟體」或「V系列」系統的系統


|===
在過程中、您會使用更換的控制器硬體來升級原始的控制器硬體、以重新定位非根集合體的擁有權。您可以多次從節點移轉Aggregate至節點、以確認在整個升級程序中、至少有一個節點正在處理來自集合體的資料。您也可以移轉資料邏輯介面（LIF）、並在繼續進行時將新控制器上的網路連接埠指派給介面群組。


NOTE: 在本文檔中，原始節點稱爲_node1_和_node2_，新節點稱爲_node3_和_node4_。在上述過程中、node1會由node3取代、node2則會由node4取代。術語_node1_、_node2_、_node3_和_node4_僅用於區分原始節點和新節點。執行此程序時、您必須取代原始節點和新節點的真實名稱。但是實際上、節點名稱並未變更：節點3的名稱為node1、而節點4的名稱為node2（控制器硬體已升級）。本文件使用「採用FlexArray NetApp虛擬化軟體的系統」一詞、來指屬於這些新平台的系統。它使用術語_V系列system_來參照可附加至儲存陣列的個別硬體系統

.重要資訊：
* 此程序相當複雜、假設您具備進階ONTAP 的功能不完整的管理技能。您也必須閱讀並瞭解 link:guidelines_upgrade_with_arl.html["使用ARL升級控制器的準則"] 和 link:arl_upgrade_workflow.html["ARL升級工作流程"] 開始升級之前的章節。
* 此程序假設更換的控制器硬體是新的、而且尚未使用。此程序不包含使用wpeconfig命令準備已用控制器所需的步驟。如果先前使用替換控制器硬體、尤其是控制器以Data ONTAP 7-Mode執行時、您必須聯絡技術支援部門。
* 您可以使用此程序來升級具有兩個以上節點之叢集中的控制器硬體、不過您需要針對叢集中的每個高可用度（HA）配對分別執行此程序。
* 本程序適用於FAS 包含AFF 「支援整合式虛擬化軟體」的各種系統、V系列系統、支援各種系統。FlexArray如果安裝了必要的授權、則可將在發行完版本號為Solide9之後的系統附加至儲存陣列。FAS ONTAP現有的V系列系統在ONTAP 支援方面、請參考資料表9。如需儲存陣列和V系列機型的相關資訊、請參閱 link:other_references.html["參考資料"] 若要連結至_ESUR__ Hardware Universe 、請參閱_V系列支援對照表_。


* 除了非MetroCluster組態之外、此程序也適用於MetroCluster 執行ONTAP 「版本號」的Fabric支援4節點和8節點組態。
+
** 如需MetroCluster 執行ONTAP 效能不符合要求的更新版本、請參閱 link:other_references.html["參考資料"] 若要連結至_使用Aggregate Relocation以手動升級執行ONTAP VMware 9.7或更早版本的控制器硬體。
** 如需MetroCluster 瞭解有關Fabric MetroCluster 支援組態的支援IP組態和其他升級選項、請前往 link:other_references.html["參考資料"] 連結至_E不明MetroCluster Upgrade and Expansion內容。



