---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/index.html 
keywords: controller, aggregate, relocation, manual, upgrade, metrocluster 
summary: 使用手動ARL升級程序來升級執行ONTAP 不含更新版本的控制器硬體、重新定位非根集合體的擁有權。 
---
= 了解 ARL 升級程序
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


此流程說明如何在執行 ONTAP 9.8 或更高版本的系統上使用手動聚合重定位 (ARL) 升級控制器硬體。

如果您正在執行以下升級之一，則可以使用此 ARL 程式：

* 從系統到系統FAS FAS
* 從系統到系統AFF AFF
+
您只能升級至相同系列的替換系統：

+
** AFF A 系列系統至 AFF A 系列系統
** AFF C 系列系統至 AFF C 系列系統


* 從系統到系統ASA ASA
+
不支援 ASA 升級至 ASA R2 更換系統。如需將資料從 ASA 移轉至 ASA R2 的相關資訊，請參閱link:https://docs.netapp.com/us-en/asa-r2/install-setup/set-up-data-access.html["啟用從 SAN 主機到 ASA R2 儲存系統的資料存取"^]。

+
您只能升級至相同系列的替換系統：

+
** ASA A 系列系統至 ASA A 系列系統
** ASA C 系列系統至 ASA C 系列系統




在過程中、您會使用更換的控制器硬體來升級原始的控制器硬體、以重新定位非根集合體的擁有權。您可以多次從節點移轉Aggregate至節點、以確認在整個升級程序中、至少有一個節點正在處理來自集合體的資料。您也可以移轉資料邏輯介面（LIF）、並在繼續進行時將新控制器上的網路連接埠指派給介面群組。


NOTE: 在本文檔中，原有節點稱為_node1_和_node2_，新節點稱為_node3_和_node4_。在所述過程中，節點 1 被節點 3 替換，節點 2 被節點 4 取代。術語 _node1_、_node2_、_node3_ 和 _node4_ 僅用於區分原始節點和新節點。按照該過程操作時，您必須替換原始節點和新節點的真實名稱。但實際上，節點的名稱並沒有改變：在控制器硬體升級後，node3 的名稱為 node1，node4 的名稱為 node2。

.重要資訊：
* 此程序相當複雜、假設您具備進階ONTAP 的功能不完整的管理技能。您還必須閱讀並理解link:guidelines_upgrade_with_arl.html["使用 ARL 升級控制器的指南"]和link:arl_upgrade_workflow.html["ARL升級工作流程"]在開始升級之前。
* 此程序假設更換的控制器硬體是新的、而且尚未使用。此程序不包含使用wpeconfig命令準備已用控制器所需的步驟。如果先前使用替換控制器硬體、尤其是控制器以Data ONTAP 7-Mode執行時、您必須聯絡技術支援部門。
* 您可以使用此程序來升級具有兩個以上節點之叢集中的控制器硬體、不過您需要針對叢集中的每個高可用度（HA）配對分別執行此程序。


* 除了非MetroCluster組態之外、此程序也適用於MetroCluster 執行ONTAP 「版本號」的Fabric支援4節點和8節點組態。
+
** 如需MetroCluster 執行ONTAP 效能不符合要求的更新版本、請參閱 link:other_references.html["參考資料"] 若要連結至_使用Aggregate Relocation以手動升級執行ONTAP VMware 9.7或更早版本的控制器硬體。
** 如需MetroCluster 瞭解有關Fabric MetroCluster 支援組態的支援IP組態和其他升級選項、請前往 link:other_references.html["參考資料"] 連結至_E不明MetroCluster Upgrade and Expansion內容。



