---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/install_boot_node4.html 
keywords: node4, install ONTAP, boot, node4, relocate, non-root aggregates, disks 
summary: 在ONTAP 執行ONTAP 更新版本的控制器上、手動進行ARL升級時、請安裝並啟動節點4、並安裝此軟體。 
---
= 安裝及開機節點4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您必須在機架中安裝node4、將node2連線傳輸至node4和開機node4。您也必須重新指派任何節點2備援磁碟、屬於根的任何磁碟、以及先前未重新部署至節點3的任何非根Aggregate。

.關於這項工作
如果節點 4 上安裝的 ONTAP 9 版本與節點 2 上安裝的 ONTAP 9 版本不同，則必須安裝node4之後、請從ONTAP 儲存在Web伺服器上的Image9映像啟動節點3。透過網路啟動節點 4。然後，您可以按照link:prepare_for_netboot.html["準備netboot"] 。

但是，如果 node4 上安裝的 ONTAP 9 與 node2 上安裝的相同或更高版本，則無需透過網路啟動 node4。

[IMPORTANT]
====
* 對於AFF A800或AFF C800控制器升級，在移除節點 2 之前，必須確保機箱中的所有驅動器都牢固地固定在中板上。有關詳細信息，請參閱 link:../upgrade-arl-auto-in-chassis/replace-node1-affa800.html["更換 AFF A800 或 AFF C800 控制器模組"]。
* 如果您要升級具有儲存磁碟的系統，則必須完成整個部分，然後繼續執行下一節link:set_fc_uta_uta2_config_node4.html["在節點4上設定FC或UTA/UTA2組態"] ，在群集提示符下輸入命令。


====
.步驟
. [[man_install4_Step1]]請採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果node4將位於... | 然後... 


| 與節點3分開的機箱 | 前往 <<man_install4_Step2,步驟2>>。 


| 同一個機箱與節點3 | 跳過步驟2和3、前往 <<man_install4_Step4,步驟4.>>。 
|===
. [[man_install4_Step2]]請確定節點4有足夠的機架空間。
+
如果node4與node3位於不同的機箱中、您可以將node4放在與node2相同的位置。如果節點3和節點4位於同一個機箱中、則節點4已位於適當的機架位置。

. 按照節點機型的安裝與設定說明_中的指示、在機架中安裝節點4。
. [[man_install4_stip4]]纜線節點4、將連線從節點2移至節點4。
+
下列參考資料可協助您建立適當的纜線連線。前往 link:other_references.html["參考資料"] 以連結至他們。

+
** node4 平台的_安裝與設定說明_
** 適當的磁碟櫃程序
** _HA 配對管理 _ 文件
+
纜線連接下列連接：

** 主控台（遠端管理連接埠）
** 叢集連接埠
** 資料連接埠
** 叢集與節點管理連接埠
** 儲存設備
** SAN組態：iSCSI乙太網路和FC交換器連接埠


+

NOTE: 您不需要將互連卡/FC_VI卡或互連/FC_VI纜線連線從節點2移至節點4、因為大多數平台機型都有獨特的互連卡機型。

. 請採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果節點4位於... | 然後... 


| 與節點3相同的機箱 | 前往 <<man_install4_Step8,步驟8.>>。 


| 與節點3分開的機箱 | 前往 <<man_install4_Step6,步驟6.>>。 
|===
. [[man_install4_Step6]] 開啟 node4 的電源、然後按 Ctrl-C 存取開機環境提示來中斷開機。
+

NOTE: 當您啟動節點4時、可能會看到下列訊息：

+
[listing]
----
WARNING: The battery is unfit to retain data during a power
         outage. This is likely because the battery is
         discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will
         complete and services will be engaged.
         To override this delay, press 'c' followed by 'Enter'
----
. [[man_install4_stept7]]如果您在步驟6中看到警告訊息、請採取下列行動：
+
.. 檢查可能指出NVRAM電池電量不足以外問題的任何主控台訊息、並視需要採取任何必要的修正行動。
.. 讓電池充電並完成開機程序。
+

WARNING: *不要覆蓋延遲。如果電池無法充電，可能會導致資料遺失。 *



. [[man_install4_Step8]]在維護模式提示下，輸入以下命令：
+
《停止》

+
系統會在開機環境提示字元停止。

. 設定node4 ONTAP 以供使用：
+
「預設值」

. 如果您安裝了 NetApp 儲存加密 (NSE) 驅動器，請執行下列步驟：
+

NOTE: 如果您尚未在程序中稍早完成此作業、請參閱知識庫文章 https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["如何判斷磁碟機是否已通過 FIPS 認證"^] 以判斷使用中的自我加密磁碟機類型。

+
.. 設定 `bootarg.storageencryption.support` 至 `true` 或 `false`：
+
[cols="35,65"]
|===
| 如果下列磁碟機正在使用中… | 然後… 


| 符合 FIPS 140-2 第 2 級自我加密要求的 NSE 磁碟機 | `setenv bootarg.storageencryption.support *true*` 


| NetApp非FIPS SED | `setenv bootarg.storageencryption.support *false*` 
|===
+
[NOTE]
====
您無法在同一個節點或HA配對上混用FIPS磁碟機與其他類型的磁碟機。

您可以在同一個節點或HA配對上混合使用SED與非加密磁碟機。

====
.. 前往特殊開機功能表並選取選項 `(10) Set Onboard Key Manager recovery secrets`。
+
輸入您先前記錄的複雜密碼和備份資訊。請參閱 link:manage_authentication_okm.html["使用 Onboard Key Manager 管理驗證金鑰"]。



. 如果ONTAP 節點4上安裝的版本的資訊與ONTAP 節點2上安裝的版本資訊相同或更新、請輸入下列命令：
+
Boot_ONTAP功能表

. 請採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果您要升級的系統... | 然後... 


| 節點4上沒有正確或最新ONTAP 的版本 | 前往<<man_install4_Step13,步驟13>>。 


| 節點4上有正確或最新版本ONTAP 的資訊 | 前往<<man_install4_Step18,步驟18>>。 
|===
. [[man_install4_Step13]]透過選擇下列其中一項操作來設定網路啟動連線。
+

NOTE: 您必須使用管理連接埠和IP位址做為netboot連線。請勿使用資料LIF IP位址、否則在執行升級時可能會發生資料中斷。

+
[cols="35,75"]
|===
| 如果動態主機組態傳輸協定（DHCP）是... | 然後... 


| 執行中  a| 
在開機環境提示字元中輸入下列命令、即可自動設定連線：「ifconfige0M -auto」



| 未執行  a| 
在開機環境提示字元中輸入下列命令、手動設定連線：
`ifconfig e0M -addr=_filer_addr_ mask=_netmask_ -gw=_gateway_ dns=_dns_addr_ domain=_dns_domain_`

`_filer_addr_` 為儲存系統的IP位址（必填）。
`_netmask_` 是儲存系統的網路遮罩（必填）。
`_gateway_` 是儲存系統的閘道（必填）。
`_dns_addr_` 為網路上名稱伺服器的IP位址（選用）。
`_dns_domain_` 為網域名稱服務（DNS）網域名稱。如果使用此選用參數、則不需要netboot伺服器URL中的完整網域名稱；您只需要伺服器的主機名稱。


NOTE: 您的介面可能需要其他參數。在韌體提示字元中輸入「Help ifconfig」以取得詳細資料。

|===
. 在節點4上執行netboot：
+
[cols="30,70"]
|===
| 適用於... | 然後... 


| FAS / AFF8000系列系統 | “netboot \http://<web_server_ip/path_to_webaccessible_directory>/netboot/kernel` 


| 所有其他系統 | “netboot \http://<web_server_ip/path_to_webaccessible_directory/ontap_version>_image.tgz` 
|===
+
「<path_to_the_web-易於 存取的目錄>」應該會引導您下載「<ONTAP_VERSION >_image.tgz」 link:prepare_for_netboot.html#man_netboot_Step1["步驟1."] 在_Prepare for netboot_一節中。

+

NOTE: 請勿中斷開機。

. 從開機功能表中、選取「Option（7）Install new software first」（選項（7）先安裝新軟體）。
+
此功能表選項會下載新Data ONTAP 的功能表映像、並將其安裝至開機裝置。

+
請忽略下列訊息：

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
本附註適用於Data ONTAP 不中斷營運的更新功能、不適用於控制器升級。

+

NOTE: 請務必使用netboot將新節點更新為所需映像。如果您使用其他方法在新控制器上安裝映像、可能會安裝不正確的映像。此問題適用於ONTAP 所有版本的更新版本。netboot程序與選項結合使用 `(7) Install new software` 清除開機媒體、並在ONTAP 兩個影像分割區上放置相同的版本。

. [[man_install4_step23]如果系統提示您繼續此程序、請輸入y、並在系統提示您輸入套件時、輸入URL：
+
http://<web_server_ip/path_to_web-accessible_directory/ontap_version>_image.tgz`

. 完成下列子步驟：
+
.. 當您看到下列提示時、請輸入「n」跳過備份恢復：
+
[listing]
----
Do you want to restore the backup configuration now? {y|n}
----
.. 當您看到下列提示時、輸入「y」重新開機：
+
[listing]
----
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
----
+
控制器模組會重新開機、但會在開機功能表停止、因為開機裝置已重新格式化、需要還原組態資料。



. [[man_install4_Step18]]選擇維護模式 `5`從啟動選單並輸入 `y`當提示您繼續啟動。
. [[man_install4_Step19]]繼續之前，請前往link:set_fc_uta_uta2_config_node4.html["在節點4上設定FC或UTA/UTA2組態"]對節點上的 FC 或 UTA/UTA2 連接埠進行任何必要的變更。按照這些部分中建議的進行更改，重新啟動節點，然後進入維護模式。
. 輸入以下命令並檢查輸出以找出節點4的系統ID：
+
「展示-A'」

+
系統會顯示節點的系統ID及其磁碟的相關資訊、如下列範例所示：

+
[listing]
----
*> disk show -a
Local System ID: 536881109
DISK         OWNER                       POOL   SERIAL NUMBER   HOME
------------ -------------               -----  -------------   -------------
0b.02.23     nst-fas2520-2(536880939)    Pool0  KPG2RK6F        nst-fas2520-2(536880939)
0b.02.13     nst-fas2520-2(536880939)    Pool0  KPG3DE4F        nst-fas2520-2(536880939)
0b.01.13     nst-fas2520-2(536880939)    Pool0  PPG4KLAA        nst-fas2520-2(536880939)
......
0a.00.0                   (536881109)    Pool0  YFKSX6JG                     (536881109)
......
----
. 重新指派節點2的備援磁碟、屬於根磁碟的磁碟、以及未重新放置到區段前面節點3的任何非根Aggregate link:relocate_non_root_aggr_node2_node3.html["將非根Aggregate從節點2重新部署到節點3"]：
+

NOTE: 如果您的系統上有共享磁碟、混合式Aggregate或兩者、則必須使用正確的 `disk reassign` 下表中的命令。

+
[cols="35,65"]
|===
| 磁碟類型... | 執行命令... 


| 共享磁碟 | "Disk reassign-s"（磁碟重新指派-s）`_node2_sysid_-d _node_sysid_-p _node_sysid_' 


| 無共享 | "Disings disk reassign-s（磁碟重新指派- s）"_node2_sysid_-d _node4_sysid_" 
|===
+
適用於 `<node2_sysid>` 請使用中擷取的資訊 link:record_node2_information.html#man_record_2_step10["步驟10"] 的「_Record node2 information_」區段。適用於 `_node4_sysid_`、請使用中擷取的資訊 <<man_install4_step23,步驟23>>。

+

NOTE: 只有在存在共享磁碟時、維護模式才需要使用「-p」選項。

+
「磁碟重新指派」命令只會重新指派目前擁有者為「節點2_sysid_」的磁碟。

+
系統會顯示下列訊息：

+
[listing]
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)? n
----
+
當要求中止磁碟重新指派時、請輸入「n」。

+
當系統要求您中止磁碟重新指派時、您必須回答一系列的提示、如下列步驟所示：

+
.. 系統會顯示下列訊息：
+
[listing]
----
After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)? y
----
.. 輸入「y」繼續。
+
系統會顯示下列訊息：

+
[listing]
----
Disk ownership will be updated on all disks previously belonging to Filer with sysid <sysid>.
Do you want to continue (y/n)? y
----
.. 輸入「y」以更新磁碟擁有權。


. 如果您要從具有外部磁碟的系統升級至支援內部和外部磁碟的系統（例如A800系統）、請將node4設為root、以確認從node2的根Aggregate開機。
+

WARNING: *警告：您必須依照所示的確切順序執行下列子步驟；否則可能導致中斷運作、甚至導致資料遺失。*

+
下列程序會將node4設定為從節點2的根Aggregate開機：

+
.. 檢查node2 Aggregate的RAID、plex和Checksum資訊：
+
「aggr狀態-r」

.. 檢查node2 Aggregate的整體狀態：
+
「aggr狀態」

.. 如有必要、請將node2 Aggregate上線：
+
"aggr_online root_aggr_from __node2__（aggr_online root_aggr_from __node2__）"

.. 防止節點4從其原始根Aggregate開機：
+
「aggr offline _root_aggr_on_node4_」

.. 將node2根Aggregate設為節點4的新根Aggregate：
+
"aggr options aggr_fe__ node2__ root"



. 輸入下列命令並觀察輸出、確認控制器和機箱已設定為「ha」：
+
《ha-config show》

+
以下範例顯示「ha-config show」命令的輸出：

+
[listing]
----
*> ha-config show
   Chassis HA configuration: ha
   Controller HA configuration: ha
----
+
無論系統是在HA配對或獨立組態中、都會記錄在PROm中。獨立式系統或HA配對內的所有元件的狀態必須相同。

+
如果控制器和機箱未設定為「ha」、請使用下列命令修正組態：

+
「ha-config modify控制器ha」

+
「ha-config modify機箱ha」。

+
如果您使用MetroCluster 的是功能不完全的組態、請使用下列命令來修正組態：

+
「ha-config modify控制器MCC」

+
「ha-config modify機箱MCC」。

. 摧毀節點4上的信箱：
+
《破壞本地的信箱》

. 結束維護模式：
+
《停止》

+
系統會在開機環境提示字元停止。

. 在節點3上、檢查系統日期、時間和時區：
+
'日期'

. 在節點4上、檢查開機環境提示字元的日期：
+
「如何日期」

. 如有必要、請在節點4上設定日期：
+
"et date _mm/dd/yed_"

. 在節點4上、檢查開機環境提示字元的時間：
+
「時間安排」

. 如有必要、請在節點4上設定時間：
+
"et time _hh：mm:ss_"

. 驗證合作夥伴系統 ID 是否依照<<man_install4_Step19,步驟19>>在選項下。
+
《prontenv合作夥伴sysid》

. 如有必要、請在節點4上設定合作夥伴系統ID：
+
"etenv PARTNER-sysid _node3_sysid_"

+
.. 儲存設定：
+
「aveenv」



. 在開機環境提示字元下進入開機功能表：
+
Boot_ONTAP功能表

. 在開機功能表中、於提示字元輸入「6」、從備份組態*選取選項*（6）Update flash。
+
系統會顯示下列訊息：

+
[listing]
----
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?:
----
. 在提示符下輸入「y」。
+
開機會正常進行、系統會提示您確認系統ID不相符。

+

NOTE: 系統可能會重新開機兩次、然後才顯示不相符的警告。

. 確認不相符。在正常開機之前、節點可能會完成一輪重新開機。
. 登入節點4。

