---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/move_nas_lifs_node1_node2.html 
keywords: nas, node1, node2, lifs, cluster, san 
summary: 如果您有雙節點叢集、請將node1資料l生命 週期移至node2；如果叢集有兩個以上的節點、則在ONTAP 執行更新版本的控制器上進行手動ARL升級時、將節點1資料lifs移至第三節點。 
---
= 將節點1擁有的NAS資料lifs移至節點2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
若要將節點1替換為節點3、您必須先將節點1擁有的NAS資料lifs移至節點2（如果您有雙節點叢集）、或移至第三節點（如果叢集有兩個以上節點）。您使用的方法取決於叢集是針對NAS或SAN進行設定。

.關於這項工作
在升級過程中、遠端LIF會處理SAN LUN的流量。在升級期間、移轉SAN LIF對於叢集或服務健全狀況並不必要。將node3聯機後，您必須驗證生命期是否正常並位於適當的端口上。

.步驟
. 輸入下列命令並擷取輸出、列出節點1上裝載的所有NAS資料lifs：
+
「網路介面show -data傳輸協定nfs | CIFS -curr-node1_」

+
[listing]
----
 cluster::> network interface show -data-protocol nfs|cifs -curr-node node1

          Logical     Status      Network             Current   Current Is
 Vserver  Interface   Admin/Oper  Address/Mask        Node      Port    Home
 -------- ----------  ----------  ------------------  --------- ------- ----
 vs0
          a0a         up/down     10.63.0.53/24       node1     a0a     true
          data1       up/up       10.63.0.50/18       node1     e0c     true
          rads1       up/up       10.63.0.51/18       node1     e1a     true
          rads2       up/down     10.63.0.52/24       node1     e1b     true
 vs1
          lif1        up/up       192.17.176.120/24   node1     e0c     true
          lif2        up/up       172.17.176.121/24   node1     e1a     true
----
. [[step2]]修改node1和node2上所有lifs的自動恢復設定：
+
「網路介面修改-vserver _vserver_name_-lif_lif_name_-auto-revert假」

. [[step3]]請採取下列步驟、移轉節點1上介面群組和VLAN上裝載的任何NAS資料lifs：
+
.. [Substepa]輸入下列命令、將節點1上任何介面群組和VLAN上裝載的LIF移轉到節點2上的連接埠、以便在與介面群組相同的網路上裝載LIF：
+
「網路介面移轉-vserver _vserver_name_-lif_lif_name_-dest-node-node2_–dest-port _netport|ifgrp_」

.. 在中修改lifs和VLAN的主連接埠和主節點 <<substepa,子步驟A>> 輸入下列命令、針對每個LIF輸入一次、即可移至目前裝載lifs的連接埠和節點：
+
「網路介面修改-vserver _vserver_name_-lif_lif_name_-home-node2_- home-port _netport|ifgrp_」



. [[step4]採取下列其中一項行動：
+
[cols="20,80"]
|===
| 如果叢集設定為... | 然後... 


| NAS | 完成 <<man_lif_1_2_step5,步驟5.>> 透過 <<man_lif_1_2_step8,步驟8.>>。 


| SAN | 停用節點上的所有SAN LIF、以便進行升級：「網路介面修改-vserver _vserver_name_-lif_lif_name_-home-node-node_to _upgrade _-home-port _netport|ifgrp_-stuse-admin drod' 
|===
. [[man_lif_1_2_step5]]輸入下列命令、將NAS資料LIF從節點1移轉至節點2、每個資料LIF一次：
+
「網路介面移轉-vserver _vserver_name_-lif_lif_name_-dest-node-node2_-dest-port _data_port_」

. [[step6]輸入下列命令並檢查其輸出、以確認已將l生命 移至正確的連接埠、並在任一節點上輸入下列命令檢查輸出、確認lIF的狀態為up：
+
「網路介面show -curr-node-node2_-data-Protocol NFS|CIFS」

. [[step7]修改移轉LIF的主節點：
+
「網路介面修改-vserver _vserver_name_-lif_lif_name_-home-node2_-home-port _port_name_」

. [[man_lif_1_2_step8]]驗證LIF是否使用連接埠作為其主連接埠或目前連接埠。如果連接埠不是主連接埠或目前連接埠、請前往 <<man_lif_1_2_step9,步驟9.>>：
+
「網路介面show -home-node_node2_-home-port _port_name_'

+
「網路介面show -curr-node_node_name_-curr-port _port_name_」

. [[man_lif_1_2_step9]]如果lifs使用連接埠做為主連接埠或目前連接埠、請修改LIF以使用不同的連接埠：
+
「網路介面移轉-vserver _vserver_name_-lif_lif_name_-destination–節點_norme_name_-destination-port _port_name_」

+
「網路介面修改-vserver _vserver_name_-lif_lif_name_-home-node_node_name_-home-port _port_name_」

. [[step10]如果有任何lifs當機、請輸入下列命令、將lifs的管理狀態設為「up」（開啟）、每個LIF只需輸入一次：
+
「網路介面修改-vserver _vserver_name_-lif_lif_name_-home-nodeame_-stale-admin up」

+

NOTE: 對於VMware組態、您可能無法變更連接埠的廣播網域、因為它與裝載目的地儲存虛擬機器（SVM）LIF的連接埠相關聯。MetroCluster從遠端站台上的對應來源SVM輸入下列命令、將目的地LIF重新分配至適當的連接埠：MetroCluster 「Sesvserver resSync -vserver _vserver_name_」

. [[step11]]輸入下列命令並檢查其輸出、以確認節點1上沒有剩餘的資料lifs：
+
「網路介面show -curr-node-node1_-role data」


