---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/relocate_node2_non_root_aggr_node3_node4.html 
keywords: relocate, non-root, aggregates, node3, node4 
summary: 在ONTAP 執行更新版本的控制器上進行手動ARL升級時、將節點2的非根Aggregate從節點3重新定位至節點4。 
---
= 將節點2的非根Aggregate從節點3重新部署到節點4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
將節點2的非根Aggregate重新放置到節點3之後、您現在必須將節點3重新定位到節點4。

.步驟
. [man重新定位_3_4_Step1]]在任一控制器上輸入下列命令、然後檢查輸出以識別要重新定位的非根Aggregate：
+
「torage Aggregate show -Owner-name _node3_-home-id _node2_system_id_」

. 完成下列子步驟、重新配置集合體：
+
.. 在任一節點上輸入下列命令、即可存取進階權限層級：
+
"進階權限"

.. 輸入下列命令：
+
「torage Aggregate regate regate regulationstart -node3_-destate _node4_-aggregate-list _aggr_name1、aggr_name2..._-ne-控制 器升級true」

+
Aggregate清單是您在中取得的node4所擁有的Aggregate清單 <<man_relocate_3_4_Step1,步驟1.>>。

.. 出現提示時、請輸入「y」。
+
重新配置會在背景中進行。重新部署集合體可能需要幾秒鐘到幾分鐘的時間。時間包括用戶端中斷和非中斷部分。此命令不會重新部署任何離線或受限的集合體。

.. 返回管理層級：
+
「et -priv. admin」



. [[step3]檢查重新配置狀態：
+
「torage Aggregate regate reg搬 移顯示-node3_」

+
在重新放置集合體之後、輸出會顯示「Done」。

+

NOTE: 請等到所有節點2集合體都已重新放置到節點4之後、再繼續下一步。

. 請採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果重新配置... | 然後... 


| 所有集合體都成功 | 前往 <<man_relocate_3_4_Step5,步驟5.>>。 


| 任何Aggregate都失敗或遭否決  a| 
.. 檢查EMS記錄以瞭解修正行動。
.. 執行修正行動。
.. 在任一節點上輸入下列命令、即可存取進階權限層級：
+
"進階權限"

.. 重新部署任何故障或被否決的集合體：
+
「torage Aggregate regate regate regulationstart -node3_ destate _node4_-aggregate-list _aggr_name1、aggr_name2..._ ne-控制 器升級true」

+
Aggregate清單是故障或被否決的Aggregate清單。

.. 出現提示時、請輸入「y」。
.. 輸入下列命令即可返回管理員層級：
+
「et -priv. admin」



如有必要、您可以使用下列其中一種方法強制重新配置：

** 壓倒一切的否決檢查：
+
「torage aggregate regate regate regate reg搬 移開始- overre-tetoes -n控制器升級」

** 覆寫目的地檢查：
+
「torage Aggregate regate regate regate regate reg搬 移開始- overre-destination-checks-ndos控制 器升級」



如需儲存Aggregate重新定位命令的詳細資訊、請參閱 link:other_references.html["參考資料"] 若要使用CLCLI和_例ONTAP 9命令連結至_磁碟和集合管理：手冊頁參考_。

|===
. [[man_allocation_3_4_Step5]]確認所有節點2非根Aggregate均處於線上狀態、以及節點4上的狀態：
+
「torage Aggregate show -node4_-state offline -root false」

+
node2 Aggregate列在中命令的輸出中 <<man_relocate_3_4_Step1,步驟1.>>。

. 如果有任何Aggregate已離線或變成外部、請針對每個Aggregate使用下列命令使其上線：
+
'線上儲存Aggregate -Agggr_name_'

. 驗證node2 Aggregate中的所有磁碟區都在節點4上處於線上狀態：
+
「Volume show -node4_-state offline」

. 如果節點4上有任何磁碟區離線、請將其上線：
+
「Volume online -vserver _vserver_name_-volume _volume _name_」

. 將升級後AutoSupport 的資訊訊息傳送給NetApp for node4：
+
「系統節點AutoSupport 無法叫用-node_node4_-type all -m則 訊息「_node2_ cSuccessfully eved from _platform _old_ to _platform _new_」


