---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/set_fc_uta_uta2_config_node3.html 
keywords: configure, configuration, fc, uta, uta2, settings 
summary: 在執行ONTAP 更新版本的控制器上進行手動ARL升級時、請在節點3內建FC連接埠、UTA/UTA2連接埠或UTA/UTA2卡上設定節點3。 
---
= 在節點3上設定FC或UTA/UTA2組態
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
如果節點3具有內建FC連接埠、內建統一化目標介面卡（UTA/UTA2）連接埠或UTA/UTA2卡、則必須先設定設定、才能完成其餘程序。

.關於這項工作
您可能需要完成<<在節點3上設定FC連接埠>>或者<<檢查並設定節點3上的UTA/UTA2連接埠>>或兩個部分。


NOTE: NetApp行銷資料可能會使用「UTA2」一詞來指稱CNA介面卡和連接埠。不過、CLI使用「CNA」一詞。

如果節點 3 沒有板載 FC 連接埠、板載 UTA/UTA2 連接埠或 UTA/UTA2 卡（例如，從ONTAP 9.15.1 開始引入的AFF和FAS系統），並且您正在升級具有儲存磁碟的系統，則可以跳至link:map_ports_node1_node3.html["將連接埠從節點1對應至節點3"]。



== 在節點3上設定FC連接埠

如果節點 3 具有 FC 連接埠（無論是板載的還是附加 FC 適配器上的），則必須在節點投入使用之前設定其連接埠配置，因為系統出廠時未預先配置連接埠。如果您不配置端口，則可能會遇到服務中斷。

.開始之前
您必須擁有儲存在節點1中的FC連接埠設定值 link:prepare_nodes_for_upgrade.html["準備節點以進行升級"]。

.關於這項工作
如果您的系統沒有FC組態、您可以跳過本節。如果您的系統內建UTA/UTA2連接埠或UTA/UTA2卡、請在中設定 <<檢查並設定節點3上的UTA/UTA2連接埠>>。


IMPORTANT: 在群集提示符下輸入本節中的命令。

.步驟
. 顯示有​​關係統上所有 FC 和融合網路適配器的資訊。
+
「系統節點硬體統一連線展示」

. 將節點 3 的 FC 設定與您先前從節點 1 擷取的設定進行比較。
. [[man_config_3_step3]]執行下列其中一項操作：
+
[cols="35,65"]
|===
| 如果新節點上的預設FC設定為... | 然後... 


| 與您在節點1上擷取的相同 | 前往<<man_config_3_step9,步驟9.>>。 


| 與您在節點1上擷取的不同 | 前往<<man_config_3_step4,步驟4.>>。 
|===
. [[man_config_3_step4]]根據需要，輸入以下命令之一修改 node3 上的 FC 連接埠：
+
** 若要設定目標連接埠：
+
`system node hardware unified-connect modify -type \| -t target -adapter _port_name_`

** 設定啟動器連接埠：
+
`system node hardware unified-connect modify -type \| -t initiator -adapter _port_name_`

+
「-t」是FC4類型：目標或啟動器。



. 輸入以下命令並檢查輸出來驗證新設定：
+
「系統節點硬體統一連線展示」

. 結束維護模式：
+
《停止》

. 輸入命令後、請等待系統在開機環境提示字元停止。
. 在啟動環境提示字元下啟動 node3：
+
Boot_ONTAP

. [[man_config_3_step9]]執行下列其中一項操作：
+
** 如果node3具有UTA/UTA2卡或UTA/UTA2內建連接埠、請前往 <<檢查並設定節點3上的UTA/UTA2連接埠>>。
** 如果節點3沒有UTA/UTA2卡或UTA/UTA2內建連接埠、請跳過 <<檢查並設定節點3上的UTA/UTA2連接埠>> 並前往 link:map_ports_node1_node3.html["將連接埠從節點1對應至節點3"]。






== 檢查並設定節點3上的UTA/UTA2連接埠

如果節點3內建UTA/UTA2連接埠或UTA/UTA2卡、您必須檢查連接埠的組態、並視您要使用升級系統的方式而可能重新設定。

.開始之前
UTA/UTA2連接埠必須具備正確的SFP+模組。

.關於這項工作
如果您要使用統一化目標介面卡（UTA/ UTA2）連接埠來連接FC、必須先確認連接埠的設定方式。


NOTE: NetApp行銷資料可能會使用UTA2一詞來指稱CNA介面卡和連接埠。不過、CLI使用「CNA」一詞。

您可以使用「ucadmin show」命令來驗證目前的連接埠組態：

[listing]
----
*> ucadmin show
          Current  Current    Pending  Pending    Admin
 Adapter  Mode     Type       Mode     Type       Status
 -------  -------  ---------  -------  ---------  -----------
 0e       fc       target     -        initiator  offline
 0f       fc       target     -        initiator  offline
 0g       fc       target     -        initiator  offline
 0h       fc       target     -        initiator  offline
 1a       fc       target     -        -          online
 1b       fc       target     -        -          online
6 entries were displayed.
----
UTA/UTA2連接埠可設定為原生FC模式或UTA/UTA2模式。FC模式支援FC啟動器和FC目標；UTA/UTA2模式可讓同時NIC和FCoE流量共用相同的10GbE SFP+介面、並支援FC目標。

UTA/UTA2連接埠可能位於介面卡或控制器上、並具有下列組態、但您應該檢查節點3上UTA/UTA2連接埠的組態、並視需要加以變更：

* 訂購控制器時所訂購的UTA/UTA2卡、在出貨前已設定為具有您要求的特性設定。
* 與控制器分開訂購的UTA/UTA2卡會隨附預設FC目標特性。
* 新控制器上的內建UTA/UTA2連接埠會在出貨前設定、以符合您要求的特性設定。
+

NOTE: 除非指示進入維護模式，否則請在叢集提示字元下輸入本節中的命令。



.步驟
. 在 node3 上輸入以下命令檢查目前連接埠配置：
+
「系統節點硬體統一連線展示」

+
系統會顯示類似下列範例的輸出：

+
[listing]
----
 cluster1::> system node hardware unified-connect show

                Current  Current    Pending  Pending  Admin
 Node  Adapter  Mode     Type       Mode     Type     Status
 ----  -------  -------  ---------  -------  -------  ------
 f-a   0e       fc       initiator  -        -        online
 f-a   0f       fc       initiator  -        -        online
 f-a   0g       cna      target     -        -        online
 f-a   0h       cna      target     -        -        online
 f-b   0e       fc       initiator  -        -        online
 f-b   0f       fc       initiator  -        -        online
 f-b   0g       cna      target     -        -        online
 f-b   0h       cna      target     -        -        online
 12 entries were displayed.
----
. [[step2]]如果目前的SFP+模組與所需用途不符、請以正確的SFP+模組加以更換。
+
請聯絡您的NetApp代表、以取得正確的SFP+模組。

. [[step3]檢查「系統節點硬體統一連線show」或「ucadmin show」命令的輸出、以判斷UTA/UTA2連接埠是否具有您想要的特性。
. [[step4]採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果UTA/UTA2連接埠... | 然後... 


| 沒有您想要的特性 | 前往 <<man_check_3_step5,步驟5.>>。 


| 擁有您想要的個人風格 | 跳過步驟 5 至步驟 13，然後轉到<<man_check_3_step14,步驟14>>。 
|===
. [[man_check_3_step5]]如果系統有儲存磁碟並且正在執行叢集模式Data ONTAP 8.3，則啟動節點 3 並進入維護模式：
+
Boot_ONTAP maint

. 驗證設定：
+
「ucadmin show」

. 請採取下列其中一項行動：
+
[cols="35,65"]
|===
| 如果您正在設定... | 然後... 


| UTA/UTA2卡上的連接埠 | 前往<<man_check_3_step8,步驟8.>>。 


| 內建UTA/UTA2連接埠 | 跳過第 8 步並轉到<<man_check_3_step9,步驟9.>>。 
|===
. [[man_check_3_step8]]如果轉接器處於啟動器模式，且 UTA/UTA2 連接埠處於線上狀態，則將 UTA/UTA2 連接埠離線：
+
「停用介面卡_adapter_name_」

+
目標模式中的介面卡會在維護模式中自動離線。

. [[man_check_3_step9]]如果目前配置與所需用途不匹配，請根據需要變更配置：
+
「ucadmin modify -m fc|cna -t啟動器| target _adapter_name_」

+
** 「m」是指個人化模式、「光纖通道」或「cna」。
** "-t"是FC4類型、"target（目標）"或"initiator（啟動器）"。
+

NOTE: 您必須對磁帶機和MetroCluster配置使用 FC 啟動器。您必須對 SAN 用戶端使用 FC 目標。



. 停止系統：
+
《停止》

+
系統會在開機環境提示字元停止。

. 輸入下列命令：
+
Boot_ONTAP

. [[step11]驗證設定：
+
「系統節點硬體統一連線展示」

+
下列範例的輸出顯示FC4類型的介面卡「1b」正在變更為「啟動器」、介面卡「2a」和「2b」的模式正在變更為「cna」：

+
[listing]
----
 cluster1::> system node hardware unified-connect show

                Current  Current    Pending  Pending      Admin
 Node  Adapter  Mode     Type       Mode     Type         Status
 ----  -------  -------  ---------  -------  -----------  ------
 f-a   1a       fc       initiator  -        -            online
 f-a   1b       fc       target     -        initiator    online
 f-a   2a       fc       target     cna      -            online
 f-a   2b       fc       target     cna      -            online

 4 entries were displayed.
----
. [[step12a]]透過對每個連接埠輸入以下命令，將所有目標連接埠置於線上狀態：
+
網路FCP介面卡修改-node_node_name_-介 面卡_adapter_name_-state up

. [[man_check_3_step14]]連接埠。

